import {CHAPTERS138} from './story138.mjs';
const $=s=>document.querySelector(s),el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const chapters=CHAPTERS138.map(c=>c.steps);
let checked={};try{checked=JSON.parse(localStorage.getItem('gaon:guide138')||'{}');if(!checked||typeof checked!=='object')checked={};}catch{}
function renderSteps(){const c=Number($('#chapter').value);$('#steps').replaceChildren();const chapter=CHAPTERS138[c],fig=$('#story-figure');fig.replaceChildren();const im=el('img');im.src='./images/'+chapter.image+'-138.png';im.alt=chapter.caption;im.width=640;im.height=384;fig.append(im,el('figcaption',chapter.caption));chapters[c].forEach(([title,text],i)=>{const li=el('li'),label=el('label'),box=el('input');box.type='checkbox';box.checked=!!checked[c+':'+i];li.classList.toggle('done',box.checked);label.append(box,el('span',title));const body=el('div');body.append(label,el('p',text));li.append(body);$('#steps').append(li);box.addEventListener('change',()=>{checked[c+':'+i]=box.checked;try{localStorage.setItem('gaon:guide138',JSON.stringify(checked));}catch{}li.classList.toggle('done',box.checked);progress();});});progress();}
function progress(){const c=Number($('#chapter').value);$('#progress').textContent=`できたこと：${chapters[c].filter((_,i)=>checked[c+':'+i]).length} / ${chapters[c].length}`;}
$('#chapter').addEventListener('change',renderSteps);$('#reset-progress').addEventListener('click',()=>{const c=$('#chapter').value;for(const k of Object.keys(checked))if(k.startsWith(c+':'))delete checked[k];try{localStorage.setItem('gaon:guide138',JSON.stringify(checked));}catch{}renderSteps();});renderSteps();
try{
const [{SPECIES},{BATTLE_ART_FILES},{TYPES,effect},{MOVES},{habitatEntries,habitatRateLabel},{WILD_WINDOWS94,wildAvailable91},{SCHEDULED_ENCOUNTERS},{MAPS}]=await Promise.all([import('/src/data/species.js'),import('/src/data/battleart.js'),import('/src/data/types.js'),import('/src/data/moves.js'),import('/src/habitats.js'),import('/src/wildAvailability91.mjs'),import('/src/scheduledEncounters62.js'),import('/src/data/maps.js')]);
const art=name=>new URL(BATTLE_ART_FILES[name],new URL('/src/data/battleart.js',location.origin)).href;
const picture=(name,lazy=true)=>{const i=el('img');i.src=art(name);i.alt=name;i.width=136;i.height=136;if(lazy)i.loading='lazy';return i;};
renderSteps();
for(const im of document.querySelectorAll('[data-mon]'))im.src=art(im.dataset.mon);
for(const id of ['type','attack','defend','defend2'])for(const type of TYPES){const o=el('option',type);o.value=type;$('#'+id).append(o);}$('#attack').value='ほのお';$('#defend').value='くさ';
function matchup(){const types=[$('#defend').value,$('#defend2').value].filter(Boolean),unique=[...new Set(types)],m=effect($('#attack').value,unique);$('#match-result').textContent=(m===0?'このわざは、こうかがないよ。':m>1?'こうかばつぐん！ ダメージは '+m+'倍。':m<1?'ちょっと苦手。ダメージは '+m+'倍。':'ふつうのあいしょうだよ。ダメージは１倍。');}for(const id of ['attack','defend','defend2'])$('#'+id).addEventListener('change',matchup);matchup();
const names=Object.keys(SPECIES).sort((a,b)=>SPECIES[a].no-SPECIES[b].no),norm=s=>s.normalize('NFKC').replace(/[ぁ-ゖ]/g,c=>String.fromCharCode(c.charCodeAt(0)+96)).toLowerCase().trim();
let page=0;const size=12,tags=types=>{const d=el('div',undefined,'tags');types.forEach(t=>d.append(el('span',t,'tag')));return d;};
function render(){const q=norm($('#search').value),type=$('#type').value,filtered=names.filter(n=>(!type||SPECIES[n].types.includes(type))&&(!q||norm(n+' '+habitatEntries(n).map(e=>e.mapName).join(' ')).includes(q)));page=Math.min(page,Math.max(0,Math.ceil(filtered.length/size)-1));$('#results').replaceChildren();for(const n of filtered.slice(page*size,(page+1)*size)){const b=el('button',undefined,'mon-card');b.append(el('span','No. '+String(SPECIES[n].no).padStart(3,'0'),'no'),picture(n),el('strong',n),tags(SPECIES[n].types),el('span','どこにいる？ →','hint'));b.addEventListener('click',()=>show(n));$('#results').append(b);}if(!filtered.length)$('#results').append(el('p','みつからなかったよ。名前を短くするか、タイプを「すべて」にしてみよう。','empty'));$('#result-count').textContent=filtered.length+'種類みつかったよ（全'+names.length+'種類）';$('#page-info').textContent=filtered.length?`${page+1} / ${Math.ceil(filtered.length/size)}`:'0 / 0';$('#prev').disabled=page===0;$('#next').disabled=(page+1)*size>=filtered.length;}
for(const id of ['search','type'])$('#'+id).addEventListener(id==='search'?'input':'change',()=>{page=0;render();});for(const [id,delta]of [['prev',-1],['next',1]])$('#'+id).addEventListener('click',()=>{page+=delta;render();$('#result-count').scrollIntoView({block:'start'});});render();
function show(n){const s=SPECIES[n],body=$('#detail-body');body.replaceChildren();const head=el('div',undefined,'detail-head'),title=el('h2',n);title.id='detail-title';head.append(picture(n,false),el('small','No. '+String(s.no).padStart(3,'0')),title,tags(s.types));body.append(head);
const places=el('div',undefined,'detail-section');places.append(el('h3','会える場所'));const entries=habitatEntries(n);if(!entries.length)places.append(el('p','野生で会う場所は登録されていないよ。下の進化のヒントや、ゲーム内のイベントをたしかめよう。'));for(const e of entries){const p=el('div',undefined,'place');p.append(el('strong',e.mapName),el('p',habitatRateLabel(e)));places.append(p);}if(entries.length)places.append(el('p','「出る割合」は、ガオンに出会ったときの割合だよ。歩くたびに必ず会えるわけではないよ。','small'));body.append(places);
const evol=el('div',undefined,'detail-section');evol.append(el('h3','進化のヒント'));let root=n;const seen=new Set();while(!seen.has(root)){seen.add(root);const prev=names.find(k=>SPECIES[k].evo?.to===root);if(!prev)break;root=prev;}const row=el('div',undefined,'evolutions');seen.clear();while(root&&!seen.has(root)){seen.add(root);const name=root,b=el('button',name);b.prepend(picture(name));b.addEventListener('click',()=>show(name));row.append(b);const e=SPECIES[root].evo;if(e){row.append(el('span','Lv.'+e.lv+' →'));root=e.to;}else root=null;}evol.append(row);if(seen.size===1)evol.append(el('p','このガオンの進化は、いまはないよ。'));body.append(evol);
const learn=el('div',undefined,'detail-section');learn.append(el('h3','おぼえるわざ'),el('p','Lv.はレベルのこと。下のレベルになると、おぼえるチャンスがあるよ。使えるわざは４つまで。'));const wrap=el('div',undefined,'table-wrap'),table=el('table'),tr=el('tr');for(const t of ['レベル','わざ','タイプ・しゅるい'])tr.append(el('th',t));const th=el('thead');th.append(tr);table.append(th);const tb=el('tbody');for(const[lv,name]of s.learn){const r=el('tr'),td=el('td'),a=el('a',name);a.href='/gaon-zukan/moves/?q='+encodeURIComponent(name);td.append(a);r.append(el('td','Lv.'+lv),td,el('td',MOVES[name].type+'・'+({phys:'ぶつり',spec:'とくしゅ',stat:'へんか'}[MOVES[name].cat])));tb.append(r);}table.append(tb);wrap.append(table);learn.append(wrap);body.append(learn);if(!$('#detail').open)$('#detail').showModal();$('#detail').scrollTop=0;}
function calendar(){const now=new Date();$('#clock').textContent='日本のいま：'+new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'long',day:'numeric',weekday:'long',hour:'2-digit',minute:'2-digit'}).format(now);$('#windows').replaceChildren();for(const [name,rule]of Object.entries(WILD_WINDOWS94)){const c=el('article',undefined,'time-card'),active=wildAvailable91(name,now,rule.map);c.append(picture(name),el('span',active?'いまは時間が合うよ':'会える時間を待とう','status'+(active?' active':'')),el('h3',name),el('p',rule.label.replace('（日本時間）','')));const b=el('button','場所をしらべる →');b.addEventListener('click',()=>show(name));c.append(b);$('#windows').append(c);}}calendar();setInterval(calendar,60000);
for(const r of SCHEDULED_ENCOUNTERS){const row=el('div',undefined,'season-row'),b=el('button',r.name+' →');b.addEventListener('click',()=>show(r.name));row.append(b,el('p',(MAPS[r.map]?.name||r.map)+' ／ '+r.label));$('#seasonal').append(row);}
}catch(e){console.error(e);$('#result-count').textContent='ガオンのデータをよみこめなかったよ。通信をたしかめて、もう一度ひらいてね。';const b=el('button','もう一度よみこむ');b.addEventListener('click',()=>location.reload());$('#results').append(b);}
