(async()=>{
const $=s=>document.querySelector(s),scene=$('#scene'),view=$('#viewport'),status=$('#status');
try{
const [data,svg]=await Promise.all([fetch('data.json?v=64').then(r=>{if(!r.ok)throw Error('地図データ');return r.json()}),fetch('map.svg?v=64').then(r=>{if(!r.ok)throw Error('地図画像');return r.text()})]);scene.innerHTML=svg;
const nodes=new Map(data.maps.map(n=>[n.id,n])),edges=data.edges;let current='village',scale=.8,tx=0,ty=0;
const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const normalize=s=>s.normalize('NFKC').replace(/\s/g,'').toLowerCase();
const connected=id=>edges.filter(e=>e.a===id||e.b===id),other=(e,id)=>e.a===id?e.b:e.a;
const mode=e=>e.kind==='ship'?'船':e.kind==='train'?'列車':'徒歩';
const transform=()=>{scene.style.transform=`translate(${tx}px,${ty}px) scale(${scale})`;$('#zoom').textContent=Math.round(scale*100)+'%'};
function focus(id){let n=nodes.get(id);if(!n.visible)n=nodes.get(n.parent);if(!n)return;const nearby=[n,...connected(n.id).map(e=>nodes.get(other(e,n.id))).filter(t=>t.visible&&Math.abs(t.x-n.x)+Math.abs(t.y-n.y)<1200)];const left=Math.min(...nearby.map(t=>t.x))-45,top=Math.min(...nearby.map(t=>t.y))-45,right=Math.max(...nearby.map(t=>t.x+270))+45,bottom=Math.max(...nearby.map(t=>t.y+260))+45;scale=Math.min(.85,(view.clientWidth-30)/(right-left),(view.clientHeight-30)/(bottom-top));tx=view.clientWidth/2-(left+right)/2*scale;ty=view.clientHeight/2-(top+bottom)/2*scale;transform()}
function highlight(ids,nums){scene.querySelectorAll('.map-node').forEach(el=>{el.classList.toggle('active',ids.includes(el.dataset.node));el.classList.toggle('dim',ids.length>0&&!ids.includes(el.dataset.node))});scene.querySelectorAll('.edge,.endpoint').forEach(el=>{const yes=nums.includes(+el.dataset.edge);el.classList.toggle('active',yes);el.classList.toggle('dim',nums.length>0&&!yes)})}
function button(id,e){const n=nodes.get(id);return `<button class="destination" data-select="${escape(id)}"><span class="num">${e.number}</span><span>${escape(n.name)}<small>${mode(e)}で移動</small></span></button>`}
function select(id,move=false){const n=nodes.get(id);if(!n)return;current=id;const list=connected(id),outside=list.filter(e=>nodes.get(other(e,id)).visible),rooms=list.filter(e=>!nodes.get(other(e,id)).visible);$('#details').innerHTML=`<h2>${escape(n.name)}</h2><p>${n.visible?'番号を選ぶと道を強調します。行き先の名前を押すと移動します。':'町の中にある建物です。'}</p><img class="preview" alt="${escape(n.name)}の地形" src="thumbs/${n.source}.png"><h3>${n.visible?'つながっている場所':'外に出る'}</h3><div class="destinations">${outside.map(e=>button(other(e,id),e)).join('')}</div>${rooms.length?`<h3>この場所の建物 · ${rooms.length}か所</h3><div class="rooms">${rooms.map(e=>{const r=nodes.get(other(e,id));return `<button data-select="${escape(r.id)}"><img alt="" src="thumbs/${r.source}.png">${escape(r.name)}</button>`}).join('')}</div>`:''}`;highlight([id,...list.map(e=>other(e,id))],list.map(e=>e.number));$('#itinerary').innerHTML='';if(move)focus(id);status.textContent='';}
function connection(number,from){const e=edges.find(e=>e.number===number);if(!e)return;select(from);highlight([e.a,e.b],[number]);const target=nodes.get(other(e,from));status.textContent=`接続 ${number}：${nodes.get(from).name} ↔ ${target.name}（${mode(e)}）`;$('#details').insertAdjacentHTML('afterbegin',`<p class="connection-info">接続 <strong>${number}</strong> · ${mode(e)}<br>${escape(nodes.get(from).name)} ↔ ${escape(target.name)}</p>`)}
function zoom(f,x=view.clientWidth/2,y=view.clientHeight/2){const next=Math.max(.07,Math.min(2.5,scale*f));tx=x-(x-tx)*next/scale;ty=y-(y-ty)*next/scale;scale=next;transform()}
$('#plus').onclick=()=>zoom(1.35);$('#minus').onclick=()=>zoom(1/1.35);$('#home').onclick=()=>select('village',true);$('#fit').onclick=()=>{scale=Math.min(view.clientWidth/data.width,view.clientHeight/data.height)*.96;tx=(view.clientWidth-data.width*scale)/2;ty=(view.clientHeight-data.height*scale)/2;highlight([],[]);transform()};
document.querySelectorAll('[data-place]').forEach(b=>{const n=nodes.get(b.dataset.place);b.textContent=n.name;b.onclick=()=>select(n.id,true)});
$('#places').innerHTML=data.maps.map(n=>`<option value="${escape(n.name)}"></option>`).join('');$('#destination').innerHTML=data.maps.map(n=>`<option value="${escape(n.id)}">${escape(n.name)}</option>`).join('');$('#destination').value='galaxy';
$('#searchForm').onsubmit=e=>{e.preventDefault();const q=normalize($('#search').value);if(!q)return;const found=data.maps.find(n=>normalize(n.name)===q)||data.maps.find(n=>normalize(n.name).includes(q));if(found)select(found.id,true);else status.textContent='その名前の場所が見つかりませんでした。'};
$('#details').onclick=e=>{const b=e.target.closest('[data-select]');if(b)select(b.dataset.select,true)};
let moved=false;scene.addEventListener('click',e=>{if(moved)return;const endpoint=e.target.closest('.endpoint'),card=e.target.closest('.map-node');if(endpoint)connection(+endpoint.dataset.edge,endpoint.dataset.from);else if(card)select(card.dataset.node)});scene.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){const el=e.target.closest('.endpoint,.map-node');if(el){e.preventDefault();moved=false;el.dispatchEvent(new MouseEvent('click',{bubbles:true}))}}});
const pointers=new Map();let pinch=0;view.addEventListener('pointerdown',e=>{moved=false;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});pinch=0});view.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const [a,b]=[...pointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y),r=view.getBoundingClientRect();if(pinch)zoom(d/pinch,(a.x+b.x)/2-r.left,(a.y+b.y)/2-r.top);pinch=d;moved=true;}else{const dx=e.clientX-old.x,dy=e.clientY-old.y;if(Math.abs(dx)+Math.abs(dy)>2){moved=true;view.setPointerCapture(e.pointerId)}tx+=dx;ty+=dy;transform()}});const release=e=>{pointers.delete(e.pointerId);pinch=0};view.addEventListener('pointerup',release);view.addEventListener('pointercancel',release);view.addEventListener('wheel',e=>{e.preventDefault();const r=view.getBoundingClientRect();zoom(Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top)},{passive:false});view.addEventListener('keydown',e=>{if(e.target!==view)return;const d={ArrowLeft:[60,0],ArrowRight:[-60,0],ArrowUp:[0,60],ArrowDown:[0,-60]}[e.key];if(d){e.preventDefault();tx+=d[0];ty+=d[1];transform()}});
$('#routeForm').onsubmit=e=>{e.preventDefault();const target=$('#destination').value,queue=[current],prev=new Map([[current,null]]);for(let i=0;i<queue.length&&!prev.has(target);i++)for(const edge of connected(queue[i])){const id=other(edge,queue[i]);if(!prev.has(id)){prev.set(id,{id:queue[i],edge});queue.push(id)}}if(!prev.has(target)){$('#itinerary').textContent='接続する道が見つかりませんでした。';return}const ids=[target],nums=[];for(let at=target;at!==current;){const p=prev.get(at);nums.unshift(p.edge.number);ids.unshift(p.id);at=p.id}highlight(ids,nums);$('#itinerary').innerHTML=`<p>${ids.length===1?'現在地が目的地です。':`${nums.length}区間でつながります。通行条件はゲームの進行状況によります。`}</p><ol>${ids.map((id,i)=>`<li><button data-route-place="${escape(id)}">${escape(nodes.get(id).name)}</button>${i<nums.length?`<br>↓ 接続 ${nums[i]} · ${mode(edges.find(e=>e.number===nums[i]))}`:''}</li>`).join('')}</ol>`;};$('#itinerary').onclick=e=>{const b=e.target.closest('[data-route-place]');if(b)focus(b.dataset.routePlace)};
select('village',true);
}catch(error){$('#details').textContent='地図を読み込めませんでした。ページを再読み込みしてください。';status.textContent=error.message;console.error(error)}
})();
