import {NATURE73} from '/src/natureCatalog73.mjs';
import {LEGACY73} from '/src/legacyCatalog73.mjs';
import {catalog,initial,applyEdit,validateEdit,objectSource,actorSource,clone,FLOORS} from '/src/editorModel72.mjs';
import {drawChapterMap,drawMaterial,drawEditorProp72} from '/src/chapterArt.js';
import {drawEditorGround72} from '/src/editorGround72.js';
import {drawNpc,NPC_VARIANTS} from '/src/npcArt.js';
import {drawFollower} from '/src/followerArt.js';
import {drawRoomStaff} from '/src/roomAssets.js';
import {drawFurniture72} from '/src/interiorArt.js';
const $=id=>document.getElementById(id),canvas=$('mapCanvas'),ctx=canvas.getContext('2d');
let maps,cat,mapId,base,doc,rendered,selection=null,category='people',tool=null,zoom=1,dirty=false,history=[],future=[],revision=0,publicRevision=0,errors=[],inflight=false,token=localStorage.getItem('vmon:token')||'',draftRead=0;
let palettePainters=[],drag=null;const ids=()=> 'a:'+crypto.randomUUID();
function notice(text){$('notice').textContent=text;$('notice').style.display='block';clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('notice').style.display='none',6500);}
async function api(body){const r=await fetch('/api/map-editor',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)}),data=await r.json();if(!r.ok)throw Error(data.message||'通信に失敗しました。');return data;}
async function enter(){const user=await api({action:'session'});[maps,cat]=await fetch('/assets/editor-v72/base-maps.json').then(r=>r.json()).then(async maps=>[maps,catalog(maps,await fetch('/assets/editor-v72/species.json').then(r=>r.json()))]);$('identity').textContent=user.name;$('login').hidden=true;$('app').hidden=false;$('mapSelect').replaceChildren();for(const[id,m]of Object.entries(maps)){const o=new Option((m.kind==='in'?'室内 / ':'屋外 / ')+m.name+' ['+id+']',id);$('mapSelect').add(o);}mapId='rods';$('mapSelect').value=mapId;await loadMap(mapId);}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginMessage').textContent='確認しています…';try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'login',name:$('account').value,pw:$('password').value})});const d=await r.json();if(!r.ok||!d.token)throw Error(d.message||'ログインできませんでした。');token=d.token;await enter();localStorage.setItem('vmon:token',token);$('password').value='';}catch(e){$('loginMessage').textContent=e.message;}};
async function loadMap(id){const serial=++draftRead;$('hint').textContent='マップを読み込んでいます…';setBusy(true);try{const data=await api({action:'read',map:id});if(serial!==draftRead)return;mapId=id;base=maps[id];doc=clone(data.draft||data.published||initial(base));revision=data.draftRevision;publicRevision=data.publicRevision;history=[];future=[];dirty=false;selection=null;tool=null;$('rollback').disabled=!data.hasPrevious;$('mapSelect').value=id;$('mapInfo').textContent=base.rows[0].length+' × '+base.rows.length+'マス'+(id==='shop'?'・各町の共通ショップ':'');refresh();fit();renderPalette();}catch(e){notice(e.message);$('mapSelect').value=mapId;}finally{setBusy(false);}}
function setBusy(v){inflight=v;document.querySelector('.layout').inert=v;for(const id of ['save','publish','reload','preview','mapSelect','confirmPublish'])$(id).disabled=v;}
function checkpoint(){history.push(clone(doc));if(history.length>60)history.shift();future=[];dirty=true;}
function change(fn){checkpoint();fn();refresh();}
function refresh(){errors=validateEdit(base,doc,cat);try{rendered=applyEdit(base,doc,cat);}catch{rendered=base;}$('validation').textContent=errors.length?errors.join('\n'):'✓ 配置と通路のチェックを通過しました。';$('validation').className=errors.length?'error':'';$('dirty').textContent=dirty?'● 未保存の変更':'下書き';$('undo').disabled=!history.length;$('redo').disabled=!future.length;$('hint').textContent=tool?tool.category==='floors'?'ドラッグして床を塗れます。':'クリックして配置。Escで選択モードに戻ります。':'クリックして選択。ドラッグ、または矢印キーで移動できます。';canvas.width=base.rows[0].length*32;canvas.height=base.rows.length*32;applyZoom();inspector();rugControls();actorList();}
function applyZoom(){canvas.style.width=canvas.width*zoom+'px';canvas.style.height=canvas.height*zoom+'px';$('zoomLabel').textContent=Math.round(zoom*100)+'%';}
function fit(){zoom=Math.max(.15,Math.min(1,($('viewport').clientWidth-48)/canvas.width,($('viewport').clientHeight-48)/canvas.height));applyZoom();}
function draw(){if(rendered){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.imageSmoothingEnabled=false;drawChapterMap(ctx,rendered,0,0);for(const n of [...rendered.npcs].sort((a,b)=>a.y-b.y)){if(n.residentPet||n.artMon)drawFollower(ctx,{sp:n.artMon},{dir:n.dir||'down',moving:false},0,n.x*32+16,n.y*32+28);else if(!drawRoomStaff(ctx,rendered,n,n.x*32,n.y*32-28))drawNpc(ctx,n,0,n.x*32,n.y*32-28);}
 if($('grid').checked){ctx.strokeStyle='#ffffff22';ctx.lineWidth=1;ctx.beginPath();for(let x=0;x<canvas.width;x+=32){ctx.moveTo(x+.5,0);ctx.lineTo(x+.5,canvas.height);}for(let y=0;y<canvas.height;y+=32){ctx.moveTo(0,y+.5);ctx.lineTo(canvas.width,y+.5);}ctx.stroke();}
 if(selection){const item=getSelected(),p=selection.kind==='actor'?{w:1,h:1}:item&&objectSource(base,item,cat);if(item&&p){ctx.strokeStyle='#fff7a0';ctx.lineWidth=3;ctx.strokeRect(item.x*32+1,item.y*32+1,p.w*32-2,p.h*32-2);}}
 }for(const f of palettePainters)f();requestAnimationFrame(draw);}
function getSelected(){return selection?(selection.kind==='actor'?doc.actors:doc.objects).find(o=>o.id===selection.id):null;}
function choose(kind,id){selection={kind,id};tool=null;document.querySelectorAll('.material.active').forEach(e=>e.classList.remove('active'));$('selectTool').classList.add('active');inspector();}
function tabLabel(key){return {people:'人',pets:'ガオン',props:'木・建物',plants:'庭の植物',grass:'季節の草むら',flowers:'花畑20色',rocks:'石・岩',furniture:'室内家具',floors:'地面・床'}[key];}
for(const key of ['people','pets','plants','grass','flowers','rocks','props','furniture','floors']){const b=document.createElement('button');b.textContent=tabLabel(key);b.onclick=()=>{category=key;$('search').value='';renderPalette();};b.dataset.category=key;$('tabs').append(b);}
function renderPalette(){palettePainters=[];$('materials').replaceChildren();document.querySelectorAll('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.category===category));let items=['grass','flowers','rocks'].includes(category)?cat.props.filter(p=>p.group===({grass:'grass',flowers:'flower',rocks:'rock'})[category]):category==='plants'?cat.props.filter(p=>p.garden):category==='props'?cat.props.filter(p=>!p.garden&&!['grass','flower','rock'].includes(p.group)):category==='pets'?cat.species.map(key=>({key,label:key})):category==='floors'?FLOORS.filter(f=>base.kind==='in'?['wood','tile','wall',...NATURE73.filter(p=>p.group==='floor').map(p=>p.key),...LEGACY73.filter(p=>p.group==='floor'&&p.indoor).map(p=>p.key)].includes(f[0]):!['wood','tile'].includes(f[0])).map(([key,label])=>({key,label})).concat({key:'original',label:'元の地面に戻す'}):cat[category];if(category==='people')items=items.map(p=>({...p,label:NPC_VARIANTS[p.variant]||p.label}));if(category==='furniture'&&base.kind!=='in'){$('materials').textContent='家具は室内マップを選ぶと配置できます。';return;}const query=$('search').value.trim();items=items.filter(p=>p.label.includes(query)||p.key.includes(query));for(const p of items){const b=document.createElement('button');b.className='material';b.title=p.label;b.dataset.key=p.key;const cv=document.createElement('canvas');cv.width=80;cv.height=72;const c=cv.getContext('2d');b.append(cv);const text=document.createElement('span');text.textContent=p.label+(p.garden||p.group?'（'+p.w+'×'+p.h+'）':'');b.append(text);b.onclick=()=>{tool={category,key:p.key};selection=null;document.querySelectorAll('.material').forEach(e=>e.classList.remove('active'));b.classList.add('active');$('selectTool').classList.remove('active');$('hint').textContent=category==='floors'?'マップをドラッグして塗ります。':'マップをクリックして配置します。';inspector();};$('materials').append(b);let count=0;palettePainters.push(()=>{if(count++>150)return;c.clearRect(0,0,80,72);c.imageSmoothingEnabled=false;if(category==='people')drawNpc(c,{variant:p.variant,dir:'down'},0,24,8);else if(category==='pets')drawFollower(c,{sp:p.key},{dir:'down',moving:false},0,40,58);else if(category==='floors'){c.save();c.translate(24,20);if(p.key==='original'){c.fillStyle='#c4d8cb';c.fillRect(0,0,32,32);c.fillStyle='#345a4f';c.font='22px sans-serif';c.fillText('↶',5,24);}else drawEditorGround72(c,{editorGround72:[{x:0,y:0,material:p.key}]},drawMaterial);c.restore();}else{const scale=Math.min(64/(p.w*32),56/(p.h*32));c.save();c.translate((80-p.w*32*scale)/2,(72-p.h*32*scale)/2);c.scale(scale,scale);if(category==='furniture')drawFurniture72(c,p.room||base.room||{theme:'home'},[[p.kind||p.key,0,0,p.w,p.h]]);else drawEditorProp72(c,{...p,x:0,y:0},maps[p.source]||base);c.restore();}});}}
function field(parent,label,value,type,onchange,options){const l=document.createElement('label');l.textContent=label;const i=document.createElement(options?'select':type==='textarea'?'textarea':'input');if(options)for(const[v,text]of options)i.add(new Option(text,v));else if(type!=='textarea')i.type=type||'text';i.value=value??'';i.onchange=()=>onchange(i.value);l.append(i);parent.append(l);return i;}
function inspector(){const el=$('selection');el.replaceChildren();const a=getSelected();if(!a){el.textContent=tool?'選んだ素材：'+tool.key:'マップ上の人・ガオン・物を選んでください。';return;}const src=selection.kind==='actor'?actorSource(base,a,cat):objectSource(base,a,cat);const name=document.createElement('strong');name.textContent=selection.kind==='actor'?src.displayName||src.name||'住人':(cat[a.type==='prop'?'props':'furniture'].find(p=>p.key===a.template)?.label||a.template);el.append(name);const coords=document.createElement('div');coords.className='coords';el.append(coords);for(const key of ['x','y'])field(coords,key.toUpperCase(),a[key],'number',v=>change(()=>a[key]=Number(v)));if(selection.kind==='actor'){field(el,'向き',a.dir,null,v=>change(()=>a.dir=v),[['down','下'],['up','上'],['left','左'],['right','右']]);const pet=src.residentPet;field(el,'動き',a.mode,null,v=>change(()=>{a.mode=v;if(v!=='follow')a.owner=null;}),[['still','その場にいる'],['roam','自由に歩く'],...(pet?[['follow','飼い主について歩く']]:[])]);if(a.mode==='follow')field(el,'飼い主',a.owner,null,v=>change(()=>a.owner=v),[['','選んでください'],...doc.actors.filter(n=>!actorSource(base,n,cat).artMon).map(n=>[n.id,actorSource(base,n,cat).displayName||actorSource(base,n,cat).name||n.id])]);if(a.id.startsWith('a:')){field(el,'名前',a.name||src.name,'text',v=>change(()=>a.name=v)).maxLength=30;field(el,'会話',a.talk||src.talk?.[0],'textarea',v=>change(()=>a.talk=v)).maxLength=240;}else{const p=document.createElement('p');p.className='muted';p.textContent='元からいる住人の会話・イベント・戦闘設定は保持されます。';el.append(p);}}
 if(a.id.startsWith('a:')||selection.kind==='object'&&!src.door){const b=document.createElement('button');b.textContent='配置を削除';b.onclick=()=>change(()=>{if(selection.kind==='actor'){doc.actors=doc.actors.filter(n=>n!==a);for(const n of doc.actors)if(n.owner===a.id){n.owner=null;n.mode='roam';}}else doc.objects=doc.objects.filter(n=>n!==a);selection=null;});el.append(b);}}
function rugControls(){const el=$('rugControls');el.replaceChildren();if(!base.room){el.textContent='室内マップで変更できます。';return;}const row=document.createElement('div');row.className='coords';el.append(row);for(const [i,label]of ['X','Y','幅','高さ'].entries())field(row,label,doc.rug?.[i]??0,'number',v=>change(()=>{doc.rug??=[0,0,0,0];doc.rug[i]=Number(v);}));const b=document.createElement('button');b.textContent='ラグをなくす';b.onclick=()=>change(()=>doc.rug=[0,0,0,0]);el.append(b);}
function actorList(){$('actorList').replaceChildren();for(const a of doc.actors){const n=actorSource(base,a,cat),b=document.createElement('button');b.textContent=(n.artMon?'◈ ':'● ')+(n.displayName||n.name||'住人')+' ('+a.x+', '+a.y+')';b.onclick=()=>{choose('actor',a.id);$('viewport').scrollTo({left:a.x*32*zoom-$('viewport').clientWidth/2,top:a.y*32*zoom-$('viewport').clientHeight/2});};$('actorList').append(b);}}
function point(e){const r=canvas.getBoundingClientRect();return {x:Math.floor((e.clientX-r.left)/zoom/32),y:Math.floor((e.clientY-r.top)/zoom/32)};}
function paint(p){if(p.x<0||p.y<0||p.x>=base.rows[0].length||p.y>=base.rows.length)return;const index=doc.tiles.findIndex(t=>t.x===p.x&&t.y===p.y);if(tool.key==='original'){if(index>=0)doc.tiles.splice(index,1);return;}const t={...p,material:tool.key};if(index>=0)doc.tiles[index]=t;else doc.tiles.push(t);}
canvas.onpointerdown=e=>{if(inflight)return;const p=point(e);canvas.focus();canvas.setPointerCapture(e.pointerId);if(tool){checkpoint();if(tool.category==='floors'){paint(p);drag={paint:true};}else if(['people','pets'].includes(tool.category)){const a={id:ids(),...p,dir:'down',mode:'still',owner:null,type:tool.category==='pets'?'pet':'person',...(tool.category==='pets'?{species:tool.key,name:tool.key}:{template:tool.key,name:NPC_VARIANTS[Number(tool.key)]})};doc.actors.push(a);selection={kind:'actor',id:a.id};tool=null;}else{const o={id:ids(),...p,type:tool.category==='furniture'?'furniture':'prop',template:tool.key};doc.objects.push(o);selection={kind:'object',id:o.id};tool=null;}refresh();return;}
 const a=[...doc.actors].reverse().find(a=>a.x===p.x&&a.y===p.y)||[...doc.actors].reverse().find(a=>a.x===p.x&&a.y===p.y+1);if(a)choose('actor',a.id);else{const o=[...doc.objects].reverse().find(o=>{const s=objectSource(base,o,cat);return p.x>=o.x&&p.x<o.x+s.w&&p.y>=o.y&&p.y<o.y+s.h;});if(o)choose('object',o.id);else{selection=null;inspector();}}const selected=getSelected();if(selected)drag={x:p.x,y:p.y,startX:selected.x,startY:selected.y,checkpoint:false};else drag={pan:true,cx:e.clientX,cy:e.clientY,left:$('viewport').scrollLeft,top:$('viewport').scrollTop};};
canvas.onpointermove=e=>{if(!drag)return;if(drag.pan){$('viewport').scrollLeft=drag.left+drag.cx-e.clientX;$('viewport').scrollTop=drag.top+drag.cy-e.clientY;return;}const p=point(e);if(drag.paint){paint(p);refresh();return;}const a=getSelected();if(a&&(p.x!==drag.x||p.y!==drag.y)){if(!drag.checkpoint){checkpoint();drag.checkpoint=true;}a.x=drag.startX+p.x-drag.x;a.y=drag.startY+p.y-drag.y;refresh();}};
canvas.onpointerup=canvas.onpointercancel=()=>{drag=null;};
canvas.onkeydown=e=>{const delta={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]}[e.key],a=getSelected();if(delta&&a){e.preventDefault();change(()=>{a.x+=delta[0];a.y+=delta[1];});}if(e.key==='Escape'){$('selectTool').click();}if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();$('undo').click();}};
$('selectTool').onclick=()=>{tool=null;selection=null;$('selectTool').classList.add('active');inspector();};$('undo').onclick=()=>{if(!history.length)return;future.push(clone(doc));doc=history.pop();dirty=true;selection=null;refresh();};$('redo').onclick=()=>{if(!future.length)return;history.push(clone(doc));doc=future.pop();dirty=true;selection=null;refresh();};$('search').oninput=renderPalette;$('plus').onclick=()=>{zoom=Math.min(3,zoom*1.25);applyZoom();};$('minus').onclick=()=>{zoom=Math.max(.1,zoom/1.25);applyZoom();};$('fit').onclick=fit;
$('mapSelect').onchange=()=>{if(dirty&&!confirm('未保存の変更を破棄してマップを切り替えますか？')){$('mapSelect').value=mapId;return;}loadMap($('mapSelect').value);};$('reload').onclick=()=>{if(!dirty||confirm('未保存の変更を破棄して再読み込みしますか？'))loadMap(mapId);};
async function save(action){if(inflight)return;if(errors.length){notice('配置を修正してから保存してください。\n'+errors[0]);return;}setBusy(true);try{const r=await api({action,map:mapId,edit:doc,revision,publicRevision});revision=r.draftRevision;publicRevision=r.publicRevision;dirty=false;$('rollback').disabled=!r.hasPrevious;$('dirty').textContent=action==='publish'?'公開済み':'下書き保存済み';notice(action==='publish'?'公開しました。ゲームを読み込み直すと反映されます。':'下書きを保存しました。');}catch(e){notice(e.message);}finally{setBusy(false);}}
$('save').onclick=()=>save('save');$('publish').onclick=()=>{if(errors.length){notice(errors[0]);return;}$('confirmText').textContent=base.name+'：住人・ガオン '+doc.actors.length+'体、物・家具 '+doc.objects.length+'個、床の変更 '+doc.tiles.length+'マス。';$('confirm').showModal();};$('cancelPublish').onclick=()=>$('confirm').close();$('confirmPublish').onclick=()=>{$('confirm').close();save('publish');};
$('rollback').onclick=async()=>{if(!confirm('このマップを前の公開状態に戻しますか？現在の下書きも置き換わります。'))return;setBusy(true);try{await api({action:'rollback',map:mapId,revision,publicRevision});await loadMap(mapId);notice('前の公開状態に戻しました。');}catch(e){notice(e.message);}finally{setBusy(false);}};
$('reset').onclick=()=>{if(confirm('編集中の内容を初期マップに戻しますか？公開するまではゲームは変わりません。'))change(()=>{doc=initial(base);selection=null;tool=null;});};
$('download').onclick=()=>{const blob=new Blob([JSON.stringify({map:mapId,edit:doc},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='gaon-'+mapId+'-draft.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('preview').onclick=()=>{if(errors.length){notice(errors[0]);return;}localStorage.setItem('gaon:editorPreview72',JSON.stringify({map:mapId,edit:doc}));window.open('/?editorPreview72='+encodeURIComponent(mapId),'_blank','noopener');};
$('logout').onclick=()=>{if(dirty&&!confirm('未保存の変更があります。ログアウトしますか？'))return;token='';localStorage.removeItem('vmon:token');location.reload();};window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
requestAnimationFrame(draw);if(token)enter().catch(e=>$('loginMessage').textContent=e.message);
