const fs=require('fs');const source=JSON.parse(fs.readFileSync('atlas-source.json','utf8')),raw=Object.fromEntries(source.map(n=>[n.id,n])),nodes={},edges=[],dedup=new Set();
// Shared interiors are displayed separately at each entrance; they are not shortcuts between towns.
for(const n of source)if(!n.warps.some(w=>w.to==='@back'))nodes[n.id]={...n};
function side(n,w){if(raw[w.to]?.kind==='in'&&!raw[w.to]?.id.startsWith('dark'))return'down';return [[w.x,'left'],[n.w-w.x-1,'right'],[w.y,'up'],[n.h-w.y-1,'down']].sort((a,b)=>a[0]-b[0])[0][1];}
function add(a,b,w={},kind='walk',note=''){if(!nodes[a]||!nodes[b]||a===b)return;const key=[a,b].sort().join('|')+kind;if(dedup.has(key))return;dedup.add(key);edges.push({a,b,kind,note,side:side(nodes[a],{x:w.x??nodes[a].w/2,y:w.y??nodes[a].h-1,to:b}),number:edges.length+1});}
for(const n of source)for(const w of n.warps){if(!raw[w.to]||w.to==='@back')continue;let to=w.to;if(raw[to].warps.some(e=>e.to==='@back')){to=n.id+'::'+to;nodes[to]={...raw[w.to],id:to,name:raw[w.to].name+'［'+n.name+'］',parent:n.id};}if(!nodes[n.id])continue;add(n.id,to,w,'walk',w.requires?'ストーリー進行による通行条件があります。':'');}
for(const n of source){for(const t of n.travel){if(['karatPort','resurePort'].includes(n.id)&&['karatPort','resurePort'].includes(t.to))continue;add(n.id,t.to,t,n.id==='shipDeck'||t.to==='shipDeck'?'ship':'train','ゲーム内の乗船・乗車条件を満たすと利用できます。');}
 for(const p of n.npcs){const target=({'end:islandShip':'belerioPort','end:returnIsland':'karatPort','end:door':'dark1','frontier:train':'galaxy','frontier:returnTrain':'manikereoStation','end:rail':'leafTown','end:returnRail':'mountainRail'})[p.script];if(target)add(n.id,target,p,/Island|island/.test(p.script)?'ship':p.script==='end:door'?'walk':'train','イベント・進行条件があります。');}
}
add('karatPort','shipDeck',{},'ship','連絡船。チケット・乗船時間などの条件があります。');add('resurePort','shipDeck',{},'ship','連絡船。チケット・乗船時間などの条件があります。');
const dirs={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]},opp={up:'down',down:'up',left:'right',right:'left'},occupied=new Set(),seen=new Set();let component=0;
for(const root of ['village',...Object.keys(nodes)]){if(seen.has(root))continue;const n=nodes[root];n.gx=component*4;n.gy=0;while(occupied.has(n.gx+',0'))n.gx++;component++;occupied.add(n.gx+',0');seen.add(root);const q=[root];for(let i=0;i<q.length;i++){const a=nodes[q[i]];for(const e of edges.filter(e=>e.a===a.id||e.b===a.id)){const bid=e.a===a.id?e.b:e.a;if(seen.has(bid))continue;const b=nodes[bid],s=e.a===a.id?e.side:opp[e.side],[dx,dy]=dirs[s];let distance=1,x=a.gx+dx,y=a.gy+dy;while(occupied.has(x+','+y)){distance++;x=a.gx+dx*distance;y=a.gy+dy*distance;}b.gx=x;b.gy=y;occupied.add(x+','+y);seen.add(bid);q.push(bid);}}}
const minx=Math.min(...Object.values(nodes).map(n=>n.gx)),miny=Math.min(...Object.values(nodes).map(n=>n.gy));for(const n of Object.values(nodes)){n.x=100+(n.gx-minx)*500;n.y=220+(n.gy-miny)*420;}
const W=Math.max(...Object.values(nodes).map(n=>n.x))+420,H=Math.max(...Object.values(nodes).map(n=>n.y))+370;
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const step=20,gw=Math.ceil(W/step)+1,gh=Math.ceil(H/step)+1,blocked=new Uint8Array(gw*gh);for(const n of Object.values(nodes))for(let y=Math.floor((n.y-12)/step);y<=Math.ceil((n.y+282)/step);y++)for(let x=Math.floor((n.x-12)/step);x<=Math.ceil((n.x+332)/step);x++)blocked[y*gw+x]=1;
const segments=new Set(),ports=new Map();
function path(a,b){const ai=ports.get(a.id+':out')||0,bi=ports.get(b.id+':in')||0;ports.set(a.id+':out',ai+1);ports.set(b.id+':in',bi+1);const ax=a.x+40+ai*40,bx=b.x+40+bi*40;const start=[Math.round(ax/step),Math.round((a.y+310)/step)],end=[Math.round(bx/step),Math.round((b.y-40)/step)],si=start[1]*gw+start[0],gi=end[1]*gw+end[0],prev=new Int32Array(gw*gh);prev.fill(-1);prev[si]=si;const q=[si];for(let i=0;i<q.length&&prev[gi]<0;i++){const p=q[i],x=p%gw,y=Math.floor(p/gw);for(const[dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx,yy=y+dy,k=yy*gw+xx;if(xx<1||yy<7||xx>=gw-1||yy>=gh-1||blocked[k]||prev[k]>=0)continue;prev[k]=p;q.push(k);}}if(prev[gi]<0)throw Error('No route');const points=[];for(let p=gi;p!==si;p=prev[p])points.push([p%gw*step,Math.floor(p/gw)*step]);points.push(start.map(x=>x*step));points.reverse();for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i];segments.add([a[1]/step*gw+a[0]/step,b[1]/step*gw+b[0]/step].sort((a,b)=>a-b).join(':'));}return [[ax,a.y+270],...points,[bx,b.y]];}
let svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="#102b32"/><style>text{font-family:Meiryo,sans-serif}.card{cursor:pointer}.edge{cursor:pointer}.edge:hover{opacity:1}</style><text x="100" y="74" font-size="40" fill="#f4ecd8">ガオン・ワールド ─ 全体図</text><text x="100" y="119" font-size="20" fill="#b6d4cd">実際のマップ画像と接続情報 ／ 出入口の方向を基準に配置（距離・縮尺は模式的） ／ 2026.09.16</text><text x="100" y="157" font-size="18" fill="#b6d4cd">緑：徒歩　青：船　黄：列車　同じ番号が接続先。番号を選ぶと経路を強調します。建物は町ごとに表示。</text>`;
for(const e of edges){const a=nodes[e.a],b=nodes[e.b],pts=path(a,b),color=e.kind==='ship'?'#69c8ff':e.kind==='train'?'#f2c766':'#78cba7';e.points=pts;svg+=`<g class="edge" data-edge="${e.number}" opacity=".7"><polyline points="${pts.map(p=>p.join(',')).join(' ')}" fill="none" stroke="#102b32" stroke-width="9"/><polyline points="${pts.map(p=>p.join(',')).join(' ')}" fill="none" stroke="${color}" stroke-width="3" ${e.kind==='walk'?'':'stroke-dasharray="9 6"'}/></g>`;}
for(const n of Object.values(nodes))svg+=`<g class="card" data-node="${esc(n.id)}"><rect x="${n.x}" y="${n.y}" width="320" height="270" rx="12" fill="#1b4146" stroke="#517779"/><text x="${n.x+16}" y="${n.y+29}" font-size="${n.name.length>20?12:16}" fill="#fff4d4">${esc(n.name)}</text><image href="${n.image}" x="${n.x+20}" y="${n.y+43}" width="280" height="210" preserveAspectRatio="xMidYMid meet"/></g>`;
// Numbered endpoints are separated along each card, so every destination is identifiable.
for(const n of Object.values(nodes)){const links=edges.filter(e=>e.a===n.id||e.b===n.id);links.forEach((e,i)=>{const x=n.x+18+i*30,y=n.y+274;svg+=`<g class="edge" data-edge="${e.number}"><circle cx="${x}" cy="${y}" r="13" fill="#f2ddb0" stroke="#102b32" stroke-width="2"/><text x="${x}" y="${y+4}" text-anchor="middle" fill="#16383e" font-size="11">${e.number}</text></g>`;});}svg+='</svg>';
const root='I:/2026/Claude code/gaon-world/world-atlas/';fs.mkdirSync(root,{recursive:true});fs.writeFileSync(root+'map.svg',svg);fs.writeFileSync(root+'data.json',JSON.stringify({width:W,height:H,maps:Object.values(nodes).map(({image,warps,npcs,travel,...n})=>n),edges}));console.log(JSON.stringify({maps:source.length,cards:Object.keys(nodes).length,connections:edges.length,W,H}));
