const fs=require('fs'),path=require('path');const {chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const p=await b.newPage();await p.goto('http://127.0.0.1:5179/');fs.mkdirSync('assets/followers-v14',{recursive:true});const records=[],hashFile='work/follow-v14-imported.json',hashes=fs.existsSync(hashFile)?JSON.parse(fs.readFileSync(hashFile,'utf8')):{};
for(let no=1;no<=153;no++){const id=String(no).padStart(3,'0'),revised='work/follow-v14-revised/'+id+'.png',original='work/follow-v14-source/'+id+'.png',file=fs.existsSync(revised)?revised:original;if(!fs.existsSync(file))continue;const output='assets/followers-v14/'+id+'.png';const hash=require('crypto').createHash('sha256').update(fs.readFileSync(file)).digest('hex');if(fs.existsSync(output)&&hashes[id]===hash&&!process.argv.includes('--force'))continue;
const out=await p.evaluate(async ({file,no})=>{const im=new Image();im.src='/'+file+'?t='+Date.now();await im.decode();const cw=Math.floor(im.width/4),ch=Math.floor(im.height/2),cells=[];let maxW=0,maxH=0;for(let row=0;row<2;row++)for(let col=0;col<4;col++){
const c=document.createElement('canvas');c.width=cw;c.height=ch;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(im,-col*cw,-row*ch);const d=ctx.getImageData(0,0,cw,ch),px=d.data,seen=new Uint8Array(cw*ch),q=[];
const add=(x,y)=>{const k=y*cw+x,i=k*4;if(seen[k])return;const min=Math.min(px[i],px[i+1],px[i+2]),max=Math.max(px[i],px[i+1],px[i+2]);const checker=[9,24,44,56,57,61,62,63,67,70,75,104,105,136,137].includes(no);const matte=no===108?(max<18&&max-min<9):(min>=(checker?105:165)&&max-min<=23);if(px[i+3]>=128&&!matte)return;seen[k]=1;q.push(k);};for(let x=0;x<cw;x++){add(x,0);add(x,ch-1);}for(let y=0;y<ch;y++){add(0,y);add(cw-1,y);}for(let n=0;n<q.length;n++){const k=q[n],x=k%cw,y=Math.floor(k/cw);px[k*4+3]=0;if(x)add(x-1,y);if(x<cw-1)add(x+1,y);if(y)add(x,y-1);if(y<ch-1)add(x,y+1);}
// Discard isolated matte noise and fragments of a neighboring atlas cell.
const visited=new Uint8Array(cw*ch),parts=[];for(let k=0;k<cw*ch;k++){if(visited[k]||px[k*4+3]<160)continue;const part=[k];visited[k]=1;let edge=false;for(let j=0;j<part.length;j++){const a=part[j],x=a%cw,y=Math.floor(a/cw);if(x<3||x>=cw-3||y<3||y>=ch-3)edge=true;for(const z of [x?a-1:-1,x<cw-1?a+1:-1,y?a-cw:-1,y<ch-1?a+cw:-1])if(z>=0&&!visited[z]&&px[z*4+3]>=160){visited[z]=1;part.push(z);}}parts.push({part,edge});}const largest=Math.max(...parts.map(v=>v.part.length));for(const v of parts)if(v.part.length<largest*.002||(v.edge&&v.part.length<largest*.25))for(const k of v.part)px[k*4+3]=0;
let x0=cw,y0=ch,x1=-1,y1=-1;for(let y=0;y<ch;y++)for(let x=0;x<cw;x++){const i=(y*cw+x)*4;if(px[i+3]<160){px[i+3]=0;continue;}px[i+3]=255;x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}ctx.putImageData(d,0,0);const w=x1-x0+1,h=y1-y0+1;if(w<=0||h<=0)throw Error('empty cell '+row+','+col);maxW=Math.max(maxW,w);maxH=Math.max(maxH,h);cells.push({c,x0,y0,w,h,row,col});}
const atlas=document.createElement('canvas');atlas.width=320;atlas.height=160;const ac=atlas.getContext('2d');const s=Math.min(68/maxW,70/maxH),frames=[];for(const f of cells){const c=document.createElement('canvas');c.width=c.height=80;const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;const w=Math.round(f.w*s),h=Math.round(f.h*s);ctx.drawImage(f.c,f.x0,f.y0,f.w,f.h,Math.floor((80-w)/2),74-h,w,h);const d=ctx.getImageData(0,0,80,80);for(let k=3;k<d.data.length;k+=4)d.data[k]=d.data[k]>=160?255:0;ctx.putImageData(d,0,0);ac.drawImage(c,f.col*80,f.row*80);frames.push(c.toDataURL().split(',')[1]);}return {atlas:atlas.toDataURL().split(',')[1],frames};},{file,no});
fs.writeFileSync(output,Buffer.from(out.atlas,'base64'));fs.mkdirSync('assets/followers-v14/'+id,{recursive:true});const dirs=['down','up','right','left'];out.frames.forEach((data,i)=>fs.writeFileSync('assets/followers-v14/'+id+'/'+dirs[i%4]+'-'+(i<4?'a':'b')+'.png',Buffer.from(data,'base64')));hashes[id]=hash;fs.writeFileSync(hashFile,JSON.stringify(hashes));records.push({no,revised:file===revised});}
console.log(JSON.stringify({imported:records,atlases:fs.readdirSync('assets/followers-v14').filter(f=>f.endsWith('.png')).length}));}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
