const fs=require('fs');const {chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const p=await b.newPage();await p.goto('http://127.0.0.1:5179/');fs.mkdirSync('assets/people-v13',{recursive:true});
for(let index=0;index<30;index++){const data=await p.evaluate(async index=>{const atlas=document.createElement('canvas');atlas.width=128;atlas.height=144;const ac=atlas.getContext('2d');ac.imageSmoothingEnabled=false;const dirs=['down','left','right','up'];
if(index<8){const {drawNpc}=await import('/tools/npcArtV6Source.js');const n={look:['boy','girl','prof','oldman','nurse','clerk','hiker','girl'][index]};if(index===7)n.script='v5:mother';for(let i=0;i<50;i++){if(drawNpc(ac,{...n,dir:'down'},0,0,0))break;await new Promise(r=>setTimeout(r,100));}ac.clearRect(0,0,128,144);for(let row=0;row<3;row++)for(let col=0;col<4;col++)drawNpc(ac,{...n,dir:dirs[col],moving:row!==1,roamProgress:row===0?.125:.375},0,col*32,row*48);return atlas.toDataURL().split(',')[1];}
const im=new Image();im.src='/work/npc-v13-source/'+index+'.png';await im.decode();const cw=Math.floor(im.width/4),ch=Math.floor(im.height/3),cells=[];let maxW=0,maxH=0;
for(let row=0;row<3;row++)for(let col=0;col<4;col++){const c=document.createElement('canvas');c.width=cw;c.height=ch;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(im,-col*cw,-row*ch);const d=ctx.getImageData(0,0,cw,ch),px=d.data;
if(px[3]>128){const seen=new Uint8Array(cw*ch),q=[];const add=(x,y)=>{const k=y*cw+x,i=k*4;if(seen[k])return;const min=Math.min(px[i],px[i+1],px[i+2]),max=Math.max(px[i],px[i+1],px[i+2]);if(min<170||max-min>22)return;seen[k]=1;q.push(k);};for(let x=0;x<cw;x++){add(x,0);add(x,ch-1);}for(let y=0;y<ch;y++){add(0,y);add(cw-1,y);}for(let n=0;n<q.length;n++){const k=q[n],x=k%cw,y=Math.floor(k/cw);px[k*4+3]=0;if(x)add(x-1,y);if(x<cw-1)add(x+1,y);if(y)add(x,y-1);if(y<ch-1)add(x,y+1);}}
let x0=cw,y0=ch,x1=-1,y1=-1;for(let y=0;y<ch;y++)for(let x=0;x<cw;x++){const i=(y*cw+x)*4;if(px[i+3]<160){px[i+3]=0;continue;}px[i+3]=255;x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}ctx.putImageData(d,0,0);const w=x1-x0+1,h=y1-y0+1;if(w<=0||h<=0)throw Error('empty '+index);maxW=Math.max(maxW,w);maxH=Math.max(maxH,h);cells.push({c,x0,y0,w,h,row,col});}
const scale=Math.min(30/maxW,46/maxH);for(const f of cells){const w=Math.round(f.w*scale),h=Math.round(f.h*scale);ac.drawImage(f.c,f.x0,f.y0,f.w,f.h,f.col*32+Math.floor((32-w)/2),f.row*48+48-h,w,h);}return atlas.toDataURL().split(',')[1];},index);fs.writeFileSync('assets/people-v13/'+String(index).padStart(2,'0')+'.png',Buffer.from(data,'base64'));}
console.log('Imported 30 NPC atlases, 360 directional walking frames');}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
