const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../world-atlas');fs.mkdirSync(root,{recursive:true});const src=require(path.resolve(process.argv[2]||'atlas-source.json')),raw=Object.fromEntries(src.map(n=>[n.id,n]));
const old=require(path.join(root,'data.json'));const nodes=Object.fromEntries(old.maps.map(n=>[n.id,{...n,source:n.id.split('::').at(-1),image:raw[n.id.split('::').at(-1)]?.image}]));
const edges=old.edges.map(({points,...e})=>({...e}));const degree=id=>edges.filter(e=>e.a===id||e.b===id).length;
for(const n of Object.values(nodes)){n.visible=n.kind!=='in'||degree(n.id)>1||['championTower','galaxyArena'].includes(n.id);n.parent=n.parent||(!n.visible?edges.find(e=>e.a===n.id||e.b===n.id)?.a:undefined);if(n.parent===n.id)n.parent=edges.find(e=>e.a===n.id||e.b===n.id).b;}
const visible=Object.values(nodes).filter(n=>n.visible),links=edges.filter(e=>nodes[e.a].visible&&nodes[e.b].visible),dirs={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]},opp={up:'down',down:'up',left:'right',right:'left'};
function exit(id,to){const m=raw[nodes[id].source],target=nodes[to].source;return m.warps.find(w=>w.to===target)||m.travel.find(w=>w.to===target);}
function side(n,e){if(!e)return null;return [[e.x,'left'],[n.w-e.x-1,'right'],[e.y,'up'],[n.h-e.y-1,'down']].sort((a,b)=>a[0]-b[0])[0][1];}
for(const e of edges){e.exitA=exit(e.a,e.b);e.exitB=exit(e.b,e.a);e.sideA=side(nodes[e.a],e.exitA)||e.side;e.sideB=side(nodes[e.b],e.exitB)||opp[e.sideA];}
const usedSlots=new Set(),seen=new Set();let component=0;
for(const rootId of ['village',...visible.map(n=>n.id)]){if(seen.has(rootId))continue;const n=nodes[rootId];n.gx=component++*5;n.gy=0;while(usedSlots.has(n.gx+',0'))n.gx++;usedSlots.add(n.gx+',0');seen.add(rootId);const q=[rootId];for(let i=0;i<q.length;i++){const a=nodes[q[i]];for(const e of links.filter(e=>e.a===a.id||e.b===a.id)){const id=e.a===a.id?e.b:e.a;if(seen.has(id))continue;const b=nodes[id],s=e.a===a.id?e.sideA:e.sideB,[dx,dy]=dirs[s];let d=1;while(usedSlots.has((a.gx+dx*d)+','+(a.gy+dy*d)))d++;b.gx=a.gx+dx*d;b.gy=a.gy+dy*d;seen.add(id);usedSlots.add(b.gx+','+b.gy);q.push(id);}}}
const minx=Math.min(...visible.map(n=>n.gx)),miny=Math.min(...visible.map(n=>n.gy));for(const n of visible){n.x=140+(n.gx-minx)*520;n.y=260+(n.gy-miny)*460;const scale=Math.min(250/n.w,210/n.h);n.iw=Math.round(n.w*scale);n.ih=Math.round(n.h*scale);n.ix=n.x+(270-n.iw)/2;n.iy=n.y+40+(210-n.ih)/2;}
const W=Math.max(...visible.map(n=>n.x))+410,H=Math.max(...visible.map(n=>n.y))+380,step=10,gw=Math.ceil(W/step)+1,gh=Math.ceil(H/step)+1,blocked=new Uint8Array(gw*gh),tracks=new Map(),labels=[];
// Block each card and title, then route only in the gaps. Each track is exclusive.
for(const n of visible)for(let y=Math.floor((n.y-14)/step);y<=Math.ceil((n.y+270)/step);y++)for(let x=Math.floor((n.x-14)/step);x<=Math.ceil((n.x+284)/step);x++)blocked[y*gw+x]=1;
function port(n,e,which){const s=e[which==='a'?'sideA':'sideB'],v=e[which==='a'?'exitA':'exitB'],[dx,dy]=dirs[s];let x=dx?(dx<0?n.x-20:n.x+290):n.x+135,y=dy?(dy<0?n.y-20:n.y+280):n.y+140;const same=links.filter(t=>(t.a===n.id?t.sideA:t.b===n.id?t.sideB:null)===s),index=same.indexOf(e),offset=(index-(same.length-1)/2)*40;if(dx)y=Math.round((y+offset)/step)*step;else x=Math.round((x+offset)/step)*step;return{x,y,dx,dy,s};}
const reserved=new Map();for(const e of links){e.ports=[port(nodes[e.a],e,'a'),port(nodes[e.b],e,'b')];for(const p of e.ports)for(let d=0;d<=30;d+=10)reserved.set(Math.round((p.y+p.dy*d)/step)*gw+Math.round((p.x+p.dx*d)/step),e.number);}
function route(p,t,owner){const start=[Math.round((p.x+p.dx*20)/step),Math.round((p.y+p.dy*20)/step)],end=[Math.round((t.x+t.dx*20)/step),Math.round((t.y+t.dy*20)/step)],si=start[1]*gw+start[0],gi=end[1]*gw+end[0],prev=new Int32Array(gw*gh);prev.fill(-1);prev[si]=si;const q=[si];for(let i=0;i<q.length&&prev[gi]<0;i++){const at=q[i],x=at%gw,y=Math.floor(at/gw);const ds=[[1,0],[-1,0],[0,1],[0,-1]].sort((a,b)=>Math.abs(x+a[0]-end[0])+Math.abs(y+a[1]-end[1])-Math.abs(x+b[0]-end[0])-Math.abs(y+b[1]-end[1]));for(const[dx,dy]of ds){let nx=x+dx,ny=y+dy,k=ny*gw+nx;if(nx<1||ny<20||nx>=gw-1||ny>=gh-1||blocked[k]||(reserved.has(k)&&reserved.get(k)!==owner)||prev[k]>=0)continue;if(tracks.has(k)){if(tracks.get(k)!==(dx?'v':'h'))continue;nx+=dx;ny+=dy;k=ny*gw+nx;if(nx<1||ny<20||nx>=gw-1||ny>=gh-1||blocked[k]||(reserved.has(k)&&reserved.get(k)!==owner)||tracks.has(k)||prev[k]>=0)continue;}prev[k]=at;q.push(k);}}
assert(prev[gi]>=0,'No path '+JSON.stringify({p,t}));const cells=[];for(let k=gi;k!==si;k=prev[k])cells.push([k%gw*step,Math.floor(k/gw)*step]);cells.push(start.map(v=>v*step));cells.reverse();for(let i=0;i<cells.length;i++){const a=cells[Math.max(0,i-1)],b=cells[Math.min(cells.length-1,i+1)],c=cells[i];tracks.set(c[1]/step*gw+c[0]/step,a[1]===b[1]?'h':a[0]===b[0]?'v':'turn');}return [[p.x,p.y],...cells,[t.x,t.y]];}
const colors=['#9fdfb0','#efd68c','#80d5e5','#c7adeb','#f2acb5','#bfd594'],esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');let svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><style>text{font-family:Meiryo,sans-serif}.map-node,.endpoint{cursor:pointer}.edge{pointer-events:none}</style><rect width="100%" height="100%" fill="#102e39"/><text x="100" y="75" font-size="38" fill="#fff1ce" font-weight="bold">ガオン・ワールド　冒険のつながり</text><text x="100" y="119" font-size="20" fill="#c1dcd6">同じ番号の出入口をたどろう。番号を押すと、その１本の道と行き先がわかります。</text><text x="100" y="155" font-size="18" fill="#c1dcd6">実線：徒歩　青い破線：船　金の破線：列車 ／ 町の中の建物は、町を選ぶと表示 ／ 距離は模式的</text>`;
for(const e of [...links].sort((a,b)=>{const dist=e=>Math.abs(e.ports[0].x-e.ports[1].x)+Math.abs(e.ports[0].y-e.ports[1].y);return dist(a)-dist(b);})){e.color=e.kind==='ship'?'#70ceff':e.kind==='train'?'#ffcd6e':colors[(e.number-1)%colors.length];const p=port(nodes[e.a],e,'a'),t=port(nodes[e.b],e,'b');e.points=route(p,t,e.number);for(const [z,from,to]of [[p,e.a,e.b],[t,e.b,e.a]])labels.push({...z,from,to,number:e.number,color:e.color});svg+=`<g class="edge" data-edge="${e.number}"><polyline points="${e.points.map(p=>p.join(',')).join(' ')}" stroke="#102e39" stroke-width="12" fill="none"/><polyline class="wire" points="${e.points.map(p=>p.join(',')).join(' ')}" stroke="${e.color}" stroke-width="4" fill="none" ${e.kind==='walk'?'':'stroke-dasharray="12 8"'}/></g>`;}
for(const n of visible){const buildings=edges.filter(e=>e.a===n.id&&!nodes[e.b].visible||e.b===n.id&&!nodes[e.a].visible).length;svg+=`<g class="map-node" data-node="${esc(n.id)}" role="button" tabindex="0" aria-label="${esc(n.name)}"><rect class="card-bg" x="${n.x}" y="${n.y}" width="270" height="260" rx="12" fill="#1a4049" stroke="#608187"/><text x="${n.x+135}" y="${n.y+26}" text-anchor="middle" font-size="${n.name.length>15?15:19}" font-weight="bold" fill="#fff3d3">${esc(n.name)}</text><image href="${n.image}" x="${n.ix}" y="${n.iy}" width="${n.iw}" height="${n.ih}" style="image-rendering:pixelated"/>${buildings?`<rect x="${n.x+173}" y="${n.y+232}" width="88" height="22" rx="8" fill="#ffe0a0"/><text x="${n.x+217}" y="${n.y+248}" font-size="13" text-anchor="middle" fill="#253d43">建物 ${buildings}か所</text>`:''}</g>`;}
for(const l of labels){const n=nodes[l.from],anchor=[l.x-l.dx*20,l.y-l.dy*20];svg+=`<g class="endpoint" data-edge="${l.number}" data-from="${esc(l.from)}" role="button" tabindex="0" aria-label="接続${l.number} ${esc(n.name)}から${esc(nodes[l.to].name)}"><path d="M${anchor} L${l.x},${l.y}" stroke="${l.color}" stroke-width="4"/><circle cx="${l.x}" cy="${l.y}" r="17" fill="#102e39" stroke="${l.color}" stroke-width="3"/><text x="${l.x}" y="${l.y+5}" font-size="14" font-weight="bold" fill="white" text-anchor="middle">${l.number}</text></g>`;}
svg+='</svg>';fs.writeFileSync(path.join(root,'map.svg'),svg);fs.writeFileSync(path.join(root,'data.json'),JSON.stringify({version:64,width:W,height:H,maps:Object.values(nodes).map(({image,...n})=>n),edges,labels}));const thumbs=path.join(root,'thumbs');fs.mkdirSync(thumbs,{recursive:true});for(const n of src)fs.writeFileSync(path.join(thumbs,n.id+'.png'),Buffer.from(n.image.split(',')[1],'base64'));console.log({visible:visible.length,total:Object.keys(nodes).length,links:links.length,W,H});
