const fs=require('fs'),path=require('path'),{execFileSync}=require('child_process');
const doc=JSON.parse(fs.readFileSync('docs/followers-v14-prompts.json','utf8').replace(/^\uFEFF/,'')),rows=doc.redesigns;
for(const r of rows){const id=String(r.no).padStart(3,'0');if(!fs.existsSync('work/follow-v14-revised/'+id+'.png'))throw Error('Revised art not ready '+r.name);for(const side of ['front','back'])fs.mkdirSync('assets/monsters/redesign-v14/'+side,{recursive:true});fs.copyFileSync('assets/followers-v14/'+id+'/down-a.png','assets/monsters/redesign-v14/front/'+id+'.png');fs.copyFileSync('assets/followers-v14/'+id+'/up-a.png','assets/monsters/redesign-v14/back/'+id+'-back.png');}
const priorAliases=JSON.parse(fs.readFileSync('src/state.js','utf8').match(/const SPECIES_ALIASES = (\{[^;]+\});/)[1]);
const aliases=Object.fromEntries(rows.filter(r=>r.old!==r.name).map(r=>[r.old,r.name]));const tracked=execFileSync('git',['ls-files'],{encoding:'utf8'}).trim().split(/\r?\n/);const files=[...new Set([...tracked.filter(f=>f.startsWith('src/')&&f.endsWith('.js')), 'src/data/gaonMotion.js'])];
for(const file of files){let s=fs.readFileSync(file,'utf8');for(const [old,name]of Object.entries(aliases))s=s.replaceAll(old,name);fs.writeFileSync(file,s);}
let state=fs.readFileSync('src/state.js','utf8');state=state.replace(/const SPECIES_ALIASES = (\{[^;]+\});/,(_,json)=>'const SPECIES_ALIASES = '+JSON.stringify(Object.fromEntries(Object.entries({...priorAliases,...aliases}).filter(([k,v])=>k!==v)))+';');fs.writeFileSync('src/state.js',state);
let art=fs.readFileSync('src/data/battleart.js','utf8');for(const r of rows){const id=String(r.no).padStart(3,'0');art=art.replace(new RegExp('('+r.name+': ")[^"]+/front/[^"\\n]+"'), '$1../../assets/monsters/redesign-v14/front/'+id+'.png"');art=art.replace(new RegExp('('+r.name+': ")[^"]+/back/[^"\\n]+"'), '$1../../assets/monsters/redesign-v14/back/'+id+'-back.png"');}fs.writeFileSync('src/data/battleart.js',art);
const descriptions={24:'ちいさな うずまきの からを せおう。やわらかな 葉を食べて ツルマキへ育つ。',36:'こけの にもつを のせて 森を歩く。木の車輪のような 足で でこぼこ道も進む。',37:'大きな 花のぼうしで 日差しをよける。つぼのような 体に 水をたくわえる。',38:'かえでの種のような 羽で 風にのる。長いリボンの尾で 向きを変える。',86:'銅のひもを 揺らして 電気をためる。夜は ちいさな灯りで 仲間を導く。',20:'しま模様の 砂岩のからを せおう。短いはさみで 宝石のかけらを 集める。',118:'花びらに似た 四枚の羽で 飛び回る。やりのような 尾で 花を守る。',119:'くるみの からの中に 住むガオン。三本の足で 転がるように 走っていく。',134:'星明かりの夜に 浮かぶ まゆ。銀の糸を ゆらして 遠くの音を感じとる。',149:'やわらかな 飛膜をひろげて 木々を渡る。長いしっぽで 体の向きを調節する。',150:'雲のように 軽い体で 空に浮かぶ。大きなひれで ゆっくり風をつかむ。',91:'小さな オレンジ色の体を 岩のよろいが守る。育つにつれて ガンセキに近づく。',5:'ヒノコマより 大きな羽と足に育つ。胸の火種で 炎のとさかを 燃やしている。',6:'黒い大きな翼に 金色の炎をまとう。ヒノコマから育った 誇り高い炎の鳥。'};
let species=fs.readFileSync('src/data/species.js','utf8');const marker='// Revised v14 character descriptions.';if(!species.includes(marker)){const code='\n'+marker+'\n'+rows.map(r=>'SPECIES['+JSON.stringify(r.name)+'].dex='+JSON.stringify(descriptions[r.no])+';').join('\n')+'\n';const at=species.indexOf('export const DEX_ORDER');if(at<0)throw Error('DEX_ORDER marker missing');species=species.slice(0,at)+code+species.slice(at);}fs.writeFileSync('src/data/species.js',species);
let motions=doc.species.map(s=>{const r=rows.find(r=>r.no===s.no);return [r?.name||s.name,{...s.motion,kind:r?.kind||s.motion.kind}];});fs.writeFileSync('src/data/gaonMotion.js','// Per-species pacing for the eight generated directional poses.\nexport const MOTION_PROFILES = '+JSON.stringify(Object.fromEntries(motions),null,2)+';\n');
for(const file of tracked.filter(f=>f.startsWith('tools/verify')&&f.endsWith('.cjs'))){let s=fs.readFileSync(file,'utf8');for(const [old,name]of Object.entries(aliases))s=s.replaceAll(old,name);fs.writeFileSync(file,s);}
execFileSync(process.execPath,['tools/integrateGaonV11.cjs'],{stdio:'inherit'});console.log('Updated 14 designs, 10 names, compatible save aliases and encyclopedia.');
