const fs=require('fs'),assert=require('assert/strict'),crypto=require('crypto');
assert(process.env.FRIEND_GATEWAY_SECRET,'Production gateway credential is required; local fallback is forbidden');
const F=require('../api/_friendStore'),{packPublished188,unpackPublished188}=require('../api/_mapCodec188');
(async()=>{
const source='C:/Users/voraz/Downloads/gaon-raden-draft.json',input=JSON.parse(fs.readFileSync(source,'utf8'));assert.equal(input.map,'raden');const inputHash=crypto.createHash('sha256').update(JSON.stringify(input.edit)).digest('hex');
const P='maps72:published',D='maps72:draft:raden',H='maps72:previous:raden',R='maps82:definitions',before=await F.read([P,D,H,R]);assert(before[P]?.version>0);const published=unpackPublished188(before[P].data);const liveBefore=await fetch('https://midori-no-shima.vercel.app/api/map-editor?verify203='+Date.now(),{cache:'no-store'}).then(r=>{assert.equal(r.status,200);return r.json()});assert.equal(liveBefore.revision,before[P].version,'Production revision must match');assert.deepEqual(liveBefore.maps,published.maps,'Production snapshot must match');
const backup='artifacts/raden-publication203/'+new Date().toISOString().replace(/[:.]/g,'-');fs.mkdirSync(backup,{recursive:true});fs.writeFileSync(backup+'/before.json',JSON.stringify(before));fs.copyFileSync(source,backup+'/input.json');
const {extendMaps82}=await import('../src/customMaps82.mjs'),{addManagedPeople120}=await import('../src/managedPeople120.mjs'),m=await import('../src/editorModel72.mjs');const definitions=before[R]?.data?.definitions||{};const base=extendMaps82(addManagedPeople120(JSON.parse(fs.readFileSync('assets/editor-v72/base-maps.json'))),definitions),cat=m.catalog(base,JSON.parse(fs.readFileSync('assets/editor-v72/species.json')));const errors=m.validateEdit(base.raden,input.edit,cat);assert.deepEqual(errors,[]);
const maps=structuredClone(published.maps),views={...base};maps.raden=input.edit;for(const[id,edit]of Object.entries(maps))if(base[id]&&!m.validateEdit(base[id],edit,cat).length)views[id]=m.applyEdit(base[id],edit,cat);assert.deepEqual((await import('../src/connections75.mjs')).validateLinks75(views),[]);assert.equal((await import('../src/peopleNames138.mjs')).nameClashes138(views.raden,views),null);assert(!input.edit.links?.some(l=>definitions[l.to]&&l.to!=='raden'&&!published.definitions?.[l.to]),'Unpublished connection target');assert.equal(crypto.createHash('sha256').update(JSON.stringify(input.edit)).digest('hex'),inputHash,'Input was modified');
console.log({validated:true,objects:input.edit.objects.length,actors:input.edit.actors.length,tiles:input.edit.tiles.length,publicRevision:before[P].version,draftRevision:before[D]?.version||0,backup});if(!process.argv.includes('--publish'))return;
const at=Date.now(),expected={[P]:before[P].version,[D]:before[D]?.version||0,[H]:before[H]?.version||0},writes={[P]:packPublished188({...published,maps,at}),[D]:{edit:input.edit,by:'ヤノケン',at},[H]:{edit:published.maps.raden||null,at}};assert(await F.commit(expected,writes),'Concurrent update; no overwrite performed');const after=await F.read([P,D,H]),afterPub=unpackPublished188(after[P].data);assert.deepEqual(afterPub.maps.raden,input.edit);assert.deepEqual(after[D].data.edit,input.edit);assert.deepEqual(after[H].data.edit,published.maps.raden||null);assert.deepEqual(afterPub.definitions,published.definitions);for(const[id,edit]of Object.entries(published.maps))if(id!=='raden')assert.deepEqual(afterPub.maps[id],edit);
const live=await fetch('https://midori-no-shima.vercel.app/api/map-editor?verify203='+Date.now(),{cache:'no-store'}).then(r=>{assert.equal(r.status,200);return r.json()});assert.deepEqual(live.maps.raden,input.edit);assert.equal(live.revision,after[P].version);const result={published:true,map:'raden',inputHash,publicRevision:after[P].version,draftRevision:after[D].version,otherMapsUnchanged:true};fs.writeFileSync(backup+'/result.json',JSON.stringify(result,null,2));console.log(result);
})().catch(e=>{console.error(e.message);process.exit(1)});
