const assert=require('node:assert/strict'),crypto=require('crypto'),B=require('../api/_friendBattle');
const base=process.env.FRIEND_TEST_URL||'http://127.0.0.1:5182';
const call=async(token,path,body)=>{const r=await fetch(base+'/api/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,...await r.json()}};
const mon=(sp,id)=>({...B.combatMon({sp,companionId:id,lv:50,iv:{},ev:{},moves:[{name:'タックル'}]},50),exp:125000,statVersion:2});
(async()=>{const tag=Date.now().toString(36),users=[];for(let i=0;i<3;i++){const pw=crypto.randomBytes(12).toString('hex');const u=await call(null,'auth',{action:'signup',name:'friend'+i+tag,pw});assert.equal(u.status,200,JSON.stringify(u));const payload={ver:3,name:'Friend'+i,party:[mon(i?'アワミィ':'トリッピ','id'+i+tag),mon('ラテット','rat'+i+tag),mon('リーフィン','leaf'+i+tag)],box:[],bag:{},flags:{},badges:[],dexOwn:{},dexSeen:{},where:{map:'village',x:13,y:12},steps:0};const save=await call(u.token,'save',{payload,rev:0});assert.equal(save.status,200,JSON.stringify(save));users.push({...u,payload,pw});}
const[a,b,c]=users;const request=(u,code,action,data={})=>call(u.token,'friends',{code,action,requestId:crypto.randomUUID(),...data});
let created=await request(a,null,'create',{mode:'trade'}),code=created.room.code;assert.equal(created.status,200);assert.equal((await request(c,code,'state')).status,409);assert.equal((await request(b,code,'join')).status,200);assert.equal((await request(c,code,'join')).status,409);assert.equal((await call(a.token,'save',{payload:a.payload,rev:1,force:true})).status,409);
await request(a,code,'offer',{ref:{place:'party',index:0}});let offered=await request(b,code,'offer',{ref:{place:'party',index:0}});const revision=offered.room.offerRevision;const results=await Promise.all([request(a,code,'confirm',{offerRevision:revision}),request(b,code,'confirm',{offerRevision:revision})]);assert(results.every(x=>x.status===200),JSON.stringify(results));let state=await request(a,code,'state');assert.equal(state.room.phase,'complete');const pa=await call(a.token,'save'),pb=await call(b.token,'save');assert.equal(pa.payload.party[0].companionId,b.payload.party[0].companionId);assert.equal(pb.payload.party[0].companionId,a.payload.party[0].companionId);assert.equal((await call(a.token,'save',{payload:a.payload,rev:pa.user.rev,force:true})).status,409);assert.equal((await request(a,code,'confirm',{offerRevision:revision})).status,409);assert.equal((await request(a,null,'resume')).room,null);
created=await request(a,null,'create',{mode:'battle',rule:'level50'});code=created.room.code;await request(b,code,'join');await request(a,code,'ready',{ids:pa.payload.party.map(m=>m.companionId)});state=await request(b,code,'ready',{ids:pb.payload.party.map(m=>m.companionId)});assert.equal(state.room.phase,'battle');assert(state.room.battle.sides.every(s=>s.team.every(m=>m.lv===50)));const turn=state.room.battle.turn;await request(a,code,'battle',{turn,command:{kind:'move',index:0}});state=await request(b,code,'state');assert.equal(state.room.battle.turn,turn);assert(!state.room.battle.pending);await request(b,code,'battle',{turn,command:{kind:'move',index:0}});state=await request(a,code,'state');assert.equal(state.room.battle.turn,turn+1);assert.equal((await request(a,code,'battle',{turn,command:{kind:'move',index:0}})).status,409);await request(a,code,'leave');assert.equal((await request(b,null,'resume')).room,null);assert.deepEqual((await call(a.token,'save')).payload,pa.payload);
created=await request(a,null,'create',{mode:'coop'});code=created.room.code;await request(b,code,'join');await request(a,code,'ready',{ids:[pa.payload.party[0].companionId]});state=await request(b,code,'ready',{ids:[pb.payload.party[0].companionId]});assert.equal(state.room.phase,'dungeon');const pos=state.room.dungeon.positions[a.user.id];await request(a,code,'walk',{dx:0,dy:-1,seq:0});state=await request(b,code,'state');assert.equal(state.room.dungeon.positions[a.user.id].y,pos.y-1);assert.equal((await request(a,code,'walk',{dx:0,dy:-1,seq:0})).status,409);assert.equal((await request(a,null,'resume')).room.code,code);await request(b,code,'leave');for(const u of users)assert.equal((await call(u.token,'account',{action:'delete',pw:u.pw})).status,200);console.log('PASS HTTP: private rooms, two-player limit, atomic simultaneous trade confirmations, stale-save guard, normalized battle, hidden synchronized actions, duplicate turn rejection, original save preserved, shared movement, sequence guard, resume and leave');
})().catch(e=>{console.error(e);process.exitCode=1});
