import fs from 'node:fs';import assert from 'node:assert/strict';import{catalog,initial,upgrade79,applyEdit,validateEdit,pass}from'../src/editorModel72.mjs';import{target173}from'../src/layout173.mjs';import{CLIFFS173}from'../src/materialCatalog173.mjs';import{addManagedPeople120}from'../src/managedPeople120.mjs';import{extendMaps82}from'../src/customMaps82.mjs';
const published=fs.existsSync('artifacts/maps173/published-before.json')?JSON.parse(fs.readFileSync('artifacts/maps173/published-before.json')):{},maps=extendMaps82(addManagedPeople120(JSON.parse(fs.readFileSync('assets/editor-v72/base-maps.json'))),published.definitions),cat=catalog(maps,JSON.parse(fs.readFileSync('assets/editor-v72/species.json')));let count=0;
for(const base of Object.values(maps).filter(target173)){const doc=upgrade79(base,published.maps?.[base.id]||initial(base));assert.deepEqual(upgrade79(base,doc),doc,base.id+' migration is idempotent');assert.deepEqual(validateEdit(base,doc,cat),[],base.id);const m=applyEdit(base,doc,cat),q=[m.spawn],seen=new Set([m.spawn.x+','+m.spawn.y]);assert(pass(m,m.spawn.x,m.spawn.y));for(let i=0;i<q.length;i++)for(const[dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const x=q[i].x+dx,y=q[i].y+dy,k=x+','+y;if(pass(m,x,y)&&!seen.has(k)){seen.add(k);q.push({x,y});}}for(const w of m.warps)assert(seen.has(w.x+','+w.y),base.id+' exit '+w.x+','+w.y);for(const n of m.npcs)assert([[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>seen.has((n.x+dx)+','+(n.y+dy))),base.id+' NPC '+n.name);for(const t of doc.tiles.filter(t=>t.material==='lava173'))assert(!pass(m,t.x,t.y),base.id+' lava collision');assert.equal(m.npcs.length,doc.actors.filter(a=>!a.stored79).length);count++;}
const original=cat.props.find(p=>p.key==='legacy73-cliff');assert(original&&original.w===1&&original.h===1);assert.equal(CLIFFS173.length,24);for(const p of CLIFFS173){assert.equal(p.w,1);assert.equal(p.h,1);assert(cat.props.some(x=>x.key===p.key));}
console.log('PASS '+count+' rebuilt maps: idempotent migration, all exits/NPCs reachable, magma blocked; original cliff retained; 24 new 1x1 cliffs');

const test={id:'test173',name:'検証',kind:'out',tileWorld:true,rows:Array(16).fill(','.repeat(16)),props:[],npcs:[],items:[],signs:[],warps:[],spawn:{x:1,y:1}};for(const p of CLIFFS173)for(let turn=0;turn<4;turn++){const d=initial(test);d.objects.push({id:'a:cliff-test',type:'prop',template:p.key,x:4,y:4,turn81:turn});assert.deepEqual(validateEdit(test,d,cat),[],p.key);const m=applyEdit(test,d,cat);assert(!pass(m,4,4));assert(pass(m,3,4)&&pass(m,5,4));}for(const id of ['route13','route14','route15','route16','blizzard']){const m=applyEdit(maps[id],initial(maps[id]),cat);assert(m.rows.some(r=>r.includes('"')),id+' encounter grass preserved');}console.log('PASS 24 cliffs x 4 rotations preserve 1-cell collision; snowy encounter grass retained');

const falls=applyEdit(maps.merire,initial(maps.merire),cat);assert(![...falls.props,...falls.editorAddedProps72].some(p=>/waterfall/i.test(p.art||'')));const cells=falls.editorGround72.filter(t=>t.material.startsWith('waterfall-'));assert.equal(cells.length,261);const altered=upgrade79(maps.merire,initial(maps.merire));const at=altered.tiles.find(t=>t.material==='waterfall-flow173');at.material='water173';const edited=applyEdit(maps.merire,altered,cat);assert.equal(edited.editorGround72.find(t=>t.x===at.x&&t.y===at.y).material,'water173');console.log('PASS both legacy waterfalls converted into 261 independent editable cells; a one-cell edit persists');
