const{chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const base=process.argv[2]||'http://127.0.0.1:5179',p=await b.newPage({timezoneId:'America/Los_Angeles'});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.evaluate(async()=>{const{world}=await import('/src/world.js?v=20260911-power-story-v27');window.testWorld=world;});const report=await p.evaluate(async()=>{
 const{G:S,makeMon,newGame,loadInto}=await import('/src/state.js');const{newMove}=await import('/src/data/moves.js');const{MAPS}=await import('/src/data/maps.js');const{SPECIES}=await import('/src/data/species.js');const rules=await import('/src/powerRules.js');const{releaseMon}=await import('/src/marineRules.js');const{powerNpc,refreshPowerNpcs}=await import('/src/powerStory.js');const{ui}=await import('/src/ui.js');const{loadLocal}=await import('/src/save.js');const{solid}=await import('/src/tiles.js');const w=window.testWorld;w.busy=true;
 const check=(x,m)=>{if(!x)throw Error(m);};const original={say:ui.say,choice:ui.choice,ask:ui.ask,timeout:window.setTimeout,random:Math.random,Date:window.Date};const messages=[];ui.say=async lines=>messages.push(...lines);ui.ask=async()=>true;ui.choice=async()=>0;window.setTimeout=(fn,ms,...args)=>original.timeout.call(window,fn,Math.min(ms,5),...args);Math.random=()=>.5;
 const enter=(id,x,y)=>{w.enter(id,x,y,'up');w.busy=true;};const talk=async script=>{const n=w.npcs.find(n=>n.script===script);check(n,'Missing NPC '+script);await powerNpc(w,n);};
 const hero=()=>{const m=makeMon('ラテット',100);m.moves=[newMove('タックル')];m.moves[0].pp=999;S.save.party=[m];};
 try{
 S.save=newGame('試験');S.save.flags['v5:dex']=true;S.save.flags['v5:netGift']=true;S.save.flags['marine:passed']=true;S.save.badges=['マリンエンブレム'];hero();
 // All visible characters, doors, and their destination tiles remain reachable.
 const structure=[];for(const [id,m]of Object.entries(MAPS)){const q=[[m.spawn.x,m.spawn.y]],seen=new Set(),at=(x,y)=>m.rows[y]?.[x];while(q.length){const[x,y]=q.shift(),k=x+','+y;if(seen.has(k)||at(x,y)==null||solid(at(x,y)))continue;seen.add(k);q.push([x+1,y],[x-1,y],[x,y+1],[x,y-1]);}for(const wp of m.warps){check(seen.has(wp.x+','+wp.y),'Unreachable '+id+' door');if(MAPS[wp.to])check(!solid(MAPS[wp.to].rows[wp.ty]?.[wp.tx]),'Blocked arrival '+id+'→'+wp.to);}for(const e of m.enc?.list||[])check(SPECIES[e[0]],'Missing species '+e[0]);structure.push([id,seen.size]);}
 check(MAPS.route5.rows[0].length>=60,'Road5 too short');check(MAPS.karat.props.filter(p=>p.art.startsWith('flowers')).length>=30,'Flower town missing beds');
 check(MAPS.route6.enc.list.map(x=>x[0]).join(',')==='ジリジリ,ハネデン','Route6 encounters');check(MAPS.radenInside.enc.encAll&&MAPS.radenInside.enc.list[2][3]===1&&MAPS.radenInside.enc.list[3][3]===1,'Factory rare encounters');
 enter('karatPort',14,22);await talk('power:ferry');check(w.mapId==='karatPort','Boat opened early');
 enter('raden',17,15);const door=MAPS.raden.warps.find(w=>w.to==='radenInside');await w.doWarp(door);check(w.mapId==='raden','Factory gate opened early');
 enter('karat',17,20);await talk('power:guide');check(S.save.flags['power:briefed'],'No briefing');
 enter('raden',17,15);await talk('power:director');check(S.save.flags['power:director'],'Jinel not defeated');check(w.npcs.find(n=>n.script==='power:director').x===19,'Door still blocked');
 await w.doWarp(door);check(w.mapId==='radenInside','Factory not unlocked');w.busy=true;await talk('power:chest');check(rules.powerOutage(S.save),'Chest no blackout');check(!S.save.flags['power:restored'],'Chest awarded win early');
 const saved=loadLocal();loadInto(saved);check(rules.powerOutage(S.save),'Blackout lost on load');enter('radenInside',3,3);await w.doWarp(MAPS.radenInside.warps.find(x=>x.x===2));check(w.mapId==='raden','Short exit failed');w.busy=true;
 check(!w.npcs.find(n=>n.script==='power:storyRaimei').gone,'Storm Raimei absent');check(w.npcs.find(n=>n.script==='power:weeklyRaimei').gone,'Weekly spawned early');
 await talk('power:storyRaimei');check(S.save.flags['power:restored']&&!rules.powerOutage(S.save),'Raimei failed to restore power');check(!S.save.flags['power:passed'],'Badge should require report');
 await talk('power:director');check(S.save.flags['power:passed']&&S.save.bag[rules.FERRY_TICKET]===1,'Missing ticket');check(S.save.badges.filter(x=>x===rules.KARAT_EMBLEM).length===1,'Missing emblem');const cash=S.save.money;await talk('power:director');check(S.save.money===cash&&S.save.badges.length===2,'Duplicate reward');
 enter('karatPort',14,22);await talk('power:ferry');check(w.mapId==='resurePort'&&S.save.bag[rules.FERRY_TICKET]===1,'Ferry forward failed');check(loadLocal().where.map==='resurePort','Arrival not saved');await talk('power:ferry');check(w.mapId==='karatPort','Return ferry failed');
 const date=s=>new original.Date(s);const sat=date('2026-09-12T00:00:00Z'),sun=date('2026-09-13T00:00:00Z'),satPM=date('2026-09-12T08:00:00Z'),nextSat=date('2026-09-19T00:00:00Z'),nextSun=date('2026-09-20T00:00:00Z');
 for(const[t,yes]of [['2026-09-11T23:59:59Z',false],['2026-09-12T00:00:00Z',true],['2026-09-12T03:59:59Z',true],['2026-09-12T04:00:00Z',false],['2026-09-12T07:59:59Z',false],['2026-09-12T08:00:00Z',true],['2026-09-12T08:59:59Z',true],['2026-09-12T09:00:00Z',false],['2026-09-13T00:00:00Z',true],['2026-09-13T04:00:00Z',false],['2026-09-13T08:00:00Z',false],['2026-09-14T00:00:00Z',false]])check(!!rules.raimeiAvailable(S.save,date(t))===yes,'Schedule '+t);
 rules.markRaimeiVisit(S.save,sat);check(!rules.raimeiAvailable(S.save,satPM)&&!rules.raimeiAvailable(S.save,sun)&&rules.raimeiAvailable(S.save,nextSat),'Saturday weekly cooldown');rules.markRaimeiVisit(S.save,sun);check(!rules.raimeiAvailable(S.save,nextSat)&&rules.raimeiAvailable(S.save,nextSun),'Sunday same-window cooldown');
 rules.markRaimeiVisit(S.save,satPM);check(!rules.raimeiAvailable(S.save,nextSat)&&rules.raimeiAvailable(S.save,date('2026-09-19T08:00:00Z')),'PM cooldown');
 delete S.save.flags['power:raimeiAfter'];S.save.box=[makeMon('ライメイ',20)];check(!rules.raimeiAvailable(S.save,sat),'Owned box spawned');releaseMon(S.save,'box',0,sat);check(!rules.raimeiAvailable(S.save,sun)&&rules.raimeiAvailable(S.save,nextSat),'Box release cooldown');S.save.party.push(makeMon('ライメイ',20));check(!rules.raimeiAvailable(S.save,nextSat),'Owned party spawned');releaseMon(S.save,'party',1,sat);check(rules.raimeiAvailable(S.save,nextSat),'Party release');
 // Exercise the real weekly encounter and persist its cooldown before battle.
 window.Date=class extends original.Date{constructor(...a){super(...(a.length?a:['2026-09-19T00:00:00Z']));}static now(){return new original.Date('2026-09-19T00:00:00Z').getTime();}};
 hero();enter('raden',25,10);check(!w.npcs.find(n=>n.script==='power:weeklyRaimei').gone,'Visible weekly NPC absent');await talk('power:weeklyRaimei');check(loadLocal().flags['power:raimeiAfter']===date('2026-09-26T00:00:00Z').getTime(),'Encounter cooldown not persisted');check(w.npcs.find(n=>n.script==='power:weeklyRaimei').gone,'Defeated NPC remains');
 delete S.save.flags['power:raimeiAfter'];S.save.party=[];S.save.box=[];S.save.bag={'マスターラグ':1}; // Capture with actual battle engine; start directly because story requires a healthy party.
 const{startBattle}=await import('/src/battle.js');const caught=await startBattle({wild:makeMon('ライメイ',20),...rules.RAIMEI_BATTLE});check(caught==='caught'&&S.save.party[0].sp==='ライメイ','Capture failed');check(!rules.raimeiAvailable(S.save,date('2026-09-26T00:00:00Z')),'Captured respawned');
 return{maps:structure.length,story:'Jinel, maze chest, persisted outage, Raimei, emblem and ticket passed',travel:'two-way ferry and arrival save passed',calendar:'Japan schedule tested in Los Angeles browser; all edges, weekly defeat and release passed',capture:caught,messages:messages.length};
 }finally{ui.say=original.say;ui.choice=original.choice;ui.ask=original.ask;window.setTimeout=original.timeout;Math.random=original.random;window.Date=original.Date;w.busy=false;}
 });if(errors.length)throw Error(errors.join(' / '));console.log(JSON.stringify(report));fs.writeFileSync('artifacts/power-story-v27-'+(base.includes('127')?'local':'production')+'.json',JSON.stringify(report,null,2));}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
