const fs=require('fs'),assert=require('assert/strict');const {chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const base=process.argv[2]||'http://127.0.0.1:5179',browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const p=await browser.newPage({viewport:{width:430,height:932},isMobile:true,hasTouch:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/gaon-zukan/');
const results=await p.evaluate(async()=>{
 const {SPECIES:S,STAT_KEYS:K}=await import('/src/data/species.js');const st=await import('/src/state.js');const check=(v,m)=>{if(!v)throw Error(m)};
 check(Object.keys(S).length===153,'species count');let generated=0;
 for(const [name,s]of Object.entries(S)){check(K.every(k=>Number.isInteger(s.base[k])&&s.base[k]>0),'base '+name);check(K.reduce((n,k)=>n+s.evYield[k],0)>=1,'yield '+name);const m=st.makeMon(name,50);check(K.every(k=>Number.isInteger(m.iv[k])&&m.iv[k]>=0&&m.iv[k]<=31),'iv '+name);check(st.evTotal(m)===0,'initial EV');check(K.every(k=>Number.isFinite(st.statOf(m,k))),'finite');generated++;}
 const iv=Object.fromEntries(K.map(k=>[k,31])),ev={hp:252,atk:252,spd:6};const m=st.makeMon('コケゴロ',100,{iv,ev});check(st.maxHp(m)===2*S[m.sp].base.hp+31+63+110,'HP formula');check(st.statOf(m,'atk')===2*S[m.sp].base.atk+31+63+5,'attack formula');check(st.evTotal(m)===510,'total');const saved=JSON.stringify(m.ev);for(const name of Object.keys(S))st.gainEffort(m,name);check(JSON.stringify(m.ev)===saved,'cap');
 const growing=st.makeMon('コケゴロ',100,{iv:Object.fromEntries(K.map(k=>[k,0]))});const foe=Object.keys(S).find(n=>S[n].evYield.hp);const before=st.maxHp(growing);growing.hp-=5;for(let i=0;i<300;i++)st.gainEffort(growing,foe);check(growing.ev.hp===252,'per-stat cap');check(st.maxHp(growing)>before&&st.maxHp(growing)-growing.hp===5,'HP deficit preserved');const frozen=JSON.stringify(growing.ev);growing.hp=0;st.gainEffort(growing,'ラテット');check(JSON.stringify(growing.ev)===frozen&&growing.hp===0,'fainted gain');
 const damaged=st.makeMon('ヨルネコ',27);damaged.iv={hp:15,atk:7,def:3,spc:8,spd:9};delete damaged.statVersion;delete damaged.ev;damaged.hp=10;const oldHp=Math.floor((S[damaged.sp].base.hp+15)*2*27/100)+27+10;const oldAtk=Math.floor((S[damaged.sp].base.atk+7)*2*27/100)+5;
 const data=st.newGame('test');data.party=[damaged];data.box=[JSON.parse(JSON.stringify(damaged))];data.box[0].hp=0;st.loadInto(data);check(st.maxHp(damaged)===oldHp&&st.statOf(damaged,'atk')===oldAtk,'legacy strength');check(damaged.iv.atk===14&&damaged.iv.sdef===16,'legacy mapping');check(damaged.hp===10&&st.G.save.box[0].hp===0,'legacy HP');const once=JSON.stringify(st.G.save);st.loadInto(JSON.parse(once));check(JSON.stringify(st.G.save)===once,'idempotent');
 const round=JSON.parse(JSON.stringify(m));st.normalizeMonStats(round);check(JSON.stringify(round)===JSON.stringify(m),'new save stable');const prior=JSON.stringify(round.iv),training=JSON.stringify(round.ev);round.sp='コケトロッコ';check(JSON.stringify(round.iv)===prior&&JSON.stringify(round.ev)===training,'evolution retains');const c=st.makeMon('コケゴロ',27);check(!st.gainExp(c,1000000).evolve,'Kokegoro stays');
 const special=st.makeMon('アワミィ',50,{iv:Object.fromEntries(K.map(k=>[k,0]))});const atkBefore=st.statOf(special,'spc');special.ev.sdef=252;check(st.statOf(special,'spc')===atkBefore&&st.statOf(special,'sdef')>atkBefore,'special defense independent');
 return {generated,legacyMigration:true,limits:true,formula:true,kokegoro:true,sixStats:K.length};
});assert.equal(await p.locator('article details.base-stats').count(),153);await p.locator('#search').fill('コケゴロ');await p.locator('article:visible details.base-stats summary').click();await p.screenshot({path:'artifacts/training-catalog.png'});
if(base.includes('127.0.0.1')){await p.goto(base+'/?v4test=route1');await p.waitForFunction(()=>window.VM);await p.waitForTimeout(500);
 await p.evaluate(async()=>{const st=await import('/src/state.js');window.trainingMon=st.makeMon('コケゴロ',100);trainingMon.moves=[(await import('/src/data/moves.js')).newMove('たいあたり')];VM.State.save.party=[trainingMon];const foe=st.makeMon('ネズミン',1);foe.hp=1;VM.startBattle({wild:foe});});
 for(let i=0;i<35;i++){await p.locator('#ba').tap();await p.waitForTimeout(100);if(await p.evaluate(()=>Object.values(trainingMon.ev).some(n=>n>0)))break;}
 assert.ok(await p.evaluate(()=>Object.values(trainingMon.ev).some(n=>n>0)),'actual battle effort award');
 await p.goto(base+'/?v4test=route1');await p.waitForFunction(()=>window.VM);await p.waitForTimeout(500);await p.evaluate(async()=>{const {ui}=await import('/src/ui.js');ui.clear();const {showStatus}=await import('/src/menu.js');showStatus(VM.makeMon('コケゴロ',30));});await p.waitForTimeout(200);await p.keyboard.press('ArrowRight');await p.waitForTimeout(200);await p.screenshot({path:'artifacts/training-status.png'});
}
assert.deepEqual(errors,[]);console.log(JSON.stringify({base,...results,errors}));fs.writeFileSync('artifacts/training-verification.json',JSON.stringify({base,...results,errors},null,2));}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
