const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),L=require(root+'/api/_lib'),F=require(root+'/api/_friendStore');
const admin={id:'ヤノケン',created:1789724902905,display:'ヤノケン'},ordinary={id:'tester',created:1};L.setPw(admin,'test-only-password');let docs={};L.readUser=async id=>id===admin.id?admin:id==='tester'?ordinary:null;L.findUser=async name=>name===admin.id?admin:null;L.configured=()=>true;F.read=async keys=>Object.fromEntries(keys.filter(k=>docs[k]).map(k=>[k,structuredClone(docs[k])]));F.commit=async(expected,writes)=>{if(Object.entries(expected).some(([k,v])=>(docs[k]?.version||0)!==v))return false;for(const[k,v]of Object.entries(writes))docs[k]={version:(docs[k]?.version||0)+1,data:structuredClone(v)};return true;};
const handler=require(root+'/api/map-editor'),auth=require(root+'/api/auth');
const mime={'.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp3':'audio/mpeg'};
const server=http.createServer(async(req,res)=>{res.status=c=>{res.statusCode=c;return res};res.json=v=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(v))};const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){let body='';for await(const b of req)body+=b;try{req.body=JSON.parse(body||'{}');}catch{req.body={};}if(url.pathname==='/api/map-editor')return handler(req,res);if(url.pathname==='/api/auth')return auth(req,res);return res.status(200).json({});}let file=path.join(root,decodeURIComponent(url.pathname));if(!file.startsWith(path.normalize(root)))return res.status(403).end();try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);}catch{res.status(404).end();}});
(async()=>{await new Promise(r=>server.listen(5183,'127.0.0.1',r));const url=require('url'),m=await import(url.pathToFileURL(root+'/src/editorModel72.mjs')),e=await import(url.pathToFileURL(root+'/src/elevation75.mjs')),links=await import(url.pathToFileURL(root+'/src/connections75.mjs'));const maps=require(root+'/assets/editor-v72/base-maps.json'),cat=m.catalog(maps,require(root+'/assets/editor-v72/species.json'));
const flat={...m.clone(maps.village),id:'flat75',rows:Array.from({length:20},()=>','.repeat(30)),props:[],npcs:[],warps:[],signs:[],items:[],spawn:{x:1,y:1},forestBorder:false,townGardens:[],townPond:null};let d=m.initial(flat);for(let y=4;y<=7;y++)for(let x=4;x<=9;x++)d.elevations.push({x,y,level:1});assert(m.validateEdit(flat,d,cat).some(s=>s.includes('高台')));d.climbs.push({x:6,y:8,kind:'ladder'});assert.deepEqual(m.validateEdit(flat,d,cat),[]);let elevated=m.applyEdit(flat,d,cat);assert.equal(e.canTraverse75(elevated,6,8,6,7),true);assert.equal(e.canTraverse75(elevated,6,7,6,8),true);assert.equal(e.canTraverse75(elevated,5,8,5,7),false);assert.equal(e.canTraverse75(elevated,3,5,4,5),false);for(const kind of ['stairs','ramp']){d.climbs[0].kind=kind;assert.deepEqual(m.validateEdit(flat,d,cat),[]);}const illegal=m.clone(d);illegal.climbs[0].y=6;assert(m.validateEdit(flat,illegal,cat).length);const two=m.clone(d);two.elevations.find(t=>t.x===6&&t.y===7).level=2;assert(m.validateEdit(flat,two,cat).length);
const gate=m.initial(flat);gate.objects.push({id:'a:gate',type:'prop',template:'garden75-extra-brick-gate',x:12,y:4});assert.deepEqual(m.validateEdit(flat,gate,cat),[]);const gm=m.applyEdit(flat,gate,cat);assert.equal(m.pass(gm,12,4),false);assert.equal(m.pass(gm,13,4),true);assert.equal(m.pass(gm,13,5),true);assert.equal(m.pass(gm,14,5),false);
const request=async body=>{const r=await fetch('http://127.0.0.1:5183/api/map-editor',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+L.makeToken('ヤノケン')},body:JSON.stringify(body)});return {status:r.status,data:await r.json()}};
let vd=m.initial(maps.village),spot;for(let y=4;y<maps.village.rows.length-4&&!spot;y++)for(let x=3;x<maps.village.rows[0].length-4&&!spot;x++){const q=m.clone(vd);q.objects.push({id:'a:gate',type:'prop',template:'garden75-extra-brick-gate',x,y});if(m.validateEdit(maps.village,q,cat).length)continue;q.links.push({id:'a:link',x:x+1,y:y+1,to:'adminHouse72',tx:7,ty:11,paired:true,sourceDir:'down',destDir:'up'});const views={...maps,village:m.applyEdit(maps.village,q,cat)};if(!links.validateLinks75(views).length){spot={x,y};vd=q;}}assert(spot,'placeable gate with room connection');assert.deepEqual(m.validateEdit(maps.village,vd,cat),[]);assert.equal((await request({action:'publish',map:'village',edit:vd,revision:0,publicRevision:0})).status,200);
const bad=m.clone(vd);bad.links[0].tx=0;const rejected=await request({action:'save',map:'village',edit:bad,revision:1});assert.equal(rejected.status,400);const badMap=m.clone(vd);badMap.links[0].to='https://invalid.example';assert(m.validateEdit(maps.village,badMap,cat).length);const block=m.initial(maps.adminHouse72);block.tiles.push({x:7,y:10,material:'wall'});assert.equal((await request({action:'save',map:'adminHouse72',edit:block,revision:0})).status,400);
const {chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const errors=[],p=await browser.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',x=>errors.push(x.message));await p.goto('http://127.0.0.1:5183/map-editor/');await p.locator('#password').fill('test-only-password');await p.locator('#loginForm button').click();await p.waitForFunction(()=>!document.getElementById('app').hidden);await p.locator('#mapSelect').selectOption('village');await p.waitForFunction(()=>!document.querySelector('.layout').inert);for(const[group,count]of [['paths',33],['decor',54],['terrain',7],['links',1]]){await p.locator('[data-category="'+group+'"]').click();assert.equal(await p.locator('#materials button').count(),count,group);}
// Published links must be loaded into the actual game's maps in both directions.
const game=await browser.newPage();game.on('pageerror',x=>errors.push(x.message));await game.goto('http://127.0.0.1:5183/');await game.waitForFunction(()=>window.VM);const travel=await game.evaluate(async s=>{const {MAPS}=await import('/src/data/maps.js?v=20260913-fashion-v50');VM.State.save=VM.newGame();const w=VM.world;w.enter('village',s.x+1,s.y+2,'up');const forward=MAPS.village.warps.find(p=>p.editorLink75);await w.doWarp(forward);const first={map:w.mapId,x:w.x,y:w.y};const back=MAPS.adminHouse72.warps.find(p=>p.editorLink75);await w.doWarp(back);return {first,last:{map:w.mapId,x:w.x,y:w.y},forward,back};},spot);assert.equal(travel.first.map,'adminHouse72');assert.equal(travel.first.x,7);assert.equal(travel.first.y,10);assert.equal(travel.last.map,'village');assert.equal(travel.back.tx,spot.x+1);assert.equal(travel.back.ty,spot.y+2);
// Runtime free movement crosses only the ladder column; both ascent and descent work.
const movement=await game.evaluate(async map=>{const w=VM.world;w.map=map;w.mapId='village';w.npcs=[];w.busy=false;const move=(x,y,key,n)=>{w.fx=w.x=x;w.fy=w.y=y;document.dispatchEvent(new KeyboardEvent('keydown',{code:key,bubbles:true}));for(let i=0;i<n;i++)w.updateFree(16);document.dispatchEvent(new KeyboardEvent('keyup',{code:key,bubbles:true}));return {x:w.fx,y:w.fy};};return {blocked:move(5.5,8.5,'ArrowUp',12),up:move(6.5,8.5,'ArrowUp',22),down:move(6.5,7.5,'ArrowDown',22)};},elevated);assert(movement.blocked.y>=8);assert(movement.up.y<8);assert(movement.down.y>=8);
const images=await p.evaluate(async()=>{const {PATHS75,OBJECTS75}=await import('/src/gardenCatalog75.mjs'),{EXTRA75}=await import('/src/extraCatalog75.mjs');await Promise.all([...PATHS75,...OBJECTS75,...EXTRA75].map(async a=>{const im=new Image();im.src='/'+a.file;await im.decode();}));return true;});assert(images);
// The inspector exposes destination, arrival side and return link controls.
await p.locator('#selectTool').click();const box=await p.locator('#mapCanvas').boundingBox(),scale=box.width/(maps.village.rows[0].length*32);await p.mouse.click(box.x+(spot.x+1.5)*32*scale,box.y+(spot.y+1.5)*32*scale);assert((await p.locator('#selection').innerText()).includes('移動先マップ'));assert.equal(await p.locator('#selection select').first().inputValue(),'adminHouse72');await p.screenshot({path:'work/admin72/screens/connections75.png'});
const showcase=await browser.newPage({viewport:{width:1150,height:920}});await showcase.goto('http://127.0.0.1:5183/map-editor/');await showcase.evaluate(async()=>{const {PATHS75,OBJECTS75}=await import('/src/gardenCatalog75.mjs'),{EXTRA75}=await import('/src/extraCatalog75.mjs'),{drawNature73}=await import('/src/natureArt73.js');document.body.innerHTML='<canvas id="gallery" width="1150" height="920"></canvas>';const c=document.querySelector('canvas').getContext('2d'),assets=[...PATHS75,...OBJECTS75,...EXTRA75];const paint=()=>{c.fillStyle='#c3dab0';c.fillRect(0,0,1150,920);assets.forEach((a,i)=>{const x=15+i%10*113,y=10+Math.floor(i/10)*115;c.fillStyle='#6d995b';c.fillRect(x,y,100,88);drawNature73(c,a.key,x+10,y+4,80,80);c.fillStyle='#203e34';c.font='11px sans-serif';c.fillText(a.label,x,y+103,107);});};setInterval(paint,100);});await showcase.waitForTimeout(2200);await showcase.screenshot({path:'work/admin72/screens/garden-gallery75.png'});
await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'work/admin72/screens/mobile75.png'});assert.deepEqual(errors,[]);console.log('PASS v75: 54 images decode, 33 path choices, 54 decor choices, 6 grounds; 0/1/2 height reachability; cliff collision; ladder ascent/descent; gate passage; API blocked landing rejection; actual game outdoor/indoor round trip; mobile UI; no page errors');}finally{await browser.close();}server.close();})().catch(e=>{console.error(e);server.close();process.exitCode=1});
