const {chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict'),fs=require('node:fs'),cp=require('node:child_process'),root=require('node:path').resolve(__dirname,'..').replaceAll('\\','/');process.env.TEMP=root+'/work/tmp';process.env.TMP=process.env.TEMP;
const old=cp.execFileSync('C:/Program Files/Git/cmd/git.exe',['show','HEAD:src/data/chapterOne.js'],{cwd:root,encoding:'utf8'});fs.writeFileSync(root+'/work/tmp/chapter-before-fixes.js',old);
(async()=>{const c=await chromium.launchPersistentContext(root+'/work/sept8-fixes',{executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,viewport:{width:430,height:932},isMobile:true,hasTouch:true});const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));try{await p.goto('http://127.0.0.1:5179/?v4test=village');await p.waitForFunction(()=>!!window.VM);await p.waitForTimeout(500);
const report=await p.evaluate(async()=>{const {MAPS}=await import('/src/data/maps.js?v=20260909-world-v12');const {buildChapterOne}=await import('/work/tmp/chapter-before-fixes.js');const before=buildChapterOne().village,after=MAPS.village;const {chapterTravelHint,chapterNpc}=await import('/src/chapterStory.js');const hints=[],prof=[],witness=[];const say=VM.ui.say;VM.ui.say=async lines=>{window.__lines.push(...lines)};try{let flags={};for(const next of [null,'v5:heardLatett','v5:latettSeen','v5:netGift','v5:dex']){if(next)flags[next]=1;VM.State.save.flags={...flags};hints.push(chapterTravelHint().join(''));if(next!=='v5:latettSeen'){window.__lines=[];await chapterNpc(VM.world,{script:'v5:professor'});prof.push(window.__lines.join(''));}if(next==='v5:netGift'||next==='v5:dex'){window.__lines=[];await chapterNpc(VM.world,{script:'v5:witness'});witness.push(window.__lines.join(''));}}
}finally{VM.ui.say=say;VM.State.save.flags={};}
return {topSame:before.rows[0]===after.rows[0],bottomSame:before.rows.at(-1)===after.rows.at(-1),borders:after.rows.slice(1,-1).every(r=>r.slice(0,2)==='TT'&&r.slice(-2)==='TT'),trees:after.props.filter(p=>p.x===0||p.x===32).length,hints,prof,witness};});
assert.ok(report.topSame&&report.bottomSame&&report.borders);assert.equal(report.trees,18);assert.ok(!report.hints[0].includes('ラテット')&&!report.hints[0].includes('報告'));assert.ok(report.hints[1].includes('さがし'));assert.ok(report.hints[2].includes('報告'));assert.ok(report.hints[3].includes('ヤノケン'));assert.ok(!report.prof[0].includes('ラテット'));assert.ok(report.prof.at(-1).includes('図鑑'));assert.ok(!report.witness[0].includes('教えてあげて'));
for(const [name,x,y] of [['lab-roof',27,21],['west-trees',3,16],['east-trees',30,16]]){await p.evaluate(({x,y})=>{VM.world.enter('village',x,y,'left');VM.setWorld();VM.world.showName=0},{x,y});await p.waitForTimeout(180);await p.screenshot({path:root+'/artifacts/fix-'+name+'.png'});}
await p.evaluate(()=>{VM.world.enter('village',16,28,'down');VM.world.doWarp(VM.world.map.warps.find(w=>w.y===28));});await p.waitForTimeout(800);await p.screenshot({path:root+'/artifacts/fix-first-gate-message.png'});
assert.deepEqual(errors,[]);console.log(JSON.stringify({...report,errors}));fs.writeFileSync(root+'/artifacts/sept8-fixes.json',JSON.stringify({...report,errors},null,2));}finally{await c.close()}})().catch(e=>{console.error(e);process.exitCode=1});
