const {chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.argv[2]||'http://127.0.0.1:5182/',{waitUntil:'networkidle'});
const report=await p.evaluate(async(baseline)=>{
const{SPECIES,DEX_ORDER}=await import('/src/data/species.js');const{V51_DESIGNS,WALK_V51_IDS}=await import('/src/data/redesignV51.js');const{SPECIES_RENAMES}=await import('/src/data/redesignV47.js');const{BATTLE_ART_FILES,battleArt}=await import('/src/data/battleart.js');const{MONART}=await import('/src/data/monart.js');const{makeMon,newGame,loadInto,G}=await import('/src/state.js');const{loadFollowerSheet,followerFrame,drawFollower}=await import('/src/followerArt.js');
if(DEX_ORDER.length!==153)throw Error('Dex count changed');
for(const[old,name]of Object.entries(SPECIES_RENAMES)){if(SPECIES[old]!==SPECIES[name])throw Error('Alias mismatch '+old);if(makeMon(old,10).sp!==name)throw Error('Save alias '+old);}
const oldByNo=new Map(Object.values(baseline.species).map(s=>[s.no,s]));
for(const name of DEX_ORDER){const s=SPECIES[name],old=oldByNo.get(s.no);if(!old)throw Error('Missing baseline');for(const[k,v]of Object.entries(old.base)){const expected=s.no===118&&k==='hp'?80:s.no===118&&k==='atk'?120:s.no===130&&k==='spc'?130:s.no===130&&k==='atk'?74:s.no===130&&k==='spd'?100:v;if(s.base[k]!==expected)throw Error('Unexpected stat '+name+' '+k+' '+s.base[k]);}}
const canvas=document.createElement('canvas');canvas.width=960;canvas.height=Math.ceil(WALK_V51_IDS.size/4)*130;const ctx=canvas.getContext('2d');ctx.fillStyle='#acd6b5';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.imageSmoothingEnabled=false;let n=0;
for(const id of WALK_V51_IDS){const name=DEX_ORDER.find(n=>SPECIES[n].no===id);if(!await loadFollowerSheet(name))throw Error('No sheet '+name);const x=n%4*240,y=Math.floor(n/4)*130;ctx.fillStyle='#173b41';ctx.font='14px sans-serif';ctx.fillText(name,x+8,y+18);for(let d=0;d<4;d++){const hashes=[];for(let row=0;row<3;row++){const f=followerFrame(name,['down','up','right','left'][d],row);hashes.push(f.toDataURL());const pixels=f.getContext('2d').getImageData(0,0,80,80).data;let count=0;for(let i=0;i<pixels.length;i+=4){if(pixels[i+3])count++;}if(count<40)throw Error('Empty pose '+name);ctx.drawImage(f,x+d*60,y+24+row*32,36,36);}if(new Set(hashes).size!==3)throw Error('Duplicate stride '+name);}
const mc=document.createElement('canvas');mc.width=mc.height=100;const mctx=mc.getContext('2d');const render=(tick,moving)=>{mctx.clearRect(0,0,100,100);drawFollower(mctx,{sp:name},{dir:'down',moving},tick,50,80);return mc.toDataURL()};if(render(0,true)===render(260,true))throw Error('Animation not cycling '+name);n++;}
for(const row of V51_DESIGNS){if(!MONART[row.name])throw Error('Missing mon art gate '+row.name);if(!BATTLE_ART_FILES[row.name].includes('redesign-v51'))throw Error('Old battle art '+row.name);}
const save=newGame('検証');save.party=[makeMon('ツチマル',17)];save.party[0].sp='ツチマル';loadInto(save);if(G.save.party[0].sp!=='ポコリズ')throw Error('Load migration');
return{count:n,designs:V51_DESIGNS.length,image:canvas.toDataURL()};},JSON.parse(fs.readFileSync('api/_friendCatalog.json','utf8')));
fs.writeFileSync('artifacts/walking-v51-contact.png',Buffer.from(report.image.split(',')[1],'base64'));assert.deepEqual(errors,[]);console.log('PASS',report.count,'walking sheets, 12 distinct poses each;',report.designs,'redesigns; stats and save aliases');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});

