const {chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),crypto=require('crypto'),fs=require('fs'),B=require('../api/_friendBattle');
const base=process.env.FRIEND_TEST_URL||'http://127.0.0.1:5182';
const losses={};async function loseReply(page,action){await page.route('**/api/friends',async route=>{const data=route.request().postDataJSON();if(data.action===action&&!losses[action]){losses[action]=true;await route.fetch();await route.abort('failed');}else await route.continue();});}

(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const pages=[],errors=[],users=[];
try{for(let i=0;i<2;i++){const ctx=await browser.newContext({viewport:{width:430,height:932},isMobile:true,hasTouch:true});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('response',async r=>{if(r.url().includes('/api/')&&r.status()>=400){let d={};try{d=await r.json()}catch{}console.log('API failure',r.status(),new URL(r.url()).pathname,d.message||'');}});await p.goto(base);const pw=crypto.randomBytes(12).toString('hex'),name='uitest'+i+Date.now().toString(36);const u=await(await fetch(base+'/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'signup',name,pw})})).json();users.push({...u,pw});
const party=['トリッピ','アワミィ','リーフィン'].map((sp,n)=>({...B.combatMon({sp,lv:25,companionId:crypto.randomUUID(),moves:[{name:'タックル'}]},25),exp:15625}));
await p.evaluate(async({u,party})=>{const {cloud}=await import('/src/cloud.js');const {G}=await import('/src/state.js');cloud.setToken(u.token);cloud.user=u.user;cloud.rev=0;G.save.party=party;G.save.name=u.user.display;G.save.box=[];const{openFriends}=await import('/src/friends.js');window.friendPromise=openFriends();},{u,party});await p.locator('#friends h1').waitFor({timeout:60000}).catch(async e=>{await p.screenshot({path:'artifacts/friends-v39-failure.png'});console.log('UI errors',errors);throw e;});pages.push(p);}
const[a,b]=pages;await a.screenshot({path:'artifacts/friends-disconnect-home.png'});
async function join(mode){await a.getByRole('button',{name:mode,exact:true}).click();await a.getByRole('button',{name:'ルームを作る',exact:true}).click();await a.locator('.friend-code strong').waitFor();const code=await a.locator('.friend-code strong').innerText();await b.getByLabel('合言葉',{exact:true}).fill(code);await b.getByRole('button',{name:'参加する',exact:true}).click();await b.locator('.friend-code').waitFor();}
async function reopen(){for(const p of pages){await p.evaluate(async()=>{const{openFriends}=await import('/src/friends.js');window.friendPromise=openFriends()});await p.locator('#friends h1').waitFor();}}
async function leave(){await a.getByRole('button',{name:'閉じる',exact:true}).click();await a.getByRole('button',{name:'ルームを退出する',exact:true}).click();await a.locator('#friends').waitFor({state:'detached'});await b.getByRole('button',{name:'冒険に戻る',exact:true}).click();await b.locator('#friends').waitFor({state:'detached'});}
const stale=await a.evaluate(async()=>JSON.parse(JSON.stringify((await import('/src/state.js')).G.save)));await join('ガオン交換');await a.getByLabel('交換するガオン').selectOption('party:0');await b.getByLabel('交換するガオン').selectOption('party:1');await a.getByRole('button',{name:'相手のガオンを確認して交換を確定'}).click();await loseReply(b,'confirm');await b.getByRole('button',{name:'相手のガオンを確認して交換を確定'}).click();for(const p of pages){await p.getByRole('button',{name:'冒険に戻る'}).waitFor();await p.getByRole('button',{name:'冒険に戻る'}).click();await p.locator('#friends').waitFor({state:'detached'});}const species=await a.evaluate(async()=>(await import('/src/state.js')).G.save.party[0].sp);assert.equal(species,'アワミィ');await a.reload();await a.evaluate(async({stale,u})=>{const{cloud}=await import('/src/cloud.js');cloud.setToken(u.token);await cloud.restore();const{applySave}=await import('/src/save.js');applySave(stale);window.friendPromise=(await import('/src/friends.js')).openFriends();},{stale,u:users[0]});await a.getByRole('button',{name:'ルームを作る',exact:true}).waitFor();assert.equal(await a.evaluate(async()=>(await import('/src/state.js')).G.save.party[0].sp),'アワミィ');await a.getByRole('button',{name:'閉じる',exact:true}).click();await a.locator('#friends').waitFor({state:'detached'});
await reopen();await join('通信バトル');for(const p of pages){for(const c of await p.locator('.friend-select').all())await c.click();await p.getByRole('button',{name:'このガオンで準備完了'}).click();}await a.locator('.friend-battle').waitFor();await a.screenshot({path:'artifacts/friends-disconnect-battle.png'});await loseReply(a,'battle');await a.locator('.friend-commands button').first().click();await a.getByText('行動を送信しました。友だちの選択を待っています。').waitFor();await b.locator('.friend-commands button').first().click();await a.locator('.friend-commands').waitFor();await leave();
await reopen();await join('協力ダンジョン');for(const p of pages){await p.locator('.friend-select').first().click();await p.getByRole('button',{name:'このガオンで準備完了'}).click();}await a.locator('.friend-map').waitFor();await a.context().setOffline(true);await a.getByRole('button',{name:'↑',exact:true}).click();await a.getByRole('button',{name:'通信を再確認'}).waitFor();await a.context().setOffline(false);await a.getByRole('button',{name:'通信を再確認'}).click();await a.getByRole('button',{name:'通信を再確認'}).waitFor({state:'detached'});await a.unroute('**/api/friends');await loseReply(a,'walk');await a.getByRole('button',{name:'↑',exact:true}).click();await a.getByRole('button',{name:'通信を再確認'}).waitFor();await a.getByRole('button',{name:'通信を再確認'}).waitFor({state:'detached'});await a.screenshot({path:'artifacts/friends-disconnect-dungeon.png'});await leave();assert.deepEqual(errors,[]);assert(losses.confirm&&losses.battle&&losses.walk);console.log('PASS network recovery: dropped replies AFTER committed exchange, battle choice and movement; offline/reconnect; authoritative state restores without duplicate actions. UI: 2 mobile browsers, create/join, confirmed trade and updated save, Lv50 battle and synchronized actions, coop map movement, clean exit; no JS errors');
}finally{for(const u of users){await fetch(base+'/api/friends',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+u.token},body:JSON.stringify({action:'resume'})}).then(r=>r.json()).then(async r=>{if(r.room)await fetch(base+'/api/friends',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+u.token},body:JSON.stringify({action:'leave',code:r.room.code})})}).catch(()=>{});await fetch(base+'/api/account',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+u.token},body:JSON.stringify({action:'delete',pw:u.pw})}).catch(()=>{});}await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
