const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict'),{chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const response=await fetch('https://midori-no-shima.vercel.app/api/map-editor?check214='+Date.now());assert(response.ok);const pub=await response.text();fs.mkdirSync('artifacts/water217',{recursive:true});fs.writeFileSync('artifacts/water217/preview.json',pub);const server=http.createServer((q,r)=>{let name=new URL(q.url,'http://localhost').pathname;if(name==='/api/map-editor'){r.setHeader('Content-Type','application/json');return r.end(pub);}if(name.endsWith('/'))name+='index.html';const f=path.resolve('.'+decodeURIComponent(name));if(!f.startsWith(process.cwd()+path.sep))return r.writeHead(403).end();r.setHeader('Content-Type',/\.(js|mjs)$/.test(f)?'text/javascript':f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':f.endsWith('.json')?'application/json':f.endsWith('.png')?'image/png':'application/octet-stream');const stream=fs.createReadStream(f);stream.on('error',()=>r.writeHead(404).end());stream.pipe(r);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});fs.mkdirSync('artifacts/water217',{recursive:true});try{const p=await b.newPage({viewport:{width:1100,height:1250}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:'+server.address().port+'/?v4test=kageri',{waitUntil:'domcontentloaded',timeout:120000});await p.waitForFunction(()=>window.VM?.world?.mapId==='kageri',null,{timeout:180000});const result=await p.evaluate(async()=>{
 const {MAPS}=await import('/src/data/maps.js'),{SPECIES}=await import('/src/data/species.js'),{waterPool150,encounterRate150}=await import('/src/encounterTerrain150.mjs'),{filterWild91}=await import('/src/wildAvailability91.mjs'),{habitatEntries}=await import('/src/habitats.js'),{enableBoat217,defaultWaterPool217}=await import('/src/waterEncounters217.mjs');
 const check=(v,msg)=>{if(!v)throw Error(msg);},maps=Object.values(MAPS).filter(m=>m.rows.some(r=>r.includes('W'))),seen=new Set();let checks=0;
 for(const m of maps){check(m.boatWater,'Boat unavailable '+m.id);const base=waterPool150(m,new Date('2026-10-04T03:00:00Z'),'inactive');check(base.length>=3,'Pool too small '+m.id);const key=base.map(e=>e[0]).sort().join();check(!seen.has(key),'Duplicate map pool '+m.id);seen.add(key);for(const [name,min,max,weight]of base){check(SPECIES[name]?.types.includes('みず'),'Not water type '+name);check(min<=max&&min>=1&&max<=100&&weight>0,'Invalid stats');check(habitatEntries(name).some(e=>e.mapId===m.id&&e.kind.startsWith('water')),'Missing water habitat '+m.id+' '+name);}
 for(let day=0;day<7;day++)for(let hour=0;hour<24;hour++){const now=new Date(Date.UTC(2026,9,4+day,hour-9));check(filterWild91(waterPool150(m,now),now,m.id).length>0,'Empty scheduled pool '+m.id);checks++;}
 check(encounterRate150(m,'W',true)===18,'Water rate '+m.id);
 }
 check(encounterRate150({enc:{rate:0}},'W',true)===18,'Zero land rate blocked water');
 check(encounterRate150({waterEncountersConfigured150:true,waterEncounters150:{rate:0}},'W',true)===0,'Custom override lost');
 check(waterPool150(MAPS.route6,new Date('2026-08-01T03:00:00Z')).some(e=>e[0]==='ウズシオヌシ'),'August event lost');
 check(!waterPool150(MAPS.route6,new Date('2026-09-01T03:00:00Z')).some(e=>e[0]==='ウズシオヌシ'),'August event leaked');
 check(enableBoat217({rows:['W.'],kind:'cave'}).boatWater,'New water map not supported');
 check(defaultWaterPool217('custom-new-map').every(([n])=>SPECIES[n]?.types.includes('みず')),'Fallback nonwater');
 const {useBoat}=await import('/src/endgameStory.js');VM.ui.say=async()=>{};let boarded=0;
 for(const id of ['marine','route6','gaonParkWetland']){VM.world.enter(id);const w=VM.world,solid=new Set('TRMW#rwSX=cbtKVPLs');let pos;for(let y=1;y<w.map.rows.length-1&&!pos;y++)for(let x=1;x<w.map.rows[0].length-1&&!pos;x++)if(w.map.rows[y][x]==='W')for(const [dx,dy,dir]of [[1,0,'left'],[-1,0,'right'],[0,1,'up'],[0,-1,'down']])if(!solid.has(w.map.rows[y+dy][x+dx])&&!w.npcAt(x,y)){pos={x:x+dx,y:y+dy,dir};break;}check(pos,'No shore '+id);Object.assign(w,pos);VM.State.save.boating=false;VM.State.save.bag['小型ボート']=1;await useBoat(w);check(VM.State.save.boating,'Could not board '+id);boarded++;}
 return {maps:maps.length,distinctPools:seen.size,timeChecks:checks,boardingTests:boarded};
});console.log(JSON.stringify(result));fs.writeFileSync("artifacts/water217/verification.json",JSON.stringify(result));assert.deepEqual(errors,[]);console.log('PASS map previews',errors);}finally{await b.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});