const assert=require('node:assert/strict'),fs=require('fs'),{chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
 const {setLanguage166,t166}=await import('../src/i18n166.mjs'),{SPECIES}=await import('../src/data/species.js'),{MOVES}=await import('../src/data/moves.js');
 const before=JSON.stringify({SPECIES,MOVES});setLanguage166('en');
 for(const key of [...Object.keys(SPECIES),...Object.keys(MOVES)])assert(!/[ぁ-龠]/.test(t166(key)),key);
 assert.equal(t166('Alex Smithは リーフィンを くりだした！'),'Alex Smith sent out Leafin!');assert.equal(t166('アカウント（Alex Smith）'),'Account (Alex Smith)');assert.equal(t166('あいての リーフィンの タックル！'),'Foe Leafin used Tackle!');setLanguage166('ja');assert.equal(t166('リーフィン'),'リーフィン');assert.equal(JSON.stringify({SPECIES,MOVES}),before);
 const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{
 const p=await b.newPage({viewport:{width:900,height:850}}),errors=[];p.on('pageerror',e=>(errors.push(e.message),console.error('PAGE ERROR',e.message)));
 if(process.env.BASE)await p.route('**/src/main.js*',async r=>{const response=await r.fetch();let body=await response.text();body=body.replace('if (/^(localhost|127.0.0.1)$/.test(location.hostname)) {','if (true) {').replace('if (/^(localhost|127.0.0.1)$/.test(location.hostname) && testMap)','if (testMap)');await r.fulfill({response,body});});
 await p.addInitScript(()=>{localStorage.setItem('gaon:welcome102:done','1');window.drawn166=[];const original=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(text,...args){if(window.drawn166.length<10000)window.drawn166.push(String(text));return original.call(this,text,...args);};});
 await p.goto((process.env.BASE||'http://127.0.0.1:5182')+'/?v4test=village',{waitUntil:'domcontentloaded',timeout:60000});
 await p.waitForFunction(()=>window.VM?.State.save?.name,null,{timeout:180000}).catch(async e=>{console.error(await p.evaluate(()=>({vm:!!window.VM,name:window.VM?.State?.save?.name,body:document.body.innerText.slice(0,700)})));throw e;});const saved=await p.evaluate(()=>JSON.stringify(VM.State.save));
 const rare=await p.evaluate(async()=>{const R=await import('/src/rareEncounters.js'),{MAPS}=await import('/src/data/maps.js');const seeded=R.createRareSpawns(7),again=R.createRareSpawns(7,seeded.spots),m=MAPS.mossSanctuary,rows=m.rows;let empty;try{m.rows=rows.map(r=>'W'.repeat(r.length));empty=R.createRareSpawns(7);}finally{m.rows=rows;}return {stable:JSON.stringify(seeded)===JSON.stringify(again),hasForest:R.rareCandidates('mossSanctuary').length>0,noInvalid:!empty.spots['コケゴロ']};});assert.deepEqual(rare,{stable:true,hasForest:true,noInvalid:true});
 await p.selectOption('#language166 select','en');assert.equal(await p.locator('html').getAttribute('lang'),'en');assert.equal(await p.evaluate(()=>JSON.stringify(VM.State.save)),saved);
 const wrap=await p.evaluate(async()=>{const G=await import('/src/gfx.js');return G.wrap('ガオン　という　いきものと、人がいっしょに　くらしている　世界だ。',250,15).map(s=>[s,G.textW(s,15)]);});assert(wrap.length>1);assert(wrap.every(([s,w])=>!/[ぁ-龠]/.test(s)&&w<=250));
 await p.evaluate(()=>{window.choice166=null;VM.ui.choice(['たたかう','どうぐ','ガオン','にげる'],{battle:true,columns:2,rows:2}).then(i=>window.choice166=i);});await p.waitForTimeout(500);assert(await p.evaluate(()=>drawn166.includes('Fight')&&drawn166.includes('Run')));
 await p.keyboard.down('ArrowRight');await p.evaluate(()=>VM.steps(1));await p.keyboard.up('ArrowRight');await p.keyboard.down('z');await p.evaluate(()=>VM.steps(1));await p.keyboard.up('z');await p.waitForFunction(()=>window.choice166!==null,null,{timeout:5000});assert.equal(await p.evaluate(()=>choice166),1);
 await require('./checkEnglish167Browser.cjs')(p);
 await p.evaluate(()=>{VM.ui.say(['ここは　ガオン・ワールド！','ガオン　という　いきものと、人がいっしょに　くらしている　世界だ。'],{speaker:'スイスはかせ'});});await p.waitForTimeout(1500);fs.mkdirSync('artifacts',{recursive:true});await p.screenshot({path:'artifacts/english166.png'});
 await p.selectOption('#language166 select','ja');assert.equal(await p.locator('html').getAttribute('lang'),'ja');await p.selectOption('#language166 select','en');await p.reload({waitUntil:'domcontentloaded'});await p.waitForSelector('#language166 select');assert.equal(await p.locator('#language166 select').inputValue(),'en');
 await p.evaluate(async()=>{const {showAuth}=await import('/src/gate.js');showAuth('login');});await p.waitForTimeout(300);assert.equal((await p.locator('#go').textContent()).trim(),'Log in');await p.fill('#who','Alex Smith');await p.selectOption('#language166 select','ja');assert.equal(await p.locator('#who').inputValue(),'Alex Smith');assert.equal((await p.locator('#go').textContent()).trim(),'ログイン');await p.setViewportSize({width:390,height:844});await p.selectOption('#language166 select','en');await p.screenshot({path:'artifacts/english-auth-mobile166.png'});assert.deepEqual(errors,[]);console.log('PASS 200 species + 292 moves, original identifiers, English wrapping, battle choice index, live switch, persistence, auth form and player input');
 }finally{await b.close();}
})().catch(e=>{console.error(e);process.exit(1)});
