const fs=require('fs'),assert=require('node:assert/strict'),{chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{
const published=await(await fetch('https://midori-no-shima.vercel.app/api/map-editor')).json();const p=await b.newPage();p.on('pageerror',e=>console.log('PAGE ERROR',e.message));await p.route('**/api/map-editor',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(published)}));await p.route('**/src/main.js*',r=>r.fulfill({body:''}));await p.goto(process.env.BASE||'http://127.0.0.1:5182',{waitUntil:'domcontentloaded',timeout:60000});
const data=await p.evaluate(async()=>{const {MAPS}=await import('/src/data/maps.js'),A=await import('/src/chapterArt.js'),N=await import('/src/npcArt.js'),E=await import('/src/editorModel72.mjs'),C=await import('/src/customMaps82.mjs'),M=await import('/src/managedPeople120.mjs'),F=await import('/map-editor/connectionFrames113.js');const bases=C.extendMaps82(M.addManagedPeople120(await(await fetch('/assets/editor-v72/base-maps.json')).json())),cat=E.catalog(bases,[]);window.draw160=()=>{const c=document.createElement('canvas');c.width=1320;c.height=1100;const ctx=c.getContext('2d');ctx.fillStyle='#223c3b';ctx.fillRect(0,0,c.width,c.height);for(const[id,x,y,s,crop]of [['shipCabins',0,0,.7],['shipLounge',735,0,.55],['manikereo',0,560,1,[13,3,17,16]],['momi',580,530,1,[31,41,11,13]],['momi',580,970,.6,[0,87,42,5]]]){const m=MAPS[id],cv=document.createElement('canvas');cv.width=m.rows[0].length*32;cv.height=m.rows.length*32;const a=cv.getContext('2d');a.imageSmoothingEnabled=false;A.drawChapterMap(a,m,0,0);F.drawConnectionFrames113(a,m,{});for(const n of m.npcs)N.drawNpc(a,n,0,n.x*32,n.y*32-28);ctx.imageSmoothingEnabled=false;if(crop)ctx.drawImage(cv,crop[0]*32,crop[1]*32,crop[2]*32,crop[3]*32,x,y,crop[2]*32*s,crop[3]*32*s);else ctx.drawImage(cv,x,y,cv.width*s,cv.height*s);}return c.toDataURL();};
const out={};for(const id of ['route3','momi','shipCabins','shipLounge','manikereo']){const base=bases[id],d=E.upgrade79(base,E.initial(base));out[id]={errors:E.validateEdit(base,d,cat),warps:MAPS[id].warps,rows:MAPS[id].rows,waterBefore:base.rows.join('').split('W').length-1,waterAfter:MAPS[id].rows.join('').split('W').length-1};}out.return=MAPS.manikereoStation.warps;draw160();return out;});
for(const [id,m]of Object.entries(data)){if(id==='return')continue;assert.deepEqual(m.errors,[],id);}assert.equal(data.route3.waterAfter,data.route3.waterBefore);assert(!data.route3.rows.join('').includes('.'),'route3 paths');assert.equal(data.manikereo.warps.filter(w=>w.to==='manikereoStation').length,2);const mm=data.momi,w=mm.rows[0].length,h=mm.rows.length;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(!x||!y||x===w-1||y===h-1)assert(mm.warps.some(p=>p.x===x&&p.y===y)||mm.rows[y][x]==='R',`momi border ${x},${y}`);
const blocked=new Set('TRMW#rwSX=cbtKVPLs');const flood=(rows,start,doors=new Set())=>{const seen=new Set(),todo=[start];while(todo.length){const[x,y]=todo.pop(),k=x+','+y;if(seen.has(k)||doors.has(k)||rows[y]?.[x]===undefined||blocked.has(rows[y][x]))continue;seen.add(k);todo.push([x-1,y],[x+1,y],[x,y-1],[x,y+1]);}return seen;};
const rooms=[[3,3],[18,3],[3,16],[18,16]],open=flood(data.shipCabins.rows,[2,11]),doors=new Set([9,13].flatMap(y=>[8,9,23,24].map(x=>x+','+y)));
for(const point of rooms)assert(open.has(point.join(',')),'room reachable '+point);for(const point of rooms){const closed=flood(data.shipCabins.rows,point,doors);assert(!closed.has('2,11'));assert.equal(rooms.filter(p=>closed.has(p.join(','))).length,1,'rooms divided');}
for(const wp of mm.warps){const dx=wp.x===w-1?-1:wp.x===0?1:0,dy=wp.y===h-1?-1:wp.y===0?1:0;for(let i=0;i<5;i++)assert(!blocked.has(mm.rows[wp.y+dy*i][wp.x+dx*i]),'snow entrance clear');}
for(let y=11;y<=23;y++){assert.equal(data.manikereo.rows[y][20],'.');assert.equal(data.manikereo.rows[y][21],'.');assert.notEqual(data.manikereo.rows[y][22],'.');}
for(let i=0;i<48;i++){await p.evaluate(()=>draw160());await p.waitForTimeout(250);}fs.writeFileSync('artifacts/layout160.png',Buffer.from((await p.evaluate(()=>draw160())).split(',')[1],'base64'));console.log('PASS route3 water/grass; station two-cell door; snow border; editor validations');console.log(JSON.stringify({station:data.manikereo.warps.filter(w=>w.to==='manikereoStation'),return:data.return,momi:data.momi.warps}));
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
