import crypto from 'node:crypto';
import fs from 'node:fs';import assert from 'node:assert/strict';import {SPECIES,DEX_TOTAL} from '../src/data/species.js';import {FAMILIES184} from '../src/data/families184.mjs';import {MOVES} from '../src/data/moves.js';import {FOLLOWER_PROFILES} from '../src/data/followerProfilesV1.js';import {WILD_ADDITIONS94} from '../src/wildPools94.mjs';
assert.equal(DEX_TOTAL,300);assert.deepEqual(Object.values(SPECIES).map(s=>s.no).sort((a,b)=>a-b),Array.from({length:300},(_,i)=>i+1));
const before=JSON.parse(fs.readFileSync('tools/fixtures/species184-baseline.json'));for(const[n,hash]of Object.entries(before))assert.equal(crypto.createHash('sha256').update(JSON.stringify(SPECIES[n])).digest('hex'),hash,n+' original species changed');
for(const f of FAMILIES184){assert(WILD_ADDITIONS94[f[2]].some(e=>e[0]===f[0][0]));for(let i=0;i<3;i++){const s=SPECIES[f[0][i]];if(i<2)assert.equal(s.evo.to,f[0][i+1]);else assert(!s.evo);assert(s.learn.length>=20);for(const[lv,n]of s.learn){assert(MOVES[n]);assert(lv>=1&&lv<=100)}assert.equal(new Set(s.learn.map(e=>e[1])).size,s.learn.length);assert(Object.values(s.base).every(n=>Number.isInteger(n)&&n>0));assert(FOLLOWER_PROFILES[s.no].srcMap);}}
const files=Object.values(SPECIES).filter(s=>s.no>200).flatMap(s=>['front','back','map','follower'].map(d=>'assets/monsters/expansion-v184/'+d+'/'+s.no+'.png'));const missing=files.filter(p=>!fs.existsSync(p));if(!process.argv.includes('--data-only'))assert.deepEqual(missing,[]);
console.log(JSON.stringify({species:300,old200Unchanged:true,threeStageFamilies:33,newSpecies:100,dragonFamilies:3,missingImages:missing.length}));

if(!process.argv.includes('--data-only')){const p='assets/monsters/expansion-v184/rejected-artwork.json';if(fs.existsSync(p))for(const e of JSON.parse(fs.readFileSync(p,'utf8')).entries){if(!/\/(front|back|map|follower)\//.test(e.file)||!fs.existsSync(e.file))continue;assert.notEqual(crypto.createHash('sha256').update(fs.readFileSync(e.file)).digest('hex'),e.sha256,'Rejected artwork must not be released: '+e.file);}}
