const {chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),assert=require('assert/strict');
(async()=>{const url=process.argv[2]||'http://127.0.0.1:5179/', c=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true}),p=await c.newPage({viewport:{width:1100,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));try{
await p.goto(url);await p.waitForTimeout(2200);
const report=await p.evaluate(async()=>{
const {SPECIES}=await import('/src/data/species.js'),{MOTION_PROFILES}=await import('/src/data/gaonMotion.js'),{followerFrame,loadFollowerSheet}=await import('/src/followerArt.js'),{npcFrame,NPC_VARIANTS}=await import('/src/npcArt.js'),{FollowerTrail}=await import('/src/followerTrail.js'),{MAPS}=await import('/src/data/maps.js?v=20260909-follow-v14');
await Promise.all(Object.keys(SPECIES).map(loadFollowerSheet));await new Promise(r=>setTimeout(r,500));const bad=[];for(const name of Object.keys(SPECIES)){for(const dir of ['down','up','left','right']){const hashes=new Set(Array.from({length:2},(_,i)=>followerFrame(name,dir,i,true)?.toDataURL()));if(hashes.has(undefined)||hashes.size<2)bad.push(name+dir);}}
const trail=new FollowerTrail();trail.reset(5,5);for(let i=1;i<=16;i++)trail.record(5,5+i/8,'down');const vertical={...trail.pose};for(let i=1;i<=4;i++)trail.record(5+i/8,7,'right');const corner={...trail.pose};trail.record(5.5,7,'right');const stopped=!trail.pose.moving;
const variants=[...new Set(Object.values(MAPS).flatMap(m=>m.npcs.filter(n=>!n.legend).map(n=>n.variant)).filter(v=>v!=null))];
const wrap=document.createElement('div');wrap.id='qa';wrap.style='position:absolute;z-index:99999;inset:0;background:#e9f3ee;display:grid;grid-template-columns:repeat(6,180px);align-content:start;color:#123;font:14px sans-serif';document.body.append(wrap);
for(let i=0;i<30;i++){const card=document.createElement('div');card.style='padding:8px;height:150px';const cv=document.createElement('canvas');cv.width=160;cv.height=120;const ctx=cv.getContext('2d');ctx.imageSmoothingEnabled=false;['down','left','up'].forEach((dir,k)=>{const f=npcFrame({variant:i,dir},1);if(f)ctx.drawImage(f,k*50,10,48,72);else bad.push('npc'+i);});card.append(cv,document.createTextNode(i+' '+NPC_VARIANTS[i]));wrap.append(card);}
return {species:Object.keys(SPECIES).length,profiles:Object.keys(MOTION_PROFILES).length,bad,vertical,corner,stopped,variants:variants.length};});
await p.screenshot({path:'artifacts/people-v13.png',fullPage:true});assert.deepEqual(report.bad,[]);assert.equal(report.species,153);assert.equal(report.profiles,153);assert.equal(report.variants,30);assert.equal(report.vertical.x,5);assert.equal(report.vertical.y,6);assert.equal(report.corner.x,5);assert.equal(report.corner.y,6.5);assert.ok(report.stopped);
await p.goto(new URL('/gaon-zukan/',url).href);const counts=await p.evaluate(()=>({cards:document.querySelectorAll('article').length,learnsets:document.querySelectorAll('.learnset').length,empty:[...document.querySelectorAll('.learnset')].filter(d=>!d.querySelector('tbody tr')).length}));assert.equal(counts.learnsets,153);assert.equal(counts.empty,0);await p.locator('.learnset summary').first().click();await p.screenshot({path:'artifacts/learnsets-v13.png',fullPage:false});assert.deepEqual(errors,[]);console.log(JSON.stringify({url,...report,...counts,errors}));
}finally{await c.close();}})().catch(e=>{console.error(e);process.exitCode=1});
