const{chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const base=process.argv[2]||'http://127.0.0.1:5180',p=await b.newPage({timezoneId:'America/Los_Angeles'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base,{waitUntil:'domcontentloaded'});const report=await p.evaluate(async()=>{
const{world:w}=await import('/src/world.js?v=20260912-frontier-v35'),{G:S,newGame,makeMon,loadInto,statOf}=await import('/src/state.js'),{newMove}=await import('/src/data/moves.js'),{MAPS}=await import('/src/data/maps.js'),{solid}=await import('/src/tiles.js'),{ui}=await import('/src/ui.js'),{saveLocal,loadLocal}=await import('/src/save.js'),{startBattle}=await import('/src/battle.js'),r=await import('/src/frontierRules.js'),v=await import('/src/frontierStory.js'),nursery=await import('/src/voyageRules.js'),{releaseMon}=await import('/src/marineRules.js');
const check=(x,m)=>{if(!x)throw Error(m)},orig={say:ui.say,ask:ui.ask,choice:ui.choice,itemList:ui.itemList,timeout:window.setTimeout,random:Math.random,Date:window.Date},messages=[];let now=new orig.Date('2026-09-12T06:00:00Z').getTime();ui.say=async a=>messages.push(...a);ui.ask=async()=>true;ui.choice=async()=>0;window.setTimeout=(fn,ms,...a)=>orig.timeout.call(window,fn,Math.min(ms,3),...a);Math.random=()=>.5;window.Date=class extends orig.Date{constructor(...a){super(...(a.length?a:[now]));}static now(){return now;}};
const enter=(id,x,y)=>{w.enter(id,x,y,'up');w.busy=true;S.save.where={map:id,x:w.x,y:w.y,dir:'up'}},hero=()=>{const m=makeMon('ラテット',100);m.moves=[newMove('タックル')];m.moves[0].pp=999;S.save.party=[m];},talk=async script=>{const n=w.npcs.find(n=>n.script===script);check(n,'Missing '+script);await v.frontierNpc(w,n)},date=s=>new orig.Date(s),idle=async()=>{for(let i=0;w.busy&&i<2000;i++)await new Promise(res=>orig.timeout.call(window,res,5));check(!w.busy,'Event never finished');w.busy=true;};
try{
S.save=newGame('続編検査');S.save.flags['v5:dex']=true;S.save.flags['v5:netGift']=true;S.save.flags['power:sailed']=true;hero();
for(const[id,m]of Object.entries(MAPS)){const q=[[m.spawn.x,m.spawn.y]],seen=new Set();for(let i=0;i<q.length;i++){const[x,y]=q[i],k=x+','+y;if(seen.has(k)||m.rows[y]?.[x]==null||solid(m.rows[y][x]))continue;seen.add(k);q.push([x+1,y],[x-1,y],[x,y+1],[x,y-1]);}for(const wp of m.warps){check(seen.has(wp.x+','+wp.y),'Unreachable exit '+id+':'+wp.x+','+wp.y);if(MAPS[wp.to])check(!solid(MAPS[wp.to].rows[wp.ty]?.[wp.tx]),'Blocked arrival '+id+' -> '+wp.to);}if(m.frontierTheme)for(const n of m.npcs){check(!solid(m.rows[n.y]?.[n.x]),'NPC on solid '+id+' '+n.name);check([[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>seen.has((n.x+dx)+','+(n.y+dy))),'Unreachable NPC '+id+' '+n.name);}if(m.enc)check(m.enc.list.length>0,'Empty encounter pool '+id);if(id!=='gaonPark')check(!m.enc?.list.some(e=>r.PARK_SPECIES.includes(e[0])),'Park species outside '+id);}
check(MAPS.route12.rows.length>=80&&MAPS.route13.rows.length>=80,'Long roads');check(MAPS.route13.npcs.filter(n=>n.trainer).every(n=>Number.isInteger(n.winterVariant)),'Winter clothes');check(MAPS.flowerPark.npcs.filter(n=>n.dailyId).length===10,'Flower trainers');
// Real captures prove only local, unique park catches count.
enter('gaonPark',20,24);for(const sp of r.PARK_SPECIES){S.save.party=[];S.save.bag['マスターラグ']=1;check(await startBattle({wild:makeMon(sp,22)})==='caught','Capture '+sp);}check(r.parkCount(S.save)===10&&!r.resureReady(S.save),'Park or premature test');r.recordParkCatch(S.save,'gaonPark',r.PARK_SPECIES[0]);check(r.parkCount(S.save)===10,'Duplicate count');saveLocal();loadInto(loadLocal());check(r.parkCount(S.save)===10,'Park save lost');const blank=newGame();r.recordParkCatch(blank,'route9',r.PARK_SPECIES[0]);check(r.parkCount(blank)===0,'Outside count');
hero();S.save.box=[makeMon('トリッピ',4),makeMon('トリッピ',4)];S.save.steps=100;nursery.depositParents(S.save,[{collection:'box',index:0},{collection:'box',index:1}],makeMon('トリッピ',1));S.save.steps=2099;r.recordBirth(S.save);check(!r.resureReady(S.save),'Early birth');S.save.steps=2100;r.recordBirth(S.save);r.recordBirth(S.save);check(S.save.daycareBirths===1&&r.resureReady(S.save),'Birth duplicate/readiness');nursery.reclaimDaycare(S.save,true);check(S.save.daycareBirths===1,'Reclaim duplicate birth');
enter('resure',27,20);ui.ask=async()=>false;w.busy=false;check(v.tickFrontier(w),'No Takara approach');await idle();check(S.save.flags['frontier:takaraMet']&&!S.save.flags['frontier:resureWon'],'Consent bypass');const tk=w.npcs.find(n=>n.script==='frontier:takara');check(!tk.noRoam&&tk.homeX===29,'Takara did not return');ui.ask=async()=>true;hero();await talk('frontier:takara');check(S.save.flags['frontier:resureWon']&&S.save.badges.includes(r.RESURE_EMBLEM),'Takara win/emblem');await talk('frontier:takara');check(S.save.badges.filter(x=>x===r.RESURE_EMBLEM).length===1,'Duplicate emblem');
// Weekly ordinary trainers: Japanese Monday boundary, refusal, acceptance and no duplicate same week.
const wk='test';r.markRematch(S.save,wk,false,date('2026-09-13T14:59:59Z'));check(!r.rematchAvailable(S.save,wk,false,date('2026-09-13T14:59:59Z'))&&r.rematchAvailable(S.save,wk,false,date('2026-09-13T15:00:00Z')),'Monday boundary');
enter('route9',16,46);hero();const t=w.npcs.find(n=>n.trainer),key='beat:route9:'+t.idx;await w.runNpc(t);check(S.save.flags[key]&&!r.rematchAvailable(S.save,key),'First win not dated');const money=S.save.money;await w.runNpc(t);check(S.save.money===money,'Same-week rematch');now=date('2026-09-13T15:00:00Z').getTime();ui.ask=async()=>false;await w.runNpc(t);check(S.save.money===money&&r.rematchAvailable(S.save,key),'Refusal spent match');ui.ask=async()=>true;await w.runNpc(t);check(S.save.money>money&&!r.rematchAvailable(S.save,key),'Monday rematch');
hero();enter('flowerPark',20,20);await talk('frontier:daily');check(!r.rematchAvailable(S.save,'flower-0',true),'Flower daily');const cash=S.save.money;await talk('frontier:daily');check(S.save.money===cash,'Daily duplicate');now+=86400000;check(r.rematchAvailable(S.save,'flower-0',true),'Daily reset');
// Gate counters count unique emblems, not duplicate entries.
S.save.badges=['a','b','c','d','d'];enter('resure',29,1);let wp=MAPS.resure.warps.find(x=>x.to==='route11');await w.doWarp(wp);check(w.mapId==='resure','Five gate early');S.save.badges.push('e');await w.doWarp(wp);check(w.mapId==='route11','Five gate failed');
enter('manikereoStation',16,10);await talk('frontier:train');check(w.mapId==='manikereoStation','Train early');S.save.badges.push('f','g');await talk('frontier:train');check(w.mapId==='galaxy'&&loadLocal().where.map==='galaxy','Train travel/save');await talk('frontier:returnTrain');check(w.mapId==='manikereoStation','Return train');
enter('mountain',14,1);wp=MAPS.mountain.warps.find(x=>x.to==='ashRoad');await w.doWarp(wp);check(w.mapId==='mountain','Volcano gate early');enter('manikereo',19,24);await talk('frontier:briefing');check(S.save.flags['frontier:briefed'],'No briefing');const snowgate=MAPS.manikereo.warps.find(x=>x.to==='route13');await w.doWarp(snowgate);check(w.mapId==='manikereo','Snow gate early');enter('mountain',14,1);await w.doWarp(wp);check(w.mapId==='ashRoad','Ash gate after briefing');
hero();enter('volcano3',18,8);ui.ask=async()=>false;w.busy=false;check(v.tickFrontier(w),'Yanoken approach missing');await idle();check(S.save.flags['frontier:yanokenMet']&&!S.save.flags['frontier:yanokenWon'],'Yanoken refusal');ui.ask=async()=>true;while(S.save.party.length<6)S.save.party.push(makeMon('カニポン',4));const count=S.save.box.length;await talk('frontier:yanoken');check(S.save.flags['frontier:yanokenWon']&&S.save.box.length===count+1&&S.save.box.at(-1).sp==='アワミィ'&&S.save.box.at(-1).lv===5,'Yanoken baby gift');await talk('frontier:yanoken');check(S.save.box.length===count+1,'Duplicate gift');
hero();enter('volcanoSummit',18,9);S.save.bag['マスターラグ']=1;let attempt=0;ui.choice=async labels=>labels.includes('にげる')?(attempt++===0?3:attempt===2?1:0):0;ui.itemList=async()=>({name:'マスターラグ'});await talk('frontier:volcano');ui.choice=async()=>0;ui.itemList=orig.itemList;check(messages.some(x=>x.includes('このバトルからは にげられない')),'Volcano escape');check(messages.some(x=>x.includes('つかまえられない'))&&S.save.bag['マスターラグ']===1,'First capture allowed');check(S.save.flags['frontier:volcanoWon']&&w.mapId==='village','Summit win/return');await talk('frontier:report');check(S.save.badges.includes(r.VOLCANO_EMBLEM),'Report reward');enter('manikereo',22,1);await w.doWarp(snowgate);check(w.mapId==='route13','Snow not unlocked');
S.save.flags['frontier:volcanoDay']='2026-09-13';S.save.box=[];hero();for(const[time,yes]of [['2026-09-14T05:59:59Z',false],['2026-09-14T06:00:00Z',true],['2026-09-14T14:59:59Z',true],['2026-09-14T15:00:00Z',false]])check(r.volcanoAvailable(S.save,date(time))===yes,'Summit time '+time);now=date('2026-09-14T06:00:00Z').getTime();enter('volcanoSummit',18,9);check(!w.npcs.find(n=>n.script==='frontier:volcano').gone,'Visible summit missing');await talk('frontier:volcano');check(!r.volcanoAvailable(S.save)&&r.volcanoAvailable(S.save,date('2026-09-15T06:00:00Z')),'Summit defeated cooldown');now+=86400000;hero();S.save.party=[];S.save.bag['マスターラグ']=1;await startBattle({wild:makeMon('ヨウガンヌシ',35),...r.VOLCANO_BATTLE});check(S.save.party[0].sp==='ヨウガンヌシ'&&!r.volcanoAvailable(S.save,date('2026-09-16T06:00:00Z')),'Owned summit respawn');releaseMon(S.save,'party',0,new Date());check(!r.volcanoAvailable(S.save)&&r.volcanoAvailable(S.save,date('2026-09-16T06:00:00Z')),'Released cooldown');
// Buy, equip and reload a held item using the real menus.
hero();S.save.money=10000;enter('manikereoStation',7,13);let shop=0;ui.choice=async()=>shop++===0?0:3;await talk('frontier:heldShop');check(S.save.money===7500&&S.save.bag['パワーバンド']===1,'Shop purchase');const baseAtk=statOf(S.save.party[0],'atk');let bag=0;ui.itemList=async()=>bag++===0?{name:'パワーバンド',category:0,index:0}:null;ui.choice=async()=>0;const{bagMenu}=await import('/src/menu.js');await bagMenu();check(S.save.party[0].heldItem==='パワーバンド'&&statOf(S.save.party[0],'atk')===Math.floor(baseAtk*1.1)&&!S.save.bag['パワーバンド'],'Equip effect');loadInto(loadLocal());check(S.save.party[0].heldItem==='パワーバンド','Held save lost');
return{maps:Object.keys(MAPS).length,park:'10 exclusive actual captures, deduplication, save/reload',daycare:'exact birth threshold, one birth counted once',story:'Takara consent/emblem, Yanoken approach/refusal/gift, summit escape/capture block, win/warp/report',travel:'5/7 emblem gates, train roundtrip/save, volcano/snow unlock',rematch:'ordinary weekly Monday JST; flower daily',legend:'15:00–24:00 JST, defeat, owned and release cooldown',items:'purchase/equip/stat effect/reload',messages:messages.length};
}finally{Object.assign(ui,{say:orig.say,ask:orig.ask,choice:orig.choice,itemList:orig.itemList});window.Date=orig.Date;window.setTimeout=orig.timeout;Math.random=orig.random;w.busy=true;}
});if(errors.length)throw Error(errors.join('\n'));fs.mkdirSync('artifacts',{recursive:true});fs.writeFileSync('artifacts/frontier-v35-'+(base.includes('127')?'local':'production')+'.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
