const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),L=require(root+'/api/_lib'),F=require(root+'/api/_friendStore');
const admin={id:'ヤノケン',created:1789724902905,display:'ヤノケン'},ordinary={id:'tester',created:1};L.setPw(admin,'test-only-password');let docs={};L.readUser=async id=>id===admin.id?admin:id==='tester'?ordinary:null;L.findUser=async name=>name===admin.id?admin:null;L.configured=()=>true;F.read=async keys=>Object.fromEntries(keys.filter(k=>docs[k]).map(k=>[k,structuredClone(docs[k])]));F.commit=async(expected,writes)=>{if(Object.entries(expected).some(([k,v])=>(docs[k]?.version||0)!==v))return false;for(const[k,v]of Object.entries(writes))docs[k]={version:(docs[k]?.version||0)+1,data:structuredClone(v)};return true;};
const handler=require(root+'/api/map-editor'),auth=require(root+'/api/auth');
const mime={'.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp3':'audio/mpeg'};
const server=http.createServer(async(req,res)=>{res.status=c=>{res.statusCode=c;return res};res.json=v=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(v))};const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){let body='';for await(const b of req)body+=b;try{req.body=JSON.parse(body||'{}');}catch{req.body={};}if(url.pathname==='/api/map-editor')return handler(req,res);if(url.pathname==='/api/auth')return auth(req,res);return res.status(200).json({});}let file=path.join(root,decodeURIComponent(url.pathname));if(!file.startsWith(path.normalize(root)))return res.status(403).end();try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);}catch{res.status(404).end();}});
(async()=>{
 await new Promise(r=>server.listen(5183,'127.0.0.1',r));
 const {chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
 const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 try{
  const errors=[],p=await browser.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',e=>errors.push(e.message));
  await p.goto('http://127.0.0.1:5183/map-editor/');await p.locator('#password').fill('test-only-password');await p.locator('#loginForm button').click();await p.waitForFunction(()=>!document.querySelector('.layout').inert&&!document.getElementById('app').hidden);
  const before=await p.locator('#dirty').innerText(),z=async()=>parseInt(await p.locator('#zoomLabel').innerText());
  const box=await p.locator('#viewport').boundingBox();await p.mouse.move(box.x+box.width/2,box.y+box.height/2);const z0=await z();await p.mouse.wheel(0,-180);await p.waitForTimeout(150);const z1=await z();assert(z1>z0);await p.mouse.wheel(0,180);await p.waitForTimeout(150);assert(Math.abs(await z()-z0)<=1);assert.equal(await p.locator('#dirty').innerText(),before);
  await p.locator('#tabs button').first().hover();await p.mouse.wheel(0,-180);await p.waitForTimeout(100);assert(Math.abs(await z()-z0)<=1);
  const noWrap=()=>[...document.querySelectorAll('#tabs button')].every(b=>getComputedStyle(b).whiteSpace==='nowrap'&&b.scrollWidth<=b.clientWidth);
  assert(await p.evaluate(noWrap));assert.equal(await p.locator('.category-group80').count(),4);
  await p.locator('summary').filter({hasText:'このマップの人・ガオン'}).click();await p.locator('#actorList button').first().click();await p.getByLabel('名前',{exact:true}).fill('やさしい町の人');await p.getByLabel('名前',{exact:true}).press('Tab');await p.locator('#save').click();await p.waitForFunction(()=>document.getElementById('dirty').textContent==='下書き保存済み');assert.equal(docs['maps72:draft:rods'].data.edit.actors[0].name,'やさしい町の人');
  await p.reload();await p.waitForFunction(()=>!document.querySelector('.layout').inert&&!document.getElementById('app').hidden);await p.locator('summary').filter({hasText:'このマップの人・ガオン'}).click();await p.locator('#actorList button').first().click();assert.equal(await p.getByLabel('名前',{exact:true}).inputValue(),'やさしい町の人');await p.locator('#publish').click();await p.locator('#confirmPublish').click();await p.waitForTimeout(400);
  await p.screenshot({path:'work/admin72/screens/editor80-desktop.png'});
  await p.setViewportSize({width:390,height:844});await p.locator('[data-panel79="materials"]').click();assert(await p.evaluate(noWrap));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#tabs').scrollIntoViewIfNeeded();await p.screenshot({path:'work/admin72/screens/editor80-mobile.png'});
  const model=await import(require('url').pathToFileURL(root+'/src/editorModel72.mjs').href),maps=require(root+'/assets/editor-v72/base-maps.json'),cat=model.catalog(maps,require(root+'/assets/editor-v72/species.json'));
  const trainerMap=Object.values(maps).find(m=>m.npcs.some(n=>n.trainer)),draft=model.initial(trainerMap),idx=trainerMap.npcs.findIndex(n=>n.trainer);draft.actors[idx].name='森のトレーナー';assert.deepEqual(model.validateEdit(trainerMap,draft,cat),[]);const changed=model.applyEdit(trainerMap,draft,cat).npcs[idx];assert.equal(changed.displayName,'森のトレーナー');assert.equal(changed.name,trainerMap.npcs[idx].name);assert.deepEqual(changed.trainer,trainerMap.npcs[idx].trainer);draft.actors[idx].name='a'.repeat(31);assert(model.validateEdit(trainerMap,draft,cat).length>0);
  const game=await browser.newPage({viewport:{width:960,height:850}});game.on('pageerror',e=>errors.push(e.message));await game.goto('http://127.0.0.1:5183/?v4test=rods');await game.waitForFunction(()=>window.VM);
  const report=await game.evaluate(async()=>{
   const e=await import('/src/economy79.js'),r=await import('/src/resource80.js'),{MAPS}=await import('/src/data/maps.js?v=20260913-fashion-v50'),{SHOP_LIST,ITEMS}=await import('/src/data/items.js'),{ui}=await import('/src/ui.js'),state=await import('/src/state.js');
   const check=(v,m)=>{if(!v)throw Error(m);};check(SHOP_LIST.includes('採掘セット')&&!SHOP_LIST.includes('つるはし'),'shop rename');const s=VM.newGame();s.bag['つるはし']=1;state.loadInto(s);check(state.G.save.bag['採掘セット']===1&&!state.G.save.bag['つるはし'],'load migration');r.migrateKit80(s);r.migrateKit80(s);check(s.bag['採掘セット']===1&&!s.bag['つるはし'],'migration idempotent');
   const date=new Date('2026-09-19T03:00:00Z');for(let i=0;i<5;i++)check(e.mine79(s,'test','tree',date,.2,'tree').name==='もくざい','wood');check(e.mine79(s,'test','tree',date,.2,'tree').error,'cap');check(e.mine79(JSON.parse(JSON.stringify(s)),'test','tree',date,.2,'tree').error,'persist cap');check(e.mine79(s,'test','tree',new Date('2026-09-20T03:00:00Z'),.95,'tree').name==='かたいもくざい','daily reset');check(e.mine79(s,'test','rock',date,.99,'rock').name==='ひかりのけっしょう','ore');check(e.mine79(s,'test','grass',date,.2,'grass').error,'no grass');check(e.mine79(VM.newGame(),'test','rock',date).error,'kit required');check(ITEMS['もくざい'].price>0&&ITEMS['もくざい'].kind!=='key','sellable wood');
   const stats=Object.values(MAPS).map(m=>({id:m.id,n:r.resourceNodes80(m)}));check(stats.some(s=>s.n.some(n=>n.type==='rock')),'rock nodes');check(stats.some(s=>s.n.some(n=>n.type==='tree')),'tree nodes');check(stats.every(s=>s.n.every(n=>['tree','rock'].includes(n.type))),'no grass nodes');
   for(const m of Object.values(MAPS)){const nodes=r.resourceNodes80(m);for(const n of nodes){check(e.miningTarget79(m,n.approach.tx,n.approach.ty)===n,'target access');}if(m.kind==='in')check(nodes.length===0,'indoor exclusion');}
   const tiny={id:'tiny',kind:'out',spawn:{x:2,y:2},rows:['TTTTTTTT','T......T','T......T','T.R..R.T','T......T','TTTTTTTT'],props:[],npcs:[],warps:[],items:[],signs:[]};check(!e.miningTarget79(tiny,3,2),'grass/ground not harvestable');check(!e.miningTarget79(tiny,5,3),'unmarked outdoor rock excluded');check(!e.miningTarget79({...tiny,kind:'in'},2,3),'ordinary rock no target');
   const town=Object.values(MAPS).find(m=>e.plot79(m));s.money=10000;e.buyLand79(s,town);e.buildShop79(s,town.id);check(e.stock79(s,town.id,'もくざい',2,1000000),'stock wood');check(e.collect79(s,town.id,1600000)===240,'wood proceeds');
   const target=stats.find(s=>s.id==='rods'&&s.n.some(n=>n.type==='tree'))||stats.find(s=>s.n.some(n=>n.type==='tree'));const n=target.n.find(n=>n.type==='tree');VM.State.save=s;VM.world.enter(target.id,n.approach.x,n.approach.y,'down');VM.world.dir=n.approach.tx>n.approach.x?'right':n.approach.tx<n.approach.x?'left':n.approach.ty>n.approach.y?'down':'up';const ask=ui.ask,say=ui.say;let messages=[];ui.ask=async()=>true;ui.say=async lines=>messages.push(...lines);try{VM.world.interact();await new Promise(res=>setTimeout(res,100));}finally{ui.ask=ask;ui.say=say;}check(messages.some(m=>m.includes('手に入れた')),'actual A harvest');check(!VM.world.busy,'interaction completed');
   return {resourceMaps:stats.filter(s=>s.n.length).length,trees:stats.flatMap(s=>s.n).filter(n=>n.type==='tree').length,rocks:stats.flatMap(s=>s.n).filter(n=>n.type==='rock').length,harvest:messages[0]};
  });await game.screenshot({path:'work/admin72/screens/resources80.png'});assert.deepEqual(errors,[]);console.log('PASS v80',JSON.stringify(report),'wheel directions/no edits/palette unaffected; desktop/mobile unwrapped tabs; existing NPC rename save/reload/publish; trainer identity; kit migration/drops/caps/sale/actual A');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1});
