const {chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.argv[2]||'http://127.0.0.1:5182/',{waitUntil:'networkidle'});const r=await p.evaluate(async()=>{const{MAPS}=await import('/src/data/maps.js');const{SOLID}=await import('/src/tiles.js');const{drawChapterMap}=await import('/src/chapterArt.js');const{environmentReady}=await import('/src/decorArt.js');while(!environmentReady(MAPS.dark1)||!environmentReady(MAPS.village))await new Promise(r=>setTimeout(r,100));await new Promise(r=>setTimeout(r,2000));const checked=[],failures=[],snapshots={};const{world}=await import('/src/world.js');for(const [x,y]of [[0,0],[20,31],[14,31],[40,30]]){world.enter('dark1',x,y,'down');if(SOLID.has(world.map.rows[world.y]?.[world.x]))throw Error('Old save trapped in wall');}for(const m of Object.values(MAPS).filter(m=>m.explorationDesign)){
const exits=m.warps.filter(w=>m.g||true),start=exits[0]||m.spawn,q=[[start.x,start.y]],seen=new Set([start.x+','+start.y]);for(let i=0;i<q.length;i++){const[x,y]=q[i];for(const[dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx,yy=y+dy,k=xx+','+yy,ch=m.rows[yy]?.[xx];if(ch!=null&&!SOLID.has(ch)&&!seen.has(k)){seen.add(k);q.push([xx,yy]);}}}
for(const w of exits)if(!seen.has(w.x+','+w.y))failures.push(m.id+' exit '+w.x+','+w.y);
for(const n of m.npcs)if(!seen.has(n.x+','+n.y)&&![[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>seen.has((n.x+dx)+','+(n.y+dy))))failures.push(m.id+' NPC '+n.name+' '+n.x+','+n.y);
if(m.ruinRooms){if(m.enc.list.length!==5||!m.enc.encAll)throw Error('Lost encounters');if(m.props.length<5)throw Error('Missing rooms');}
checked.push({id:m.id,reachable:seen.size,infill:m.townInfill,grass:m.rows.join('').split('"').length-1});
if(['village','rods','karat','clearTown','route1','natureforest','route13','route14','route17','glacier','dark1','dark2','dark3','dark4'].includes(m.id)){const c=document.createElement('canvas');c.width=m.rows[0].length*32;c.height=m.rows.length*32;drawChapterMap(c.getContext('2d'),m,0,0);snapshots[m.id]=c.toDataURL();}
}return{checked,failures,snapshots};});for(const[name,data]of Object.entries(r.snapshots))fs.writeFileSync('artifacts/exploration-v43-'+name+'.png',Buffer.from(data.split(',')[1],'base64'));delete r.snapshots;console.log(JSON.stringify(r));assert.deepEqual(r.failures,[]);assert.deepEqual(errors,[]);}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
