const {chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('fs');
(async()=>{const base=process.argv[2]||'http://127.0.0.1:5179',b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base);const result=await p.evaluate(async()=>{
 const{world}=await import('/src/world.js?v=20260912-dialogue-v33'),{G:S,newGame}=await import('/src/state.js'),{MAPS}=await import('/src/data/maps.js'),{npcDialogue}=await import('/src/npcDialogue.js'),{ui}=await import('/src/ui.js');S.save=newGame('会話確認');world.busy=true;const check=(v,m)=>{if(!v)throw Error(m)},oldSay=ui.say;let lines;ui.say=async x=>{lines=x};let changed=0,fixed=0;
 try{for(const [id,m] of Object.entries(MAPS))for(const [idx,n] of m.npcs.entries()){
  const original=JSON.stringify(n);let previous,seen=new Set();for(let i=0;i<20;i++){const text=JSON.stringify(npcDialogue(S.save,id,{...n,idx},'talk',n.talk));seen.add(text);if(seen.size>1)check(text!==previous,'Consecutive repeat '+id+n.name);previous=text;}
  check(JSON.stringify(n)===original,'Mutated data');if(seen.size>1){changed++;check(!n.script||n.script==='voyage:trainer','Changed quest');}else fixed++;
 }
 world.enter('village',13,12,'down');const n=world.npcs.find(n=>n.name==='庭しごとの人');const seen=new Set();let last;for(let i=0;i<12;i++){await world.runNpc(n);const s=JSON.stringify(lines);check(s!==last,'World repeats');seen.add(s);last=s;}check(seen.size>=4,'Not varied');
 const guide=world.npcs.find(n=>n.name==='村のひと');await world.runNpc(guide);const important=JSON.stringify(lines);await world.runNpc(guide);check(JSON.stringify(lines)===important,'Directions changed');
 const trainer=MAPS.route2.npcs.find(n=>n.trainer);for(const phase of ['talk','win','after']){const set=new Set();let last;for(let i=0;i<12;i++){const text=JSON.stringify(npcDialogue(S.save,'route2',trainer,phase));check(text!==last,'Trainer repeat');last=text;set.add(text);}check(set.size>=3,'Trainer phase fixed');}
 for(const n of [{script:'v5:professor'},{script:'marine:guide'},{script:'voyage:daycare'},{trainer:{major:true}},{fixedDialogue:true},{healAll:true}])for(let i=0;i<10;i++)check(JSON.stringify(npcDialogue(S.save,'village',{...n,name:'庭しごとの人'},'talk',['固定']))==='["固定"]','Protected NPC varies');
 const{chapterNpc}=await import('/src/chapterStory.js');S.save.flags['v5:netGift']=true;const messages=[];ui.say=async x=>messages.push(...x);await chapterNpc(world,{script:'v5:dex'});const expected=['はじめまして！僕はヤノケンです！','キミはガオントレーナーかな？','僕もガオンを育てて研究しているトレーナーなんだ！','僕が作ったものがあるんだけど使ってみてくれない？','ガオンずかんっていうんだけど、見つけたり捕まえたりしたガオンを登録することができるんだ！','よかったら使ってみてね！','また会えたら、今度はバトルしようぜ！'];check(JSON.stringify(messages.slice(0,7))===JSON.stringify(expected),'Yanoken intro mismatch');check(S.save.flags['v5:dex']&&S.save.bag['ガオンずかん']===1,'Dex gift missing');const greetings=new Set();let previous;for(let i=0;i<18;i++){messages.length=0;await chapterNpc(world,{script:'v5:dex'});const text=messages.join('');check(text!==previous,'Greeting repeated');previous=text;greetings.add(text);}check(greetings.has('オッス！元気？')&&greetings.has('また会えたね！')&&greetings.has('今日はいい日になるさ！'),'Missing greetings');check(S.save.bag['ガオンずかん']===1,'Duplicate gift');check(changed>=20,'Too few varied people '+changed);return{changed,fixed,yanokenIntroAndGreetings:true,worldDialogue:true,importantDirectionsFixed:true,trainerPhases:true,noConsecutiveRepeats:true};}finally{ui.say=oldSay;}
 });if(errors.length)throw Error(errors.join('/'));fs.writeFileSync('artifacts/dialogue-v33-'+(base.includes('127')?'local':'production')+'.json',JSON.stringify(result,null,2));console.log(result);}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
