const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),L=require(root+'/api/_lib'),F=require(root+'/api/_friendStore');
const admin={id:'ヤノケン',created:1789724902905,display:'ヤノケン'},ordinary={id:'tester',created:1};L.setPw(admin,'test-only-password');let docs={};L.readUser=async id=>id===admin.id?admin:id==='tester'?ordinary:null;L.findUser=async name=>name===admin.id?admin:null;L.configured=()=>true;F.read=async keys=>Object.fromEntries(keys.filter(k=>docs[k]).map(k=>[k,structuredClone(docs[k])]));F.commit=async(expected,writes)=>{if(Object.entries(expected).some(([k,v])=>(docs[k]?.version||0)!==v))return false;for(const[k,v]of Object.entries(writes))docs[k]={version:(docs[k]?.version||0)+1,data:structuredClone(v)};return true;};
const handler=require(root+'/api/map-editor'),auth=require(root+'/api/auth');
const mime={'.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp3':'audio/mpeg'};
const server=http.createServer(async(req,res)=>{res.status=c=>{res.statusCode=c;return res};res.json=v=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(v))};const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){let body='';for await(const b of req)body+=b;try{req.body=JSON.parse(body||'{}');}catch{req.body={};}if(url.pathname==='/api/map-editor')return handler(req,res);if(url.pathname==='/api/auth')return auth(req,res);return res.status(200).json({});}let file=path.join(root,decodeURIComponent(url.pathname));if(!file.startsWith(path.normalize(root)))return res.status(403).end();try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);}catch{res.status(404).end();}});
(async()=>{await new Promise(r=>server.listen(5183,'127.0.0.1',r));const {chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{
 const p=await browser.newPage({viewport:{width:1100,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5183/?v4test=rods');await p.waitForFunction(()=>window.VM);await p.waitForFunction(async()=>(await import('/src/readableArt84.js')).readableReady84());
 const result=await p.evaluate(async()=>{const {MAPS}=await import('/src/data/maps.js?v=20260913-fashion-v50'),m=await import('/src/editorModel72.mjs'),{SCENE86,CITY86,FURNITURE86}=await import('/src/sceneCatalog86.mjs'),{drawReadable84}=await import('/src/readableArt84.js'),{drawNpc}=await import('/src/npcArt.js');const cat=m.catalog(MAPS,await fetch('/assets/editor-v72/species.json').then(r=>r.json()));const check=(v,msg)=>{if(!v)throw Error(msg);};for(const[k,[,w,h]]of Object.entries(CITY86)){const p=cat.props.find(p=>p.key==='legacy73-'+k);check(p&&p.w===w&&p.h===h,'size '+k);if(p.building)check(MAPS[p.building],'indoor '+k);}
 const ships=['shipDeck','shipLounge','shipCabins','shipCaptain86','shipGalley86'];for(const id of ships){const map=MAPS[id],seen=new Set(),queue=[[map.spawn.x,map.spawn.y]];while(queue.length){const[x,y]=queue.pop(),key=x+','+y;if(seen.has(key)||!m.pass(map,x,y))continue;seen.add(key);queue.push([x+1,y],[x-1,y],[x,y+1],[x,y-1]);}for(const w of map.warps)check(seen.has(w.x+','+w.y),'unreachable '+id+' '+w.to);for(const n of map.npcs)check([[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>seen.has((n.x+dx)+','+(n.y+dy))),'NPC '+id+' '+n.name);check(m.validateEdit(map,m.initial(map),cat).length===0,'initial ship editor '+id);}
 check(ships.flatMap(id=>MAPS[id].npcs).filter(n=>n.dailyId?.startsWith('ship-')).length===10,'trainer preservation');
 for(const id of ['shipCaptain86','shipGalley86']){VM.world.enter('shipLounge',16,20,'up');await VM.world.doWarp(VM.world.map.warps.find(w=>w.to===id));check(VM.world.mapId===id,'enter '+id);await VM.world.doWarp(VM.world.map.warps[0]);check(VM.world.mapId==='shipLounge','return '+id);}
 const map=MAPS.shipCaptain86,d=m.initial(map);d.objects.push({id:'a:test-wall',type:'furniture',template:'wall-clock86',x:2,y:0});check(!m.validateEdit(map,d,cat).length,'wall placement');check(m.applyEdit(map,d,cat).rows[0][2]==='X','wall collision preserved');d.tiles=[{x:8,y:8,material:'ship-floor86'}];check(!m.validateEdit(map,d,cat).length,'ship floor selectable');
 const cv=document.createElement('canvas');cv.width=1200;cv.height=1500;const c=cv.getContext('2d');c.fillStyle='#dfeada';c.fillRect(0,0,cv.width,cv.height);const list=[...Object.entries(CITY86).map(([k,[label,w,h]])=>[k+'86',label,w,h]),['tower86','塔',5,8],['snow-hall86','雪国のホール',5,5],['holiday-tree86','飾りの木',2,3],['lamp86','街灯',1,2],['snow-lamp86','雪国の街灯',1,2],['decor-lamp86','飾り街灯',1,2],...FURNITURE86.map(f=>[f.key,f.label,f.w,f.h]),['liner86','船',10,5]];for(let i=0;i<list.length;i++){const[key,label,w,h]=list[i],x=i%4*300,y=Math.floor(i/4)*250;c.strokeStyle='#cad8c5';for(let xx=0;xx<280;xx+=24){c.beginPath();c.moveTo(x+xx,y);c.lineTo(x+xx,y+216);c.stroke();}for(let yy=0;yy<216;yy+=24){c.beginPath();c.moveTo(x,y+yy);c.lineTo(x+280,y+yy);c.stroke();}drawReadable84(c,key,x+30,y+216-h*24,w*24,h*24);drawNpc(c,{variant:0,dir:'down'},0,x+260,y+170);c.fillStyle='#17382f';c.font='15px sans-serif';c.fillText(label+' '+w+'×'+h,x+8,y+238);}return {gallery:cv.toDataURL(),maps:Object.keys(MAPS).length,ships:ships.length,assets:SCENE86.length};});fs.writeFileSync(root+'/work/admin72/screens/scene86.png',Buffer.from(result.gallery.split(',')[1],'base64'));delete result.gallery;assert.deepEqual(errors,[]);console.log('PASS scene sizes/ship routes/NPC access/trainer preservation/indoor editor/wall mounts',result);
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
