const{chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const p=await b.newPage();await p.goto(process.argv[2]||'http://127.0.0.1:5179');await p.evaluate(async()=>{window.VM={world:(await import('/src/world.js?v=20260912-frontier-v35')).world};});const report=await p.evaluate(async()=>{
 const{G:S,makeMon,newGame,loadInto}=await import('/src/state.js');const{newMove}=await import('/src/data/moves.js');const{MAPS}=await import('/src/data/maps.js');const{SPECIES}=await import('/src/data/species.js');const rules=await import('/src/marineRules.js');const{marineNpc,refreshMarineNpcs}=await import('/src/marineStory.js');const{startBattle}=await import('/src/battle.js');const{ui}=await import('/src/ui.js');const{loadLocal}=await import('/src/save.js');const w=VM.world;w.busy=true;
 const check=(x,m)=>{if(!x)throw Error(m);};const pools=['route3','route4','remoteLake'].map(id=>MAPS[id].enc.list.map(e=>e[0]));check(new Set(pools.flat()).size===pools.flat().length,'Shared water species');check(pools.flat().every(n=>SPECIES[n].types.includes('みず')),'Wrong type');
 const original={say:ui.say,choice:ui.choice,ask:ui.ask,timeout:window.setTimeout,random:Math.random};const messages=[];ui.say=async lines=>messages.push(...lines);ui.ask=async()=>true;ui.choice=async()=>0;window.setTimeout=(fn,ms,...args)=>original.timeout.call(window,fn,Math.min(ms,5),...args);Math.random=()=>.5;
 try{
 S.save=newGame('試験');S.save.flags['v5:netGift']=true;S.save.flags['v5:dex']=true;const hero=makeMon('ラテット',100);hero.moves=[newMove('タックル')];hero.moves[0].pp=999;S.save.party=[hero];
 w.enter('marine',37,18,'right');w.busy=true;const gate=MAPS.marine.warps.find(w=>w.to==='route5');await w.doWarp(gate);check(w.mapId==='marine','Early road access');
 w.enter('remoteLake',20,21,'up');w.busy=true;const chest=w.npcs.find(n=>n.script==='marine:chest');check(w.npcs.find(n=>n.script==='marine:elder').gone,'Elder early');await marineNpc(w,chest);check(S.save.flags['marine:started'],'Chest did not start');
 for(let i=0;i<4;i++){w.busy=true;const n=w.npcs.find(n=>n.crab===i);await marineNpc(w,n);check(rules.trialCount(S.save)===i+1,'Crab progress');check(n.gone,'Crab still visible');if(i===1){const saved=loadLocal();loadInto(saved);w.enter('remoteLake',20,21,'up');w.busy=true;check(rules.trialCount(S.save)===2,'Progress lost on load');}}
 const elder=w.npcs.find(n=>n.script==='marine:elder');check(!elder.gone,'Elder absent');await marineNpc(w,elder);check(S.save.flags['marine:passed'],'Test failed');check(S.save.badges.filter(x=>x===rules.MARINE_EMBLEM).length===1,'Badge not unique');const money=S.save.money;await marineNpc(w,elder);check(S.save.money===money,'Repeat reward');
 await w.doWarp(gate);check(w.mapId==='route5','Road not unlocked');
 const fog=MAPS.remoteLake.warps.find(x=>x.to==='kageri');check(rules.marineGate(fog,S.save),'Fog early unlocked');S.save.badges=['a','b','c','d'];check(rules.marineGate(fog,S.save)===null,'Fog still locked');
 const before=new Date('2026-09-11T07:59:00Z'),open=new Date('2026-09-11T08:00:00Z'),late=new Date('2026-09-11T14:59:00Z'),midnight=new Date('2026-09-11T15:00:00Z'),next=new Date('2026-09-12T08:00:00Z');
 check(!rules.meroronAvailable(S.save,before)&&rules.meroronAvailable(S.save,open)&&rules.meroronAvailable(S.save,late)&&!rules.meroronAvailable(S.save,midnight),'Time boundary');rules.markMeroronDay(S.save,open);check(!rules.meroronAvailable(S.save,late)&&rules.meroronAvailable(S.save,next),'Daily reset');
 S.save.box=[makeMon('メロロン',30)];check(!rules.meroronAvailable(S.save,next),'Owned box respawn');rules.releaseMon(S.save,'box',0,next);check(!rules.meroronAvailable(S.save,next)&&rules.meroronAvailable(S.save,new Date('2026-09-13T08:00:00Z')),'Release day');
 // The real altar interaction records a defeated visit before allowing another day.
 const RealDate=window.Date;window.Date=class extends RealDate{constructor(...a){super(...(a.length?a:['2026-09-13T08:00:00Z']));}static now(){return new RealDate('2026-09-13T08:00:00Z').getTime();}};
 try{S.save.party=[makeMon('ラテット',100)];S.save.party[0].moves=[newMove('タックル')];S.save.party[0].moves[0].pp=999;w.enter('mountainAltar',17,13,'up');w.busy=true;const legend=w.npcs.find(n=>n.script==='marine:meroron');check(!legend.gone,'Altar spawn absent');await marineNpc(w,legend);check(loadLocal().flags['marine:meroronDay']==='2026-09-13','Altar attempt not saved');check(legend.gone,'Defeated legend remained');check(rules.meroronAvailable(S.save,new RealDate('2026-09-14T08:00:00Z')),'Defeated legend never returns');}finally{window.Date=RealDate;}
 // Actual capture engine: low catch rate fails, then the scripted flee roll ends the battle.
 S.save.party=[];S.save.box=[];S.save.bag={'ラグネット':1};Math.random=()=>.99;ui.say=async lines=>{messages.push(...lines);if(lines.some(x=>x.includes('ネットから')||x.includes('とびだされた')))Math.random=()=>0;};
 let attempts=0;ui.choice=async()=>attempts++===0?1:0;const flee=await startBattle({wild:makeMon('メロロン',30),...rules.MERORON_BATTLE});check(messages.some(x=>x.includes('このバトルからは にげられない')),'Player escaped Meroron');ui.choice=async()=>0;check(flee==='fled','Wild flee did not end battle');check(S.save.box.length===0&&S.save.party.length===0,'Failed capture added creature');
 // Master net stays guaranteed even for this rare creature.
 S.save.bag={'マスターラグ':1};ui.say=async lines=>messages.push(...lines);Math.random=()=>.99;const caught=await startBattle({wild:makeMon('メロロン',30),...rules.MERORON_BATTLE});check(caught==='caught'&&S.save.party[0].sp==='メロロン','Guaranteed capture broken');check(!rules.meroronAvailable(S.save,new Date('2026-09-14T08:00:00Z')),'Captured respawn');
 // Trial creatures cannot be caught and do not consume a net.
 S.save.party=[];S.save.bag={'ラグネット':1};let picks=0;ui.choice=async()=>picks++===0?0:1;const trial=await startBattle({wild:makeMon('カニポン',8),captureDisabled:true});check(trial==='run'&&S.save.bag['ラグネット']===1,'Trial capture restriction');
 return{maps:Object.keys(MAPS).length,pools,trial:'four wins, reload, elder and unique reward passed',daily:'Japan boundaries, day reset, release and owned checks passed',battle:{flee,caught,trial},messages:messages.length};
 }finally{ui.say=original.say;ui.choice=original.choice;ui.ask=original.ask;window.setTimeout=original.timeout;Math.random=original.random;w.busy=false;}
 });console.log(JSON.stringify(report));fs.writeFileSync('artifacts/marine-story-v26.json',JSON.stringify(report,null,2));}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});

