const {chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),fs=require('fs'),assert=require('assert/strict');
(async()=>{const base=process.argv[2]||'http://127.0.0.1:5179',b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const p=await b.newPage({viewport:{width:1000,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const press=async k=>{await p.keyboard.down(k);await p.waitForTimeout(75);await p.keyboard.up(k);await p.waitForTimeout(125);};try{
await p.goto(base+'/?v4test=route1');await p.waitForTimeout(2200);
await p.evaluate(async()=>{window.st=await import('/src/state.js');window.u=(await import('/src/ui.js')).ui;window.menus=await import('/src/menu.js');window.w=(await import('/src/world.js?v=20260909-follow-v14')).world;st.loadInto(st.newGame('確認'));st.G.save.party=[st.makeMon('トリッピ',5),st.makeMon('コケゴロ',5)];w.enter('hut',7,10,'up');window.captures=[];});
for(const id of ['hut','rodsHome','lab','hospital','shop']){await p.evaluate(id=>{u.clear();w.enter(id,7,10,'up');w.draw();captures.push({name:id,data:document.querySelector('#screen').toDataURL()});},id);}
await p.evaluate(async()=>{const {ITEMS}=await import('/src/data/items.js');u.clear();u.itemList(Object.keys(ITEMS).map(name=>({name,n:15})),{pockets:true,category:1});u.draw();captures.push({name:'どうぐ',data:document.querySelector('#screen').toDataURL()});u.clear();u.itemList(Object.keys(ITEMS).filter(name=>ITEMS[name].price>0).map(name=>({name,n:2})),{mode:'buy',money:3000});u.draw();captures.push({name:'ショップ',data:document.querySelector('#screen').toDataURL()});u.clear();});
// Stable individual selection and stopping survive serialization and party reorder.
const follower=await p.evaluate(()=>{const a=st.G.save.party[1];st.chooseFollower(a);st.G.save.party.reverse();const id=st.followingMon().companionId;st.loadInto(JSON.parse(JSON.stringify(st.G.save)));const stable=st.followingMon().companionId===id;st.stopFollowing();const stopped=st.followingMon()===null;return {stable,stopped};});assert.ok(follower.stable&&follower.stopped);
await p.evaluate(()=>{u.clear();window.words=[];const ctx=document.querySelector('#screen').getContext('2d');window.fill=ctx.fillText.bind(ctx);ctx.fillText=(s,...args)=>{words.push(s);fill(s,...args);};menus.showStatus(st.G.save.party[0]);});await press('ArrowRight');assert.ok(await p.evaluate(()=>!words.some(s=>/個体値|努力値/.test(s))));await press('Escape');await p.evaluate(()=>{u.clear();menus.dexEntry('トリッピ');});await press('ArrowRight');assert.ok(await p.evaluate(()=>words.some(s=>String(s).includes('おぼえるわざ'))));await p.evaluate(()=>{u.clear();document.querySelector('#screen').getContext('2d').fillText=fill;});
// Drive the real shop purchase flow, exactly one purchase.
await p.evaluate(()=>{st.G.save.money=3000;st.G.save.bag={};menus.shopMenu();});await press('Enter');await press('Enter');await press('Enter');for(let i=0;i<20;i++){if(await p.evaluate(()=>st.G.save.money<3000))break;await press('Enter');}const purchase=await p.evaluate(()=>({money:st.G.save.money,bag:st.bagList('normal')}));assert.equal(purchase.money,2800);assert.equal(purchase.bag.find(x=>x.name==='ラグネット').n,1);
// Check nurse reachable across counter.
await p.evaluate(()=>{u.clear();w.busy=false;w.enter('hospital',7,7,'up');w.interact();});assert.ok(await p.evaluate(()=>u.busy));await p.evaluate(()=>u.clear());
await p.evaluate(async()=>{const {drawItem,ITEM_NAMES}=await import('/src/itemArt.js');const {MAPS}=await import('/src/data/maps.js?v=20260909-follow-v14');const {drawChapterMap}=await import('/src/chapterArt.js');for(const id of ['village','rods']){const cv=document.createElement('canvas');cv.width=320;cv.height=288;const ctx=cv.getContext('2d');ctx.scale(320/(34*32),288/(29*32));drawChapterMap(ctx,MAPS[id],0,0);captures.push({name:id,data:cv.toDataURL()});}const cv=document.createElement('canvas');cv.width=640;cv.height=640;const ctx=cv.getContext('2d');ctx.fillStyle='#e9f3ee';ctx.fillRect(0,0,640,640);ITEM_NAMES.forEach((name,i)=>{drawItem(ctx,name,i%5*128+24,Math.floor(i/5)*128+4,80);ctx.fillStyle='#203c42';ctx.font='12px sans-serif';ctx.fillText(name,i%5*128+8,Math.floor(i/5)*128+104);});captures.push({name:'全25道具',data:cv.toDataURL()});document.documentElement.style='height:auto;overflow:visible';document.body.style='height:auto;overflow:visible;display:block;background:#edf3ef;color:#123';document.body.innerHTML='<div id="qa" style="display:grid;grid-template-columns:repeat(3,320px);gap:12px;background:#edf3ef"></div>';for(const shot of captures){const el=document.createElement('div');el.innerHTML='<p>'+shot.name+'</p><img style="width:320px;image-rendering:pixelated" src="'+shot.data+'">';document.querySelector('#qa').append(el);}});await p.screenshot({path:'artifacts/rooms-items-v13.png',fullPage:true});assert.deepEqual(errors,[]);console.log(JSON.stringify({base,follower,purchase,statusHidden:true,learnset:true,counter:true,errors}));
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
