const{chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const base=process.argv[2]||'http://127.0.0.1:5181',p=await b.newPage({timezoneId:'America/Los_Angeles'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base,{waitUntil:'domcontentloaded'});const report=await p.evaluate(async()=>{
const {world:w}=await import('/src/world.js'),{G:S,newGame,makeMon,maxHp,loadInto}=await import('/src/state.js'),{ui}=await import('/src/ui.js'),r=await import('/src/endgameRules.js'),story=await import('/src/endgameStory.js'),{frontierGate}=await import('/src/frontierRules.js'),{MOVES,newMove}=await import('/src/data/moves.js'),{saveLocal,loadLocal}=await import('/src/save.js'),{releaseMon}=await import('/src/marineRules.js'),{startBattle}=await import('/src/battle.js');const assert=(x,m)=>{if(!x)throw Error(m)};const orig={say:ui.say,ask:ui.ask,choice:ui.choice,itemList:ui.itemList,timeout:window.setTimeout,Date:window.Date,random:Math.random},log=[];let now=new orig.Date('2026-09-17T08:00:00Z').getTime();window.Date=class extends orig.Date{constructor(...a){super(...(a.length?a:[now]));}static now(){return now;}};window.setTimeout=(fn,ms,...a)=>orig.timeout.call(window,fn,Math.min(ms,1),...a);Math.random=()=>.5;ui.say=async a=>log.push(...a);ui.ask=async()=>true;ui.choice=async()=>0;
const hero=()=>{const m=makeMon('ラテット',100);m.moves=[newMove('スピードブロー')];m.moves[0].pp=9999;S.save.party=[m];},enter=(id,x,y)=>{w.enter(id,x,y,'up');w.busy=true;},talk=async script=>{let n=w.npcs.find(x=>x.script===script);assert(n,'missing '+script);await story.endNpc(w,n);};
try{MOVES['スピードブロー'].pow=1000;S.save=newGame('検査');S.save.flags['v5:netGift']=true;S.save.flags['v5:dex']=true;S.save.flags['frontier:reported']=true;hero();
assert(frontierGate({requires:'frontier:five'},S.save),'Galaxy open early');S.save.badges=[r.HAILAS];assert(!frontierGate({requires:'frontier:five'},S.save),'Galaxy blocked');S.save.badges=[];
for(let i=0;i<14;i++){const d=new orig.Date(now+i*86400000),days=r.starDays(S.save,d);assert(days.length===2&&days[0]!==days[1],'star schedule');const clone=structuredClone(S.save);assert(JSON.stringify(r.starDays(clone,d))===JSON.stringify(days),'star reload');}assert(!r.starAvailable(S.save,new orig.Date('2026-09-17T06:59:00Z')),'star early');
enter('momi',20,87);await talk('end:eden');assert(S.save.flags['end:eden'],'Eden join');S.save.party[0].hp=1;await talk('end:eden');assert(S.save.party[0].hp===maxHp(S.save.party[0]),'Eden heal');story.endStep(w,{x:20,y:87});assert(w.npcs.find(n=>n.eden).x===20,'Eden follows');await talk('end:forestRat');assert(S.save.flags['end:forestRat']&&S.save.dexSeen['ラテット']&&!S.save.dexOwn['ラテット'],'forest Rat');hero();await talk('end:momiBoss');assert(S.save.flags['end:momiWon']&&S.save.party.some(m=>m.sp==='リーフィン'&&m.lv===5),'Momi gift');enter('clearElder',8,6);await talk('end:elder');assert(S.save.badges.includes(r.CLEAR),'clear badge');
hero();enter('glacier',20,6);S.save.bag['マスターラグ']=1;let blockChoice=0;ui.choice=async()=>blockChoice++===0?3:blockChoice===2?1:0;ui.itemList=async()=>({name:'マスターラグ'});await talk('end:ice');assert(S.save.bag['マスターラグ']===1&&log.some(x=>x.includes('つかまえられない')),'first ice capture guard');ui.choice=async()=>0;assert(S.save.flags['end:iceWonDay']&&!S.save.badges.includes(r.HAILAS),'ice drop');await talk('end:iceEmblem');assert(S.save.badges.includes(r.HAILAS)&&!r.legendAvailable(S.save,'ヒョウガン'),'ice badge/day');now+=86400000;assert(r.legendAvailable(S.save,'ヒョウガン'),'ice next day');S.save.box.push(makeMon('ヒョウガン',50));assert(r.legendAvailable(S.save,'ヒョウガン'),'ice repeat owned');
enter('glacier',20,80);w.busy=false;assert(!story.tickEnd(w,9999)&&w.coldMs===9999,'cold 9999');assert(story.tickEnd(w,1),'cold deadline');for(let i=0;w.busy&&i<300;i++)await new Promise(res=>orig.timeout.call(window,res,2));assert(w.mapId==='clearTown','cold return');S.save.party.push(makeMon('オオヒノオ',5));enter('glacier',20,80);assert(!story.tickEnd(w,20000)&&!w.coldMs,'fire protection');
hero();enter('galaxy',18,27);await talk('end:galaxy');assert(S.save.flags['end:galaxyWon'],'Yanoken');const yn=w.npcs.find(n=>n.script==='end:galaxy');assert(yn.gone&&Math.hypot(yn.x-w.x,yn.y-w.y)>12,'Yanoken vanished on screen');enter('route17',20,12);await talk('end:door');assert(w.mapId==='dark1'&&S.save.flags['end:door'],'ruins door');hero();enter('dark4',20,6);await talk('end:dark');await talk('end:darkEmblem');assert(S.save.badges.includes(r.DARK),'dark badge');const day=new orig.Date(now);now=new orig.Date('2026-09-19T16:00:00Z').getTime();assert(r.legendAvailable(S.save,'ヤミノヌシ'),'dark 01');now=new orig.Date('2026-09-19T23:00:00Z').getTime();assert(!r.legendAvailable(S.save,'ヤミノヌシ'),'dark 08');
// Actual legendary capture and release cooldown, using guaranteed net and no party.
now=new orig.Date('2026-09-20T08:00:00Z').getTime();S.save.party=[];S.save.bag['マスターラグ']=2;enter('merire',20,6);await talk('end:rat');assert(S.save.party.some(m=>m.sp==='ラテット')&&!r.legendAvailable(S.save,'ラテット'),'Rat catch');releaseMon(S.save,'party',0);assert(!r.legendAvailable(S.save,'ラテット'),'Rat release today');now+=86400000;assert(r.legendAvailable(S.save,'ラテット'),'Rat release tomorrow');hero();enter('lab',8,7);await story.endNpc(w,{script:'end:professor'});assert(S.save.flags['end:clear']&&S.save.badges.includes(r.MASTER),'ending');
// Boat from actual item menu, water collision, landfall, reload and water scene.
enter('belerio',35,30);w.dir='right';await talk('end:boat');const {bagMenu}=await import('/src/menu.js');let bag=0;ui.itemList=async()=>bag++===0?{name:'小型ボート',category:0,index:0}:null;await bagMenu();assert(S.save.boating&&w.x===36,'boat menu');saveLocal();loadInto(loadLocal());w.enter('belerio',36,30,'right');w.busy=true;assert(S.save.boating&&w.x===36,'boat reload');w.dir='left';await story.useBoat(w);assert(!S.save.boating&&w.x===35,'boat landing');
assert(!r.specialShip(S.save,new orig.Date('2026-09-18T03:00:00Z'))&&r.specialShip(S.save,new orig.Date('2026-09-17T03:00:00Z')),'Thursday ship');const origParty=structuredClone(S.save.party);const team=story.trialTeam([makeMon('ラテット',100),makeMon('ギガビート',48),makeMon('オオヒノオ',70)]);assert(team.map(m=>m.lv).join(',')==='50,48,50','level cap');assert(JSON.stringify(S.save.party)===JSON.stringify(origParty),'party mutation');
// Battle engine trial party with fixed high damage fixture; no XP/EV or real-team changes.
const originalMove={...MOVES['スピードブロー']};MOVES['スピードブロー'].pow=10000;for(const m of team)m.moves=[newMove('スピードブロー')];const before=JSON.stringify(S.save.party),ev=JSON.stringify(team[0].ev),xp=team[0].exp;
await startBattle({trainer:{name:'大会検査',party:[['コオリン',1],['コオリン',1],['コオリン',1]]},playerParty:team,facility:true,tournament:true});assert(JSON.stringify(S.save.party)===before&&JSON.stringify(team[0].ev)===ev&&team[0].exp===xp,'facility rewards leak');
S.save.facilities={tower:{active:true,streak:9,best:9,team:structuredClone(team)}};let asks=0;ui.ask=async()=>asks++===0;enter('championTower',12,11);await story.runFacility(w,'tower');assert(S.save.facilities.tower.streak===10&&S.save.bag['レベルの実']===1,'tower 10 reward');S.save.facilities.galaxy={active:true,streak:49,best:49,team:structuredClone(team)};asks=0;await story.runFacility(w,'galaxy');assert(S.save.facilities.galaxy.streak===50&&S.save.flags['end:masterRag'],'galaxy 50');assert(r.facilityOpponent('tower',50).name==='ヤノケン'&&r.facilityOpponent('tower',100).name==='スイスはかせ','tower bosses');assert(['エデン','スイスはかせ'].includes(r.facilityOpponent('galaxy',40).name),'40 boss');Object.assign(MOVES['スピードブロー'],originalMove);saveLocal();loadInto(loadLocal());assert(S.save.facilities.tower.best===10&&S.save.flags['end:clear'],'save');return {story:'Momi, Clear, ice, Galaxy Yanoken, ruins, Dark, Rat, Swiss ending',calendar:'JST star days, legend first/next/owned/release',boat:'actual menu embark, save/reload, landing',facility:'cloned levels, actual 3-foe battle, no XP/EV leak, 10/50 rewards, 40/50/100 bosses',messages:log.length};
}finally{Object.assign(ui,{say:orig.say,ask:orig.ask,choice:orig.choice,itemList:orig.itemList});window.setTimeout=orig.timeout;window.Date=orig.Date;Math.random=orig.random;w.busy=true;}
});if(errors.length)throw Error(errors.join('\n'));fs.writeFileSync('artifacts/endgame-v37-'+(base.includes('127')?'local':'production')+'.json',JSON.stringify(report,null,2));console.log(report);}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
