const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('**/src/main.js*',r=>r.fulfill({body:'',contentType:'text/javascript'}));await p.route('**/usage-tracker.js*',r=>r.fulfill({body:'',contentType:'text/javascript'}));await p.goto(process.env.BASE||'http://127.0.0.1:5182/');
const result=await p.evaluate(async()=>{const A=await import('/src/heroArt127.js'),B=await import('/src/peopleArt119.js'),C=await import('/src/heroCatalog127.mjs');let maps=0,battles=0;
const pixels=(f,w,h)=>{const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(f,0,0);return c.getContext('2d').getImageData(0,0,w,h).data;};
const ready=async fn=>{for(let n=0;n<200;n++){const f=fn();if(f)return f;await new Promise(r=>setTimeout(r,20));}throw Error('Asset timeout');};
for(const gender of ['boy','girl'])for(const [hair]of C.HAIRSTYLES127[gender])for(const [outfit]of C.OUTFITS127){const look={gender,hairMap119:hair,outfit119:outfit,hair:''};
for(const dir of ['down','left','right','up'])for(const step of [0,1,2]){const f=await ready(()=>A.mapHeroFrame127(dir,step,look)),original=pixels(f,32,48);if(original.filter((v,i)=>i%4===3&&v>0).length<200)throw Error('Empty frame '+JSON.stringify({look,dir,step}));
for(const color of ['#f0f0f0','#21956c']){const changed=pixels(A.mapHeroFrame127(dir,step,{...look,hair:color}),32,48);let changes=0;for(let i=0;i<original.length;i++){if(i%4===3&&original[i]!==changed[i])throw Error('Alpha changed');if(original[i]!==changed[i]){changes++;if(i>=38*32*4)throw Error('Hair tint leaked onto legs');}}if(changes<6)throw Error('Hair not recolored '+JSON.stringify({look,dir,step,color}));}maps++;}
for(const view of ['front','back']){const f=await ready(()=>B.heroBattle119(look,view)),original=pixels(f,64,96),changed=pixels(B.heroBattle119({...look,hair:'#eeeeee'},view),64,96);let n=0;for(let i=0;i<original.length;i++){if(i%4===3&&original[i]!==changed[i])throw Error('Battle alpha');if(original[i]!==changed[i]){n++;if(i>=68*64*4)throw Error('Battle hair leaked');}}if(n<6)throw Error('Battle hair not recolored '+JSON.stringify({look,view}));battles++;}
}
return{maps,battles};});assert.deepEqual(errors,[]);console.log('PASS '+JSON.stringify(result));}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
