const fs=require('fs'),{chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
fs.mkdirSync('work/routes65',{recursive:true});
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const p=await b.newPage({viewport:{width:480,height:960}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.argv[2]||'http://127.0.0.1:5182/',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.VM);const result=await p.evaluate(async()=>{
 const {MAPS}=await import('/src/data/maps.js'),{SOLID}=await import('/src/tiles.js'),{drawChapterMap}=await import('/src/chapterArt.js');const report=[];
 for(const id of ['route3','route4']){const m=MAPS[id],q=[[m.spawn.x,m.spawn.y]],seen=new Set([q[0].join(',')]);for(let i=0;i<q.length;i++){const[x,y]=q[i];for(const[dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const a=x+dx,b=y+dy,k=a+','+b;if(m.rows[b]?.[a]!==undefined&&!SOLID.has(m.rows[b][a])&&!m.npcs.some(n=>n.x===a&&n.y===b)&&!seen.has(k)){seen.add(k);q.push([a,b])}}}
 for(const wp of m.warps)if(!seen.has(wp.x+','+wp.y))throw Error(id+' inaccessible exit '+JSON.stringify(wp));for(const other of Object.values(MAPS))for(const wp of other.warps)if(wp.to===id&&!seen.has(wp.tx+','+wp.ty))throw Error(id+' inaccessible arrival');
 for(const n of [...m.npcs,...m.signs,...m.items])if(![[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>seen.has((n.x+dx)+','+(n.y+dy))))throw Error(id+' inaccessible event '+n.name);
 for(const n of m.npcs){if(SOLID.has(m.rows[n.y][n.x]))throw Error('NPC blocked '+n.name);for(const [name,lv]of n.trainer?.party||[]){const mon=window.VM.makeMon(name,lv);if(!mon)throw Error('Unknown species '+name)}}
 for(const g of m.grassPlots)for(let y=g.y;y<g.y+g.h;y++)for(let x=g.x;x<g.x+g.w;x++)if(!seen.has(x+','+y))throw Error('Unreachable grass');
 report.push({id,reachable:seen.size,grass:m.grassPlots.length,trainers:m.npcs.filter(n=>n.trainer).length,props:m.props.length});}
 const images={};for(let repeat=0;repeat<3;repeat++){for(const id of ['route3','route4']){const m=MAPS[id],cv=document.createElement('canvas');cv.width=m.rows[0].length*32;cv.height=m.rows.length*32;drawChapterMap(cv.getContext('2d'),m,0,0);if(repeat===2)images[id]=cv.toDataURL();}if(repeat<2)await new Promise(r=>setTimeout(r,2500));}return{report,images};});
 for(const[id,url]of Object.entries(result.images))fs.writeFileSync('work/routes65/'+id+'.png',Buffer.from(url.split(',')[1],'base64'));
 for(const[id,x,y]of [['route3',22,14],['route4',6,8],['route4',19,16]]){await p.evaluate(({id,x,y})=>{const v=window.VM;v.State.save=v.newGame();v.State.save.party=[v.makeMon('トリッピ',10)];v.State.save.flags['v5:netGift']=true;v.world.enter(id,x,y,'up');v.setWorld();},{id,x,y});await p.waitForTimeout(700);await p.locator('#screen').screenshot({path:`work/routes65/game-${id}-${x}.png`});}console.log(JSON.stringify({report:result.report,errors}));if(errors.length)throw Error(errors.join(';'));}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
