const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const origin=process.env.VERIFY_ORIGIN||'http://127.0.0.1:5182',b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const p=await b.newPage();await p.route('**/src/main.js*',r=>r.fulfill({body:'',contentType:'text/javascript'}));await p.goto(origin,{waitUntil:'domcontentloaded'});const result=await p.evaluate(async()=>{
 const S=await import('/src/state.js'),{SPECIES}=await import('/src/data/species.js'),{MOVES}=await import('/src/data/moves.js'),{ui}=await import('/src/ui.js'),{bagMenu}=await import('/src/menu.js'),{moveStyle192,allowsMove192}=await import('/src/moveRules192.mjs'),{pocket}=await import('/src/itemScreens.js'),{catalog,initial,validateEdit}=await import('/src/editorModel72.mjs'),{MAPS}=await import('/src/data/maps.js');
 const mixed=Object.keys(SPECIES).find(n=>moveStyle192(SPECIES[n])==='mixed');S.G.save=S.newGame('検証');const mon=S.makeMon(mixed,20);mon.moves=[];S.G.save.party=[mon];const key='わざじゅもん：タックル';S.G.save.bag[key]=2;let shown=false;ui.say=async()=>{};ui.ask=async()=>true;ui.choice=async()=>0;ui.itemList=async()=>shown?null:(shown=true,{name:key,index:0,category:3});await bagMenu();if(mon.moves[0]?.name!=='タックル'||S.G.save.bag[key]!==1)throw Error('scroll usage failed');shown=false;await bagMenu();if(S.G.save.bag[key]!==1)throw Error('duplicate consumed');mon.moves=[];ui.ask=async()=>false;shown=false;await bagMenu();if(S.G.save.bag[key]!==1||mon.moves.length)throw Error('cancel consumed');
 for(const [name,sp]of Object.entries(SPECIES))for(const lv of[1,30,100]){const m=S.makeMon(name,lv);if(!m.moves.every(x=>allowsMove192(sp,x.name)))throw Error('invalid '+name);}
 const cat=catalog(MAPS),found=cat.props.filter(x=>x.pickup138?.startsWith('わざじゅもん：'));if(found.length!==Object.keys(MOVES).length)throw Error('palette missing');return {species:Object.keys(SPECIES).length,scrolls:found.length,pocket:pocket(key),use:true,cancel:true,duplicate:true};
 });assert.equal(result.pocket,3);console.log('PASS browser',result);
 const pub=await fetch(origin+'/api/map-editor').then(r=>r.json());pub.maps={};await p.addInitScript(()=>localStorage.setItem('vmon:token','test-only'));await p.route('**/api/map-editor',r=>{const d=r.request().method()==='POST'?r.request().postDataJSON():{};return r.fulfill({json:d.action==='session'?{name:'検証',definitions:pub.definitions}:d.action==='read'?{draft:null,published:null,draftRevision:0,publicRevision:pub.revision}:pub});});await p.goto(origin+'/map-editor/',{waitUntil:'domcontentloaded'});await p.locator('[data-category="items138"]').waitFor({timeout:60000});await p.locator('[data-category="items138"]').click();await p.locator('#search').fill('わざじゅもん：タックル');await p.getByText('わざじゅもん：タックル',{exact:false}).first().waitFor();await p.screenshot({path:'artifacts/moves192/workshop.png'});console.log('PASS workshop scroll search');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});

