const{chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{
 const base=process.argv[2]||'http://127.0.0.1:5179',p=await b.newPage({timezoneId:'America/Los_Angeles'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base);
 const report=await p.evaluate(async()=>{
 const {world:w}=await import('/src/world.js?v=20260912-daycare-yard-v29'),{G:S,newGame,makeMon,loadInto}=await import('/src/state.js'),{SPECIES}=await import('/src/data/species.js'),{newMove}=await import('/src/data/moves.js'),{MAPS}=await import('/src/data/maps.js'),{ui}=await import('/src/ui.js'),{saveLocal,loadLocal}=await import('/src/save.js'),r=await import('/src/voyageRules.js'),v=await import('/src/voyageStory.js');
 const check=(x,m)=>{if(!x)throw Error(m);};const original={say:ui.say,choice:ui.choice,ask:ui.ask,timeout:window.setTimeout,random:Math.random,Date:window.Date};const messages=[];ui.say=async a=>messages.push(...a);ui.ask=async()=>true;ui.choice=async()=>0;window.setTimeout=(fn,ms,...args)=>original.timeout.call(window,fn,Math.min(ms,5),...args);Math.random=()=>.5;let now=new original.Date('2026-09-12T03:00:00Z').getTime();window.Date=class extends original.Date{constructor(...a){super(...(a.length?a:[now]));}static now(){return now;}};
 const enter=(id,x,y)=>{w.enter(id,x,y,'up');w.busy=true;S.save.where={map:id,x:w.x,y:w.y,dir:'up'};};const talk=async script=>{const n=w.npcs.find(n=>n.script===script);check(n,'Missing '+script);await v.voyageNpc(w,n);};const hero=()=>{const m=makeMon('ラテット',100);m.moves=[newMove('タックル')];m.moves[0].pp=999;S.save.party=[m];};
 try{
 S.save=newGame('航海テスト');S.save.flags['v5:dex']=true;S.save.flags['power:passed']=true;S.save.flags['marine:passed']=true;hero();const species=Object.keys(SPECIES);
 S.save.dexOwn=Object.fromEntries(species.slice(0,14).map(n=>[n,true]));S.save.dexSeen=Object.fromEntries(species.map(n=>[n,true]));check(r.registeredCount(S.save)===14,'Seen counted');enter('karat',17,20);w.busy=false;check(v.tickVoyage(w),'No shop exit event');check(w.cameraFocus?.x===31,'Shop exit camera absent');while(w.busy)await new Promise(resolve=>original.timeout.call(window,resolve,20));w.busy=true;check(!w.cameraFocus,'Cutscene camera not restored');check(S.save.flags['voyage:professorMet']&&!r.hasShipTicket(S.save),'14 species awarded ticket');check(w.npcs.find(n=>n.script==='voyage:professor').y===16,'Professor did not exit shop');
 enter('lab',7,10);check(w.npcs.find(n=>n.script==='v5:professor').gone,'Professor duplicated');enter('karat',31,17);S.save.dexOwn[species[14]]=true;await talk('voyage:professor');check(S.save.bag[r.SHIP_TICKET]===1,'15 species no ticket');await talk('voyage:professor');check(S.save.bag[r.SHIP_TICKET]===1,'Duplicate ticket');enter('lab',7,10);check(!w.npcs.find(n=>n.script==='v5:professor').gone,'Professor not returned');
 const old=newGame('旧版');old.bag['れんらくせんチケット']=1;r.migrateVoyageSave(old);check(old.bag[r.SHIP_TICKET]===1&&!old.bag['れんらくせんチケット'],'Old ticket migration');
 for(const [t,yes] of [['2026-09-12T02:59:59Z',false],['2026-09-12T03:00:00Z',true],['2026-09-12T07:59:59Z',true],['2026-09-12T08:00:00Z',false]])check(r.boardingOpen(new original.Date(t))===yes,'JST boarding '+t);
 enter('karatPort',14,22);now=new original.Date('2026-09-12T08:00:00Z').getTime();await talk('voyage:board');check(w.mapId==='karatPort','Off-hours boarding');now=new original.Date('2026-09-12T03:00:00Z').getTime();await talk('voyage:board');check(w.mapId==='shipDeck'&&r.voyageRemaining(S.save)===180000,'Boarding/three minutes');check(S.save.bag[r.SHIP_TICKET]===1,'Ticket consumed');const arrival=S.save.voyage.arriveAt;await talk('voyage:disembark');check(w.mapId==='shipDeck','Early arrival');loadInto(loadLocal());check(S.save.voyage.arriveAt===arrival,'Reload reset voyage');now=arrival-1;check(!r.voyageDocked(S.save),'Arrival too early');now=arrival;check(r.voyageDocked(S.save),'3 minute arrival');w.busy=false;check(v.tickVoyage(w),'No arrival notification');while(w.busy)await new Promise(resolve=>original.timeout.call(window,resolve,10));w.busy=true;check(w.mapId==='shipDeck'&&S.save.voyage.arrivalAnnounced,'Forced off ship');
 const trainers=r.SHIP_MAPS.flatMap(id=>MAPS[id].npcs.filter(n=>n.dailyId).map(n=>({id,n})));check(trainers.length===10&&new Set(trainers.map(x=>x.n.dailyId)).size===10,'10 unique daily trainers');for(const {id,n}of trainers){for(const [sp]of n.dailyTeam)check(SPECIES[sp],'Unknown trainer species '+sp);hero();enter(id,n.x,n.y+1);await v.voyageNpc(w,w.npcs.find(x=>x.dailyId===n.dailyId));check(!r.trainerAvailable(S.save,n.dailyId),'Daily mark missing');}const xp=S.save.party[0].exp,money=S.save.money;await v.voyageNpc(w,w.npcs.find(x=>x.dailyId==='ship-9'));check(S.save.money===money&&S.save.party[0].exp===xp,'Second daily fight');check(r.trainerAvailable(S.save,'ship-0',new original.Date('2026-09-12T15:00:00Z')),'Midnight reset');
 hero();enter('shipLounge',19,19);await talk('voyage:yanoken');await talk('voyage:yanoken');check(S.save.flags['voyage:yanokenTalks']===2&&!S.save.flags['voyage:yanokenWon'],'Yanoken too early');await talk('voyage:yanoken');check(S.save.flags['voyage:yanokenWon'],'Yanoken battle failed');check(messages.some(x=>x.includes('ヨルネコ'))&&messages.some(x=>x.includes('アワミィ'))&&messages.some(x=>x.includes('コケゴロ')),'Yanoken wrong team');
 // Losing a daily battle uses the ship nurse and preserves the voyage.
 now+=86400000;S.save.party=[makeMon('トリッピ',1)];S.save.party[0].hp=1;enter('shipDeck',10,8);await talk('voyage:trainer');check(w.mapId==='shipLounge'&&S.save.party[0].hp>0&&S.save.voyage,'Ship loss stranded player');check(!r.trainerAvailable(S.save,'ship-0'),'Loss allowed repeat');
 enter('shipDeck',14,21);await talk('voyage:disembark');check(w.mapId==='resurePort'&&!S.save.voyage,'Disembark destination');check(loadLocal().where.map==='resurePort','Arrival not saved');now=new original.Date('2026-09-13T03:00:00Z').getTime();await talk('voyage:board');check(w.mapId==='shipDeck'&&S.save.voyage.to==='karatPort','Reusable return ticket');now+=180000;await talk('voyage:disembark');check(w.mapId==='karatPort','Return destination');
 // All species have a real, normally unlearnable child move.
 for(const [sp,info]of Object.entries(SPECIES)){const pool=r.eggMoves(sp);check(pool.length>0&&pool.every(n=>!info.learn.some(e=>e[1]===n)),'Invalid egg moves '+sp);}
 S.save.daycare=null;hero();const a=makeMon('トリッピ',7),b=makeMon('トリッピ',9);a.nick='親いち';b.nick='親に';S.save.party.push(a);S.save.box=[b];S.save.steps=100;enter('daycare',10,9);await talk('voyage:daycare');check(S.save.daycare&&S.save.party.length===1&&S.save.box.length===0,'Parents not deposited');check(S.save.daycare.parents[0]===a&&S.save.daycare.parents[1]===b,'Parents changed');const child=JSON.stringify(S.save.daycare.child);saveLocal();loadInto(loadLocal());check(JSON.stringify(S.save.daycare.child)===child,'Egg rerolled on load');check(S.save.daycare.child.lv===1&&S.save.daycare.child.moves.some(m=>m.name===S.save.daycare.child.eggMove),'Child level/move');
 S.save.steps=2099;check(r.daycareRemaining(S.save)===1&&!r.reclaimDaycare(S.save,true),'Born early');S.save.steps=2100;check(r.daycareRemaining(S.save)===0,'2000 step birth');while(S.save.party.length<6)S.save.party.push(makeMon('カニポン',8));await talk('voyage:daycare');check(!S.save.daycare&&S.save.box.length===3,'Overflow/return parents');check(S.save.box[0].nick==='親いち'&&S.save.box[1].nick==='親に'&&S.save.box[2].lv===1,'Parent identity lost');check(!r.reclaimDaycare(S.save,true),'Duplicate baby');
 const refs=[{collection:'box',index:0},{collection:'box',index:1}],baby=makeMon('トリッピ',1);check(!r.depositParents(S.save,refs,baby),'Redeposit');S.save.steps+=3;await talk('voyage:daycare');check(!S.save.daycare,'Cancel failed');check(S.save.box.length===3,'Cancelled child incorrectly delivered');
 check(r.checkParents(S.save,[{collection:'party',index:0},{collection:'party',index:0}]),'Same reference allowed');S.save.party=[makeMon('トリッピ',1),makeMon('トリッピ',1)];check(r.checkParents(S.save,[{collection:'party',index:0},{collection:'party',index:1}]),'Last healthy party deposited');
 const power=await import('/src/powerRules.js'),marine=await import('/src/marineRules.js');const held=newGame('預かり');held.flags['power:passed']=true;held.badges=['1','2','3','4'];held.daycare={parents:[makeMon('ライメイ',20),makeMon('メロロン',30)],child:makeMon('トリッピ',1)};check(!power.raimeiAvailable(held,new original.Date('2026-09-12T00:00:00Z')),'Daycare Raimei spawned again');check(marine.holdsMeroron(held)&&!marine.meroronAvailable(held,new original.Date('2026-09-12T09:00:00Z')),'Daycare Meroron spawned again');
 // Actual movement step path persists nursery progress (rather than elapsed time).
 hero();S.save.box=[makeMon('トリッピ',4),makeMon('トリッピ',4)];S.save.steps=0;r.depositParents(S.save,[{collection:'box',index:0},{collection:'box',index:1}],makeMon('トリッピ',1));enter('daycare',10,12);for(let i=0;i<2000;i++){w.x=i%2?10:11;w.y=12;await w.afterStep();}check(S.save.steps===2000&&r.daycareRemaining(S.save)===0,'Actual 2000 movement steps');check(loadLocal().steps===2000,'Movement not persisted');
 return {maps:Object.keys(MAPS).length,ticket:'14/15 caught species, walkout, lab return, legacy migration',voyage:'JST boundaries, reusable roundtrip, 180000ms, reload and arrival notification',trainers:'10 actual battles, daily reset, defeat recovery; Yanoken third conversation',daycare:'153 species egg moves, retained parents, reload, exact 2000 real step calls, cancel, overflow and no duplicates',messages:messages.length};
 }finally{Object.assign(ui,{say:original.say,ask:original.ask,choice:original.choice});window.Date=original.Date;window.setTimeout=original.timeout;Math.random=original.random;w.busy=true;}
 });if(errors.length)throw Error(errors.join('\n'));fs.writeFileSync('artifacts/voyage-v28-'+(base.includes('127')?'local':'production')+'.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
