const assert=require('node:assert/strict');
(async()=>{const E=await import('../src/editorModel72.mjs'),{addManagedPeople120}=await import('../src/managedPeople120.mjs'),{extendMaps82}=await import('../src/customMaps82.mjs'),{PARK_AREAS131,isGaonPark131}=await import('../src/parkMaps131.mjs'),{forestCell131}=await import('../src/forestObjects131.mjs'),{recordParkCatch,parkCount}=await import('../src/frontierRules.js');
const maps=extendMaps82(addManagedPeople120(structuredClone(require('../assets/editor-v72/base-maps.json')))),cat=E.catalog(maps,require('../assets/editor-v72/species.json'));
for(const id of ['mountain','gaonPark','gaonParkWoods','gaonParkWetland','gaonParkFlowers','gaonParkHill','flowerPark','belerioPort','belerioPortHome131'])assert.deepEqual(E.validateEdit(maps[id],E.initial(maps[id]),cat),[],id);
const m=maps.mountain,d=E.initial(m),trees=d.objects.filter(o=>E.objectSource(m,o,cat)?.forest131);assert(trees.length>30);const tree=trees.find(o=>o.x===28&&o.y>=3),art=E.objectSource(m,tree,cat);assert.equal(art.art,'mountain-conifer131');assert(art.forest131.h>=64);tree.x=18;tree.y=12;assert.deepEqual(E.validateEdit(m,d,cat),[]);const applied=E.applyEdit(m,d,cat),moved=applied.editorAddedProps72.find(p=>p.editorObjectId72===tree.id);assert.deepEqual(moved.forest131,art.forest131);assert(applied.forestObjects131);assert(applied.editorAddedProps72.filter(p=>p.forest131).length<trees.length,'duplicate border trees are removed');
const legacy=E.initial(m);delete legacy.forest131;legacy.objects=legacy.objects.filter(o=>!E.objectSource(m,o,cat)?.forest131);for(let y=0;y<m.rows.length;y++)for(let x=0;x<m.rows[0].length;x++)if(forestCell131(m,x,y))legacy.objects.push({id:'g:'+(y*m.rows[0].length+x),type:'prop',template:'tree',x,y});const upgraded=E.upgrade79(m,legacy);assert.deepEqual(E.validateEdit(m,upgraded,cat),[]);assert(upgraded.objects.filter(o=>E.objectSource(m,o,cat)?.forest131).length<trees.length,'legacy border migrates to a single row');assert.deepEqual(E.upgrade79(m,upgraded),upgraded);
const caught={};const pools=[];for(const [id,,pool]of PARK_AREAS131){assert(isGaonPark131(id));assert.deepEqual(maps[id].enc.list.map(e=>e[0]),pool);for(const n of pool){assert(!pools.includes(n));pools.push(n);recordParkCatch(caught,id,n);}for(const wp of maps[id].warps){assert(maps[wp.to]);assert(E.pass(maps[wp.to],wp.tx,wp.ty),id+' destination '+wp.to);}}assert.equal(parkCount(caught),10);assert.equal(maps.flowerPark.rows[0].length,84);assert.equal(maps.flowerPark.rows.length,42);
for(const id of ['gaonPark','flowerPark','belerioPort']){const next=maps[id],old=next.layoutBefore131,doc=E.initial(old);delete doc.areas131;assert.deepEqual(E.validateEdit(next,doc,cat),[],id+' saved migration');const migrated=E.upgrade79(next,doc);assert.deepEqual(E.upgrade79(next,migrated),migrated);}
const port=maps.belerioPort;const ship=port.props.find(p=>p.art==='eShip');for(let y=ship.y;y<ship.y+ship.h;y++)for(let x=ship.x;x<ship.x+ship.w;x++)assert.equal(port.rows[y][x],'W');assert(port.warps.some(w=>w.to==='shop'));assert(port.warps.some(w=>w.to==='belerioPortHome131'));
const dark=cat.props.find(p=>p.key==='legacy73-eDarkTree');assert.equal(dark.w,2);assert.equal(dark.h,3);console.log('PASS forest trees',trees.length,'move/migration; 5 unique park pools and catches; 84x42 flower park; port houses and water; dark tree 2x3');
})().catch(e=>{console.error(e);process.exit(1)});
