const {chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict'),fs=require('node:fs'),root=require('node:path').resolve(__dirname,'..').replaceAll('\\','/');process.env.TEMP=root+'/work/tmp';process.env.TMP=process.env.TEMP;
(async()=>{const c=await chromium.launchPersistentContext(root+'/work/chapter-mobile',{executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,viewport:{width:430,height:932},isMobile:true,hasTouch:true});const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));try{await p.goto('http://127.0.0.1:5179/?v4test=hut');await p.waitForFunction(()=>window.VM?.world.map?.tileWorld);const cd=await c.newCDPSession(p);
const stick=async(x,y)=>{const b=await p.locator('#joystick').boundingBox(),cx=b.x+b.width/2,cy=b.y+b.height/2;await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx,y:cy}]});await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx+x*35,y:cy+y*35}]});await p.waitForTimeout(90);await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(230)};
const y=await p.evaluate(()=>VM.world.y);await stick(0,-1);assert.ok(await p.evaluate(y=>VM.world.y<y,y));
await p.evaluate(()=>VM.world.enter('rods',5,11,'up'));await stick(0,-1);await p.waitForFunction(()=>VM.world.mapId==='hospital'&&!VM.world.busy);await p.screenshot({path:root+'/artifacts/chapter-mobile-hospital.png'});
const checks=await p.evaluate(async()=>{const {MAPS}=await import('/src/data/maps.js?v=20260908-gaon-v9'),{solid}=await import('/src/tiles.js');const issues=[];for(const [id,m] of Object.entries(MAPS)){for(const prop of m.props.filter(p=>p.art==='tree'||p.art==='fir'))for(let y=prop.y;y<prop.y+prop.h;y++)for(let x=prop.x;x<prop.x+prop.w;x++)if(!solid(m.rows[y][x]))issues.push(id+' tree');if(['village','rods'].includes(id)&&m.enc)issues.push(id+' town encounter');}if(![MAPS.route1,MAPS.route2,MAPS.mountain,MAPS.natureforest].every(m=>m.rows.some(r=>r.includes('"'))))issues.push('missing grass');return issues;});assert.deepEqual(checks,[]);
await p.evaluate(()=>{VM.world.enter('natureforest',9,13,'down')});const before=await p.evaluate(()=>[VM.world.x,VM.world.y]);await stick(0,1);assert.deepEqual(await p.evaluate(()=>[VM.world.x,VM.world.y]),before);
await p.evaluate(()=>{VM.world.enter('village',13,12,'down');VM.State.save.backTo={map:'village',x:13,y:12}});await p.waitForTimeout(200);await p.screenshot({path:root+'/artifacts/chapter-mobile-village.png'});
// Battle rendering and item menu at phone dimensions, with a fixture encounter.
await p.evaluate(()=>{VM.State.save.party=[VM.makeMon('ネズミン',3)];VM.State.save.bag={'ラグネット':3};VM.State.save.battleTerrain='grass';VM.startBattle({wild:VM.makeMon('トリッピ',3)});});for(let i=0;i<18;i++){await p.locator('#ba').tap();await p.waitForTimeout(100)}await p.screenshot({path:root+'/artifacts/chapter-mobile-battle.png'});
assert.deepEqual(errors,[]);console.log(JSON.stringify({touchMovement:true,door:true,shoreBlocked:true,treeFootprints:true,grassEveryRoute:true,townNoEncounters:true,errors}));fs.writeFileSync(root+'/artifacts/chapter-mobile.json',JSON.stringify({touchMovement:true,door:true,shoreBlocked:true,treeFootprints:true,grassEveryRoute:true,townNoEncounters:true,errors},null,2));}finally{await c.close()}})().catch(e=>{console.error(e);process.exitCode=1});
