const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),L=require(root+'/api/_lib'),F=require(root+'/api/_friendStore');
const admin={id:'ヤノケン',created:1789724902905,display:'ヤノケン'},ordinary={id:'tester',created:1};L.setPw(admin,'test-only-password');let docs={};L.readUser=async id=>id===admin.id?admin:id==='tester'?ordinary:null;L.findUser=async name=>name===admin.id?admin:null;L.configured=()=>true;F.read=async keys=>Object.fromEntries(keys.filter(k=>docs[k]).map(k=>[k,structuredClone(docs[k])]));F.commit=async(expected,writes)=>{if(Object.entries(expected).some(([k,v])=>(docs[k]?.version||0)!==v))return false;for(const[k,v]of Object.entries(writes))docs[k]={version:(docs[k]?.version||0)+1,data:structuredClone(v)};return true;};
const handler=require(root+'/api/map-editor'),auth=require(root+'/api/auth');
const mime={'.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp3':'audio/mpeg'};
const server=http.createServer(async(req,res)=>{res.status=c=>{res.statusCode=c;return res};res.json=v=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(v))};const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){let body='';for await(const b of req)body+=b;try{req.body=JSON.parse(body||'{}');}catch{req.body={};}if(url.pathname==='/api/map-editor')return handler(req,res);if(url.pathname==='/api/auth')return auth(req,res);return res.status(200).json({});}let file=path.join(root,decodeURIComponent(url.pathname));if(!file.startsWith(path.normalize(root)))return res.status(403).end();try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);}catch{res.status(404).end();}});
(async()=>{await new Promise(r=>server.listen(5183,'127.0.0.1',r));const {chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{
 const m=await import(require('url').pathToFileURL(root+'/src/editorModel72.mjs').href),maps=require(root+'/assets/editor-v72/base-maps.json'),cat=m.catalog(maps,require(root+'/assets/editor-v72/species.json'));
 const base={...maps.rods,id:'fixture81',rows:Array.from({length:24},()=>'.'.repeat(24)),props:[],npcs:[],warps:[],items:[],signs:[],spawn:{x:2,y:2},townGardens:[]};
 for(let turn81=0;turn81<4;turn81++){const d=m.initial(base);d.objects.push({id:'a:clinic',type:'prop',template:'hospital',x:8,y:8,turn81});assert.deepEqual(m.validateEdit(base,d,cat),[]);const out=m.applyEdit(base,d,cat),wp=out.warps[0];assert(m.pass(out,wp.x,wp.y));assert(m.pass(out,wp.back.x,wp.back.y));d.objects[0].template='lamp';assert.deepEqual(m.validateEdit(base,d,cat),[]);const p=m.objectSource(base,d.objects[0],cat);assert.deepEqual([p.w,p.h],turn81%2?[2,1]:[1,2]);}
 const paths=await import(require('url').pathToFileURL(root+'/src/gardenCatalog75.mjs').href);assert(paths.PATHS75.length>=69);for(const label of ['青い装飾タイル','和風の丸石畳','透過の白レンガ'])for(const edge of ['上ふち','右ふち','下ふち','左ふち'])assert(paths.PATHS75.some(p=>p.label===label+'・'+edge),label+edge);
 const errors=[],p=await browser.newPage({viewport:{width:960,height:850}});p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5183/?v4test=rods');await p.waitForFunction(()=>window.VM);await p.waitForTimeout(1500);
 const data=await p.evaluate(async()=>{const menu=await import('/src/menu.js'),{ui}=await import('/src/ui.js'),{APPEARANCE_COLORS}=await import('/src/data/fashion.js');const old={choice:ui.choice,ask:ui.ask,say:ui.say};VM.State.save.money=0;let seq=[0,38,3,14,-1];ui.choice=async()=>seq.shift();ui.ask=async()=>true;ui.say=async()=>{};try{await menu.freeColors81();if(VM.State.save.money!==0||VM.State.save.look.shirt!==APPEARANCE_COLORS[38].color||VM.State.save.look.hair!==APPEARANCE_COLORS[14].color)throw Error('Free colors');}finally{Object.assign(ui,old);}VM.world.enter('rods',7,11,'up');const wp=VM.world.map.warps.find(w=>w.x===7&&w.y===10);if(!wp)throw Error('door missing');await VM.world.doWarp(wp);const inside=VM.world.mapId;await VM.world.doWarp(VM.world.map.warps.find(w=>w.to==='@back'));if(VM.world.mapId!=='rods')throw Error('hospital return');return {inside,colors:'free and saved',paths:69};});
 await p.screenshot({path:'work/admin72/screens/hospital81-game.png'});
 const sheet=await p.evaluate(async()=>{const {drawMaterial}=await import('/src/chapterArt.js'),{drawShop74}=await import('/src/shopArt74.js');const cv=document.createElement('canvas');cv.width=768;cv.height=240;const c=cv.getContext('2d');c.fillStyle='#73c68d';c.fillRect(0,0,768,240);c.imageSmoothingEnabled=false;drawMaterial(c,'chaletClinic',16,16,160,160);drawShop74(c,{art:'harborShop',x:7,y:.5,w:5,h:5});drawShop74(c,{art:'fashionShop74',x:14,y:1.5,w:4,h:4});c.strokeStyle='#ffffff80';for(let x=16;x<768;x+=32){c.beginPath();c.moveTo(x,0);c.lineTo(x,200);c.stroke();}c.strokeStyle='#fffd73';c.strokeRect(16+128,16+128,32,32);c.beginPath();c.moveTo(160,132);c.lineTo(160,188);c.stroke();return cv.toDataURL().split(',')[1];});fs.writeFileSync('work/admin72/screens/buildings81.png',Buffer.from(sheet,'base64'));
 await p.evaluate(async()=>{const menu=await import('/src/menu.js'),{ui}=await import('/src/ui.js');const old=ui.choice;let calls=0;ui.choice=(items,o)=>{if(calls++===0)return Promise.resolve(1);return old.call(ui,items,o);};window.runShop81=menu.clothesShop('rods');});await p.waitForTimeout(700);await p.screenshot({path:'work/admin72/screens/clothes81.png'});
 const ed=await browser.newPage({viewport:{width:1440,height:1000}});ed.on('pageerror',e=>errors.push(e.message));await ed.goto('http://127.0.0.1:5183/map-editor/');await ed.locator('#password').fill('test-only-password');await ed.locator('#loginForm button').click();await ed.waitForFunction(()=>!document.querySelector('.layout').inert&&!document.getElementById('app').hidden);await ed.locator('[data-category="paths"]').click();await ed.locator('.material').first().click();await ed.locator('#rotateRight81').click();assert.equal(await ed.locator('#rotation81').textContent(),'90°');await ed.locator('#rotateLeft81').click();assert.equal(await ed.locator('#rotation81').textContent(),'0°');await ed.screenshot({path:'work/admin72/screens/rotation81.png'});
 assert.deepEqual(errors,[]);console.log('PASS v81',JSON.stringify(data),'4 rotations with door access, rectangular footprint, path directions, free colors, real hospital roundtrip, editor controls',errors);
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
