const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict'),{chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const response=await fetch('https://midori-no-shima.vercel.app/api/map-editor?check214='+Date.now());assert(response.ok);const pub=await response.text();fs.mkdirSync('artifacts/shore218',{recursive:true});fs.writeFileSync('artifacts/shore218/preview.json',pub);const server=http.createServer((q,r)=>{let name=new URL(q.url,'http://localhost').pathname;if(name==='/api/map-editor'){r.setHeader('Content-Type','application/json');return r.end(pub);}if(name.endsWith('/'))name+='index.html';const f=path.resolve('.'+decodeURIComponent(name));if(!f.startsWith(process.cwd()+path.sep))return r.writeHead(403).end();r.setHeader('Content-Type',/\.(js|mjs)$/.test(f)?'text/javascript':f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':f.endsWith('.json')?'application/json':f.endsWith('.png')?'image/png':'application/octet-stream');const stream=fs.createReadStream(f);stream.on('error',()=>r.writeHead(404).end());stream.pipe(r);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});fs.mkdirSync('artifacts/shore218',{recursive:true});try{const p=await b.newPage({viewport:{width:1100,height:1250}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:'+server.address().port+'/?v4test=kageri',{waitUntil:'domcontentloaded',timeout:120000});await p.waitForFunction(()=>window.VM?.world?.mapId==='kageri',null,{timeout:180000});const result=await p.evaluate(async()=>{
 const {drawPortShore163}=await import('/src/portLayout163.mjs'),{drawShore173}=await import('/src/shore173.js'),{sizeTemplate86}=await import('/src/sceneCatalog86.mjs'),{upgradeShip218}=await import('/src/shipFootprint218.mjs'),{MAPS}=await import('/src/data/maps.js');
 const ok=(v,m)=>{if(!v)throw Error(m);};const c=document.createElement('canvas');c.width=c.height=96;const ctx=c.getContext('2d'),count=()=>ctx.getImageData(0,0,96,96).data.filter((v,i)=>i%4===3&&v>0).length;
 for(const [id,draw]of [['karatPort',drawPortShore163],['route7',drawShore173]]){const map={id,port163:{},rows:[',,,','WWW','WWW'],editorGround72:[]};draw(ctx,map,0,0);ok(count()>0,'Unpainted shore missing '+id);ctx.clearRect(0,0,96,96);map.editorGround72=[0,1,2].map(x=>({x,y:0,material:'grass'}));draw(ctx,map,0,0);ok(count()===0,'Land repaint retains shore '+id);ctx.clearRect(0,0,96,96);map.editorGround72=[0,1,2].map(x=>({x,y:1,material:'sea-floor140'}));draw(ctx,map,0,0);ok(count()===0,'Water repaint retains shore '+id);}
 for(const key of ['ferry','eShip','legacy73-ferry','liner86'])ok(sizeTemplate86({art:key}).h===3,'Tall boat '+key);
 const d={objects:[{id:'p:0',x:1,y:2}]},base={props:[{art:'ferry'}]},up=upgradeShip218(base,d);ok(up.objects[0].y===4,'Boat position');ok(upgradeShip218(base,up)===up,'Migration repeats');
 VM.world.enter('karatPort');VM.ui.clear();const map=VM.world.map,boats=[...(map.props||[]),...(map.editorAddedProps72||[])].filter(p=>/ferry|eShip|liner86/.test(p.art));ok(boats.length>0,'No ship');ok(boats.every(p=>p.h===3),'Live boat remains tall');
 const {drawChapterMap}=await import('/src/chapterArt.js');const cv=document.createElement('canvas');cv.id='preview218';cv.width=map.rows[0].length*32;cv.height=map.rows.length*32;cv.style.cssText='position:fixed;top:0;left:0;z-index:99999;max-width:100vw;max-height:100vh;object-fit:contain;background:#173833';document.body.append(cv);window.redraw218=()=>drawChapterMap(cv.getContext('2d'),map,0,0);redraw218();return {shoreRepaintChecks:4,boats:boats.map(p=>({x:p.x,y:p.y,w:p.w,h:p.h}))};
});await p.waitForTimeout(1500);await p.evaluate(()=>redraw218());await p.locator("#preview218").screenshot({path:"artifacts/shore218/port.png"});console.log(JSON.stringify(result));assert.deepEqual(errors,[]);console.log('PASS map previews',errors);}finally{await b.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});