const fs=require('fs'),assert=require('assert/strict');const{chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.argv[2]||'http://127.0.0.1:5182/',{waitUntil:'networkidle'});
const report=await p.evaluate(async()=>{const{MAPS}=await import('/src/data/maps.js');const{drawChapterMap}=await import('/src/chapterArt.js');const{drawFollower,loadFollowerSheet,followerSize,followerFrame}=await import('/src/followerArt.js');
const results=[];for(const m of Object.values(MAPS)){if(m.townPond){const[x,y,w,h]=m.townPond;for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)if(m.rows[yy][xx]!=='W')throw Error('Pond corner missing '+m.id+' '+xx+','+yy);}
if(m.grassPlots){let count=0;for(const q of m.grassPlots){for(let y=q.y;y<q.y+q.h;y++)for(let x=q.x;x<q.x+q.w;x++){if(m.rows[y][x]!=='"')throw Error('Broken grass rectangle');count++;}}
const actual=m.rows.join('').split('"').length-1;if(count!==actual||!count)throw Error('Unbounded or empty habitat '+m.id);results.push([m.id,m.grassPlots.length,count]);}}
if(followerSize('アビサージ')!==56)throw Error('Follower size');await loadFollowerSheet('アビサージ');
// A disconnected large shape is a neighbouring sprite fragment, not a stride.
for(const dir of ['up','down','left','right'])for(let row=0;row<3;row++){const f=followerFrame('アビサージ',dir,row),a=f.getContext('2d').getImageData(0,0,80,80).data,seen=new Set(),parts=[];for(let k=0;k<6400;k++){if(seen.has(k)||!a[k*4+3])continue;let q=[k];seen.add(k);for(let i=0;i<q.length;i++){const n=q[i],x=n%80,y=Math.floor(n/80);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const xx=x+dx,yy=y+dy,z=yy*80+xx;if(xx>=0&&xx<80&&yy>=0&&yy<80&&!seen.has(z)&&a[z*4+3]){seen.add(z);q.push(z);}}}parts.push(q.length);}parts.sort((a,b)=>b-a);if(parts[1]>parts[0]*.08)throw Error('Detached follower fragment '+dir+' '+row);}
const panels=[['village',7,17],['village',17,4],['route1',3,8],['mountain',9,37]];const cv=document.createElement('canvas');cv.width=1280;cv.height=1152;const c=cv.getContext('2d');c.imageSmoothingEnabled=false;
const draw=()=>{for(let i=0;i<panels.length;i++){const[id,x,y]=panels[i];c.save();c.translate(i%2*640,Math.floor(i/2)*576);c.scale(2,2);c.beginPath();c.rect(0,0,320,288);c.clip();drawChapterMap(c,MAPS[id],x*32,y*32);if(i===0)drawFollower(c,{sp:'アビサージ'},{dir:'up',moving:true},0,200,80);c.restore();}};draw();await new Promise(r=>setTimeout(r,2500));draw();return{plots:results,image:cv.toDataURL()};});
assert.deepEqual(errors,[]);fs.writeFileSync('artifacts/gardens-v52.png',Buffer.from(report.image.split(',')[1],'base64'));console.log('PASS rectangular ponds, bounded grass plots, follower scale and no detached fragments',JSON.stringify(report.plots));}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
