const fs=require('fs');fs.mkdirSync('work/art63',{recursive:true});const {chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const p=await b.newPage({viewport:{width:1100,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const base=process.argv[2]||'http://127.0.0.1:5182';await p.goto(base,{waitUntil:'domcontentloaded'});const r=await p.evaluate(async()=>{
 const {SPECIES,DEX_TOTAL}=await import('/src/data/species.js'),{canonicalName}=await import('/src/data/redesignV47.js'),{V63_DESIGNS}=await import('/src/data/redesignV63.js'),{BATTLE_ART_FILES,BATTLE_BACK_ART_FILES}=await import('/src/data/battleart.js'),{MONART}=await import('/src/data/monart.js'),{loadFollowerSheet,followerFrame,followerSheet}=await import('/src/followerArt.js'),{makeMon,loadInto,G,newGame}=await import('/src/state.js'),{ordinaryEncounters}=await import('/src/rareEncounters.js'),{MAPS}=await import('/src/data/maps.js'),{habitatEntries}=await import('/src/habitats.js');
 const assert=(ok,m)=>{if(!ok)throw Error(m);};assert(DEX_TOTAL===156,'Count');assert(new Set(Object.values(SPECIES).map(s=>s.no)).size===156,'Unique ids');
 for(const [from,to,lv]of [['コノハギ','ハヤナギ',16],['ハヤナギ','カゲナギ',36],['ワルニール','ワルヴェイン',42]])assert(SPECIES[from].evo.to===to&&SPECIES[from].evo.lv===lv,'Evolution '+from);
 assert(!SPECIES['カゲナギ'].evo&&!SPECIES['ワルヴェイン'].evo,'Final stages');
 const oldNames=['アビサージ','ザンガルド','スナコロネ','ウロコロ','ネズミン','ヨロイガル','ヒカリギリ'];const save=newGame();save.party=oldNames.map(n=>({...makeMon(n,50),sp:n}));save.dexOwn=Object.fromEntries(oldNames.map(n=>[n,1]));loadInto(save);for(let i=0;i<oldNames.length;i++)assert(G.save.party[i].sp===canonicalName(oldNames[i]),'Save alias '+oldNames[i]);
 const sheet=document.createElement('canvas');sheet.width=760;sheet.height=V63_DESIGNS.length*110;const ctx=sheet.getContext('2d');ctx.fillStyle='#d9e7e4';ctx.fillRect(0,0,sheet.width,sheet.height);ctx.imageSmoothingEnabled=false;
 for(let i=0;i<V63_DESIGNS.length;i++){const n=V63_DESIGNS[i].name;assert(MONART[n],'Battle guard '+n);ctx.fillStyle='#172b3b';ctx.font='15px sans-serif';ctx.fillText(n,5,i*110+18);for(const[v,files]of [[0,BATTLE_ART_FILES],[1,BATTLE_BACK_ART_FILES]]){assert(files[n].includes('redesign-v63'),'Old path '+n);const im=new Image();im.src=new URL(files[n],location.origin+'/src/data/battleart.js');await im.decode();ctx.drawImage(im,130+v*90,i*110,90,90);}
 assert(await loadFollowerSheet(n),'Follower load '+n);assert(followerSheet(n).naturalWidth===320&&followerSheet(n).naturalHeight===240,'Sheet size '+n);
 for(let d=0;d<4;d++){const dir=['down','up','right','left'][d],hashes=[];for(let f=0;f<3;f++){const c=followerFrame(n,dir,f),data=c.getContext('2d').getImageData(0,0,80,80).data;let opaque=0;for(let y=0;y<80;y++)for(let x=0;x<80;x++){if(data[(y*80+x)*4+3]>128){opaque++;assert(x>=4&&x<76&&y>=3&&y<76,'Bleed '+n);}}assert(opaque>100,'Empty '+n);hashes.push(c.toDataURL());if(f===1)ctx.drawImage(c,320+d*85,i*110+10,80,80);}assert(new Set(hashes).size===3,'Missing walk frames '+n+dir);}
 }
 for(const[name,s]of Object.entries(SPECIES)){if(s.evo)assert(SPECIES[s.evo.to],'Missing target '+name);}
 assert(habitatEntries('コノハギ').some(e=>e.mapId==='natureforest'),'No habitat');assert(ordinaryEncounters(MAPS.natureforest.enc.list,'natureforest').some(e=>e[0]==='コノハギ'),'No encounter');return{image:sheet.toDataURL(),count:DEX_TOTAL,names:V63_DESIGNS.map(s=>s.name),build:document.querySelector('meta[name="voraz-build"]').content};});fs.writeFileSync('work/art63/browser.png',Buffer.from(r.image.split(',')[1],'base64'));delete r.image;
 await p.goto(base+'/gaon-zukan/',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.querySelectorAll('.habitat-map').length===156);const cards=await p.evaluate(()=>({count:document.querySelectorAll('article').length,old:[...document.querySelectorAll('article b')].some(b=>['アビサージ','ヒカリギリ','ウロコロ','ヨロイガル'].includes(b.textContent))}));if(cards.count!==156||cards.old||errors.length)throw Error(JSON.stringify({cards,errors}));console.log(JSON.stringify({...r,cards,errors,checks:'aliases, evolutions, battle art, 120 walking frames, habitats passed'}));}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
