const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),L=require(root+'/api/_lib'),F=require(root+'/api/_friendStore');
const admin={id:'ヤノケン',created:1789724902905,display:'ヤノケン'},ordinary={id:'tester',created:1};L.setPw(admin,'test-only-password');let docs={};L.readUser=async id=>id===admin.id?admin:id==='tester'?ordinary:null;L.findUser=async name=>name===admin.id?admin:null;L.configured=()=>true;F.read=async keys=>Object.fromEntries(keys.filter(k=>docs[k]).map(k=>[k,structuredClone(docs[k])]));F.commit=async(expected,writes)=>{if(Object.entries(expected).some(([k,v])=>(docs[k]?.version||0)!==v))return false;for(const[k,v]of Object.entries(writes))docs[k]={version:(docs[k]?.version||0)+1,data:structuredClone(v)};return true;};
const handler=require(root+'/api/map-editor'),auth=require(root+'/api/auth');
const mime={'.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp3':'audio/mpeg'};
const server=http.createServer(async(req,res)=>{res.status=c=>{res.statusCode=c;return res};res.json=v=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(v))};const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){let body='';for await(const b of req)body+=b;try{req.body=JSON.parse(body||'{}');}catch{req.body={};}if(url.pathname==='/api/map-editor')return handler(req,res);if(url.pathname==='/api/auth')return auth(req,res);return res.status(200).json({});}let file=path.join(root,decodeURIComponent(url.pathname));if(!file.startsWith(path.normalize(root)))return res.status(403).end();try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);}catch{res.status(404).end();}});
(async()=>{await new Promise(r=>server.listen(5183,'127.0.0.1',r));const {chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{
 const p=await browser.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5183/map-editor/');await p.locator('#password').fill('test-only-password');await p.locator('#loginForm button').click();await p.waitForFunction(()=>!document.querySelector('.layout').inert&&!document.getElementById('app').hidden);await p.locator('[data-panel79=materials]').click();await p.locator('#newMap82').click();await p.locator('#newMapName82').fill('出現設定テスト');await p.locator('#newEncounters86 button').click();await p.locator('#newEncounters86 select').selectOption('ハナビィ');const inputs=p.locator('#newEncounters86 input');await inputs.nth(0).fill('100');await inputs.nth(0).press('Tab');await inputs.nth(1).fill('12');await inputs.nth(1).press('Tab');await inputs.nth(2).fill('18');await inputs.nth(2).press('Tab');await p.screenshot({path:'work/admin72/screens/encounters86-mobile.png'});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#newMapForm82 button[type=submit]').click();await p.waitForFunction(()=>document.getElementById('mapSelect').value.startsWith('custom82-')&&!document.querySelector('.layout').inert);const id=await p.locator('#mapSelect').inputValue();await p.locator('#publish').click();await p.locator('#confirmPublish').click();await p.waitForFunction(()=>document.getElementById('dirty').textContent==='公開済み');let published=await (await fetch('http://127.0.0.1:5183/api/map-editor')).json();assert.deepEqual(published.definitions[id].encounters86,{rate:100,list:[['ハナビィ',12,18,10]]});
 await p.locator('summary').filter({hasText:'出現するガオンを設定'}).click();await p.locator('#mapEncounters86 select').selectOption('コケゴロ');await p.locator('#save').click();await p.waitForFunction(()=>!document.querySelector('.layout').inert);await p.reload();await p.waitForFunction(()=>!document.getElementById('app').hidden);await p.locator('[data-panel79=materials]').click();await p.locator('#mapSelect').selectOption(id);await p.waitForFunction(()=>!document.querySelector('.layout').inert);assert.equal(await p.locator('#mapEncounters86 select').inputValue(),'コケゴロ');await p.locator('#publish').click();await p.locator('#confirmPublish').click();await p.waitForFunction(()=>document.getElementById('dirty').textContent==='公開済み');
 const invalid=await p.evaluate(async id=>{const mod=await import('/src/editorModel72.mjs'),{extendMaps82}=await import('/src/customMaps82.mjs'),pub=await fetch('/api/map-editor').then(r=>r.json()),base=extendMaps82(await fetch('/assets/editor-v72/base-maps.json').then(r=>r.json()),pub.definitions),species=await fetch('/assets/editor-v72/species.json').then(r=>r.json()),cat=mod.catalog(base,species),edit=pub.maps[id];return [['存在しない',1,5,10],['コケゴロ',20,5,10],['コケゴロ',1,101,10],['コケゴロ',1,5,0]].map(e=>mod.validateEdit(base[id],{...edit,encounters86:{rate:18,list:[e]}},cat).length);},id);assert(invalid.every(Boolean));
 const game=await browser.newPage();game.on('pageerror',e=>errors.push(e.message));await game.goto('http://127.0.0.1:5183/?v4test=rods');await game.waitForFunction(()=>window.VM);const enc=await game.evaluate(async id=>{const {MAPS}=await import('/src/data/maps.js?v=20260913-fashion-v50');VM.world.enter(id,5,5,'down');return {enc:VM.world.map.enc,explicit:VM.world.map.encountersConfigured86};},id);assert.deepEqual(enc,{enc:{rate:100,list:[['コケゴロ',12,18,10]]},explicit:true});await game.evaluate(()=>{VM.State.save.flags['v5:netGift']=true;VM.State.save.boating=false;VM.world.map.rows[5]=VM.world.map.rows[5].slice(0,5)+'"'+VM.world.map.rows[5].slice(6);VM.ui.say=lines=>{window.wildIntro86=lines.join(' ');return new Promise(()=>{});};void VM.world.afterStep();});await game.waitForFunction(()=>window.wildIntro86?.includes('コケゴロ'));assert(await game.evaluate(()=>VM.battle.active));assert.deepEqual(errors,[]);console.log('PASS encounter create/mobile/save/reload/publish/runtime/invalid species/level validation');
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
