const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),L=require(root+'/api/_lib'),F=require(root+'/api/_friendStore');
const admin={id:'ヤノケン',created:1789724902905,display:'ヤノケン'},ordinary={id:'tester',created:1};L.setPw(admin,'test-only-password');let docs={};L.readUser=async id=>id===admin.id?admin:id==='tester'?ordinary:null;L.findUser=async name=>name===admin.id?admin:null;L.configured=()=>true;F.read=async keys=>Object.fromEntries(keys.filter(k=>docs[k]).map(k=>[k,structuredClone(docs[k])]));F.commit=async(expected,writes)=>{if(Object.entries(expected).some(([k,v])=>(docs[k]?.version||0)!==v))return false;for(const[k,v]of Object.entries(writes))docs[k]={version:(docs[k]?.version||0)+1,data:structuredClone(v)};return true;};
const handler=require(root+'/api/map-editor'),auth=require(root+'/api/auth');
const mime={'.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp3':'audio/mpeg'};
const server=http.createServer(async(req,res)=>{res.status=c=>{res.statusCode=c;return res};res.json=v=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(v))};const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){let body='';for await(const b of req)body+=b;try{req.body=JSON.parse(body||'{}');}catch{req.body={};}if(url.pathname==='/api/map-editor')return handler(req,res);if(url.pathname==='/api/auth')return auth(req,res);return res.status(200).json({});}let file=path.join(root,decodeURIComponent(url.pathname));if(!file.startsWith(path.normalize(root)))return res.status(403).end();try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);}catch{res.status(404).end();}});
(async()=>{await new Promise(r=>server.listen(5183,'127.0.0.1',r));const {chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const p=await browser.newPage({viewport:{width:940,height:980}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5183/?v4test=village');await p.waitForFunction(()=>window.VM);const before=await p.evaluate(async()=>{const {makeMon}=await import('/src/state.js'),{showStatus}=await import('/src/menu.js'),{ui}=await import('/src/ui.js');VM.State.save=VM.newGame();window.testMon=makeMon('リーフィン',40);testMon.moves.forEach((m,i)=>m.pp=i+1);VM.State.save.party=[testMon];VM.world.enter('village',NaN,NaN,'down');VM.setWorld();ui.clear();window.statusClosed=false;showStatus(testMon).then(()=>statusClosed=true);return JSON.parse(JSON.stringify(testMon.moves));});const key=async k=>{await p.keyboard.down(k);await p.waitForTimeout(70);await p.keyboard.up(k);await p.waitForTimeout(130);};await p.waitForTimeout(600);await key('z');await key('ArrowDown');await key('z');let after=await p.evaluate(()=>testMon.moves);assert.deepEqual(after,[before[1],before[0],before[2],before[3]]);assert.equal(await p.evaluate(()=>statusClosed),false);assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('gaon-world:save:v3')).party[0].moves),after);
await key('z');await key('ArrowDown');await key('x');assert.equal(await p.evaluate(()=>statusClosed),false);assert.deepEqual(await p.evaluate(()=>testMon.moves),after);await key('x');await p.waitForFunction(()=>statusClosed);await p.evaluate(async()=>{const {loadLocal,applySave}=await import('/src/save.js');applySave(loadLocal());});assert.deepEqual(await p.evaluate(()=>VM.State.save.party[0].moves),after);
// The same status screen also edits boxed Gaon without moving them into the party.
await p.evaluate(async()=>{const {makeMon}=await import('/src/state.js'),{showStatus}=await import('/src/menu.js');const m=makeMon('リーフィン',40);VM.State.save.box=[m];window.boxBefore=JSON.parse(JSON.stringify(m.moves));window.statusClosed=false;showStatus(m).then(()=>statusClosed=true);});await key('z');await key('ArrowUp');await key('z');const box=await p.evaluate(()=>({before:boxBefore,after:VM.State.save.box[0].moves,saved:JSON.parse(localStorage.getItem('gaon-world:save:v3')).box[0].moves}));assert.deepEqual(box.after,[box.before[3],box.before[1],box.before[2],box.before[0]]);assert.deepEqual(box.saved,box.after);await key('x');
await p.evaluate(async()=>{const {showStatus}=await import('/src/menu.js');const m=VM.State.save.party[0];m.moves=m.moves.slice(0,1);window.statusClosed=false;showStatus(m).then(()=>statusClosed=true);});await key('z');await key('x');await p.waitForFunction(()=>statusClosed);
// Existing custom screens still close with A when no custom input handler exists.
await p.evaluate(async()=>{const{ui}=await import('/src/ui.js');window.customClosed=false;ui.custom(()=>{}).then(()=>customClosed=true);});await key('z');await p.waitForFunction(()=>customClosed);
await p.evaluate(async()=>{const{makeMon}=await import('/src/state.js'),{showStatus}=await import('/src/menu.js');const{MOVES}=await import('/src/data/moves.js');window.samples=Object.entries(MOVES);const m=makeMon('リーフィン',40);m.moves=['ひかり','くさ','ほのお','みず'].map(type=>{const[name,d]=samples.find(([,d])=>d.type===type);return {name,pp:1,max:d.pp}});VM.State.save.party=[m];showStatus(m);});await p.waitForTimeout(800);await p.screenshot({path:'work/admin72/screens/status-types77.png'});await key('x');await p.evaluate(async()=>{const{showStatus}=await import('/src/menu.js');const m=VM.State.save.party[0];m.moves=['でんき','じめん','むし','やみ'].map(type=>{const[name,d]=samples.find(([,d])=>d.type===type);return {name,pp:1,max:d.pp}});showStatus(m);});await p.waitForTimeout(800);await p.screenshot({path:'work/admin72/screens/status-types77b.png'});const imageOK=await p.evaluate(async()=>{for(const id of ['light','grass','fire','water','electric','ground','bug','dark']){const im=new Image();im.src='/assets/types-v77/'+id+'.png';await im.decode();}return true;});assert(imageOK);await key('x');await p.evaluate(async()=>{const{ui}=await import('/src/ui.js'),{makeMon}=await import('/src/state.js'),{startBattle}=await import('/src/battle.js');VM.State.save.party=JSON.parse(localStorage.getItem('gaon-world:save:v3')).party;window.battleExpected=VM.State.save.party[0].moves.map(m=>m.name);ui.clear();ui.say=async()=>true;ui.choice=async items=>{if(items[0]==='たたかう')return 0;window.battleMoveLabels=items;return new Promise(()=>{});};startBattle({wild:makeMon('リーフィン',2)});});await p.waitForFunction(()=>window.battleMoveLabels);assert.deepEqual(await p.evaluate(()=>battleMoveLabels),await p.evaluate(()=>battleExpected));assert.deepEqual(errors,[]);console.log('PASS move swap preserves name/PP/max; immediate save + reload; B cancels pending selection; boxed Gaon; one move; old custom screens; eight generated type icons; no browser errors');}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
