const{chromium}=require('C:/Users/voraz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),fs=require('fs');
(async()=>{const base=process.argv[2]||'http://127.0.0.1:5179',b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--autoplay-policy=no-user-gesture-required']});try{const p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{const Original=window.Audio;window.tracks=[];window.Audio=class extends Original{constructor(...a){super(...a);window.tracks.push(this);}}});await p.goto(base,{waitUntil:'networkidle'});const result=await p.evaluate(async()=>{
 const{world,bgmFor}=await import('/src/world.js?v=20260912-road-music-v32'),{G:S,newGame,makeMon}=await import('/src/state.js'),a=await import('/src/audio.js'),{ui}=await import('/src/ui.js'),{startBattle}=await import('/src/battle.js');const check=(x,m)=>{if(!x)throw Error(m)},sleep=ms=>new Promise(r=>setTimeout(r,ms));S.save=newGame('music');world.busy=true;a.initAudio();const results=[];
 async function inspect(key,file,duration){check(a.currentBgm()===key,'Wrong key '+a.currentBgm());const t=window.tracks.find(t=>t.src.includes(file));check(t,'Missing '+file);await t.play();await sleep(250);check(!t.paused&&t.currentTime>0&&t.loop,'Playback '+file);check(Math.abs(t.duration-duration)<1,'Duration '+file);check(window.tracks.filter(t=>!t.paused).length===1,'Overlapping music');const pos=t.currentTime;a.playBgm(key);check(t.currentTime>=pos,'Restart');a.setMuted(true);check(t.muted,'Mute');a.setMuted(false);check(!t.muted,'Unmute');results.push({key,duration:t.duration});}
 for(const [map,key,file,duration] of [['village','natureTown','morning-meadow',147.76],['marine','marineTown','marine-whispering',126.32],['karat','karatTown','karat-cozy',163.2]]){world.enter(map,13,12,'down');await inspect(key,file,duration);S.save.backTo={map,x:13,y:12};for(const room of ['hut','shop','hospital'])check(bgmFor(room)===key,'Interior '+room);world.enter('shop',7,8,'down');check(a.currentBgm()===key,'Enter shop');world.enter(map,13,12,'down');}
 check(bgmFor('shipDeck')==='town','Ship inherits town');
 for(let n=1;n<=8;n++){world.enter('route'+n,10,10,'down');await inspect('route','cozy-adventure',151.96);} a.playBgm('battle');world.resumeBgm();check(a.currentBgm()==='route','Road battle return');world.enter('karat',13,12,'down');
 const oldSay=ui.say;ui.say=async()=>{throw Error('TEST_STOP_INTRO')};S.save.party=[makeMon('ラテット',50)];
 for(const [trainer,key,file,duration] of [[null,'battle','heroic-charge',112.8],[{name:'test',party:[['カニポン',8]],leader:'test'},'boss','triumph-of-the-champion',173.2],[{name:'ヤノケン',party:[['コケゴロ',22]]},'yanokenBattle','yanoken-warriors',123.2]]){const done=startBattle(trainer?{trainer}:{wild:makeMon('カニポン',8)}).catch(e=>{if(e.message!=='TEST_STOP_INTRO')throw e});await inspect(key,file,duration);await done;world.resumeBgm();check(a.currentBgm()==='karatTown','Battle return');}
 for(const [opts,key,file,duration] of [[{wild:makeMon('カニポン',8),emblemTest:true},'boss','triumph-of-the-champion',173.2],[{trainer:{name:'所長 ジネル',major:true,party:[['カニポン',8]]}},'boss','triumph-of-the-champion',173.2],[{tournament:true,trainer:{name:'フィロア',champ:true,party:[['カニポン',8]]}},'tournament','the-final-stand',163.2]]){const done=startBattle(opts).catch(e=>{if(e.message!=='TEST_STOP_INTRO')throw e});await inspect(key,file,duration);await done;world.resumeBgm();} ui.say=oldSay;a.stopBgm();check(window.tracks.every(t=>t.paused),'Stop');return {results,interiors:true,mute:true,singleTrack:true,battleSelection:true};
 });if(errors.length)throw Error(errors.join('/'));fs.writeFileSync('artifacts/music-v31-'+(base.includes('127')?'local':'production')+'.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
