// Generated originals remain in assets/environment-v41; extraction only isolates atlas cells.
const sheets={},frames=new Map();
const names=['interiors','facilities','coast','shops','shop-sides'];
function sheet(name){if(!sheets[name]){const im=new Image();im.src=new URL('../assets/environment-v41/'+name+'.png',import.meta.url).href;sheets[name]=im;}return sheets[name];}
function frame(name,index){const key=name+index;if(frames.has(key))return frames.get(key);const im=sheet(name);if(!im.complete||!im.naturalWidth)return null;let rect=[(index%4)/4,Math.floor(index/4)/2,1/4,1/2];
 if(name==='coast'){const edges=index<4?[0,.269,.506,.742,1]:[0,.26,.515,.69,1],i=index%4;rect=[edges[i],Math.floor(index/4)/2,edges[i+1]-edges[i],.5];}
 if(name==='facilities'&&index>=4)rect=[[0,.5,.255,.5],[.27,.5,.18,.5],[.46,.5,.35,.5],[.82,.5,.18,.5]][index-4];
 const [sx,sy,w,h]=rect.map((v,i)=>Math.round(v*(i%2?im.height:im.width)));const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(im,sx,sy,w,h,0,0,w,h);const pixels=ctx.getImageData(0,0,w,h),d=pixels.data;
 // Some generated source atlases retain a neutral matte. Remove only border-connected
 // matte pixels, preserving enclosed highlights and the original source file.
 if(['coast','shops','shop-sides'].includes(name)){const seen=new Uint8Array(w*h),q=[];const push=(x,y)=>{if(x<0||y<0||x>=w||y>=h)return;const k=y*w+x;if(seen[k])return;seen[k]=1;const i=k*4,r=d[i],g=d[i+1],b=d[i+2],neutral=name!=='shop-sides'&&Math.max(r,g,b)-Math.min(r,g,b)<28&&Math.min(r,g,b)>95,magenta=r>175&&b>175&&g<100;if(d[i+3]<32||neutral||magenta){d[i+3]=0;q.push(k);}};for(let x=0;x<w;x++){push(x,0);push(x,h-1);}for(let y=0;y<h;y++){push(0,y);push(w-1,y);}for(let i=0;i<q.length;i++){const k=q[i],x=k%w,y=Math.floor(k/w);push(x-1,y);push(x+1,y);push(x,y-1);push(x,y+1);}ctx.putImageData(pixels,0,0);}
 let l=w,t=h,r=0,b=0;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(d[(y*w+x)*4+3]>32){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y);}const f={image:c,sx:l,sy:t,w:r-l+1,h:b-t+1};frames.set(key,f);return f;}
export function decor(c,name,index,x,y,w,h){const f=frame(name,index);if(!f)return false;const scale=Math.min(w/f.w,h/f.h),dw=f.w*scale,dh=f.h*scale;c.imageSmoothingEnabled=false;c.drawImage(f.image,f.sx,f.sy,f.w,f.h,Math.round(x+(w-dw)/2),Math.round(y+h-dh),Math.round(dw),Math.round(dh));return true;}
export const SHOP_STYLES={
 village:[0,'#c7d6ae','#8ca578','#f2e9cd','#44775e'],rods:[3,'#d5be94','#b59b74','#f1dfbd','#8b6651'],marine:[1,'#bddce0','#81aeba','#edf4e9','#275c77'],karat:[2,'#e9d5db','#c4a8bd','#fff1e5','#a95e80'],karatPort:[1,'#a9c6ce','#7399a9','#e8e9db','#28586b'],resurePort:[1,'#c2d5c7','#8cae9e','#f3ebd1','#3d7365'],resure:[3,'#d6c7a1','#b5a580','#f0e6c9','#687f53'],manikereo:[4,'#b8c2ce','#8593a7','#e0e6ea','#3b556d'],galaxy:[4,'#9ca8cb','#667397','#e4e8fa','#45467e'],clearTown:[5,'#d2e4eb','#a7c4d5','#f5f8f4','#507e9f'],belerio:[6,'#ded2a0','#bcac73','#faf0d1','#268b82'],leafTown:[7,'#b9d2bf','#84a992','#edeed9','#276b59']};
export function shopStyle(r){return SHOP_STYLES[r.shopTown]||SHOP_STYLES.village;}
export function furnitureArt(c,r,kind,x,y,w,h){let name='interiors',index;if(r.theme==='shop'&&r.shopTown){const style=shopStyle(r);if(kind==='shelf')return decor(c,'shops',style[0],x,y,w,h);if(kind==='shelfLeft'||kind==='shelfRight'){const group=style[0]===1?1:style[0]===2?2:style[0]>=4?3:0;return decor(c,'shop-sides',group*2+(kind==='shelfRight'?1:0),x,y,w,h);}if(kind==='counter')return decor(c,'facilities',4,x,y-16,w,h+16);}
 if(kind==='healer')index=1;else if(kind==='counter'&&r.theme==='hospital')return decor(c,name,0,x,y-18,w,h+18);else if(kind==='bed')index=r.theme==='hospital'?2:7;else if(kind==='sofa')index=3;else if(kind==='kitchen')index=4;else if(kind==='table')index=5;else if(kind==='books')index=6;else if(kind==='plant')return decor(c,'facilities',7,x,y-8,w,h+8);else return false;return decor(c,name,index,x,y,w,h);}
export function environmentReady(map){const required=[];if(map.room){required.push('interiors','facilities');if(map.room.shopTown)required.push('shops','shop-sides');}if(map.shipRoom||map.biome==='arena'||map.environmentArena)required.push('facilities');if(map.coastDesign||map.townGardens?.length)required.push('coast');return required.every(n=>{const im=sheet(n);return im.complete&&im.naturalWidth>0;});}
export function environmentProp(c,p,map){const x=p.x*32,y=p.y*32,w=p.w*32,h=p.h*32;if(p.art==='v41-fence'){c.fillStyle='#536c60';c.fillRect(x,y+19,w,4);c.fillStyle='#e0e3cf';c.fillRect(x,y+13,w,3);for(let i=0;i<w;i+=12){c.fillStyle='#667f70';c.fillRect(x+i+1,y+8,6,20);c.fillStyle='#e4e7d6';c.fillRect(x+i,y+6,5,20);}return true;}if(p.art.startsWith('v41-')){const [,name,index]=p.art.split('-');return decor(c,name,Number(index),x,y,w,h);}if(p.art==='shipSeats')return decor(c,'facilities',map.id==='shipCabins'?2:0,x,y,w,h);if(p.art==='shipHelm')return decor(c,'facilities',1,x,y,w,h);if(p.art==='shoreRock'&&map.coastDesign)return decor(c,'coast',0,x,y,w,h);return false;}
export function paintEnvironment(c,map,material){const w=map.rows[0].length*32,h=map.rows.length*32;if(map.environmentArena){const champion=map.id==='championTower';c.fillStyle='#182c38';c.fillRect(0,0,w,h);c.fillStyle=champion?'#d7e2d1':'#c4cbe0';c.fillRect(32,32,w-64,h-64);for(let y=32;y<h-32;y+=32)for(let x=32;x<w-32;x+=32){c.strokeStyle=champion?'#bccdbb':'#a9b3ce';c.strokeRect(x+.5,y+.5,31,31);}c.fillStyle=champion?'#316950':'#373b72';c.fillRect(10*32,7*32,6*32,h-8*32);c.strokeStyle='#d6bf79';c.lineWidth=3;c.strokeRect(10*32+5,7*32+5,6*32-10,h-8*32-10);c.fillStyle=champion?'#759a79':'#7e83b6';c.fillRect(6*32,12*32,14*32,7*32);c.strokeStyle='#f2e5b9';c.strokeRect(6*32+5,12*32+5,14*32-10,7*32-10);c.beginPath();c.ellipse(13*32,15.5*32,52,52,0,0,Math.PI*2);c.stroke();c.beginPath();c.moveTo(6*32+5,15.5*32);c.lineTo(20*32-5,15.5*32);c.stroke();}
 if(map.shipRoom&&!map.openDeck&&map.biome==='ship'){for(let x=4;x<map.rows[0].length-3;x+=5){c.fillStyle='#c9a960';c.beginPath();c.arc(x*32,49,12,0,Math.PI*2);c.fill();c.fillStyle='#75baca';c.beginPath();c.arc(x*32,49,8,0,Math.PI*2);c.fill();c.fillStyle='#dcf5ed';c.fillRect(x*32-4,44,6,2);}for(const p of map.props.filter(p=>p.art==='shipSeats')){c.fillStyle='#304c62';c.fillRect(p.x*32-8,p.y*32-5,p.w*32+16,p.h*32+12);c.strokeStyle='#bda370';c.strokeRect(p.x*32-6,p.y*32-3,p.w*32+12,p.h*32+8);}}
 for(const plot of map.townGardens||[]){const{x,y,w:gw,h:gh}=plot;c.fillStyle=map.frontierTheme==='snow'?'#c5d7d7':'#609b76';c.fillRect(x*32+2,y*32+2,gw*32-4,gh*32-4);c.strokeStyle=map.frontierTheme==='snow'?'#edf4ed':'#adc595';c.lineWidth=2;c.strokeRect(x*32+3,y*32+3,gw*32-6,gh*32-6);for(let yy=y;yy<y+gh;yy++)for(let xx=x;xx<x+gw;xx++)material?.(c,'flowers',xx*32+3,yy*32+3,26,26);}}
export function coastTile(c,map,x,y,ch){if(!map.coastDesign)return;const dx=x*32,dy=y*32;if(ch==='W'){for(const [a,b]of [[-1,0],[1,0],[0,-1],[0,1]]){const n=map.rows[y+b]?.[x+a];if(n&&!['W','d','X'].includes(n)){c.fillStyle='#79d3d0';c.fillRect(dx+(a===1?25:0),dy+(b===1?25:0),a?7:32,b?7:32);c.fillStyle='#d8f3e6';c.fillRect(dx+(a===1?29:0),dy+(b===1?29:0),a?3:32,b?3:32);}}}else if([',','.'].includes(ch)&&[[-1,0],[1,0],[0,-1],[0,1]].some(([a,b])=>map.rows[y+b]?.[x+a]==='W')){c.fillStyle='#e7d4a6';c.fillRect(dx,dy,32,32);c.fillStyle='#c9b785';for(let i=0;i<6;i++)c.fillRect(dx+(x*7+y*3+i*11)%29,dy+(x*13+y*7+i*5)%29,2,1);}}
