import {G as State} from './state.js';
import {item,ITEMS} from './data/items.js';
import {ui} from './ui.js';
import {saveLocal} from './save.js';
import {jstDay} from './frontierRules.js';
export const ORES79={'こいし':80,'てっこうせき':240,'どうこうせき':360,'きんこうせき':1200,'ひかりのけっしょう':2400};
export function economy79(save){return save.economy79??={mining:{},shops:{}};}
const plotCache79=new WeakMap();
const open=(m,x,y)=>['.',',','F'].includes(m.rows[y]?.[x]);
export function plot79(map){if(plotCache79.has(map))return plotCache79.get(map);if(map.kind!=='out'||!(map.townDesign||['village','rods','karat','resure','natureTown'].includes(map.id)))return null;const seen=new Set(),queue=[map.spawn||{x:1,y:1}];for(let i=0;i<queue.length;i++){const p=queue[i],k=p.x+','+p.y;if(seen.has(k)||!map.rows[p.y]?.[p.x]||'TRMW#rwSX=cbtKVPLs'.includes(map.rows[p.y][p.x]))continue;seen.add(k);for(const[dx,dy]of [[0,1],[0,-1],[1,0],[-1,0]])if(!seen.has((p.x+dx)+','+(p.y+dy)))queue.push({x:p.x+dx,y:p.y+dy});}const points=[];for(let y=3;y<map.rows.length-4;y++)for(let x=3;x<map.rows[0].length-4;x++){if(!seen.has((x+1)+','+(y+2)))continue;if(![0,1,2].every(dy=>[0,1,2].every(dx=>open(map,x+dx,y+dy))))continue;if([...map.props||[],...map.editorAddedProps72||[]].some(p=>x<p.x+p.w&&x+3>p.x&&y<p.y+p.h&&y+3>p.y))continue;if([...map.npcs||[],...map.warps||[],...map.signs||[],...map.items||[]].some(p=>p.x>=x-1&&p.x<=x+3&&p.y>=y-1&&p.y<=y+3))continue;points.push({x,y});}const result=points.sort((a,b)=>Math.abs(a.x-(map.spawn?.x||10))+Math.abs(a.y-(map.spawn?.y||10))-Math.abs(b.x-(map.spawn?.x||10))-Math.abs(b.y-(map.spawn?.y||10)))[0]||null;plotCache79.set(map,result);return result;}
export function mine79(save,mapId,key,now=new Date(),roll=Math.random()){const e=economy79(save),day=jstDay(now);if(e.miningDay!==day){e.miningDay=day;e.mining={};}if(!(save.bag['つるはし']>0))return {error:'ショップで つるはしを買おう。'};const id=mapId+':'+key,n=e.mining[id]||0;if(n>=5)return {error:'この岩は 今日は掘りつくした。\nまた明日 採掘しよう。'};const name=roll<.45?'こいし':roll<.75?'てっこうせき':roll<.9?'どうこうせき':roll<.98?'きんこうせき':'ひかりのけっしょう';e.mining[id]=n+1;save.bag[name]=(save.bag[name]||0)+1;return {name,left:4-n};}
export function settle79(shop,now=Date.now()){if(!shop?.built)return;shop.stock??=[];shop.proceeds??=0;shop.lastSale??=now;let turns=Math.max(0,Math.floor((now-shop.lastSale)/300000));if(!turns)return;shop.lastSale+=turns*300000;for(const line of shop.stock){const n=Math.min(turns,line.quantity);shop.proceeds+=n*line.price;line.quantity-=n;turns-=n;if(!turns)break;}shop.stock=shop.stock.filter(l=>l.quantity>0);}
export function buyLand79(save,map){const e=economy79(save);if(e.shops[map.id])return 'この町の土地は 購入済みです。';const p=plot79(map);if(!p)return 'この町には 空き地がありません。';if(save.money<3000)return 'お金が たりません。';save.money-=3000;e.shops[map.id]={...p,built:false,stock:[],proceeds:0,lastSale:Date.now()};return null;}
export function buildShop79(save,id){const shop=economy79(save).shops[id];if(!shop||shop.built)return '建てられる土地を 選んでください。';if(save.money<2000)return 'お金が たりません。';save.money-=2000;shop.built=true;shop.lastSale=Date.now();return null;}
export function stock79(save,id,name,n,now=Date.now()){const shop=economy79(save).shops[id],data=item(name);if(!shop?.built||!Number.isInteger(n)||n<1||!(data.price>0)||data.kind==='key'||(save.bag[name]||0)<n)return false;settle79(shop,now);if(!shop.stock.length)shop.lastSale=now;save.bag[name]-=n;if(!save.bag[name])delete save.bag[name];const line=shop.stock.find(l=>l.name===name);if(line)line.quantity+=n;else shop.stock.push({name,quantity:n,price:Math.floor(data.price*.75)});return true;}
export function collect79(save,id,now=Date.now()){const shop=economy79(save).shops[id];settle79(shop,now);const money=shop?.proceeds||0;if(shop)shop.proceeds=0;save.money+=money;return money;}
export function economyMap79(base,save){const shop=economy79(save).shops[base.id],lot=shop||plot79(base);if(!lot)return base;const map={...base,props:[...base.props],warps:[...base.warps],signs:[...base.signs],lot79:{x:lot.x+1,y:lot.y+2,owned:!!shop}};if(shop?.built){const grid=base.rows.map(r=>[...r]);for(let y=lot.y;y<lot.y+2;y++)for(let x=lot.x;x<lot.x+3;x++)grid[y][x]='#';grid[lot.y+1][lot.x+1]='D';map.rows=grid.map(r=>r.join(''));map.editorVisualRows73=undefined;map.props.push({art:'harborShop',x:lot.x,y:lot.y,w:3,h:2,door:{x:lot.x+1,y:lot.y+1}});map.warps.push({x:lot.x+1,y:lot.y+1,to:'playerShop79',tx:7,ty:10,back:{map:base.id,x:lot.x+1,y:lot.y+2}});}else map.signs.push({x:lot.x+1,y:lot.y+2,text:[shop?'あなたの土地':'売り土地 3000円','ショップの「土地・お店」で手続きできます。']});return map;}
export function drawLot79(c,map,cx,cy){if(!map.lot79)return;const p=map.lot79,x=p.x*32-cx,y=p.y*32-cy;c.save();c.fillStyle='#805935';c.fillRect(x+14,y+11,4,20);c.fillStyle=p.owned?'#e9ca7c':'#fff1b5';c.fillRect(x+2,y+1,28,18);c.fillStyle='#4e5037';c.font='8px sans-serif';c.textAlign='center';c.fillText(p.owned?'MY SHOP':'売土地',x+16,y+13);c.restore();}
export function miningTarget79(map,x,y){const p=[...map.props||[],...map.editorAddedProps72||[]].find(p=>/rock|crag/i.test(p.art)&&x>=p.x&&x<p.x+p.w&&y>=p.y&&y<p.y+p.h);return p?{key:p.x+','+p.y}:map.rows[y]?.[x]==='R'?{key:x+','+y}:null;}
export async function miningMenu79(w,t){if(!State.save.bag['つるはし']){await ui.say(['この岩は 採掘できそうだ。','ショップで つるはしを手に入れよう。']);return;}if(!await ui.ask(['つるはしで 採掘しますか？']))return;const r=mine79(State.save,w.mapId,t.key);saveLocal();await ui.say(r.error?r.error.split('\n'):[r.name+'を 掘り出した！','ショップで売るか 自分のお店に並べよう。','今日の残り '+r.left+'回']);}
export async function businessMenu79(w,maps){for(;;){const towns=Object.values(maps).filter(m=>plot79(m)||economy79(State.save).shops[m.id]);const i=await ui.choice(towns.map(m=>m.name+(economy79(State.save).shops[m.id]?'（所有）':'')).concat('もどる'),{rows:6});if(i<0||i===towns.length)return;const map=towns[i],shop=economy79(State.save).shops[map.id];if(!shop){if(await ui.ask([map.name+'の 土地は3000円です。','所持金 '+State.save.money+'円','購入しますか？'])){const error=buyLand79(State.save,map);saveLocal();await ui.say([error||'土地を 購入しました！']);}}else if(!shop.built){if(await ui.ask(['建築費2000円で お店を建てますか？','所持金 '+State.save.money+'円'])){const error=buildShop79(State.save,map.id);saveLocal();await ui.say([error||'あなたのお店が 完成しました！']);}}else await ownShop79(map.id);if(w&&w.mapId===map.id)w.enter(w.mapId,w.x,w.y,w.dir);}}
export async function ownShop79(id){for(;;){const s=State.save,shop=economy79(s).shops[id];if(!shop?.built)return;settle79(shop);saveLocal();const i=await ui.choice(['商品を並べる','売上を受け取る '+shop.proceeds+'円','商品を引き上げる','お店の説明','もどる'],{rows:5});if(i<0||i===4)return;if(i===0){const names=Object.keys(s.bag).filter(n=>s.bag[n]>0&&item(n).price>0&&item(n).kind!=='key');if(!names.length){await ui.say(['並べられる商品がありません。']);continue;}const n=await ui.choice(names.map(n=>n+' ×'+s.bag[n]).concat('もどる'),{rows:6});if(n<0||n===names.length)continue;const name=names[n],q=await ui.choice(['1個','全部 '+s.bag[name]+'個','もどる']);if(q<0||q===2)continue;const count=q===0?1:s.bag[name];if(await ui.ask([name+' ×'+count,'1個 '+Math.floor(item(name).price*.75)+'円で 並べますか？'])){stock79(s,id,name,count);saveLocal();await ui.say(['商品を お店に並べた！']);}}if(i===1){const n=collect79(s,id);saveLocal();await ui.say(['売上 '+n+'円を 受け取りました。']);}if(i===2){const n=await ui.choice(shop.stock.map(l=>l.name+' ×'+l.quantity).concat('もどる'),{rows:6});if(n>=0&&n<shop.stock.length){const [l]=shop.stock.splice(n,1);s.bag[l.name]=(s.bag[l.name]||0)+l.quantity;saveLocal();await ui.say(['商品を バッグに戻した。']);}}if(i===3)await ui.say(['町のお客さんが 5分に1個 購入します。','ゲームを閉じている間も 売れます。','売値はショップの買取額の1.5倍です。','商品がなくなると 販売は止まります。']);}}
