import {GROUND88} from './groundCatalog88.mjs';
import {PONDS87,POND_TILES87,pondObject87,upgradePond87} from './pondCatalog87.mjs';
import {FLOORS86} from './sceneCatalog86.mjs';
import {validEncounters86} from './encounters86.mjs';
import {FURNITURE84,sizeTemplate84} from './readableCatalog84.mjs';
import {buildingTemplate83} from './buildingRooms83.mjs';
import {treeKind83,isTree83} from './treeFootprint83.mjs';
import {GOODS82} from './shopCatalog82.mjs';
import {REFERENCE78} from './referenceCatalog78.mjs';
import {validAnchor78} from './linkAnchors78.mjs';
import {canTraverse75} from './elevation75.mjs';
import {GROUND75,DECOR75} from './extraCatalog75.mjs';
import {PATHS75,OBJECTS75} from './gardenCatalog75.mjs';
import {NATURE73} from './natureCatalog73.mjs';
import {LEGACY73} from './legacyCatalog73.mjs';
import {GARDEN72} from './gardenCatalog72.mjs';
// Pure shared editor model. No client-supplied scripts, URLs, battle data or arbitrary map JSON.
export const FLOORS=[...GROUND88.map(p=>[p.key,p.label,p.tile]),...POND_TILES87.map(p=>[p.key,p.label,'W']),...FLOORS86,...GROUND75.map(p=>[p.key,p.label,p.tile]),...PATHS75.map(p=>[p.key,p.label,p.tile]),['grass','草地',','],['path','土の道','.'],['cobble','石畳','.'],['redCobble','赤い石畳','.'],['snow','雪',','],['river','川','W'],['tallGrass','草むら','"'],['wood','木の床','f'],['tile','タイルの床','f'],['wall','壁','X'],...NATURE73.filter(p=>p.group==='floor').map(p=>[p.key,p.label,p.tile]),...LEGACY73.filter(p=>p.group==='floor').map(p=>[p.key,p.label,p.tile])];
export const clone=v=>JSON.parse(JSON.stringify(v));
const solid=new Set(['T','R','M','W','#','r','w','S','X','=','c','b','t','K','V','P','s','L']);
export const pass=(m,x,y)=>m.rows[y]?.[x]!==undefined&&!solid.has(m.rows[y][x]);
export function fingerprint(map){let n=2166136261;for(const ch of JSON.stringify(map)){n^=ch.charCodeAt(0);n=Math.imul(n,16777619);}return (n>>>0).toString(16);}
export function catalog(maps,species){
 const props=[...PONDS87],seen=new Set(PONDS87.map(p=>p.key));for(const [mapId,m]of Object.entries(maps))for(const p of m.props||[]){if(seen.has(p.art))continue;seen.add(p.art);props.push({key:p.art,label:p.label||p.art,art:p.art,w:p.w,h:p.h,source:mapId});}
 for(const [art,label,w,h]of [['tree','広葉樹',2,2],['fir','針葉樹',2,2],['flowers','花',1,1],['rock','岩',1,1],['smallRock','小石',1,1],['bush','低木',1,1],['lamp','街灯',1,2],['fenceHorizontal','横の柵',1,1],['fenceVertical','縦の柵',1,1]]){const p=props.find(p=>p.art===art);if(p)p.label=label;else props.push({key:art,art,label,w,h,source:'village'});}
 props.push({key:'house',label:'家（室内つき）',art:'chalet',w:5,h:5,building:'house',source:'village'},{key:'shop',label:'ショップ（室内つき）',art:'harborShop',w:5,h:5,building:'shop',source:'rods'},{key:'hospital',label:'ガオン病院',art:'chaletClinic',w:5,h:5,building:'hospital',source:'rods'});
 for(const p of props.filter(p=>p.building)){const original=Object.values(maps).flatMap(m=>m.props||[]).find(o=>o.art===p.art&&o.w===p.w&&o.h===p.h&&o.door);p.doorOffset=original?[original.door.x-original.x,original.door.y-original.y]:[2,4];}
 props.push(...['rural','road','mountain'].map((n,i)=>({key:'active83-'+n,art:'active83-'+n,label:['町の草むら（使用中）','道路の草むら（使用中）','山の草むら（使用中）'][i],w:1,h:1,group:'grass',walkable:true,tile:'"',source:'village'})),{key:'resource83-blue-tree',art:'resource83-blue-tree',label:'青い素材木（広葉樹）',w:2,h:3,source:'village'},{key:'resource83-blue-rock',art:'resource83-blue-rock',label:'青い採掘岩（使用中）',w:1,h:1,source:'mountain'});
 props.push({key:'sign82',label:'木製の看板（使用中・文章編集）',art:'sign',w:1,h:1,source:'village'});
 props.push({key:'wall79',label:'外周の壁',art:'wall79',w:1,h:1,tile:'X'});
 props.push({key:'fashionShop74',label:'服屋（ピンク・室内つき）',art:'fashionShop74',w:4,h:4,building:'fashion-village',doorOffset:[1,3],source:'village'});
 const furniture=[],fseen=new Set();for(const m of Object.values(maps))for(const [kind,x,y,w,h]of m.room?.furniture||[]){if(fseen.has(kind))continue;fseen.add(kind);furniture.push({key:kind,label:({chair:'椅子',table:'テーブル',bed:'ベッド',sofa:'ソファ',books:'本棚',plant:'観葉植物',counter:'カウンター',shelf:'商品棚',shelfLeft:'商品棚（左）',shelfRight:'商品棚（右）',tv:'テレビ',computer:'パソコン',kitchen:'キッチン',ward:'ガオンの病室'})[kind]||kind,w,h});}
 const labels={mountainCrag:'山の岩壁',alpineCheese65:'チーズ工房',shoreRock:'海岸の岩',marineHouse:'港の家',marineShop:'港の店',marineHall:'港のホール',alpineGazebo65:'東屋',ancientTree:'森の大木',flowersPink:'ピンクの花',flowersGold:'黄色い花',flowerTree:'花の木',flowerHouse:'花の家',ancientAltar:'古代の祭壇',solarPanels:'太陽光パネル',powerStation:'発電施設',controlBank:'制御盤',transformers:'変圧器',pipePump:'ポンプ',turbine:'タービン',generator:'発電機',ferry:'船',parkGate:'公園の門',ranchBarn:'牧場の納屋',daycareHouse:'育て屋',shipSeats:'船の座席',shipHelm:'操舵席',nurseryPen:'ガオンの囲い',station:'駅',train:'列車',shopCounter:'売店カウンター',eTower:'塔',snowFir:'雪の針葉樹',snowHouse:'雪国の家',snowHall:'雪国のホール',holidayTree:'飾りの木',snowLamp:'雪国の街灯',ashTree:'灰の木',lavaRock:'溶岩の岩',eFir:'深緑の針葉樹',eTree:'大樹',eIce:'氷の岩',eShip:'大型船',ePalm:'ヤシの木',eHouse:'石造りの家',eDarkTree:'闇の木',eMansion:'屋敷',eLamp:'飾り街灯',eWaterfall:'滝','v41-fence':'木の柵','v41-facilities-7':'屋外施設','v41-facilities-3':'受付施設','v41-facilities-6':'公共施設','v41-facilities-5':'広場の施設','v41-facilities-4':'売店','v41-interiors-6':'室内の飾り','v41-coast-2':'海辺の草木','v41-coast-3':'海辺の飾り','v41-coast-4':'海辺の小物','v41-coast-5':'海辺の岩'};for(const p of props)p.label=({harborShop:'ショップ（青い屋根）',chaletClinic:'ガオン病院（最新画像）',fashionShop74:'服屋（ピンクの屋根）'})[p.key]||labels[p.key]||p.label;for(const f of furniture)f.label=({machine:'装置',labtable:'研究テーブル',tank:'水槽',healer:'治療台'})[f.key]||f.label;
 for(const p of [...LEGACY73.filter(p=>p.group!=='floor')])if(!props.some(q=>q.key===p.key))props.push({...p,label:labels[p.original]||p.label});
 for(const f of furniture)if(f.key.startsWith('reference78-'))f.label=({'reference78-throne':'王座','reference78-column':'石の柱','reference78-banner':'城の旗','reference78-armor':'よろいの置物'})[f.key]||f.label;
 const styles=new Set();for(const [id,m]of Object.entries(maps))for(const f of m.room?.furniture||[]){const signature=JSON.stringify([m.room.theme,m.room.shopTown||'',f[0],f[3],f[4]]);if(styles.has(signature))continue;styles.add(signature);furniture.push({key:'furniture73-'+id+'-'+f[0],kind:f[0],label:m.name+'・'+(furniture.find(p=>p.key===f[0])?.label||f[0]),w:f[3],h:f[4],room:{theme:m.room.theme,shopTown:m.room.shopTown}});}
 for(const p of props)if(p.art==='parkGate'||p.art==='legacy73-parkGate'){p.walkable=true;p.mask=['#..#','#..#','#..#'];}
 return {maps,props:[...new Map([...props,...GARDEN72,...OBJECTS75,...DECOR75,...REFERENCE78,{key:'ship-stairs86',art:'ship-stairs86',label:'船内の階段',w:2,h:2,walkable:true,tile:'H'},...NATURE73.filter(p=>p.group!=='floor')].map(p=>[p.key,p])).values()].map(sizeTemplate84).map(p=>/^(legacy73-)?stairs$/.test(p.art)?{...p,walkable:true,tile:'H'}:p).map(buildingTemplate83).map(p=>treeKind83(p)?{...p,w:2,h:3,walkable:false,tile:'T',label:p.key==='legacy73-world-v19-tree'?'外周の森の木（使用中）':p.label}:p),furniture:[...new Map([...furniture,...FURNITURE84].map(p=>[p.key,p])).values()],people:Array.from({length:34},(_,variant)=>({key:String(variant),variant,label:'住人 '+(variant+1)})),species};
}
const groundCache79=new WeakMap(),groundIndex79=new WeakMap();
export function groundObjects79(map){if(groundCache79.has(map))return groundCache79.get(map);const out=[];if(map.kind!=='in'&&!map.powerArt)map.rows.forEach((r,y)=>[...r].forEach((ch,x)=>{if(('FTRX=S'.includes(ch)||(map.townGardens||[]).some(p=>x>=p.x&&x<p.x+p.w&&y>=p.y&&y<p.y+p.h))&&!map.props.some(p=>x>=p.x&&x<p.x+p.w&&y>=p.y&&y<p.y+p.h))out.push({id:'g:'+(y*r.length+x),type:'prop',template:({F:'flowers',T:'tree',R:'rock',X:'wall79','=':'fenceHorizontal',S:'sign'})[ch]||'flowers',x,y});}));const pond=pondObject87(map);if(pond)out.push(pond);groundCache79.set(map,out);groundIndex79.set(map,new Map(out.map(o=>[o.id,o])));return out;}
export function upgrade79(base,d){d=upgradePond87(base,d);if(!d.signs82)d={...d,signs82:true,objects:[...d.objects,...groundObjects79(base).filter(o=>o.template==='sign'&&!d.objects.some(a=>a.id===o.id))]};if(d.materials79)return d;return {...d,materials79:true,objects:[...d.objects,...groundObjects79(base).filter(o=>!d.tiles.some(t=>t.x===o.x&&t.y===o.y))]};}
export function initial(map){return {schema:1,ponds87:true,materials79:true,signs82:true,base:fingerprint(map),links:[],elevations:[],climbs:[],tiles:[],objects:[...groundObjects79(map),...(map.props||[]).map((p,i)=>({id:'p:'+i,type:'prop',template:p.art,x:p.x,y:p.y})),...(map.room?.furniture||[]).map((f,i)=>({id:'f:'+i,type:'furniture',template:f[0],x:f[1],y:f[2]}))],actors:(map.npcs||[]).map((n,i)=>({id:'n:'+i,x:n.x,y:n.y,dir:n.dir||'down',mode:n.followOwner!==undefined?'follow':n.noRoam?'still':'roam',owner:n.followOwner!==undefined?'n:'+n.followOwner:null})),rug:map.room?.rug?clone(map.room.rug):null};}
function rawObjectSource81(base,o,cat){if(o.id.startsWith('g:')){groundObjects79(base);const p=groundIndex79.get(base).get(o.id);if(p?.pond87)return {...p,art:p.template,tile:'W'};return p?{...p,art:p.template,w:1,h:1,tile:p.template==='flowers'?'F':base.rows[p.y][p.x],walkable:p.template==='flowers'}:null;}if(o.id.startsWith('p:')){const p=base.props[Number(o.id.slice(2))];if(p?.art==='parkGate'){const door=base.warps.find(w=>w.x>=p.x&&w.x<p.x+p.w&&w.y===p.y+p.h);return {...p,walkable:true,mask:['#..#','#..#','#..#'],...(door?{door:{x:door.x,y:door.y}}:{})};}return p;}if(o.id.startsWith('f:')){const f=base.room?.furniture[Number(o.id.slice(2))];return f?{wallMount86:f[0].startsWith('wall-'),art:f[0],x:f[1],y:f[2],w:f[3],h:f[4]}:null;}const p=cat[o.type==='prop'?'props':'furniture'].find(p=>p.key===o.template);return p?{...p,art:p.art||p.key}:null;}
function originalActor82(base,a,cat){if(a.id.startsWith('n:')){const original=base.npcs[Number(a.id.slice(2))];return typeof a.name==='string'&&a.name.trim()?{...original,displayName:a.name.trim()}:original;}return a.type==='pet'?{name:a.species,displayName:a.name||a.species,artMon:a.species,residentPet:true,roamMon:true,talk:[a.talk||'ごきげんに 過ごしている。']}:{look:'boy',variant:Number(a.template),name:a.name||'住人',displayName:a.name||'住人',talk:[a.talk||'こんにちは！']};}
export function applyEdit(base,doc,cat){doc=upgrade79(base,doc);doc={...doc,objects:doc.objects.filter(o=>!o.stored79)};const map=clone(base),original=initial(base),oldIndex=new Map(original.objects.map(o=>[o.id,o])),newIndex=new Map(doc.objects.map(o=>[o.id,o])),grid=map.rows.map(r=>[...r]);map.editor72=true;if(doc.encounters86!==undefined){map.enc=clone(doc.encounters86);map.encountersConfigured86=true;}if(doc.shopItems82!==undefined)map.shopItems82=clone(doc.shopItems82);map.townGardens=[];map.editorObjects78=doc.objects.filter(o=>o.type==='prop').map(o=>({...clone(objectSource(base,o,cat)),id:o.id,x:o.x,y:o.y}));map.editorLinks75=clone(doc.links||[]);map.elevations75=clone(doc.elevations||[]);map.climbs75=clone(doc.climbs||[]);map.elevationIndex75=Object.fromEntries(map.elevations75.map(t=>[t.x+','+t.y,t.level]));map.editorGround72=clone(doc.tiles);const set=(x,y,ch)=>{if(grid[y]?.[x]!==undefined)grid[y][x]=ch;};const fill=(p,ch)=>{for(let y=Math.floor(p.y);y<p.y+p.h;y++)for(let x=Math.floor(p.x);x<p.x+p.w;x++)set(x,y,ch);};map.warps=map.warps.map((w,i)=>({...w,editorWarpIndex79:i}));const fallback=map.kind==='in'?'f':map.kind==='cave'?'.':',';
 // Clear old footprints before placing anything, including swaps.
 for(const old of original.objects){const now=newIndex.get(old.id);if(now&&now.x===old.x&&now.y===old.y&&!now.turn81)continue;const src=objectSource(base,old,cat);if(!src.wallMount86)fill(src,fallback);if(!now&&src.door){map.warps=map.warps.filter(w=>w.x!==src.door.x||w.y!==src.door.y);set(src.door.x,src.door.y,fallback);}}
 for(const t of doc.tiles)set(t.x,t.y,FLOORS.find(f=>f[0]===t.material)[2]);
 const signSources82=original.objects.map(o=>objectSource(base,o,cat)).filter(isSign82);map.signs=map.signs.filter(s=>!signSources82.some(p=>s.x>=p.x&&s.x<p.x+p.w&&s.y>=p.y&&s.y<p.y+p.h));
 for(const o of doc.objects){const p=objectSource(base,o,cat);if(!isSign82(p))continue;const text=(o.signText82??signText82(base,p)).trim()||'まだ 何も 書かれていない。';for(let yy=0;yy<p.h;yy++)for(let xx=0;xx<p.w;xx++)map.signs.push({x:o.x+xx,y:o.y+yy,text:text.split('\n'),editorSign82:o.id});}
 map.props=[];if(map.room)map.room.furniture=[];map.editorAddedProps72=[];map.editorAddedFurniture72=[];map.editorStyledFurniture73=[];
 for(const o of doc.objects){const src=objectSource(base,o,cat),p={...clone(src),x:o.x,y:o.y},old=oldIndex.get(o.id),changed=!old||old.x!==o.x||old.y!==o.y||!!o.turn81;
 if(o.id.startsWith('g:')){if(src.pond87){fill(p,'W');map.editorAddedProps72.push(p);continue;}if(o.turn81){fill(p,src.walkable?fallback:'#');map.editorAddedProps72.push(p);}else set(o.x,o.y,src.tile);continue;}
 if(o.type==='furniture'&&src.room){map.editorStyledFurniture73.push({room:src.room,f:[src.kind,o.x,o.y,p.w,p.h,o.turn81||0,src.originalW81||p.w,src.originalH81||p.h]});if(changed&&!src.wallMount86)fill(p,'t');continue;}
 if(o.type==='furniture'){(map.room?map.room.furniture:map.editorAddedFurniture72).push([o.template,o.x,o.y,p.w,p.h,o.turn81||0,src.originalW81||p.w,src.originalH81||p.h]);if(changed&&!src.wallMount86)fill(p,'t');continue;}
 if(isTree83(p))fill(p,'T');
 if(changed&&src.mask){for(let yy=0;yy<src.h;yy++)for(let xx=0;xx<src.w;xx++)set(p.x+xx,p.y+yy,src.mask[yy]?.[xx]==='#'?'#':fallback);}else if(changed&&src.walkable){p.editorUnder73=[];for(let y=p.y;y<p.y+p.h;y++)for(let x=p.x;x<p.x+p.w;x++){const ch=grid[y]?.[x];p.editorUnder73.push({x,y,ch:['.',',','f'].includes(ch)?ch:fallback});}if(src.group==='grass'||src.tile==='\"')fill(p,'\"');else for(const t of p.editorUnder73)set(t.x,t.y,t.ch);}else if(changed)fill(p,src.tile||'#');
 if(src.door){const origin=src.originalDoor81||src.door,dx=o.x-src.x,dy=o.y-src.y;p.door={...src.door,x:src.door.x+dx,y:src.door.y+dy};map.warps=map.warps.map(w=>w.x===origin.x&&w.y===origin.y?{...w,x:p.door.x,y:p.door.y,back:w.back?{...w.back,x:p.door.x+[0,-1,0,1][o.turn81||0],y:p.door.y+[1,0,-1,0][o.turn81||0],editorDoorId72:o.id}:w.back}:w);set(p.door.x,p.door.y,'D');}
 if(!old){p.editorSource72=src.source;map.editorAddedProps72.push(p);if(src.building){p.door={x:o.x+src.doorOffset[0],y:o.y+src.doorOffset[1]};set(p.door.x,p.door.y,'D');map.warps.push({x:p.door.x,y:p.door.y,to:src.building==='house'?'adminHouse72':src.building,tx:src.arrival?.[0]??7,ty:src.arrival?.[1]??10,back:{map:map.id,x:p.door.x+[0,-1,0,1][o.turn81||0],y:p.door.y+[1,0,-1,0][o.turn81||0],editorDoorId72:o.id}});}}
 else {p.editorObjectId72=o.id;map.props.push(p);}
 }
 map.npcs=doc.actors.map(a=>{const n=clone(actorSource(base,a,cat));if(a.id.startsWith('n:')&&(n.x!==a.x||n.y!==a.y))n.editorPosition72=true;if(n.roamBounds&&n.editorPosition72)n.roamBounds=n.roamBounds.map((v,i)=>v+(i%2?a.y-n.y:a.x-n.x));n.x=a.x;n.y=a.y;n.dir=a.dir;n.noRoam=a.mode==='still';if(n.artMon)n.roamMon=a.mode!=='still';delete n.followOwner;if(a.mode==='follow')n.followOwner=doc.actors.findIndex(p=>p.id===a.owner);if(a.id.startsWith('a:'))n.editorAdded72=true;return n;});
 if(map.room&&doc.rug)map.room.rug=clone(doc.rug);map.rows=grid.map(r=>r.join(''));const visual=grid.map(r=>[...r]);for(const p of map.editorAddedProps72)for(const t of p.editorUnder73||[])visual[t.y][t.x]=t.ch;map.editorVisualRows73=visual.map(r=>r.join(''));return map;
}
function flood(map,start){const visited=new Set(),queue=[];if(start&&pass(map,start.x,start.y)){queue.push(start);visited.add(start.x+','+start.y);}for(let i=0;i<queue.length;i++){const{x,y}=queue[i];for(const[dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx,yy=y+dy,k=xx+','+yy;if(!visited.has(k)&&pass(map,xx,yy)&&canTraverse75(map,x,y,xx,yy)){visited.add(k);queue.push({x:xx,y:yy});}}}return visited;}
export function validateEdit(base,d,cat){if(!d||!Array.isArray(d.objects)||!Array.isArray(d.tiles)||!Array.isArray(d.actors))return ['編集データの形式が不正です。'];d=upgrade79(base,d);if(d.encounters86!==undefined&&!validEncounters86(d.encounters86,cat.species))return ['出現ガオンは重複なしで30種類まで、レベル1〜100（最低≦最高）、出現率・出やすさ1〜100で指定してください。'];if(d.objects.some(o=>o.interior83!==undefined&&(!cat.maps[o.interior83]||cat.maps[o.interior83].kind!=='in'||!cat.maps[o.interior83].warps.some(w=>w.to==='@back')||!cat.maps[o.interior83].spawn)))return ['室内の接続先が不正です。'];if(d.shopItems82!==undefined&&(!Array.isArray(d.shopItems82)||d.shopItems82.length>GOODS82.length||new Set(d.shopItems82).size!==d.shopItems82.length||d.shopItems82.some(n=>!GOODS82.some(g=>g.name===n))))return ['ショップの商品が不正です。'];if(d.actors?.some(a=>a.trainerParty82!==undefined&&(!Array.isArray(a.trainerParty82)||a.trainerParty82.length<1||a.trainerParty82.length>6||a.trainerParty82.some(p=>!Array.isArray(p)||p.length!==2||!cat.species.includes(p[0])||!Number.isInteger(p[1])||p[1]<1||p[1]>100)||originalActor82(base,a,cat)?.artMon)))return ['トレーナーのガオンは1〜6体、レベルは1〜100で指定してください。'];if([...d.objects,...d.tiles].some(o=>o.turn81!==undefined&&(!Number.isInteger(o.turn81)||o.turn81<0||o.turn81>3)))return ['回転は0・90・180・270度から選んでください。'];if(d.objects.some(o=>o.signText82!==undefined&&(typeof o.signText82!=='string'||o.signText82.length>500||!isSign82(objectSource(base,o,cat)))))return ['看板の文章は500文字以内で入力してください。'];if(d.objects.some(o=>o.stored79!==undefined&&typeof o.stored79!=='boolean'))return ['収納状態が不正です。'];const all=validateActive79(base,{...d,objects:d.objects.filter(o=>!o.stored79)},cat);const seen=new Set();for(const o of d.objects){if(seen.has(o.id))all.push('物の識別番号が重複しています。');seen.add(o.id);if(o.stored79){const src=objectSource(base,o,cat);if(!src||!['prop','furniture'].includes(o.type)||!Number.isInteger(o.x)||!Number.isInteger(o.y)||!/^((p|f|g):\d+|a:[\w-]{1,60})$/.test(o.id))all.push('収納した素材が不正です。');}}if(d.objects.length>base.rows.length*base.rows[0].length+1000)all.push('素材が多すぎます。');return [...new Set(all)];}
function validateActive79(base,d,cat){const errors=[],fail=s=>{if(!errors.includes(s))errors.push(s);};if(!d||d.schema!==1||d.base!==fingerprint(base))return ['元のマップが更新されています。再読み込みしてください。'];if(!Array.isArray(d.tiles)||!Array.isArray(d.objects)||!Array.isArray(d.actors)||d.objects.length>base.rows.length*base.rows[0].length+1000||d.actors.length>300||d.tiles.length>base.rows.length*base.rows[0].length)return ['編集データの形式または件数が不正です。'];const w=base.rows[0].length,h=base.rows.length,at=(x,y)=>Number.isInteger(x)&&Number.isInteger(y)&&x>=0&&y>=0&&x<w&&y<h;let ids=new Set();const originals=initial(base),originalIndex=new Map(originals.objects.map(o=>[o.id,o]));
 if((d.elevations!==undefined&&!Array.isArray(d.elevations))||(d.climbs!==undefined&&!Array.isArray(d.climbs)))return ['高さ・昇降設備の形式が不正です。'];if((d.elevations||[]).length>w*h||(d.climbs||[]).length>w*h)return ['高さ・昇降設備が多すぎます。'];
 if(d.links!==undefined&&!Array.isArray(d.links))return ['入口の形式が不正です。'];if((d.links||[]).length>100)return ['入口は100個までです。'];const linkIds=new Set(),linkCells=new Set();for(const l of d.links||[]){if(!l||typeof l.id!=='string'||!/^a:[\w-]{1,60}$/.test(l.id)||linkIds.has(l.id)||!at(l.x,l.y)||typeof l.to!=='string'||!cat.maps[l.to]||!Number.isInteger(l.tx)||!Number.isInteger(l.ty)||l.tx<0||l.ty<0||l.tx>=cat.maps[l.to].rows[0].length||l.ty>=cat.maps[l.to].rows.length||typeof l.paired!=='boolean'||!validAnchor78(l.sourceAnchor)||!validAnchor78(l.targetAnchor)||[l.sourceDir||'down',l.destDir||'down'].some(v=>!['up','down','left','right'].includes(v))||linkCells.has(l.x+','+l.y))fail('入口の位置・接続先・識別番号が不正です。');linkIds.add(l?.id);linkCells.add(l?.x+','+l?.y);}if(errors.length)return errors;const heights=new Map(),climbIds=new Set();for(const t of d.elevations||[]){const k=t.x+','+t.y;if(!at(t.x,t.y)||!Number.isInteger(t.level)||t.level<1||t.level>2||heights.has(k))fail('高さは屋外のマスごとに1段・2段で指定してください。');heights.set(k,t.level);}if(base.kind==='in'&&heights.size)fail('高さの変更は屋外で使えます。');
 for(const l of d.climbs||[]){const k=l.x+','+l.y;if(!at(l.x,l.y)||l.y<1||!['ladder','stairs','ramp'].includes(l.kind)||climbIds.has(k))fail('昇降設備の位置・種類が不正です。');climbIds.add(k);if(Math.abs((heights.get(l.x+','+l.y)||0)-(heights.get(l.x+','+(l.y-1))||0))!==1)fail('はしご・階段・坂は、上下に隣り合う1段差の境目へ置いてください。');}

 for(const t of d.tiles){if(!at(t.x,t.y)||!FLOORS.some(f=>f[0]===t.material))fail('床の指定が不正です。');if(base.kind==='in'&&!['wood','tile','wall','ship-floor86','ship-wall86',...GROUND88.filter(p=>p.indoor).map(p=>p.key),...NATURE73.filter(p=>p.group==='floor').map(p=>p.key),...LEGACY73.filter(p=>p.group==='floor'&&p.indoor).map(p=>p.key)].includes(t.material))fail('室内用の床素材を選んでください。');const k=t.x+','+t.y;if(ids.has(k))fail('床の指定が重複しています。');ids.add(k);if([...base.warps,...base.signs,...base.items||[]].some(p=>p.x===t.x&&p.y===t.y))fail('入口・看板・アイテムのマスは塗り替えられません。');}
 ids=new Set();for(const o of d.objects){if(typeof o.id!=='string'||!/^(p|f|g):\d+$|^a:[\w-]{1,60}$/.test(o.id)||ids.has(o.id)){fail('物の識別番号が不正です。');continue;}ids.add(o.id);const src=objectSource(base,o,cat),old=originalIndex.get(o.id);if(!src||(!o.id.startsWith('a:')&&!old)||!['prop','furniture'].includes(o.type)||old&&(old.type!==o.type||old.template!==o.template)||o.type==='furniture'&&base.kind!=='in'){fail('未対応の素材です。');continue;}if(!at(o.x,o.y)||o.x+src.w>w||o.y+src.h>h)fail('物がマップの外にはみ出しています。');if(src.building&&o.y+src.h>=h)fail('建物の入口前に通路が必要です。');}

 ids=new Set();for(const a of d.actors){if(typeof a.id!=='string'||!/^(n):\d+$|^a:[\w-]{1,60}$/.test(a.id)||ids.has(a.id)){fail('住人の識別番号が不正です。');continue;}ids.add(a.id);if(!at(a.x,a.y)||!['up','down','left','right'].includes(a.dir)||!['still','roam','follow'].includes(a.mode))fail('住人の位置・向き・動きが不正です。');if(a.id.startsWith('n:')&&!base.npcs[Number(a.id.slice(2))])fail('元の住人が見つかりません。');if(a.id.startsWith('a:')&&!(a.type==='pet'&&cat.species.includes(a.species)||a.type==='person'&&cat.people.some(p=>p.key===a.template)))fail('住人の素材が不正です。');if(a.name!==undefined&&(typeof a.name!=='string'||a.name.length>30)||a.talk!==undefined&&(typeof a.talk!=='string'||a.talk.length>240))fail('名前は30文字、会話は240文字以内です。');if(a.mode==='follow'){const owner=d.actors.find(o=>o.id===a.owner);if(!owner||owner===a||actorSource(base,owner,cat)?.artMon||!actorSource(base,a,cat)?.residentPet)fail('ペットの飼い主には人を選んでください。');}}
 for(const a of originals.actors)if(!ids.has(a.id))fail('既存の住人は削除できません。初期位置を変更してください。');
 // Keep original actor indices: story flags and ownership refer to them.
 for(let i=0;i<originals.actors.length;i++)if(d.actors[i]?.id!=='n:'+i)fail('既存の住人の順番は変更できません。');
 if(d.rug!==null&&(!base.room||!Array.isArray(d.rug)||d.rug.length!==4||!d.rug.every(Number.isFinite)||d.rug[0]<0||d.rug[1]<0||d.rug[2]<0||d.rug[3]<0||d.rug[0]+d.rug[2]>w||d.rug[1]+d.rug[3]>h))fail('ラグが室内に収まりません。');if(errors.length)return errors;
 const map=applyEdit(base,d,cat),baseReach=flood(base,base.spawn||base.warps.find(p=>pass(base,p.x,p.y))),reach=flood(map,map.spawn||map.warps.find(p=>pass(map,p.x,p.y)));
 for(const l of d.climbs||[]){if(!pass(map,l.x,l.y)||!pass(map,l.x,l.y-1))fail('昇降設備の上下に通れるマスを確保してください。');if(map.warps.some(w=>w.x===l.x&&(w.y===l.y||w.y===l.y-1)))fail('入口と昇降設備は重ねられません。');}for(const t of d.elevations||[])if(pass(map,t.x,t.y)&&baseReach.size&&!reach.has(t.x+','+t.y))fail('高台へ行くためのはしご・階段・坂と通路を用意してください。');
 if(baseReach.size&&!reach.size)fail('開始位置をふさいでいます。');
 for(let i=0;i<base.warps.length;i++){const old=base.warps[i],next=map.warps.find(w=>w.editorWarpIndex79===i);if(next&&baseReach.has(old.x+','+old.y)&&!reach.has(next.x+','+next.y))fail('既存の出口へ行けなくなっています。通路を確保してください。');}
 for(const a of d.actors){const old=originals.actors.find(v=>v.id===a.id),changed=!old||old.x!==a.x||old.y!==a.y;if(!changed&&pass(base,a.x,a.y)&&!pass(map,a.x,a.y))fail('住人の初期位置をふさいでいます。');if(!changed){if(baseReach.size&&[[-1,0],[1,0],[0,-1],[0,1]].some(([dx,dy])=>baseReach.has((a.x+dx)+','+(a.y+dy)))&&![[ -1,0],[1,0],[0,-1],[0,1]].some(([dx,dy])=>reach.has((a.x+dx)+','+(a.y+dy))))fail('既存の住人へ話しかけられる通路を残してください。');continue;}if(!pass(map,a.x,a.y))fail('人・ガオンを壁や家具の上に置けません。');if(d.actors.some(b=>b!==a&&b.x===a.x&&b.y===a.y))fail('人・ガオンの初期位置が重なっています。');if(map.warps.some(b=>Math.abs(b.x-a.x)+Math.abs(b.y-a.y)<=1))fail('入口の前には人・ガオンを置けません。');if(baseReach.size&&![[-1,0],[1,0],[0,-1],[0,1]].some(([dx,dy])=>reach.has((a.x+dx)+','+(a.y+dy))))fail('住人の周りに通路がありません。');}
 for(const o of d.objects){const old=originalIndex.get(o.id);if(old&&old.x===o.x&&old.y===o.y&&!o.turn81)continue;const p=objectSource(base,o,cat),hit=(x,y)=>x>=o.x&&x<o.x+p.w&&y>=o.y&&y<o.y+p.h;for(const n of d.actors)if(!p.walkable&&hit(n.x,n.y))fail('家具・建物と住人が重なっています。');for(const other of d.objects){if(other===o)continue;const q=objectSource(base,other,cat);if(o.x<other.x+q.w&&o.x+p.w>other.x&&o.y<other.y+q.h&&o.y+p.h>other.y)fail('配置した物が別の物と重なっています。');}for(const wp of map.warps)if(hit(wp.x,wp.y)&&!(p.door||p.building))fail('入口を物でふさいでいます。');if(p.building&&!reach.has((o.x+p.doorOffset[0]+[0,-1,0,1][o.turn81||0])+','+(o.y+p.doorOffset[1]+[1,0,-1,0][o.turn81||0])))fail('新しい建物の入口まで通路をつないでください。');}
 for(const t of d.tiles)for(const o of d.objects){const p=objectSource(base,o,cat);if(t.x>=o.x&&t.x<o.x+p.w&&t.y>=o.y&&t.y<o.y+p.h)fail('物の下を塗る場合は、先に物を移動してください。');}
 return errors;
}

export function objectSource(base,o,cat){let p=rawObjectSource81(base,o,cat);if(p?.building&&o.interior83)p={...p,building:o.interior83,arrival:[cat.maps[o.interior83].spawn.x,cat.maps[o.interior83].spawn.y]};if(!p||!o.turn81)return p;const t=o.turn81,w=p.w,h=p.h,point=(x,y)=>t===1?[h-1-y,x]:t===2?[w-1-x,h-1-y]:[y,w-1-x],out={...p,w:t%2?h:w,h:t%2?w:h,turn81:t,originalW81:w,originalH81:h};if(p.door){const[x,y]=point(p.door.x-(p.x||0),p.door.y-(p.y||0));out.door={...p.door,x:(p.x||0)+x,y:(p.y||0)+y};out.originalDoor81=p.door;}if(p.doorOffset)out.doorOffset=point(...p.doorOffset);if(p.mask){const mask=Array.from({length:out.h},()=>Array(out.w).fill('.'));for(let y=0;y<h;y++)for(let x=0;x<w;x++){const[xx,yy]=point(x,y);if(mask[yy]?.[xx]!==undefined)mask[yy][xx]=p.mask[y]?.[x]||'.';}out.mask=mask.map(r=>r.join(''));}return out;}

export function isSign82(p){return !!p&&(/sign|board/i.test(p.art||'')||/看板/.test(p.label||''));}
export function signText82(base,p){return (base.signs.find(s=>s.x>=p.x&&s.x<p.x+p.w&&s.y>=p.y&&s.y<p.y+p.h)?.text||[]).join('\n');}

export function actorSource(base,a,cat){const n=originalActor82(base,a,cat);return n&&a.trainerParty82?{...n,trainer:{...(n.trainer||{money:100}),party:clone(a.trainerParty82)}}:n;}
