import {NATURE73} from './natureCatalog73.mjs';
import {LEGACY73} from './legacyCatalog73.mjs';
import {GARDEN72} from './gardenCatalog72.mjs';
// Pure shared editor model. No client-supplied scripts, URLs, battle data or arbitrary map JSON.
export const FLOORS=[['grass','草地',','],['path','土の道','.'],['cobble','石畳','.'],['redCobble','赤い石畳','.'],['snow','雪',','],['river','川','W'],['tallGrass','草むら','"'],['wood','木の床','f'],['tile','タイルの床','f'],['wall','壁','X'],...NATURE73.filter(p=>p.group==='floor').map(p=>[p.key,p.label,p.tile]),...LEGACY73.filter(p=>p.group==='floor').map(p=>[p.key,p.label,p.tile])];
export const clone=v=>JSON.parse(JSON.stringify(v));
const solid=new Set(['T','R','M','W','#','r','w','S','X','=','c','b','t','K','V','P','s','L']);
export const pass=(m,x,y)=>m.rows[y]?.[x]!==undefined&&!solid.has(m.rows[y][x]);
export function fingerprint(map){let n=2166136261;for(const ch of JSON.stringify(map)){n^=ch.charCodeAt(0);n=Math.imul(n,16777619);}return (n>>>0).toString(16);}
export function catalog(maps,species){
 const props=[],seen=new Set();for(const [mapId,m]of Object.entries(maps))for(const p of m.props||[]){if(seen.has(p.art))continue;seen.add(p.art);props.push({key:p.art,label:p.label||p.art,art:p.art,w:p.w,h:p.h,source:mapId});}
 for(const [art,label,w,h]of [['tree','広葉樹',2,2],['fir','針葉樹',2,2],['flowers','花',1,1],['rock','岩',1,1],['smallRock','小石',1,1],['bush','低木',1,1],['lamp','街灯',1,2],['fenceHorizontal','横の柵',1,1],['fenceVertical','縦の柵',1,1]]){const p=props.find(p=>p.art===art);if(p)p.label=label;else props.push({key:art,art,label,w,h,source:'village'});}
 props.push({key:'house',label:'家（室内つき）',art:'chalet',w:5,h:5,building:'house',source:'village'},{key:'shop',label:'ショップ（室内つき）',art:'harborShop',w:5,h:5,building:'shop',source:'rods'},{key:'hospital',label:'ガオン病院',art:'chaletClinic',w:5,h:5,building:'hospital',source:'rods'});
 for(const p of props.filter(p=>p.building)){const original=Object.values(maps).flatMap(m=>m.props||[]).find(o=>o.art===p.art&&o.w===p.w&&o.h===p.h&&o.door);p.doorOffset=original?[original.door.x-original.x,original.door.y-original.y]:[2,4];}
 const furniture=[],fseen=new Set();for(const m of Object.values(maps))for(const [kind,x,y,w,h]of m.room?.furniture||[]){if(fseen.has(kind))continue;fseen.add(kind);furniture.push({key:kind,label:({chair:'椅子',table:'テーブル',bed:'ベッド',sofa:'ソファ',books:'本棚',plant:'観葉植物',counter:'カウンター',shelf:'商品棚',shelfLeft:'商品棚（左）',shelfRight:'商品棚（右）',tv:'テレビ',computer:'パソコン',kitchen:'キッチン',ward:'ガオンの病室'})[kind]||kind,w,h});}
 const labels={mountainCrag:'山の岩壁',alpineCheese65:'チーズ工房',shoreRock:'海岸の岩',marineHouse:'港の家',marineShop:'港の店',marineHall:'港のホール',alpineGazebo65:'東屋',ancientTree:'森の大木',flowersPink:'ピンクの花',flowersGold:'黄色い花',flowerTree:'花の木',flowerHouse:'花の家',ancientAltar:'古代の祭壇',solarPanels:'太陽光パネル',powerStation:'発電施設',controlBank:'制御盤',transformers:'変圧器',pipePump:'ポンプ',turbine:'タービン',generator:'発電機',ferry:'船',parkGate:'公園の門',ranchBarn:'牧場の納屋',daycareHouse:'育て屋',shipSeats:'船の座席',shipHelm:'操舵席',nurseryPen:'ガオンの囲い',station:'駅',train:'列車',shopCounter:'売店カウンター',eTower:'塔',snowFir:'雪の針葉樹',snowHouse:'雪国の家',snowHall:'雪国のホール',holidayTree:'飾りの木',snowLamp:'雪国の街灯',ashTree:'灰の木',lavaRock:'溶岩の岩',eFir:'深緑の針葉樹',eTree:'大樹',eIce:'氷の岩',eShip:'大型船',ePalm:'ヤシの木',eHouse:'石造りの家',eDarkTree:'闇の木',eMansion:'屋敷',eLamp:'飾り街灯',eWaterfall:'滝','v41-fence':'木の柵','v41-facilities-7':'屋外施設','v41-facilities-3':'受付施設','v41-facilities-6':'公共施設','v41-facilities-5':'広場の施設','v41-facilities-4':'売店','v41-interiors-6':'室内の飾り','v41-coast-2':'海辺の草木','v41-coast-3':'海辺の飾り','v41-coast-4':'海辺の小物','v41-coast-5':'海辺の岩'};for(const p of props)p.label=labels[p.key]||p.label;for(const f of furniture)f.label=({machine:'装置',labtable:'研究テーブル',tank:'水槽',healer:'治療台'})[f.key]||f.label;
 for(const p of [...LEGACY73.filter(p=>p.group!=='floor')])if(!props.some(q=>q.key===p.key))props.push({...p,label:labels[p.original]||p.label});
 const styles=new Set();for(const [id,m]of Object.entries(maps))for(const f of m.room?.furniture||[]){const signature=JSON.stringify([m.room.theme,m.room.shopTown||'',f[0],f[3],f[4]]);if(styles.has(signature))continue;styles.add(signature);furniture.push({key:'furniture73-'+id+'-'+f[0],kind:f[0],label:m.name+'・'+(furniture.find(p=>p.key===f[0])?.label||f[0]),w:f[3],h:f[4],room:{theme:m.room.theme,shopTown:m.room.shopTown}});}
 return {props:[...props,...GARDEN72,...NATURE73.filter(p=>p.group!=='floor')],furniture,people:Array.from({length:30},(_,variant)=>({key:String(variant),variant,label:'住人 '+(variant+1)})),species};
}
export function initial(map){return {schema:1,base:fingerprint(map),tiles:[],objects:[...(map.props||[]).map((p,i)=>({id:'p:'+i,type:'prop',template:p.art,x:p.x,y:p.y})),...(map.room?.furniture||[]).map((f,i)=>({id:'f:'+i,type:'furniture',template:f[0],x:f[1],y:f[2]}))],actors:(map.npcs||[]).map((n,i)=>({id:'n:'+i,x:n.x,y:n.y,dir:n.dir||'down',mode:n.followOwner!==undefined?'follow':n.noRoam?'still':'roam',owner:n.followOwner!==undefined?'n:'+n.followOwner:null})),rug:map.room?.rug?clone(map.room.rug):null};}
export function objectSource(base,o,cat){if(o.id.startsWith('p:'))return base.props[Number(o.id.slice(2))];if(o.id.startsWith('f:')){const f=base.room?.furniture[Number(o.id.slice(2))];return f?{art:f[0],x:f[1],y:f[2],w:f[3],h:f[4]}:null;}const p=cat[o.type==='prop'?'props':'furniture'].find(p=>p.key===o.template);return p?{...p,art:p.art||p.key}:null;}
export function actorSource(base,a,cat){if(a.id.startsWith('n:'))return base.npcs[Number(a.id.slice(2))];return a.type==='pet'?{name:a.species,displayName:a.name||a.species,artMon:a.species,residentPet:true,roamMon:true,talk:[a.talk||'ごきげんに 過ごしている。']}:{look:'boy',variant:Number(a.template),name:a.name||'住人',displayName:a.name||'住人',talk:[a.talk||'こんにちは！']};}
export function applyEdit(base,doc,cat){const map=clone(base),original=initial(base),grid=map.rows.map(r=>[...r]);map.editor72=true;map.editorGround72=clone(doc.tiles);const set=(x,y,ch)=>{if(grid[y]?.[x]!==undefined)grid[y][x]=ch;};const fill=(p,ch)=>{for(let y=Math.floor(p.y);y<p.y+p.h;y++)for(let x=Math.floor(p.x);x<p.x+p.w;x++)set(x,y,ch);};const fallback=map.kind==='in'?'f':map.kind==='cave'?'.':',';
 // Clear old footprints before placing anything, including swaps.
 for(const old of original.objects){const now=doc.objects.find(o=>o.id===old.id);if(now&&now.x===old.x&&now.y===old.y)continue;const src=objectSource(base,old,cat);fill(src,fallback);}
 for(const t of doc.tiles)set(t.x,t.y,FLOORS.find(f=>f[0]===t.material)[2]);
 map.props=[];if(map.room)map.room.furniture=[];map.editorAddedProps72=[];map.editorAddedFurniture72=[];map.editorStyledFurniture73=[];
 for(const o of doc.objects){const src=objectSource(base,o,cat),p={...clone(src),x:o.x,y:o.y},old=original.objects.find(v=>v.id===o.id),changed=!old||old.x!==o.x||old.y!==o.y;
 if(o.type==='furniture'&&src.room){map.editorStyledFurniture73.push({room:src.room,f:[src.kind,o.x,o.y,p.w,p.h]});if(changed)fill(p,'t');continue;}
 if(o.type==='furniture'){(map.room?map.room.furniture:map.editorAddedFurniture72).push([o.template,o.x,o.y,p.w,p.h]);if(changed)fill(p,'t');continue;}
 if(changed&&src.walkable){p.editorUnder73=[];for(let y=p.y;y<p.y+p.h;y++)for(let x=p.x;x<p.x+p.w;x++){const ch=grid[y]?.[x];p.editorUnder73.push({x,y,ch:['.',',','f'].includes(ch)?ch:fallback});}if(src.group==='grass'||src.tile==='\"')fill(p,'\"');else for(const t of p.editorUnder73)set(t.x,t.y,t.ch);}else if(changed)fill(p,src.tile||'#');
 if(src.door){const dx=o.x-src.x,dy=o.y-src.y;p.door={...src.door,x:src.door.x+dx,y:src.door.y+dy};map.warps=map.warps.map(w=>w.x===src.door.x&&w.y===src.door.y?{...w,x:p.door.x,y:p.door.y,back:w.back?{...w.back,x:w.back.x+dx,y:w.back.y+dy,editorDoorId72:o.id}:w.back}:w);set(p.door.x,p.door.y,'D');}
 if(!old){p.editorSource72=src.source;map.editorAddedProps72.push(p);if(src.building){p.door={x:o.x+src.doorOffset[0],y:o.y+src.doorOffset[1]};set(p.door.x,p.door.y,'D');map.warps.push({x:p.door.x,y:p.door.y,to:src.building==='house'?'adminHouse72':src.building,tx:7,ty:10,back:{map:map.id,x:p.door.x,y:p.door.y+1,editorDoorId72:o.id}});}}
 else {p.editorObjectId72=o.id;map.props.push(p);}
 }
 map.npcs=doc.actors.map(a=>{const n=clone(actorSource(base,a,cat));if(a.id.startsWith('n:')&&(n.x!==a.x||n.y!==a.y))n.editorPosition72=true;if(n.roamBounds&&n.editorPosition72)n.roamBounds=n.roamBounds.map((v,i)=>v+(i%2?a.y-n.y:a.x-n.x));n.x=a.x;n.y=a.y;n.dir=a.dir;n.noRoam=a.mode==='still';if(n.artMon)n.roamMon=a.mode!=='still';delete n.followOwner;if(a.mode==='follow')n.followOwner=doc.actors.findIndex(p=>p.id===a.owner);if(a.id.startsWith('a:'))n.editorAdded72=true;return n;});
 if(map.room&&doc.rug)map.room.rug=clone(doc.rug);map.rows=grid.map(r=>r.join(''));const visual=grid.map(r=>[...r]);for(const p of map.editorAddedProps72)for(const t of p.editorUnder73||[])visual[t.y][t.x]=t.ch;map.editorVisualRows73=visual.map(r=>r.join(''));return map;
}
function flood(map,start){const visited=new Set(),queue=[];if(start&&pass(map,start.x,start.y)){queue.push(start);visited.add(start.x+','+start.y);}for(let i=0;i<queue.length;i++){const{x,y}=queue[i];for(const[dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx,yy=y+dy,k=xx+','+yy;if(!visited.has(k)&&pass(map,xx,yy)){visited.add(k);queue.push({x:xx,y:yy});}}}return visited;}
export function validateEdit(base,d,cat){const errors=[],fail=s=>{if(!errors.includes(s))errors.push(s);};if(!d||d.schema!==1||d.base!==fingerprint(base))return ['元のマップが更新されています。再読み込みしてください。'];if(!Array.isArray(d.tiles)||!Array.isArray(d.objects)||!Array.isArray(d.actors)||d.objects.length>1000||d.actors.length>300||d.tiles.length>base.rows.length*base.rows[0].length)return ['編集データの形式または件数が不正です。'];const w=base.rows[0].length,h=base.rows.length,at=(x,y)=>Number.isInteger(x)&&Number.isInteger(y)&&x>=0&&y>=0&&x<w&&y<h;let ids=new Set();const originals=initial(base);
 for(const t of d.tiles){if(!at(t.x,t.y)||!FLOORS.some(f=>f[0]===t.material))fail('床の指定が不正です。');if(base.kind==='in'&&!['wood','tile','wall',...NATURE73.filter(p=>p.group==='floor').map(p=>p.key),...LEGACY73.filter(p=>p.group==='floor'&&p.indoor).map(p=>p.key)].includes(t.material))fail('室内用の床素材を選んでください。');const k=t.x+','+t.y;if(ids.has(k))fail('床の指定が重複しています。');ids.add(k);if([...base.warps,...base.signs,...base.items||[]].some(p=>p.x===t.x&&p.y===t.y))fail('入口・看板・アイテムのマスは塗り替えられません。');}
 ids=new Set();for(const o of d.objects){if(typeof o.id!=='string'||!/^(p|f):\d+$|^a:[\w-]{1,60}$/.test(o.id)||ids.has(o.id)){fail('物の識別番号が不正です。');continue;}ids.add(o.id);const src=objectSource(base,o,cat),old=originals.objects.find(v=>v.id===o.id);if(!src||(!o.id.startsWith('a:')&&!old)||!['prop','furniture'].includes(o.type)||old&&(old.type!==o.type||old.template!==o.template)||o.type==='furniture'&&base.kind!=='in'){fail('未対応の素材です。');continue;}if(!at(o.x,o.y)||o.x+src.w>w||o.y+src.h>h)fail('物がマップの外にはみ出しています。');if(src.building&&o.y+src.h>=h)fail('建物の入口前に通路が必要です。');}
 for(const old of originals.objects){const p=objectSource(base,old,cat);if(p.door&&!ids.has(old.id))fail('既存の建物は削除できません。移動できます。');}
 ids=new Set();for(const a of d.actors){if(typeof a.id!=='string'||!/^(n):\d+$|^a:[\w-]{1,60}$/.test(a.id)||ids.has(a.id)){fail('住人の識別番号が不正です。');continue;}ids.add(a.id);if(!at(a.x,a.y)||!['up','down','left','right'].includes(a.dir)||!['still','roam','follow'].includes(a.mode))fail('住人の位置・向き・動きが不正です。');if(a.id.startsWith('n:')&&!base.npcs[Number(a.id.slice(2))])fail('元の住人が見つかりません。');if(a.id.startsWith('a:')&&!(a.type==='pet'&&cat.species.includes(a.species)||a.type==='person'&&cat.people.some(p=>p.key===a.template)))fail('住人の素材が不正です。');if(a.name!==undefined&&(typeof a.name!=='string'||a.name.length>30)||a.talk!==undefined&&(typeof a.talk!=='string'||a.talk.length>240))fail('名前は30文字、会話は240文字以内です。');if(a.mode==='follow'){const owner=d.actors.find(o=>o.id===a.owner);if(!owner||owner===a||actorSource(base,owner,cat)?.artMon||!actorSource(base,a,cat)?.residentPet)fail('ペットの飼い主には人を選んでください。');}}
 for(const a of originals.actors)if(!ids.has(a.id))fail('既存の住人は削除できません。初期位置を変更してください。');
 // Keep original actor indices: story flags and ownership refer to them.
 for(let i=0;i<originals.actors.length;i++)if(d.actors[i]?.id!=='n:'+i)fail('既存の住人の順番は変更できません。');
 if(d.rug!==null&&(!base.room||!Array.isArray(d.rug)||d.rug.length!==4||!d.rug.every(Number.isFinite)||d.rug[0]<0||d.rug[1]<0||d.rug[2]<0||d.rug[3]<0||d.rug[0]+d.rug[2]>w||d.rug[1]+d.rug[3]>h))fail('ラグが室内に収まりません。');if(errors.length)return errors;
 const map=applyEdit(base,d,cat),baseReach=flood(base,base.spawn||base.warps.find(p=>pass(base,p.x,p.y))),reach=flood(map,map.spawn||map.warps.find(p=>pass(map,p.x,p.y)));
 if(baseReach.size&&!reach.size)fail('開始位置をふさいでいます。');
 for(let i=0;i<base.warps.length;i++){const old=base.warps[i],next=map.warps[i];if(baseReach.has(old.x+','+old.y)&&!reach.has(next.x+','+next.y))fail('既存の出口へ行けなくなっています。通路を確保してください。');}
 for(const a of d.actors){const old=originals.actors.find(v=>v.id===a.id),changed=!old||old.x!==a.x||old.y!==a.y;if(!changed&&pass(base,a.x,a.y)&&!pass(map,a.x,a.y))fail('住人の初期位置をふさいでいます。');if(!changed){if(baseReach.size&&[[-1,0],[1,0],[0,-1],[0,1]].some(([dx,dy])=>baseReach.has((a.x+dx)+','+(a.y+dy)))&&![[ -1,0],[1,0],[0,-1],[0,1]].some(([dx,dy])=>reach.has((a.x+dx)+','+(a.y+dy))))fail('既存の住人へ話しかけられる通路を残してください。');continue;}if(!pass(map,a.x,a.y))fail('人・ガオンを壁や家具の上に置けません。');if(d.actors.some(b=>b!==a&&b.x===a.x&&b.y===a.y))fail('人・ガオンの初期位置が重なっています。');if(map.warps.some(b=>Math.abs(b.x-a.x)+Math.abs(b.y-a.y)<=1))fail('入口の前には人・ガオンを置けません。');if(baseReach.size&&![[-1,0],[1,0],[0,-1],[0,1]].some(([dx,dy])=>reach.has((a.x+dx)+','+(a.y+dy))))fail('住人の周りに通路がありません。');}
 for(const o of d.objects){const old=originals.objects.find(v=>v.id===o.id);if(old&&old.x===o.x&&old.y===o.y)continue;const p=objectSource(base,o,cat),hit=(x,y)=>x>=o.x&&x<o.x+p.w&&y>=o.y&&y<o.y+p.h;for(const n of d.actors)if(!p.walkable&&hit(n.x,n.y))fail('家具・建物と住人が重なっています。');for(const other of d.objects){if(other===o)continue;const q=objectSource(base,other,cat);if(o.x<other.x+q.w&&o.x+p.w>other.x&&o.y<other.y+q.h&&o.y+p.h>other.y)fail('配置した物が別の物と重なっています。');}for(const wp of map.warps)if(hit(wp.x,wp.y)&&!(p.door||p.building))fail('入口を物でふさいでいます。');if(p.building&&!reach.has((o.x+p.doorOffset[0])+','+(o.y+p.doorOffset[1]+1)))fail('新しい建物の入口まで通路をつないでください。');}
 for(const t of d.tiles)for(const o of d.objects){const p=objectSource(base,o,cat);if(t.x>=o.x&&t.x<o.x+p.w&&t.y>=o.y&&t.y<o.y+p.h)fail('物の下を塗る場合は、先に物を移動してください。');}
 return errors;
}
