import {G as State,makeMon,healParty,healFull,addToParty,ownMon,maxHp} from './state.js';
import {SPECIES} from './data/species.js';
import {ui} from './ui.js';
import {startBattle,wait} from './battle.js';
import {saveLocal,saveCloud} from './save.js';
import {cloud} from './cloud.js';
import {solid} from './tiles.js';
import {walk} from './frontierStory.js';
import {CLEAR,HAILAS,DARK,MASTER,starAvailable,legendAvailable,markLegend,hasFire,specialShip,GALAXY_TEAM,SWISS_TEAM,facilityOpponent} from './endgameRules.js';
import {jstDay} from './frontierRules.js';
const persist=async()=>{saveLocal();if(cloud.signedIn)await saveCloud(true);};
async function finish(w,r){if(r==='lose')await w.blackout();else await w.checkEvolution();await persist();w.resumeBgm();refreshEnd(w);}
function award(s,name){if(!s.badges.includes(name))s.badges.push(name);s.bag[name]=1;}
async function gift(name){const m=makeMon(name,5),where=addToParty(m);ownMon(name);await ui.say([name+' Lv.5を もらった！',where==='box'?'ボックスに送った。':'仲間に加わった！']);}
export function refreshEnd(w){const s=State.save,f=s.flags;if(f['end:eden']&&!f['end:momiWon']&&!w.npcs.some(n=>n.eden)){w.npcs.push({name:'エデン',script:'end:eden',eden:true,x:w.x,y:w.y,dir:w.dir,look:'hiker',variant:6,noRoam:true,gone:false});}for(const n of w.npcs){if(n.eden){n.gone=!!f['end:momiWon'];continue;}if(n.script==='end:forestRat')n.gone=!!f['end:forestRat'];if(n.script==='end:momiBoss')n.gone=!!f['end:momiWon'];if(n.script==='end:star')n.gone=!starAvailable(s);if(n.script==='end:ice')n.gone=!!f['end:iceWonDay']&&!legendAvailable(s,'ヒョウガン');if(n.script==='end:dark')n.gone=!!f['end:darkWonDay']&&!legendAvailable(s,'ヤミノヌシ');if(n.script==='end:rat')n.gone=!legendAvailable(s,'ラテット');if(n.script==='end:iceEmblem')n.gone=!f['end:iceWonDay']||s.badges.includes(HAILAS);if(n.script==='end:darkEmblem')n.gone=!f['end:darkWonDay']||s.badges.includes(DARK);if(n.script==='end:galaxy')n.gone=!!f['end:galaxyWon'];if(n.script==='end:islandShip')n.gone=!specialShip(s);}}
// Move along real traversable tiles to a point outside the player's camera.
async function depart(w,n){const candidates=[];for(let y=1;y<w.map.rows.length-1;y++)for(let x=1;x<w.map.rows[y].length-1;x++)if(!solid(w.map.rows[y][x])&&Math.hypot(x-w.x,y-w.y)>12)candidates.push({x,y});candidates.sort((a,b)=>Math.hypot(a.x-n.x,a.y-n.y)-Math.hypot(b.x-n.x,b.y-n.y));for(const p of candidates){await walk(w,n,p,false);if(Math.hypot(n.x-w.x,n.y-w.y)>12)break;}n.gone=true;}
export function endStep(w,from){const s=State.save;if(s.flags['end:eden']&&!s.flags['end:momiWon']){const n=w.npcs.find(n=>n.eden);if(n&&from){n.x=from.x;n.y=from.y;n.dir=w.dir;n.moving=true;}}if(s.boating&&w.map.rows[w.y]?.[w.x]!=='W')s.boating=false;}
export function tickEnd(w,dt){const s=State.save,f=s.flags;if(w.mapId==='glacier'&&!hasFire(s,SPECIES)){w.coldMs=(w.coldMs||0)+dt;if(w.coldMs>=10000&&!w.busy&&!ui.busy){w.busy=true;(async()=>{await ui.say(['寒さに 耐えられず 倒れてしまった…','ほのおタイプを 手持ちに加えよう。']);healParty();w.enter('clearTown',20,24,'down');w.coldMs=0;await persist();})().finally(()=>w.busy=false);return true;}}else w.coldMs=0;
if(w.busy||ui.busy||w.moving)return false;let n;if(w.mapId==='momi'&&!f['end:eden']&&!f['end:momiWon'])n=w.npcs.find(n=>n.eden);if(w.mapId==='momi'&&!f['end:forestRat'])n=w.npcs.find(n=>n.script==='end:forestRat'&&Math.abs(n.x-w.x)+Math.abs(n.y-w.y)<4)||n;if(w.mapId==='galaxy'&&!f['end:galaxyWon'])n=w.npcs.find(n=>n.script==='end:galaxy');if(!n||n.gone||!n.eden&&!s.party.some(m=>m.hp>0))return false;w.busy=true;(async()=>{if(!n.artMon)await walk(w,n,{x:w.x,y:w.y});await endNpc(w,n);})().catch(console.error).finally(()=>w.busy=false);return true;}
export async function useBoat(w){const s=State.save;if(!w.map.boatWater){await ui.say(['ここでは ボートを使えない。']);return;}const d=({up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]})[w.dir],x=w.x+d[0],y=w.y+d[1],ch=w.map.rows[y]?.[x];if(s.boating){if(ch==null||solid(ch)||w.npcAt(x,y)){await ui.say(['岸の方を向いて ボートを使おう。']);return;}s.boating=false;w.x=x;w.y=y;}else{if(ch!=='W'||w.npcAt(x,y)){await ui.say(['川や海の横で 水の方を向いて使おう。']);return;}s.boating=true;w.x=x;w.y=y;}s.where={map:w.mapId,x:w.x,y:w.y,dir:w.dir};await persist();}
export async function endNpc(w,n){const s=State.save,f=s.flags;if(['end:forestRat','end:momiBoss','end:galaxy','end:professor'].includes(n.script)&&!s.party.some(m=>m.hp>0)){await ui.say(['元気なガオンを 連れてこよう。']);return;}
if(n.script==='end:elder'){if(f['end:momiWon']){if(!s.badges.includes(CLEAR)){award(s,CLEAR);await persist();await ui.say(['森の試験を 乗り越えたのじゃな。','クリア・エンブレムを 手に入れた！']);}else await ui.say(['次は ほのおタイプと 氷河へ向かうのじゃ。']);}else await ui.say(['エンブレムテストを受けに来たのか？','エンブレムテストはモミの森にある','１４番道路を 抜けてゆくのじゃ。']);return;}
if(n.script==='end:eden'){if(!f['end:eden']){await ui.say(['私は エデン。雪の国から来たんだ。','一緒に 森を進もう！','バトルは任せるけど 回復は任せてね。']);f['end:eden']=true;}else await ui.say(['少し休もう。ガオンを回復するね！']);healParty();await persist();return;}
if(n.script==='end:forestRat'){const r=await startBattle({wild:makeMon('ラテット',40),captureDisabled:true,escapeDisabled:true});if(r==='win'){f['end:forestRat']=true;await ui.say(['ラテットは 森の奥へ逃げていった。','ずかんのデータは まだ「？？？」だ。']);}await finish(w,r);return;}
if(n.script==='end:momiBoss'){if(!f['end:forestRat']){await ui.say(['森の中ほどで 不思議な気配がする。']);return;}const r=await startBattle({wild:makeMon('オオウミオ',45),captureDisabled:true,escapeDisabled:true,emblemTest:true});if(r==='win'){const e=w.npcs.find(n=>n.eden);await ui.say(['エデン「一緒に旅をしてくれて ありがとう！」','旅のお礼に この子を受け取って。']);await gift('リーフィン');f['end:momiWon']=true;await persist();await ui.say(['エデン「また会おう！」']);if(e)await depart(w,e);}await finish(w,r);return;}
if(['end:ice','end:dark','end:rat','end:star'].includes(n.script)){const name=n.script==='end:ice'?'ヒョウガン':n.script==='end:dark'?'ヤミノヌシ':n.script==='end:rat'?'ラテット':'ホシミノ',key=name==='ヒョウガン'?'end:iceWonDay':'end:darkWonDay',first=['ヒョウガン','ヤミノヌシ'].includes(name)&&!f[key];if(first&&!s.party.some(m=>m.hp>0)){await ui.say(['元気なガオンを 連れてこよう。']);return;}if(!first&&(name==='ホシミノ'?!starAvailable(s):!legendAvailable(s,name)))return;if(name!=='ヒョウガン'&&name!=='ホシミノ')markLegend(s,name);await persist();const r=await startBattle({wild:makeMon(name,name==='ラテット'?60:name==='ホシミノ'?42:50),escapeDisabled:name!=='ホシミノ',captureDisabled:first,catchRate:name==='ラテット'?1:3,emblemTest:first});if(first&&r==='win'){f[key]=jstDay();await ui.say(['地面に エンブレムが落ちた。','そばにある証を 拾おう。']);}await finish(w,r);return;}
if(n.script==='end:iceEmblem'||n.script==='end:darkEmblem'){const name=n.script==='end:iceEmblem'?HAILAS:DARK,key=n.script==='end:iceEmblem'?'end:iceWonDay':'end:darkWonDay';if(!f[key])return;award(s,name);await persist();await ui.say([name+'を 手に入れた！']);n.gone=true;return;}
if(n.script==='end:galaxy'){await ui.say([s.name+'！ついに来たんだな！','強くなったかバトルしようぜ！']);const r=await startBattle({trainer:{name:'ヤノケン',party:GALAXY_TEAM,money:5000}});if(r==='win'){f['end:galaxyWon']=true;await persist();await ui.say(['１７番道路の先に カゲの廃墟があるんだ。','僕はそこで やみタイプを捕まえたよ。','キミも 行ってみなよ！']);await depart(w,n);}await finish(w,r);return;}
if(n.script==='end:professor'){if(f['end:clear']){await ui.say(['君とラテットの出会いは 感動的じゃった。','これからも 自由に世界を旅するのじゃ！']);return;}await ui.say(['あのラテットが 君の仲間になったのか！','長年の研究が 報われた気分じゃ…','わしも昔はトレーナじゃった。','ぜひお手合わせ願いたい']);const r=await startBattle({trainer:{name:'スイスはかせ',major:true,party:SWISS_TEAM,money:8000}});if(r==='win'){award(s,MASTER);f['end:clear']=true;await persist();await ui.say(['マスター・エンブレムを 手に入れた！','おめでとう！ 冒険の物語をクリアした！','登山鉄道で リーフタウンへ行けるぞ。']);}await finish(w,r);return;}
if(n.script==='end:door'){if(!f['end:door']){await ui.say(['鍵がかかっている…']);await wait(2200);await ui.say(['ガチャ…','扉が勝手に開いた…']);f['end:door']=true;await persist();}w.enter('dark1',20,61,'up');await persist();return;}
if(n.script==='end:islandShip'){if(!specialShip(s))return;if(await ui.ask(['木曜日だけの ベレリオ島行きです。','乗船しますか？'])){w.enter('belerioPort',20,31,'up');await persist();}return;}
if(n.script==='end:returnIsland'){if(await ui.ask(['カラット港へ 戻りますか？'])){w.enter('karatPort',10,17,'down');await persist();}return;}
if(n.script==='end:boat'){s.bag['小型ボート']=1;await persist();await ui.say(['この小型ボートを 使っておくれ！','川や海の横で 水の方を向いて','どうぐから 小型ボートを選ぶんだ。','岸へ進むと 上陸できるよ。','岩と 急流の先には進めないからね。']);return;}
if(n.script==='end:fashion'){const {clothesShop}=await import('./menu.js');await clothesShop('island');return;}
if(n.script==='end:rail'||n.script==='end:returnRail'){if(!f['end:clear']){await ui.say(['この登山鉄道は マスターの証を得た方だけ','リーフタウンへ お連れします。']);return;}if(await ui.ask(['登山鉄道に 乗りますか？'])){w.enter(n.script==='end:rail'?'leafTown':'mountainRail',20,n.script==='end:rail'?45:11,'down');await persist();}return;}
if(n.script==='end:arena'||n.script==='end:tower'){await runFacility(w,n.script==='end:tower'?'tower':'galaxy');return;}
}
export function trialTeam(mons){return mons.map(m=>{const clone=structuredClone(m);clone.lv=Math.min(50,clone.lv);healFull(clone);return clone;});}
export async function runFacility(w,mode){const s=State.save;s.facilities||={};let run=s.facilities[mode];await ui.say([mode==='tower'?'３匹で挑む チャンピオンタワー。':'ギャラクシー大会へ ようこそ！','最高連勝：'+(run?.best||0)]);if(mode==='tower'&&!s.flags['end:clear'])return;if(run?.inBattle){run.active=false;run.streak=0;run.inBattle=false;await persist();await ui.say(['中断された試合は 敗退扱いになりました。']);}
if(!run?.active){if(!await ui.ask(['大会に エントリーしますか？']))return;let team;if(mode==='tower'){if(s.party.length<3){await ui.say(['手持ちに３匹 連れてきてね。']);return;}const selected=[];for(let i=0;i<3;i++){const choices=s.party.map((m,index)=>({m,index})).filter(x=>!selected.includes(x.index));const pick=await ui.choice(choices.map(x=>x.m.sp+' Lv'+x.m.lv),{rows:6});if(pick<0)return;selected.push(choices[pick].index);}team=trialTeam(selected.map(i=>s.party[i]));}else {if(!s.party.length)return;team=structuredClone(s.party);team.forEach(healFull);}run=s.facilities[mode]={active:true,streak:0,best:run?.best||0,team,inBattle:false,healed:false};await persist();}
for(;;){const bout=run.streak+1,foe=facilityOpponent(mode,bout);if(!await ui.ask([run.streak+'連勝中！ 次は '+foe.name,'次の試合に進みますか？','やめても 受付から再開できます。']))return;run.inBattle=true;await persist();s.battleTerrain='arena';const r=await startBattle({trainer:{...foe,money:0},playerParty:run.team,facility:true,tournament:true});run.inBattle=false;if(r!=='win'){run.active=false;run.streak=0;await persist();await ui.say(['今回の挑戦は ここまで。','最高連勝：'+run.best]);w.resumeBgm();return;}run.streak++;run.best=Math.max(run.best,run.streak);if(mode==='tower'&&run.streak%10===0){s.bag['レベルの実']=(s.bag['レベルの実']||0)+1;await ui.say(['レベルの実を もらった！']);}if(mode==='galaxy'&&run.streak===50&&!s.flags['end:masterRag']){s.flags['end:masterRag']=true;s.bag['マスターラグ']=(s.bag['マスターラグ']||0)+1;await ui.say(['ヤノケン「50連勝 おめでとう！」','マスターラグを 手に入れた！']);}await persist();if(mode==='tower')run.team.forEach(healFull);if(mode==='galaxy'&&run.streak===6&&!run.healed){run.healed=true;if(await ui.ask(['６連勝おめでとう！','一度だけ 回復しますか？']))run.team.forEach(healFull);}await persist();w.resumeBgm();}
}
