import {jstDay,weekKey,holds} from './frontierRules.js';
export const CLEAR='クリア・エンブレム',HAILAS='ハイラス・エンブレム',DARK='ダーク・エンブレム',MASTER='マスター・エンブレム';
export function clock(now=new Date()){const d=new Date(now.getTime()+9*3600000);return {day:jstDay(now),hour:d.getUTCHours(),weekday:d.getUTCDay(),week:weekKey(now)};}
export function starDays(save,now=new Date()){const key=clock(now).week;let hash=(save.rareSpawns?.seed??12345)>>>0;for(const c of key)hash=(Math.imul(hash,31)+c.charCodeAt(0))>>>0;const a=hash%7,b=(a+1+(hash>>>8)%6)%7;return [a,b];}
export function starAvailable(s,now=new Date()){const t=clock(now);return t.hour>=16&&starDays(s,now).includes(t.weekday);}
export function legendAvailable(s,name,now=new Date()){const f=s.flags||{},t=clock(now);if(name==='ヒョウガン')return !!f['end:iceWonDay']&&t.day>f['end:iceWonDay'];if(holds(s,name)||f['end:day:'+name]===t.day)return false;if(name==='ヤミノヌシ')return !!f['end:darkWonDay']&&t.day>f['end:darkWonDay']&&t.hour>=1&&t.hour<8;return name==='ラテット';}
export function markLegend(s,name,now=new Date()){s.flags||={};s.flags['end:day:'+name]=jstDay(now);}
export function hasFire(s,species){return (s.party||[]).some(m=>species[m.sp]?.types.includes('ほのお'));}
export function specialShip(s,now=new Date()){return s.badges.includes(HAILAS)&&clock(now).weekday===4;}
export function endGate(wp,s){const f=s.flags||{};if(wp.requires==='end:clear'&&!s.badges.includes(CLEAR))return ['吹雪が激しく 先へ進めない。','クリア・エンブレムを 手に入れよう。'];if(wp.requires==='end:door'&&!f['end:door'])return ['扉を調べてみよう。'];return null;}
export function endTarget(s){const f=s.flags||{};if(!f['frontier:reported'])return null;const target=(map,x,y,name)=>({map,x,y,name});if(!f['end:momiWon'])return target('momi',20,5,'モミの森の エンブレムテスト');if(!s.badges.includes(CLEAR))return target('clearElder',8,5,'バルコレに 森の試験を報告しよう');if(!s.badges.includes(HAILAS))return target('glacier',20,5,'氷河へ ほのおタイプと向かおう');if(!f['end:galaxyWon'])return target('galaxy',18,23,'ギャラクシータウンへ');if(!s.badges.includes(DARK))return target('dark4',20,5,'カゲの廃墟の最奥へ');if(!s.dexOwn?.['ラテット'])return target('merire',20,5,'メリレの谷で ラテットと再会しよう');if(!f['end:clear'])return target('lab',7,4,'スイスはかせに ラテットを報告しよう');return target('championTower',12,10,'リーフタウンで 連勝記録に挑戦しよう');}
export const GALAXY_TEAM=[['タイダルオ',45],['コケゴロ',48],['オオヒノオ',42],['シャドネコ',50],['ボウレイ',50]];
export const SWISS_TEAM=[['ヤミノヌシ',70],['ギガビート',68],['オニイワ',71],['ヨウガンヌシ',76]];
export function facilityOpponent(mode,bout,rng=Math.random){const tower=mode==='tower';if(tower&&bout%100===0)return {name:'スイスはかせ',party:['ヨウガンヌシ','ヤミノヌシ','ギガビート'].map(n=>[n,50])};if(bout===50||(tower&&bout%50===0))return {name:'ヤノケン',party:(tower?['リュウグウ','ボウレイ','コケゴロ']:GALAXY_TEAM.map(x=>x[0])).map(n=>[n,tower?50:60])};if(!tower&&bout>=30&&bout%10===0){const names=bout===40?['エデン','スイスはかせ']:['エビゲル','ジネル','タカラダ','バルコレ','ヤノケン'];const name=names[Math.floor(rng()*names.length)];const teams={'エビゲル':['カニポン','サカナビ','ミナモリス'],'ジネル':['ビリタマ','ビリボール','コンセン'],'タカラダ':['ウリボン','タヌポン','フワクジ'],'バルコレ':['コオリン','オオウミオ','ヒョウガン'],'エデン':['リーフィン','オオウミオ','コオリン'],'スイスはかせ':['ギガビート','オニイワ','ヨウガンヌシ'],'ヤノケン':['コケゴロ','ボウレイ','タイダルオ']};return {name,party:teams[name].map(n=>[n,Math.min(75,50+Math.floor(bout/10))])};}const pool=['タイダルオ','ギガビート','オオヒノオ','オオウミオ','オニイワ','シャドネコ','コンセン','ガンセキ','フラワン'];const chosen=[...pool].sort(()=>rng()-.5).slice(0,3);return {name:'大会トレーナー '+bout,party:chosen.map(n=>[n,tower?50:Math.min(70,40+Math.floor(bout/3))])};}
