export const EXTRA75=[
  {
    "key": "garden75-extra-brick-wall",
    "art": "garden75-extra-brick-wall",
    "label": "レンガ壁",
    "w": 1,
    "h": 2,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/extra-brick-wall.png"
  },
  {
    "key": "garden75-extra-brick-gate",
    "art": "garden75-extra-brick-gate",
    "label": "レンガの門",
    "w": 3,
    "h": 2,
    "group": "decor",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/garden-v75/extra-brick-gate.png",
    "mask": [
      "#.#",
      "#.#"
    ]
  },
  {
    "key": "garden75-extra-ivy-planter",
    "art": "garden75-extra-ivy-planter",
    "label": "ツタのプランター",
    "w": 2,
    "h": 1,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/extra-ivy-planter.png"
  },
  {
    "key": "garden75-extra-iron-bench",
    "art": "garden75-extra-iron-bench",
    "label": "緑の鉄のベンチ",
    "w": 2,
    "h": 1,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/extra-iron-bench.png"
  },
  {
    "key": "garden75-extra-phone-booth",
    "art": "garden75-extra-phone-booth",
    "label": "木色の電話ボックス",
    "w": 1,
    "h": 2,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/extra-phone-booth.png"
  },
  {
    "key": "garden75-extra-low-lamp",
    "art": "garden75-extra-low-lamp",
    "label": "低い庭園ライト",
    "w": 1,
    "h": 1,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/extra-low-lamp.png"
  },
  {
    "key": "garden75-extra-signpost",
    "art": "garden75-extra-signpost",
    "label": "木の道しるべ",
    "w": 1,
    "h": 2,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/extra-signpost.png"
  },
  {
    "key": "garden75-extra-potted-cedar",
    "art": "garden75-extra-potted-cedar",
    "label": "針葉樹の鉢植え",
    "w": 1,
    "h": 2,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/extra-potted-cedar.png"
  },
  {
    "key": "garden75-extra-apple-tree",
    "art": "garden75-extra-apple-tree",
    "label": "リンゴの木",
    "w": 2,
    "h": 3,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/extra-apple-tree.png"
  },
  {
    "key": "garden75-extra-roses",
    "art": "garden75-extra-roses",
    "label": "紫のバラ",
    "w": 1,
    "h": 1,
    "group": "decor",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/garden-v75/extra-roses.png"
  },
  {
    "key": "garden75-extra-duck-ornament",
    "art": "garden75-extra-duck-ornament",
    "label": "アヒルの置物",
    "w": 1,
    "h": 1,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/extra-duck-ornament.png"
  },
  {
    "key": "garden75-extra-stone-pond",
    "art": "garden75-extra-stone-pond",
    "label": "丸石の池",
    "w": 3,
    "h": 2,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/extra-stone-pond.png"
  },
  {
    "key": "garden75-extra-cliff",
    "art": "garden75-extra-cliff",
    "label": "草地の崖",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/extra-cliff.png"
  },
  {
    "key": "garden75-extra-ladder",
    "art": "garden75-extra-ladder",
    "label": "木のはしご",
    "w": 1,
    "h": 2,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/extra-ladder.png"
  },
  {
    "key": "garden75-extra-snow-white",
    "art": "garden75-extra-snow-white",
    "label": "白い雪",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": ",",
    "source": "village",
    "file": "assets/garden-v75/extra-snow-white.png"
  },
  {
    "key": "garden75-extra-snow-blue",
    "art": "garden75-extra-snow-blue",
    "label": "青みの雪",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": ",",
    "source": "village",
    "file": "assets/garden-v75/extra-snow-blue.png"
  },
  {
    "key": "garden75-extra-sand-gold",
    "art": "garden75-extra-sand-gold",
    "label": "金色の砂",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": ",",
    "source": "village",
    "file": "assets/garden-v75/extra-sand-gold.png"
  },
  {
    "key": "garden75-extra-sand-white",
    "art": "garden75-extra-sand-white",
    "label": "白い砂",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": ",",
    "source": "village",
    "file": "assets/garden-v75/extra-sand-white.png"
  },
  {
    "key": "garden75-extra-concrete-gray",
    "art": "garden75-extra-concrete-gray",
    "label": "灰色のコンクリート",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": ",",
    "source": "village",
    "file": "assets/garden-v75/extra-concrete-gray.png"
  },
  {
    "key": "garden75-extra-concrete-cream",
    "art": "garden75-extra-concrete-cream",
    "label": "クリームのコンクリート",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": ",",
    "source": "village",
    "file": "assets/garden-v75/extra-concrete-cream.png"
  },
  {
    "key": "garden75-extra-castle",
    "art": "garden75-extra-castle",
    "label": "青屋根のお城",
    "w": 6,
    "h": 6,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/extra-castle.png",
    "building": "house",
    "doorOffset": [
      3,
      5
    ]
  },
  {
    "key": "garden75-extra-castle-wall-white",
    "art": "garden75-extra-castle-wall-white",
    "label": "白い城壁",
    "w": 1,
    "h": 2,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/extra-castle-wall-white.png"
  },
  {
    "key": "garden75-extra-castle-wall-dark",
    "art": "garden75-extra-castle-wall-dark",
    "label": "黒い城壁",
    "w": 1,
    "h": 2,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/extra-castle-wall-dark.png"
  },
  {
    "key": "garden75-extra-stairs",
    "art": "garden75-extra-stairs",
    "label": "石の階段",
    "w": 1,
    "h": 2,
    "group": "decor",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/garden-v75/extra-stairs.png"
  },
  {
    "key": "garden75-extra-ramp",
    "art": "garden75-extra-ramp",
    "label": "土の坂",
    "w": 1,
    "h": 2,
    "group": "decor",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/garden-v75/extra-ramp.png"
  }
];
export const GROUND75=EXTRA75.filter(p=>p.group==='floor'&&!p.key.endsWith('-cliff'));
export const DECOR75=EXTRA75.filter(p=>p.group==='decor'&&!/-(ladder|stairs|ramp)$/.test(p.key));
