// Eight genuinely drawn poses per Gaon: down/up/right/left, each A and B.
import {SPECIES} from './data/species.js';
import {MOTION_PROFILES} from './data/gaonMotion.js';
import {battleArt} from './data/battleart.js';
const sheets=new Map(),frames=new Map();
export function followerSheet(name){const no=SPECIES[name]?.no;if(!no)return null;if(!sheets.has(no)){const im=new Image();im.src=new URL('../assets/followers-v14/'+String(no).padStart(3,'0')+'.png',import.meta.url).href;sheets.set(no,im);}return sheets.get(no);}
export async function loadFollowerSheet(name){const im=followerSheet(name);if(!im)return false;try{await im.decode();return true;}catch{return false;}}
export function followerFrame(name,dir,phase=0){const im=followerSheet(name);if(!im?.complete||!im.naturalWidth)return null;const col=({down:0,up:1,right:2,left:3})[dir]??0,row=phase%2,key=SPECIES[name].no+':'+col+':'+row;if(frames.has(key))return frames.get(key);const c=document.createElement('canvas');c.width=c.height=80;c.getContext('2d').drawImage(im,col*80,row*80,80,80,0,0,80,80);frames.set(key,c);return c;}
export function drawFollower(ctx,mon,pose,tick,cx,feetY){const kind=MOTION_PROFILES[mon.sp]?.kind||'walk',active=pose.moving||['fly','float','swim'].includes(kind),ms=({walk:160,hop:200,fly:150,swim:220,float:260,crawl:260,slither:220})[kind]||180,phase=active?Math.floor(tick/ms)%2:0;const frame=followerFrame(mon.sp,pose.dir,phase);ctx.save();ctx.imageSmoothingEnabled=false;ctx.fillStyle='rgba(12,44,37,.18)';ctx.beginPath();ctx.ellipse(Math.round(cx),Math.round(feetY-1),12,3,0,0,Math.PI*2);ctx.fill();if(frame)ctx.drawImage(frame,Math.round(cx-24),Math.round(feetY-44.4),48,48);else{const initial=battleArt(mon.sp,pose.dir==='up');if(initial)ctx.drawImage(initial,Math.round(cx-24),Math.round(feetY-44.4),48,48);}ctx.restore();return !!frame;}
