import {cloud} from './cloud.js';
import {G as State} from './state.js';
import {snapshot,saveLocal,applySave} from './save.js';
import {ui} from './ui.js';
import {battleArt} from './data/battleart.js';
import {heroFrame} from './revampArt.js';
const labels={battle:'通信バトル',trade:'ガオン交換',coop:'協力ダンジョン'};
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;};
export async function openFriends(){
 if(!cloud.signedIn){await ui.say(['友だちと遊ぶには ログインが必要です。','せってい → アカウントから ログインしてください。']);return;}
 let resume;for(;;){resume=await cloud.call('/api/friends',{method:'POST',timeoutMs:12000,body:{action:'resume'}});if(resume.ok)break;if((!resume.status||resume.status>=500)&&await ui.ask([resume.why,'通信を再確認しますか？']))continue;await ui.say([resume.why]);return;}
 if(resume.data.payload&&(resume.data.room||(resume.data.payload.friendEpoch||0)>(State.save.friendEpoch||0))){applySave(resume.data.payload);cloud.user=resume.data.user;cloud.rev=resume.data.user.rev;}
 if(!resume.data.room){saveLocal();const saved=await cloud.push(snapshot(),false);if(!saved.ok){await ui.say([saved.why,'レポートで記録を確認してから、もう一度お試しください。']);return;}}
 if(!document.getElementById('friend-css')){const css=el('link');css.id='friend-css';css.rel='stylesheet';css.href=new URL('./friends.css',import.meta.url).href;document.head.append(css);}
 const root=el('section',null,'friend-overlay');root.id='friends';root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-label','友だちと遊ぶ');document.body.append(root);
 let room=resume.data.room||null,selected=new Set(),busy=false,connectionLost=false,sessionExpired=false,closed=false,timer,message='',mode='battle',rule='level50',joinCode='',leaving=false;
 const viewerId=cloud.user.id;
 const done=new Promise(resolve=>root.finish=resolve);
 const button=(text,fn,cls)=>{const b=el('button',text,cls);b.type='button';b.disabled=busy||connectionLost;b.onclick=fn;return b;};
 function artwork(mon,back=false){const img=battleArt(mon.sp,back);const e=el('img');if(img)e.src=img.src;e.alt=mon.sp;return e;}
 function card(mon){const c=el('article',null,'friend-mon');c.append(artwork(mon),el('strong',(mon.nick||mon.sp)+' Lv.'+mon.lv));if(mon.nick)c.append(el('small',mon.sp));return c;}
 async function api(action,extra={},silent=false){if(busy&&!silent)return;if(connectionLost&&!silent)return;const currentCode=room?.code;if(!silent){busy=true;message='';render();}try{const r=await cloud.call('/api/friends',{method:'POST',timeoutMs:12000,body:{action,code:currentCode,...extra,...(!silent?{requestId:crypto.randomUUID()}: {})}});if(closed)return;if(!r.ok){message=r.why;if(!r.status||r.status>=500)connectionLost=true;if(r.status===401)sessionExpired=true;return;}if(connectionLost){message='';connectionLost=false;}if(!r.data.room&&action==='resume'&&r.data.payload&&(r.data.payload.friendEpoch||0)>(State.save.friendEpoch||0)){applySave(r.data.payload);cloud.rev=r.data.user.rev;cloud.user=r.data.user;}if(r.data.room){if(room&&room.code===r.data.room.code&&room.version>r.data.room.version)return;room=r.data.room;if(['complete','closed'].includes(room.phase)&&r.data.payload){applySave(r.data.payload);cloud.rev=r.data.user.rev;cloud.user=r.data.user;}}}finally{if(!silent)busy=false;if(!closed)render();}}
 function closeLocal(){closed=true;clearTimeout(timer);document.removeEventListener('keydown',onKey,true);root.remove();root.finish();}
 async function finish(){if(sessionExpired){closeLocal();return;}if(busy)return;if(room&&!['closed','complete'].includes(room.phase)&&!leaving){leaving=true;render();return;}if(room){await api('leave');if(!['closed','complete'].includes(room.phase))return;const pulled=await cloud.pull();if(!pulled.ok){message='最新の記録を取得できません。再接続してから閉じてください。';render();return;}if(pulled.data.payload)applySave(pulled.data.payload);}closeLocal();}
 function choices(parent){const own=room.players.find(p=>p.id===viewerId);const size=room.mode==='coop'?1:room.rule==='level50'?3:State.save.party.length;parent.append(el('p',room.mode==='coop'?'一緒に冒険するガオンを1匹選んでください。':'参加するガオンを'+size+'匹選んでください。'));
 const list=el('div',null,'friend-team');for(const mon of State.save.party){const c=button('',()=>{selected.has(mon.companionId)?selected.delete(mon.companionId):selected.size<size&&selected.add(mon.companionId);render();},'friend-select');c.append(card(mon));c.setAttribute('aria-label',(mon.nick||mon.sp)+'を選択');c.setAttribute('aria-pressed',String(selected.has(mon.companionId)));c.disabled=busy||connectionLost||own.ready;list.append(c);}parent.append(list);const ready=button(own.ready?'準備完了・友だちを待っています':'このガオンで準備完了',()=>api('ready',{ids:[...selected]}),'primary');ready.disabled=busy||connectionLost||own.ready||selected.size!==size;parent.append(ready);}
 function trade(parent){const offers=el('div',null,'friend-offers');for(const p of room.players){const c=el('section',null,'friend-offer');c.append(el('h3',p.name));const m=room.offers[p.id]?.mon;if(m){c.append(card(m),el('p','持ち物：'+(m.heldItem||'なし')));const list=el('ul');for(const move of m.moves||[])list.append(el('li',move.name+'　'+move.pp+'/'+move.max+'回'));c.append(list);}else c.append(el('p','ガオンを選んでいます'));if(room.confirmations.includes(p.id))c.append(el('b','確認済み'));offers.append(c);}parent.append(offers);
 const select=el('select');select.setAttribute('aria-label','交換するガオン');select.append(new Option('交換に出すガオンを選ぶ',''));for(const place of ['party','box'])State.save[place].forEach((m,i)=>select.append(new Option((place==='party'?'手持ち':'ボックス')+'：'+(m.nick||m.sp)+' Lv.'+m.lv,place+':'+i)));select.disabled=busy||connectionLost;select.onchange=()=>{if(select.value){const[place,index]=select.value.split(':');api('offer',{ref:{place,index:Number(index)}})}};parent.append(select);
 const confirm=button('相手のガオンを確認して交換を確定',()=>api('confirm',{offerRevision:room.offerRevision}),'primary');confirm.disabled=busy||connectionLost||room.players.length!==2||Object.keys(room.offers).length!==2||room.confirmations.includes(viewerId);parent.append(confirm,el('small','両方が確定すると交換します。どちらかが選び直すと、確認は解除されます。'));}
 function fight(parent,b){const scene=el('div',null,'friend-battle');scene.style.backgroundImage='url('+new URL('../assets/battle-v38/'+(room.mode==='coop'?'cave':'arena')+'.png',import.meta.url).href+')';
 for(const [i,s]of b.sides.entries()){const m=s.team[s.active],c=el('div',null,'fighter '+(s.id===viewerId?'mine':s.ai||!b.coop?'enemy':'ally'));c.append(artwork(m,s.id===viewerId));const info=el('div',null,'fighter-info');info.append(el('strong',(m.nick||m.sp)+' Lv.'+m.lv));const meter=el('meter');meter.min=0;meter.max=m.maxHp;meter.value=m.hp;meter.setAttribute('aria-label',m.sp+'のHP');info.append(meter,el('small',m.hp+'/'+m.maxHp+(m.status?' '+m.status:'')));c.append(info);scene.append(c);}parent.append(scene);
 const log=el('div',null,'friend-log');log.setAttribute('role','status');log.textContent=b.logs.join('　');parent.append(log);if(b.finished){if(room.mode==='coop')parent.append(button('探索に戻る',()=>{room.dungeon.battle=null;render();}));return;}
 const side=b.sides.find(s=>s.id===viewerId),m=side.team[side.active];if(!m.hp){parent.append(el('p','友だちのバトルを応援しよう！'));return;}if(b.waiting.includes(viewerId)){parent.append(el('p','行動を送信しました。友だちの選択を待っています。'));return;}const commands=el('div',null,'friend-commands');m.moves.forEach((move,index)=>{const c=button(move.name+'　'+move.pp+'/'+move.max+'回',()=>api('battle',{turn:b.turn,command:{kind:'move',index}}));c.disabled=busy||connectionLost||move.pp<=0;commands.append(c)});if(!m.moves.some(x=>x.pp>0))commands.append(button('わるあがき',()=>api('battle',{turn:b.turn,command:{kind:'move',index:-1}})));side.team.forEach((mon,index)=>{if(index!==side.active&&mon.hp)commands.append(button('交代：'+mon.sp,()=>api('battle',{turn:b.turn,command:{kind:'switch',index}})));});parent.append(commands);}
 function dungeon(parent){const d=room.dungeon;if(d.battle&&!d.battle.finished){fight(parent,d.battle);return;}parent.append(el('h3','こだまの洞窟　'+(d.floor+1)+' / 3階'),el('p',d.cleared.includes(d.floor)?'守りのガオンを倒した！ 2人で奥に集まろう。':'2人で奥へ進み、守りのガオンに挑もう。'));const canvas=el('canvas');canvas.width=480;canvas.height=352;canvas.className='friend-map';canvas.setAttribute('aria-label','協力ダンジョンの地図');const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;d.map.forEach((row,y)=>[...row].forEach((tile,x)=>{ctx.fillStyle=tile==='#'?'#283c43':(x+y)%2?'#80968a':'#83998c';ctx.fillRect(x*32,y*32,32,32);if(tile==='#'){ctx.fillStyle='#415961';ctx.fillRect(x*32+2,y*32+2,28,21);ctx.fillStyle='#50676a';ctx.fillRect(x*32+4,y*32+3,24,3);}}));const cleared=d.cleared.includes(d.floor);const boss=battleArt(['コケゴロ','シャドネコ','ギガビート'][d.floor]);if(cleared){ctx.fillStyle='#d4c99e';for(let i=0;i<5;i++)ctx.fillRect(384+i*2,64+i*5,32-i*4,3);}else if(boss)ctx.drawImage(boss,376,40,48,48);
 room.players.forEach((p,i)=>{const pos=d.positions[p.id];if(!pos)return;const f=heroFrame('down',1,{...State.save.look,appearanceVersion:1,shirt:i?'#edab59':'#568fff'});ctx.fillStyle=i?'#ffcb65':'#b3ddff';ctx.beginPath();ctx.ellipse(pos.x*32+16,pos.y*32+27,13,5,0,0,Math.PI*2);ctx.fill();if(f)ctx.drawImage(f,pos.x*32,pos.y*32-14,32,48);ctx.font='bold 12px sans-serif';ctx.strokeStyle='#142733';ctx.lineWidth=3;ctx.strokeText(p.name.slice(0,8),pos.x*32-4,pos.y*32-16);ctx.fillStyle='white';ctx.fillText(p.name.slice(0,8),pos.x*32-4,pos.y*32-16);});parent.append(canvas);
 const controls=el('div',null,'friend-controls');for(const[text,dx,dy]of [['↑',0,-1],['←',-1,0],['↓',0,1],['→',1,0]])controls.append(button(text,()=>api('walk',{dx,dy,seq:room.seq[viewerId]||0})));controls.append(button(cleared?'次へ進む':'ボスに挑む',()=>api('interact'),'primary'));parent.append(controls,el('small','矢印キーでも移動できます。2人とも奥の近くに集まってください。'));}
 function render(){if(closed)return;const scroll=root.scrollTop;root.replaceChildren();const panel=el('div',null,'friend-panel');const head=el('header');head.append(el('div','FRIENDS / GAON WORLD','friend-eyebrow'),el('h1',room?labels[room.mode]:'友だちと遊ぶ'),button('閉じる',finish,'friend-close'));panel.append(head);if(sessionExpired){const login=button('閉じてログインし直す',closeLocal);login.disabled=false;panel.append(el('p','ログインし直してから「友だちと遊ぶ」を開くと、ルームに復帰できます。'),login);root.append(panel);return;}if(connectionLost){const reconnect=button('通信を再確認',()=>api(room?'state':'resume',{},true));reconnect.disabled=false;panel.append(el('p','通信が途切れました。接続が戻ると自動で確認します。交換や行動を重ねて送ることはありません。','friend-connection'),reconnect);}if(message){const msg=el('p',message,'friend-error');msg.setAttribute('role','alert');panel.append(msg);}if(leaving){panel.append(el('p','退出すると、このルームでの遊びを終了します。'),button('ルームを退出する',finish,'primary'),button('続ける',()=>{leaving=false;render();}));root.append(panel);return;}
 if(!room){panel.append(el('p','合言葉を伝えて、友だちと2人で遊ぼう。'));const modes=el('div',null,'friend-modes');for(const[k,v]of Object.entries(labels)){const b=button(v,()=>{mode=k;render();});b.setAttribute('aria-pressed',String(mode===k));modes.append(b);}panel.append(modes);if(mode==='battle'){const s=el('select');s.setAttribute('aria-label','バトルルール');s.append(new Option('3匹・Lv.50にそろえる','level50'),new Option('手持ち全員・現在のレベル','current'));s.value=rule;s.onchange=()=>rule=s.value;panel.append(s);}panel.append(el('p',mode==='trade'?'お互いのガオンを確認してから、1匹ずつ交換します。':mode==='coop'?'1匹ずつ選び、2人で全3階と協力ボス戦に挑みます。':'バトル後も元のHP・技の回数・経験値は変わりません。'),button('ルームを作る',()=>api('create',{mode,rule}),'primary'));const join=el('section',null,'friend-join');join.append(el('h2','友だちのルームに入る'));const input=el('input');input.placeholder='8文字の合言葉';input.setAttribute('aria-label','合言葉');input.maxLength=12;input.autocomplete='off';input.value=joinCode;input.oninput=()=>joinCode=input.value;join.append(input,button('参加する',()=>api('join',{code:joinCode})));panel.append(join);
 }else{const code=el('div',null,'friend-code');code.append(el('span','合言葉'),el('strong',room.code.slice(0,4)+'-'+room.code.slice(4)));panel.append(code,el('p',room.players.map(p=>p.name+(p.online?' ●':' 再接続待ち')+(p.ready?' 準備OK':'')).join('　／　')));if(room.players.length<2)panel.append(el('p','友だちの参加を待っています。'));if(['complete','closed'].includes(room.phase)){panel.append(el('h2',room.result),button('冒険に戻る',finish,'primary'));}else if(room.phase==='lobby'){if(room.mode==='trade')trade(panel);else choices(panel);}else if(room.phase==='battle')fight(panel,room.battle);else if(room.phase==='dungeon')dungeon(panel);}
 if(busy)panel.append(el('p','通信中…','friend-connection'));root.append(panel);root.scrollTop=scroll;}
 function onKey(e){if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();finish();return;}if(room?.phase==='dungeon'&&!room.dungeon.battle?.finished&&room.dungeon.battle)return;const dir={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]}[e.key];if(dir&&room?.phase==='dungeon'){e.preventDefault();e.stopImmediatePropagation();if(!busy)api('walk',{dx:dir[0],dy:dir[1],seq:room.seq[viewerId]||0});}}
 document.addEventListener('keydown',onKey,true);render();async function poll(){if(closed||sessionExpired)return;if(!busy&&connectionLost)await api(room?'state':'resume',{},true);else if(room&&!busy&&!['complete','closed'].includes(room.phase))await api('state',{},true);timer=setTimeout(poll,2000);}timer=setTimeout(poll,2000);await done;
}
