export const PATHS75=[
  {
    "key": "garden75-grass-center",
    "label": "草道・中央",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 0,
    "file": "assets/garden-v75/grass-center.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-grass-edge-0",
    "label": "草道・上ふち",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 0,
    "file": "assets/garden-v75/grass-edge.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-grass-edge-1",
    "label": "草道・右ふち",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 1,
    "file": "assets/garden-v75/grass-edge.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-grass-edge-2",
    "label": "草道・下ふち",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 2,
    "file": "assets/garden-v75/grass-edge.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-grass-edge-3",
    "label": "草道・左ふち",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 3,
    "file": "assets/garden-v75/grass-edge.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-grass-outer-0",
    "label": "草道・左上外角",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 0,
    "file": "assets/garden-v75/grass-outer.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-grass-outer-1",
    "label": "草道・右上外角",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 1,
    "file": "assets/garden-v75/grass-outer.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-grass-outer-2",
    "label": "草道・右下外角",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 2,
    "file": "assets/garden-v75/grass-outer.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-grass-outer-3",
    "label": "草道・左下外角",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 3,
    "file": "assets/garden-v75/grass-outer.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-grass-inner-0",
    "label": "草道・左上内角",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 0,
    "file": "assets/garden-v75/grass-inner.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-grass-inner-1",
    "label": "草道・右上内角",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 1,
    "file": "assets/garden-v75/grass-inner.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-grass-inner-2",
    "label": "草道・右下内角",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 2,
    "file": "assets/garden-v75/grass-inner.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-grass-inner-3",
    "label": "草道・左下内角",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 3,
    "file": "assets/garden-v75/grass-inner.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-grass-island",
    "label": "草道・小さな土の丸",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 0,
    "file": "assets/garden-v75/grass-island.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-grass-sprigs",
    "label": "草道・草花の飾り",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 0,
    "file": "assets/garden-v75/grass-sprigs.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-leaf-center",
    "label": "けもの道・中央",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 0,
    "file": "assets/garden-v75/leaf-center.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-leaf-edge-0",
    "label": "けもの道・上ふち",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 0,
    "file": "assets/garden-v75/leaf-edge.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-leaf-edge-1",
    "label": "けもの道・右ふち",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 1,
    "file": "assets/garden-v75/leaf-edge.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-leaf-edge-2",
    "label": "けもの道・下ふち",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 2,
    "file": "assets/garden-v75/leaf-edge.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-leaf-edge-3",
    "label": "けもの道・左ふち",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 3,
    "file": "assets/garden-v75/leaf-edge.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-leaf-outer-0",
    "label": "けもの道・左上外角",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 0,
    "file": "assets/garden-v75/leaf-outer.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-leaf-outer-1",
    "label": "けもの道・右上外角",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 1,
    "file": "assets/garden-v75/leaf-outer.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-leaf-outer-2",
    "label": "けもの道・右下外角",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 2,
    "file": "assets/garden-v75/leaf-outer.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-leaf-outer-3",
    "label": "けもの道・左下外角",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 3,
    "file": "assets/garden-v75/leaf-outer.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-leaf-inner-0",
    "label": "けもの道・左上内角",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 0,
    "file": "assets/garden-v75/leaf-inner.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-leaf-inner-1",
    "label": "けもの道・右上内角",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 1,
    "file": "assets/garden-v75/leaf-inner.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-leaf-inner-2",
    "label": "けもの道・右下内角",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 2,
    "file": "assets/garden-v75/leaf-inner.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-leaf-inner-3",
    "label": "けもの道・左下内角",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 3,
    "file": "assets/garden-v75/leaf-inner.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-leaf-island",
    "label": "けもの道・小さな土の丸",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 0,
    "file": "assets/garden-v75/leaf-island.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-leaf-sprigs",
    "label": "けもの道・草花の飾り",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 0,
    "file": "assets/garden-v75/leaf-sprigs.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-blue-mosaic",
    "label": "青い装飾タイル",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 0,
    "file": "assets/garden-v75/blue-mosaic.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-japan-stone",
    "label": "和風の丸石畳",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 0,
    "file": "assets/garden-v75/japan-stone.png",
    "w": 1,
    "h": 1
  },
  {
    "key": "garden75-white-brick",
    "label": "透過の白レンガ",
    "group": "floor",
    "tile": ",",
    "overlay": true,
    "rotation": 0,
    "file": "assets/garden-v75/white-brick.png",
    "w": 1,
    "h": 1
  }
];
export const OBJECTS75=[
  {
    "key": "garden75-prop-wood-bench",
    "art": "garden75-prop-wood-bench",
    "label": "木のベンチ",
    "w": 2,
    "h": 1,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/prop-wood-bench.png"
  },
  {
    "key": "garden75-prop-log-bench",
    "art": "garden75-prop-log-bench",
    "label": "丸太ベンチ",
    "w": 2,
    "h": 1,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/prop-log-bench.png"
  },
  {
    "key": "garden75-prop-flower-cart",
    "art": "garden75-prop-flower-cart",
    "label": "花のカート",
    "w": 2,
    "h": 2,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/prop-flower-cart.png"
  },
  {
    "key": "garden75-prop-garden-lamp",
    "art": "garden75-prop-garden-lamp",
    "label": "緑の街灯",
    "w": 1,
    "h": 2,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/prop-garden-lamp.png"
  },
  {
    "key": "garden75-prop-chalkboard",
    "art": "garden75-prop-chalkboard",
    "label": "立て看板",
    "w": 1,
    "h": 1,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/prop-chalkboard.png"
  },
  {
    "key": "garden75-prop-birdhouse",
    "art": "garden75-prop-birdhouse",
    "label": "巣箱",
    "w": 1,
    "h": 2,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/prop-birdhouse.png"
  },
  {
    "key": "garden75-prop-gaon-statue",
    "art": "garden75-prop-gaon-statue",
    "label": "ガオン風の置物",
    "w": 1,
    "h": 1,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/prop-gaon-statue.png"
  },
  {
    "key": "garden75-prop-stump",
    "art": "garden75-prop-stump",
    "label": "切り株",
    "w": 1,
    "h": 1,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/prop-stump.png"
  },
  {
    "key": "garden75-prop-pinecones",
    "art": "garden75-prop-pinecones",
    "label": "まつぼっくり",
    "w": 1,
    "h": 1,
    "group": "decor",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/garden-v75/prop-pinecones.png"
  },
  {
    "key": "garden75-prop-basket",
    "art": "garden75-prop-basket",
    "label": "花かご",
    "w": 1,
    "h": 1,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/prop-basket.png"
  },
  {
    "key": "garden75-prop-log-fence",
    "art": "garden75-prop-log-fence",
    "label": "丸太の柵",
    "w": 2,
    "h": 1,
    "group": "decor",
    "walkable": false,
    "tile": "#",
    "source": "village",
    "file": "assets/garden-v75/prop-log-fence.png"
  },
  {
    "key": "garden75-prop-wood-planks",
    "art": "garden75-prop-wood-planks",
    "label": "透過の木の板",
    "w": 1,
    "h": 1,
    "group": "decor",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/garden-v75/prop-wood-planks.png"
  },
  {
    "key": "garden75-prop-clover",
    "art": "garden75-prop-clover",
    "label": "クローバー",
    "w": 1,
    "h": 1,
    "group": "decor",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/garden-v75/prop-clover.png"
  },
  {
    "key": "garden75-prop-daisies",
    "art": "garden75-prop-daisies",
    "label": "白い野花",
    "w": 1,
    "h": 1,
    "group": "decor",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/garden-v75/prop-daisies.png"
  }
];

// Complete directional sets for the three decorative paving families.
for(const p of PATHS75.filter(p=>!p.label.includes('・'))){for(const[shape,labels]of [['edge',['上ふち','右ふち','下ふち','左ふち']],['corner',['左上外角','右上外角','右下外角','左下外角']],['inner',['左上内角','右上内角','右下内角','左下内角']]])for(let i=0;i<4;i++)PATHS75.push({...p,key:p.key+'-'+shape+'-'+i,label:p.label+'・'+labels[i],rotation:i,shape81:shape});}
