const blocked=new Set('TRMW#rwSX=cbtKVPLs');
export const edge140=(m,p)=>p.y===0?'top':p.y===m.rows.length-1?'bottom':p.x===0?'left':p.x===m.rows[0].length-1?'right':[...(m.props||[]),...(m.editorAddedProps72||[])].some(g=>g.art==='parkGate'&&p.x>g.x&&p.x<g.x+g.w-1&&p.y===g.y+g.h)?'gate':null;
const vector={gate:[0,1],top:[0,1],bottom:[0,-1],left:[1,0],right:[-1,0]};
export function exitGroups140(m){if(m.kind==='in')return [];const out=[];for(const p of m.warps||[]){const edge=edge140(m,p);if(!edge||!p.to||p.to==='@back')continue;const axis=['top','bottom','gate'].includes(edge)?'x':'y';let g=out.find(g=>g.edge===edge&&g.to===p.to&&JSON.stringify(g.points[0].requires)===JSON.stringify(p.requires));if(!g){g={edge,axis,to:p.to,points:[]};out.push(g);}g.points.push(p);}return out.flatMap(g=>{g.points.sort((a,b)=>a[g.axis]-b[g.axis]);const runs=[];for(const p of g.points){let r=runs.at(-1);if(!r||p[g.axis]>r.points.at(-1)[g.axis]+1){r={...g,points:[]};runs.push(r);}r.points.push(p);}return runs;});}
export function twoCellExits140(map){if(map.kind==='in')return map;const groups=exitGroups140(map);if(!groups.length)return map;const rows=map.rows.map(r=>[...r]),visual=(map.editorVisualRows73||map.rows).map(r=>[...r]),cells=new Map(),removed=new Set(),warps=[...map.warps];const width=rows[0].length,height=rows.length;
 for(const g of groups){const [dx,dy]=vector[g.edge],first=g.points[0],lo=first[g.axis],hi=g.points.at(-1)[g.axis],limit=g.axis==='x'?width:height;let start=lo;
  if(g.points.length!==2){const candidates=g.points.length===1?[Math.min(lo,limit-3)]:Array.from({length:hi-lo},(_,i)=>lo+i);let best=-Infinity;for(const a of candidates){if(a<1||a+1>limit-2)continue;let score=-Math.abs(a-(lo+hi-1)/2)*.01;for(let lane=0;lane<2;lane++)for(let d=0;d<4;d++){const x=g.axis==='x'?a+lane:first.x+dx*d,y=g.axis==='y'?a+lane:first.y+dy*d;score+=blocked.has(rows[y]?.[x])?-5:2;}if(score>best){best=score;start=a;}}}
  for(const p of g.points)removed.add(p);for(let lane=0;lane<2;lane++){const pos={x:first.x,y:first.y,[g.axis]:start+lane},old=g.points.find(p=>p[g.axis]===start+lane)||first;warps.push({...old,...pos,twoCellExit140:true});let floor=map.kind==='cave'?'C':',';let material;for(let d=1;d<=5;d++){const x=pos.x+dx*d,y=pos.y+dy*d,ch=rows[y]?.[x];if(ch!==undefined&&!blocked.has(ch)&&ch!=='D'){floor=ch;material=(map.editorGround72||[]).find(t=>t.x===x&&t.y===y);break;}}if(floor==='"')floor=',';for(let d=0;d<3;d++){const x=pos.x+dx*d,y=pos.y+dy*d;if(rows[y]?.[x]!==undefined)cells.set(x+','+y,{x,y,floor,material,edge:d===0});}}
  // Formerly wide trigger strips retain their terrain but only two cells transfer maps.
  for(const p of g.points)if(p[g.axis]<start||p[g.axis]>start+1){if(rows[p.y][p.x]==='D')rows[p.y][p.x]=visual[p.y][p.x]=map.kind==='cave'?'C':'.';}
 }
 const obstacles=p=>/tree|fir|conifer|broadleaf|palm|rock/i.test(p.art||p.template||'')&&[...cells.values()].some(t=>t.x>=p.x&&t.x<p.x+p.w&&t.y>=p.y&&t.y<p.y+p.h);
 for(const key of ['props','editorAddedProps72','editorObjects78']){const old=map[key]||[];for(const p of old.filter(obstacles))for(let y=Math.max(0,p.y);y<Math.min(height,p.y+p.h);y++)for(let x=Math.max(0,p.x);x<Math.min(width,p.x+p.w);x++)rows[y][x]=visual[y][x]=map.kind==='cave'?'C':',';map[key]=old.filter(p=>!obstacles(p));}
 map.editorGround72=(map.editorGround72||[]).filter(t=>!cells.has(t.x+','+t.y));for(const t of cells.values()){rows[t.y][t.x]=t.edge?'D':t.floor;visual[t.y][t.x]=t.floor;if(t.material)map.editorGround72.push({...t.material,x:t.x,y:t.y});}map.rows=rows.map(r=>r.join(''));if(map.editorVisualRows73)map.editorVisualRows73=visual.map(r=>r.join(''));map.warps=warps.filter(p=>!removed.has(p));return map;
}
export function connectTwoCellExits140(maps){for(const m of Object.values(maps))twoCellExits140(m);for(const m of Object.values(maps))for(const g of exitGroups140(m)){const target=maps[g.to];if(!target||target.kind==='in')continue;const returns=exitGroups140(target).filter(r=>r.to===m.id);if(!returns.length)continue;for(const [lane,w]of g.points.entries()){const r=returns.reduce((a,b)=>Math.min(...a.points.map(p=>Math.abs(p.x-w.tx)+Math.abs(p.y-w.ty)))<=Math.min(...b.points.map(p=>Math.abs(p.x-w.tx)+Math.abs(p.y-w.ty)))?a:b);const p=r.points[lane%r.points.length],[dx,dy]=vector[r.edge];w.tx=p.x+dx;w.ty=p.y+dy;}}return maps;}
