// 200 individually illustrated assets; native tile=16px, displayed tile=32px.
export const MATERIAL_GROUPS172={"vehicles":"車・乗り物","furniture":"いす・机・家具","storage":"収納・家電","street":"街・橋・設備","garden":"畑・市場の小物","crops":"野菜・作物","nature":"木・森の植物","dungeon":"岩・遺跡","minerals":"鉱石アイテム","food":"収穫アイテム"};
export const MATERIAL_PROPS172=[
  {
    "key": "material172-truck",
    "art": "material172-truck",
    "label": "青い配送トラック",
    "w": 3,
    "h": 2,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/truck.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-pickup-truck",
    "art": "material172-pickup-truck",
    "label": "木材運搬車",
    "w": 3,
    "h": 2,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/pickup-truck.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-van",
    "art": "material172-van",
    "label": "配送バン",
    "w": 3,
    "h": 2,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/van.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-compact-car",
    "art": "material172-compact-car",
    "label": "小型自動車",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/compact-car.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-jeep",
    "art": "material172-jeep",
    "label": "山道の四輪車",
    "w": 3,
    "h": 2,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/jeep.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-bus",
    "art": "material172-bus",
    "label": "町のバス",
    "w": 4,
    "h": 2,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/bus.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-tractor",
    "art": "material172-tractor",
    "label": "農場トラクター",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/tractor.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-cart",
    "art": "material172-cart",
    "label": "荷馬車",
    "w": 3,
    "h": 2,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/cart.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-handcart",
    "art": "material172-handcart",
    "label": "手押し荷車",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/handcart.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-bicycle",
    "art": "material172-bicycle",
    "label": "自転車",
    "w": 2,
    "h": 1,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/bicycle.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-scooter",
    "art": "material172-scooter",
    "label": "スクーター",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/scooter.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-motorbike",
    "art": "material172-motorbike",
    "label": "バイク",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/motorbike.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-rowboat",
    "art": "material172-rowboat",
    "label": "木のボート",
    "w": 2,
    "h": 3,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/rowboat.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-canoe",
    "art": "material172-canoe",
    "label": "カヌー",
    "w": 1,
    "h": 3,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/canoe.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-sailboat",
    "art": "material172-sailboat",
    "label": "帆の小舟",
    "w": 3,
    "h": 3,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/sailboat.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-fishingboat",
    "art": "material172-fishingboat",
    "label": "漁船",
    "w": 3,
    "h": 3,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/fishingboat.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-minecart",
    "art": "material172-minecart",
    "label": "トロッコ",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/minecart.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-wheelbarrow",
    "art": "material172-wheelbarrow",
    "label": "一輪車",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/wheelbarrow.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-sled",
    "art": "material172-sled",
    "label": "雪ぞり",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/sled.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-forklift",
    "art": "material172-forklift",
    "label": "荷役車",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "vehicles",
    "source": "village",
    "file": "assets/materials-v172/forklift.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-sofa",
    "art": "material172-sofa",
    "label": "ミントのソファ",
    "w": 2,
    "h": 1,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/sofa.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-armchair",
    "art": "material172-armchair",
    "label": "読書いす",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/armchair.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-rockingchair",
    "art": "material172-rockingchair",
    "label": "揺りいす",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/rockingchair.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-stool",
    "art": "material172-stool",
    "label": "丸いスツール",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/stool.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-diningchair",
    "art": "material172-diningchair",
    "label": "食卓いす",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/diningchair.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-officechair",
    "art": "material172-officechair",
    "label": "事務いす",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/officechair.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-bench",
    "art": "material172-bench",
    "label": "室内ベンチ",
    "w": 2,
    "h": 1,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/bench.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-roundtable",
    "art": "material172-roundtable",
    "label": "丸テーブル",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/roundtable.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-coffeetable",
    "art": "material172-coffeetable",
    "label": "低いテーブル",
    "w": 2,
    "h": 1,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/coffeetable.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-diningtable",
    "art": "material172-diningtable",
    "label": "食卓",
    "w": 3,
    "h": 2,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/diningtable.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-writingdesk",
    "art": "material172-writingdesk",
    "label": "書き物机",
    "w": 2,
    "h": 1,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/writingdesk.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-workbench",
    "art": "material172-workbench",
    "label": "作業台",
    "w": 2,
    "h": 1,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/workbench.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-singlebed",
    "art": "material172-singlebed",
    "label": "一人用ベッド",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/singlebed.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-bunkbed",
    "art": "material172-bunkbed",
    "label": "二段ベッド",
    "w": 2,
    "h": 3,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/bunkbed.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-crib",
    "art": "material172-crib",
    "label": "ゆりかご",
    "w": 2,
    "h": 1,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/crib.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-piano",
    "art": "material172-piano",
    "label": "アップライトピアノ",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/piano.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-clock",
    "art": "material172-clock",
    "label": "振り子時計",
    "w": 1,
    "h": 3,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/clock.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-mirror",
    "art": "material172-mirror",
    "label": "姿見",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/mirror.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-fireplace",
    "art": "material172-fireplace",
    "label": "暖炉",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/fireplace.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-coatstand",
    "art": "material172-coatstand",
    "label": "コート掛け",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "furniture",
    "source": "village",
    "file": "assets/materials-v172/coatstand.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-bookshelf",
    "art": "material172-bookshelf",
    "label": "小さな本棚",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/bookshelf.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-cabinet",
    "art": "material172-cabinet",
    "label": "食器棚",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/cabinet.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-wardrobe",
    "art": "material172-wardrobe",
    "label": "洋服だんす",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/wardrobe.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-drawers",
    "art": "material172-drawers",
    "label": "引き出し棚",
    "w": 2,
    "h": 1,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/drawers.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-chest",
    "art": "material172-chest",
    "label": "旅行かばん箱",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/chest.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-safe",
    "art": "material172-safe",
    "label": "金庫",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/safe.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-fridge",
    "art": "material172-fridge",
    "label": "冷蔵庫",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/fridge.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-stove",
    "art": "material172-stove",
    "label": "調理コンロ",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/stove.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-sink",
    "art": "material172-sink",
    "label": "流し台",
    "w": 2,
    "h": 1,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/sink.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-washingmachine",
    "art": "material172-washingmachine",
    "label": "洗濯機",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/washingmachine.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-oven",
    "art": "material172-oven",
    "label": "石焼きオーブン",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/oven.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-counter",
    "art": "material172-counter",
    "label": "店のカウンター",
    "w": 3,
    "h": 1,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/counter.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-register",
    "art": "material172-register",
    "label": "レジ",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/register.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-computer",
    "art": "material172-computer",
    "label": "卓上パソコン",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/computer.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-radio",
    "art": "material172-radio",
    "label": "ラジオ",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/radio.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-television",
    "art": "material172-television",
    "label": "テレビ",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/television.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-lamp",
    "art": "material172-lamp",
    "label": "卓上ランプ",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/lamp.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-aquarium",
    "art": "material172-aquarium",
    "label": "水槽",
    "w": 2,
    "h": 1,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/aquarium.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-medicinecabinet",
    "art": "material172-medicinecabinet",
    "label": "救急棚",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/medicinecabinet.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-shoe-rack",
    "art": "material172-shoe-rack",
    "label": "くつ棚",
    "w": 2,
    "h": 1,
    "group": "decor",
    "group172": "storage",
    "source": "village",
    "file": "assets/materials-v172/shoe-rack.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-stone-well",
    "art": "material172-stone-well",
    "label": "石の井戸",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/stone-well.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-wood-bridge",
    "art": "material172-wood-bridge",
    "label": "木の橋",
    "w": 3,
    "h": 4,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/wood-bridge.png",
    "walkable": true,
    "tile": "#",
    "mask": [
      "#.#",
      "#.#",
      "#.#",
      "#.#"
    ],
    "material172": true
  },
  {
    "key": "material172-stone-bridge",
    "art": "material172-stone-bridge",
    "label": "石の小橋",
    "w": 3,
    "h": 3,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/stone-bridge.png",
    "walkable": true,
    "tile": "#",
    "mask": [
      "#.#",
      "#.#",
      "#.#"
    ],
    "material172": true
  },
  {
    "key": "material172-lamp-post",
    "art": "material172-lamp-post",
    "label": "街灯",
    "w": 1,
    "h": 3,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/lamp-post.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-wood-lantern",
    "art": "material172-wood-lantern",
    "label": "木の灯り柱",
    "w": 1,
    "h": 3,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/wood-lantern.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-postbox",
    "art": "material172-postbox",
    "label": "郵便ポスト",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/postbox.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-noticeboard",
    "art": "material172-noticeboard",
    "label": "掲示板",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/noticeboard.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-fountain",
    "art": "material172-fountain",
    "label": "小噴水",
    "w": 3,
    "h": 3,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/fountain.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-park-bench",
    "art": "material172-park-bench",
    "label": "公園ベンチ",
    "w": 2,
    "h": 1,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/park-bench.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-trashcan",
    "art": "material172-trashcan",
    "label": "ごみ箱",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/trashcan.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-hydrant",
    "art": "material172-hydrant",
    "label": "消火栓",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/hydrant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-bollard",
    "art": "material172-bollard",
    "label": "港の係船柱",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/bollard.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-marketstall",
    "art": "material172-marketstall",
    "label": "青果屋台",
    "w": 3,
    "h": 3,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/marketstall.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-awningstall",
    "art": "material172-awningstall",
    "label": "雑貨屋台",
    "w": 3,
    "h": 3,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/awningstall.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-barrier",
    "art": "material172-barrier",
    "label": "通行止め柵",
    "w": 2,
    "h": 1,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/barrier.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-signpost",
    "art": "material172-signpost",
    "label": "道しるべ柱",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/signpost.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-waterpump",
    "art": "material172-waterpump",
    "label": "手押しポンプ",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/waterpump.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-phonebooth",
    "art": "material172-phonebooth",
    "label": "電話ボックス",
    "w": 1,
    "h": 3,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/phonebooth.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-clocktower",
    "art": "material172-clocktower",
    "label": "時計柱",
    "w": 2,
    "h": 4,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/clocktower.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-busstop",
    "art": "material172-busstop",
    "label": "バス停",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "street",
    "source": "village",
    "file": "assets/materials-v172/busstop.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-vegetable-crate",
    "art": "material172-vegetable-crate",
    "label": "野菜の木箱",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/vegetable-crate.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-fruit-basket",
    "art": "material172-fruit-basket",
    "label": "果物のかご",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/fruit-basket.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-flowerbox",
    "art": "material172-flowerbox",
    "label": "花の木箱",
    "w": 2,
    "h": 1,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/flowerbox.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-wateringcan",
    "art": "material172-wateringcan",
    "label": "じょうろ",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/wateringcan.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-barrel",
    "art": "material172-barrel",
    "label": "木のたる",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/barrel.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-waterbarrel",
    "art": "material172-waterbarrel",
    "label": "水のたる",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/waterbarrel.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-haybale",
    "art": "material172-haybale",
    "label": "干し草の束",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/haybale.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-haystack",
    "art": "material172-haystack",
    "label": "干し草の山",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/haystack.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-sacks",
    "art": "material172-sacks",
    "label": "穀物袋",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/sacks.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-firewood",
    "art": "material172-firewood",
    "label": "薪の束",
    "w": 2,
    "h": 1,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/firewood.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-logpile",
    "art": "material172-logpile",
    "label": "丸太の山",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/logpile.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-crate",
    "art": "material172-crate",
    "label": "空の木箱",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/crate.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-crate-stack",
    "art": "material172-crate-stack",
    "label": "積み木箱",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/crate-stack.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-claypot",
    "art": "material172-claypot",
    "label": "素焼きのつぼ",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/claypot.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-jar",
    "art": "material172-jar",
    "label": "ふた付きかめ",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/jar.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-scarecrow",
    "art": "material172-scarecrow",
    "label": "かかし",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/scarecrow.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-beehive",
    "art": "material172-beehive",
    "label": "養蜂箱",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/beehive.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-compost",
    "art": "material172-compost",
    "label": "たい肥箱",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/compost.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-trellis",
    "art": "material172-trellis",
    "label": "つる棚",
    "w": 2,
    "h": 3,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/trellis.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-birdhouse",
    "art": "material172-birdhouse",
    "label": "巣箱",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "garden",
    "source": "village",
    "file": "assets/materials-v172/birdhouse.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-tomato-plant",
    "art": "material172-tomato-plant",
    "label": "トマトの株",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/tomato-plant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-carrot-plant",
    "art": "material172-carrot-plant",
    "label": "ニンジンの株",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/carrot-plant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-corn-plant",
    "art": "material172-corn-plant",
    "label": "トウモロコシの株",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/corn-plant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-wheat-plant",
    "art": "material172-wheat-plant",
    "label": "小麦の株",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/wheat-plant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-cabbage-plant",
    "art": "material172-cabbage-plant",
    "label": "キャベツの株",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/cabbage-plant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-potato-plant",
    "art": "material172-potato-plant",
    "label": "ジャガイモの株",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/potato-plant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-pumpkin-plant",
    "art": "material172-pumpkin-plant",
    "label": "カボチャの株",
    "w": 2,
    "h": 1,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/pumpkin-plant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-eggplant-plant",
    "art": "material172-eggplant-plant",
    "label": "ナスの株",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/eggplant-plant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-pepper-plant",
    "art": "material172-pepper-plant",
    "label": "ピーマンの株",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/pepper-plant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-chili-plant",
    "art": "material172-chili-plant",
    "label": "トウガラシの株",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/chili-plant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-strawberry-plant",
    "art": "material172-strawberry-plant",
    "label": "イチゴの株",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/strawberry-plant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-blueberry-plant",
    "art": "material172-blueberry-plant",
    "label": "ブルーベリーの株",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/blueberry-plant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-grape-plant",
    "art": "material172-grape-plant",
    "label": "ブドウの棚",
    "w": 2,
    "h": 2,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/grape-plant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-cucumber-plant",
    "art": "material172-cucumber-plant",
    "label": "キュウリの株",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/cucumber-plant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-onion-plant",
    "art": "material172-onion-plant",
    "label": "タマネギの株",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/onion-plant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-turnip-plant",
    "art": "material172-turnip-plant",
    "label": "カブの株",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/turnip-plant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-lettuce-plant",
    "art": "material172-lettuce-plant",
    "label": "レタスの株",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/lettuce-plant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-sunflower",
    "art": "material172-sunflower",
    "label": "ヒマワリ",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/sunflower.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-cotton-plant",
    "art": "material172-cotton-plant",
    "label": "綿の株",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/cotton-plant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-tea-plant",
    "art": "material172-tea-plant",
    "label": "茶の低木",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "crops",
    "source": "village",
    "file": "assets/materials-v172/tea-plant.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-moss-log",
    "art": "material172-moss-log",
    "label": "苔の倒木",
    "w": 2,
    "h": 1,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/moss-log.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-oak-tree",
    "art": "material172-oak-tree",
    "label": "小さな広葉樹",
    "w": 2,
    "h": 3,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/oak-tree.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-birch-tree",
    "art": "material172-birch-tree",
    "label": "白樺",
    "w": 2,
    "h": 3,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/birch-tree.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-pine-tree",
    "art": "material172-pine-tree",
    "label": "若い針葉樹",
    "w": 2,
    "h": 3,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/pine-tree.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-snow-pine",
    "art": "material172-snow-pine",
    "label": "雪をかぶった木",
    "w": 2,
    "h": 3,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/snow-pine.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-dead-tree",
    "art": "material172-dead-tree",
    "label": "枯れ木",
    "w": 2,
    "h": 3,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/dead-tree.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-apple-tree",
    "art": "material172-apple-tree",
    "label": "リンゴの木",
    "w": 2,
    "h": 3,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/apple-tree.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-lemon-tree",
    "art": "material172-lemon-tree",
    "label": "レモンの木",
    "w": 2,
    "h": 3,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/lemon-tree.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-palm-tree",
    "art": "material172-palm-tree",
    "label": "小さなヤシ",
    "w": 2,
    "h": 3,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/palm-tree.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-stump",
    "art": "material172-stump",
    "label": "切り株",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/stump.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-root",
    "art": "material172-root",
    "label": "古い根",
    "w": 2,
    "h": 1,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/root.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-fern",
    "art": "material172-fern",
    "label": "森のシダ",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/fern.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-bamboo",
    "art": "material172-bamboo",
    "label": "若竹",
    "w": 1,
    "h": 3,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/bamboo.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-cactus",
    "art": "material172-cactus",
    "label": "柱サボテン",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/cactus.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-mushrooms",
    "art": "material172-mushrooms",
    "label": "茶色のキノコ",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/mushrooms.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-red-mushroom",
    "art": "material172-red-mushroom",
    "label": "赤いキノコ",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/red-mushroom.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-lily-pad",
    "art": "material172-lily-pad",
    "label": "スイレン",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/lily-pad.png",
    "walkable": true,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-reed",
    "art": "material172-reed",
    "label": "水辺のアシ",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/reed.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-berry-bush",
    "art": "material172-berry-bush",
    "label": "赤い実の茂み",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/berry-bush.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-flower-meadow",
    "art": "material172-flower-meadow",
    "label": "小さな野花",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "nature",
    "source": "village",
    "file": "assets/materials-v172/flower-meadow.png",
    "walkable": true,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-crystal-rock",
    "art": "material172-crystal-rock",
    "label": "青水晶の岩",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/crystal-rock.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-ruby-rock",
    "art": "material172-ruby-rock",
    "label": "紅玉の鉱脈",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/ruby-rock.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-gold-rock",
    "art": "material172-gold-rock",
    "label": "金の鉱脈",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/gold-rock.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-iron-rock",
    "art": "material172-iron-rock",
    "label": "鉄の鉱脈",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/iron-rock.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-coal-rock",
    "art": "material172-coal-rock",
    "label": "石炭の山",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/coal-rock.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-white-rock",
    "art": "material172-white-rock",
    "label": "白い岩塊",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/white-rock.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-basalt",
    "art": "material172-basalt",
    "label": "黒い岩塊",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/basalt.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-moss-rock",
    "art": "material172-moss-rock",
    "label": "苔の岩塊",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/moss-rock.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-rubble",
    "art": "material172-rubble",
    "label": "崩れた石",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/rubble.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-stalagmite",
    "art": "material172-stalagmite",
    "label": "石筍",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/stalagmite.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-pillar",
    "art": "material172-pillar",
    "label": "遺跡の柱",
    "w": 1,
    "h": 3,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/pillar.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-brokenpillar",
    "art": "material172-brokenpillar",
    "label": "折れた柱",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/brokenpillar.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-arch",
    "art": "material172-arch",
    "label": "石のアーチ",
    "w": 3,
    "h": 3,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/arch.png",
    "walkable": true,
    "tile": "#",
    "mask": [
      "###",
      "#.#",
      "#.#"
    ],
    "material172": true
  },
  {
    "key": "material172-statue",
    "art": "material172-statue",
    "label": "守り手の石像",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/statue.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-obelisk",
    "art": "material172-obelisk",
    "label": "古い石碑",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/obelisk.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-brazier",
    "art": "material172-brazier",
    "label": "火の台座",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/brazier.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-torch",
    "art": "material172-torch",
    "label": "たいまつ台",
    "w": 1,
    "h": 2,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/torch.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-chest-iron",
    "art": "material172-chest-iron",
    "label": "鉄張り宝箱",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/chest-iron.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-chest-gold",
    "art": "material172-chest-gold",
    "label": "金飾り宝箱",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/chest-gold.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  },
  {
    "key": "material172-rope-coil",
    "art": "material172-rope-coil",
    "label": "ロープの束",
    "w": 1,
    "h": 1,
    "group": "decor",
    "group172": "dungeon",
    "source": "village",
    "file": "assets/materials-v172/rope-coil.png",
    "walkable": false,
    "tile": "#",
    "material172": true
  }
];
export const MATERIAL_ITEMS172=[
  {
    "name": "ルビーの原石",
    "english": "Three red ruby crystals",
    "file": "assets/materials-v172/ruby.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 4000,
    "desc": "ショップで2000円で売れる鉱物。"
  },
  {
    "name": "サファイア",
    "english": "Faceted blue sapphire",
    "file": "assets/materials-v172/sapphire.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 6000,
    "desc": "ショップで3000円で売れる鉱物。"
  },
  {
    "name": "エメラルド",
    "english": "Green emerald crystal",
    "file": "assets/materials-v172/emerald.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 8000,
    "desc": "ショップで4000円で売れる鉱物。"
  },
  {
    "name": "アメシスト",
    "english": "Purple amethyst crystal",
    "file": "assets/materials-v172/amethyst.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 10000,
    "desc": "ショップで5000円で売れる鉱物。"
  },
  {
    "name": "オパール",
    "english": "Iridescent oval opal",
    "file": "assets/materials-v172/opal.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 12000,
    "desc": "ショップで6000円で売れる鉱物。"
  },
  {
    "name": "トパーズ",
    "english": "Amber yellow topaz",
    "file": "assets/materials-v172/topaz.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 4000,
    "desc": "ショップで2000円で売れる鉱物。"
  },
  {
    "name": "真珠",
    "english": "Single cream pearl",
    "file": "assets/materials-v172/pearl.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 6000,
    "desc": "ショップで3000円で売れる鉱物。"
  },
  {
    "name": "黒曜石",
    "english": "Sharp black obsidian shard",
    "file": "assets/materials-v172/obsidian.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 8000,
    "desc": "ショップで4000円で売れる鉱物。"
  },
  {
    "name": "水晶",
    "english": "Cluster of clear white quartz",
    "file": "assets/materials-v172/quartz.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 10000,
    "desc": "ショップで5000円で売れる鉱物。"
  },
  {
    "name": "紅水晶",
    "english": "Pink quartz cluster",
    "file": "assets/materials-v172/rose-quartz.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 12000,
    "desc": "ショップで6000円で売れる鉱物。"
  },
  {
    "name": "アクアマリン",
    "english": "Pale blue aquamarine crystal",
    "file": "assets/materials-v172/aquamarine.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 4000,
    "desc": "ショップで2000円で売れる鉱物。"
  },
  {
    "name": "ヒスイ",
    "english": "Smooth jade green stone",
    "file": "assets/materials-v172/jade.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 6000,
    "desc": "ショップで3000円で売れる鉱物。"
  },
  {
    "name": "ガーネット",
    "english": "Dark red garnet stone",
    "file": "assets/materials-v172/garnet.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 8000,
    "desc": "ショップで4000円で売れる鉱物。"
  },
  {
    "name": "トルコ石",
    "english": "Turquoise blue rough stone",
    "file": "assets/materials-v172/turquoise.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 10000,
    "desc": "ショップで5000円で売れる鉱物。"
  },
  {
    "name": "月長石",
    "english": "Pale luminous moonstone",
    "file": "assets/materials-v172/moonstone.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 12000,
    "desc": "ショップで6000円で売れる鉱物。"
  },
  {
    "name": "銀のインゴット",
    "english": "Small silver metal ingot",
    "file": "assets/materials-v172/silver-ingot.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 4000,
    "desc": "ショップで2000円で売れる鉱物。"
  },
  {
    "name": "金のインゴット",
    "english": "Small gold ingot",
    "file": "assets/materials-v172/gold-ingot.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 6000,
    "desc": "ショップで3000円で売れる鉱物。"
  },
  {
    "name": "銅のインゴット",
    "english": "Small copper ingot",
    "file": "assets/materials-v172/copper-ingot.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 8000,
    "desc": "ショップで4000円で売れる鉱物。"
  },
  {
    "name": "貝の化石",
    "english": "Spiral shell fossil in stone",
    "file": "assets/materials-v172/fossil-shell.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 10000,
    "desc": "ショップで5000円で売れる鉱物。"
  },
  {
    "name": "虫入りこはく",
    "english": "Golden amber with tiny insect silhouette",
    "file": "assets/materials-v172/amber.png",
    "group172": "minerals",
    "kind": "treasure",
    "price": 12000,
    "desc": "ショップで6000円で売れる鉱物。"
  },
  {
    "name": "畑のトマト",
    "english": "Ripe red tomato green calyx",
    "file": "assets/materials-v172/tomato.png",
    "group172": "food",
    "kind": "heal",
    "price": 200,
    "amount": 40,
    "desc": "ガオンのHPを40回復する収穫物。"
  },
  {
    "name": "畑のニンジン",
    "english": "Orange carrot with green tops",
    "file": "assets/materials-v172/carrot.png",
    "group172": "food",
    "kind": "heal",
    "price": 300,
    "amount": 20,
    "desc": "ガオンのHPを20回復する収穫物。"
  },
  {
    "name": "畑のトウモロコシ",
    "english": "Yellow corn cob with husk",
    "file": "assets/materials-v172/corn.png",
    "group172": "food",
    "kind": "heal",
    "price": 400,
    "amount": 30,
    "desc": "ガオンのHPを30回復する収穫物。"
  },
  {
    "name": "畑のジャガイモ",
    "english": "Two golden potatoes",
    "file": "assets/materials-v172/potato.png",
    "group172": "food",
    "kind": "heal",
    "price": 500,
    "amount": 40,
    "desc": "ガオンのHPを40回復する収穫物。"
  },
  {
    "name": "畑のカボチャ",
    "english": "Small orange pumpkin",
    "file": "assets/materials-v172/pumpkin.png",
    "group172": "food",
    "kind": "heal",
    "price": 200,
    "amount": 20,
    "desc": "ガオンのHPを20回復する収穫物。"
  },
  {
    "name": "畑のキャベツ",
    "english": "Green cabbage head",
    "file": "assets/materials-v172/cabbage.png",
    "group172": "food",
    "kind": "heal",
    "price": 300,
    "amount": 30,
    "desc": "ガオンのHPを30回復する収穫物。"
  },
  {
    "name": "畑のナス",
    "english": "Purple eggplant",
    "file": "assets/materials-v172/eggplant.png",
    "group172": "food",
    "kind": "heal",
    "price": 400,
    "amount": 40,
    "desc": "ガオンのHPを40回復する収穫物。"
  },
  {
    "name": "畑のピーマン",
    "english": "Green bell pepper",
    "file": "assets/materials-v172/pepper.png",
    "group172": "food",
    "kind": "heal",
    "price": 500,
    "amount": 20,
    "desc": "ガオンのHPを20回復する収穫物。"
  },
  {
    "name": "畑のイチゴ",
    "english": "Two red strawberries",
    "file": "assets/materials-v172/strawberry.png",
    "group172": "food",
    "kind": "heal",
    "price": 200,
    "amount": 30,
    "desc": "ガオンのHPを30回復する収穫物。"
  },
  {
    "name": "畑のブルーベリー",
    "english": "Small cluster of blueberries",
    "file": "assets/materials-v172/blueberry.png",
    "group172": "food",
    "kind": "heal",
    "price": 300,
    "amount": 40,
    "desc": "ガオンのHPを40回復する収穫物。"
  },
  {
    "name": "畑のブドウ",
    "english": "Purple grape bunch",
    "file": "assets/materials-v172/grapes.png",
    "group172": "food",
    "kind": "heal",
    "price": 400,
    "amount": 20,
    "desc": "ガオンのHPを20回復する収穫物。"
  },
  {
    "name": "畑のリンゴ",
    "english": "Shiny red apple",
    "file": "assets/materials-v172/apple.png",
    "group172": "food",
    "kind": "heal",
    "price": 500,
    "amount": 30,
    "desc": "ガオンのHPを30回復する収穫物。"
  },
  {
    "name": "畑のレモン",
    "english": "Yellow lemon green leaf",
    "file": "assets/materials-v172/lemon.png",
    "group172": "food",
    "kind": "heal",
    "price": 200,
    "amount": 40,
    "desc": "ガオンのHPを40回復する収穫物。"
  },
  {
    "name": "畑のモモ",
    "english": "Pink peach",
    "file": "assets/materials-v172/peach.png",
    "group172": "food",
    "kind": "heal",
    "price": 300,
    "amount": 20,
    "desc": "ガオンのHPを20回復する収穫物。"
  },
  {
    "name": "畑のバナナ",
    "english": "Small bunch of bananas",
    "file": "assets/materials-v172/banana.png",
    "group172": "food",
    "kind": "heal",
    "price": 400,
    "amount": 30,
    "desc": "ガオンのHPを30回復する収穫物。"
  },
  {
    "name": "畑のパイナップル",
    "english": "Small pineapple",
    "file": "assets/materials-v172/pineapple.png",
    "group172": "food",
    "kind": "heal",
    "price": 500,
    "amount": 40,
    "desc": "ガオンのHPを40回復する収穫物。"
  },
  {
    "name": "森のキノコ",
    "english": "Brown edible mushroom",
    "file": "assets/materials-v172/mushroom.png",
    "group172": "food",
    "kind": "heal",
    "price": 200,
    "amount": 20,
    "desc": "ガオンのHPを20回復する収穫物。"
  },
  {
    "name": "小麦の束",
    "english": "Tied sheaf of wheat",
    "file": "assets/materials-v172/wheat.png",
    "group172": "food",
    "kind": "heal",
    "price": 300,
    "amount": 30,
    "desc": "ガオンのHPを30回復する収穫物。"
  },
  {
    "name": "森のはちみつ",
    "english": "Small glass honey jar",
    "file": "assets/materials-v172/honey.png",
    "group172": "food",
    "kind": "heal",
    "price": 400,
    "amount": 40,
    "desc": "ガオンのHPを40回復する収穫物。"
  },
  {
    "name": "茶葉の袋",
    "english": "Small green bag of tea leaves",
    "file": "assets/materials-v172/tea.png",
    "group172": "food",
    "kind": "heal",
    "price": 500,
    "amount": 20,
    "desc": "ガオンのHPを20回復する収穫物。"
  }
];
