export const MATERIALS123=[
  {
    "key": "tower-floor123",
    "art": "tower-floor123",
    "label": "タワー・床",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": true,
    "tile": "f",
    "indoor": true,
    "file": "assets/interiors-v123/tower-floor123.png"
  },
  {
    "key": "tower-accent123",
    "art": "tower-accent123",
    "label": "タワー・模様の床",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": true,
    "tile": "f",
    "indoor": true,
    "file": "assets/interiors-v123/tower-accent123.png"
  },
  {
    "key": "tower-wall123",
    "art": "tower-wall123",
    "label": "タワー・壁",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": "X",
    "indoor": true,
    "file": "assets/interiors-v123/tower-wall123.png"
  },
  {
    "key": "tower-panel123",
    "art": "tower-panel123",
    "label": "タワー・飾り壁",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": "X",
    "indoor": true,
    "file": "assets/interiors-v123/tower-panel123.png"
  },
  {
    "key": "galaxy-floor123",
    "art": "galaxy-floor123",
    "label": "ギャラクシー・床",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": true,
    "tile": "f",
    "indoor": true,
    "file": "assets/interiors-v123/galaxy-floor123.png"
  },
  {
    "key": "galaxy-accent123",
    "art": "galaxy-accent123",
    "label": "ギャラクシー・模様の床",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": true,
    "tile": "f",
    "indoor": true,
    "file": "assets/interiors-v123/galaxy-accent123.png"
  },
  {
    "key": "galaxy-wall123",
    "art": "galaxy-wall123",
    "label": "ギャラクシー・壁",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": "X",
    "indoor": true,
    "file": "assets/interiors-v123/galaxy-wall123.png"
  },
  {
    "key": "galaxy-panel123",
    "art": "galaxy-panel123",
    "label": "ギャラクシー・飾り壁",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": "X",
    "indoor": true,
    "file": "assets/interiors-v123/galaxy-panel123.png"
  },
  {
    "key": "ruin-floor123",
    "art": "ruin-floor123",
    "label": "廃墟・床",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": true,
    "tile": "f",
    "indoor": true,
    "file": "assets/interiors-v123/ruin-floor123.png"
  },
  {
    "key": "ruin-accent123",
    "art": "ruin-accent123",
    "label": "廃墟・模様の床",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": true,
    "tile": "f",
    "indoor": true,
    "file": "assets/interiors-v123/ruin-accent123.png"
  },
  {
    "key": "ruin-wall123",
    "art": "ruin-wall123",
    "label": "廃墟・壁",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": "X",
    "indoor": true,
    "file": "assets/interiors-v123/ruin-wall123.png"
  },
  {
    "key": "ruin-panel123",
    "art": "ruin-panel123",
    "label": "廃墟・飾り壁",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": "X",
    "indoor": true,
    "file": "assets/interiors-v123/ruin-panel123.png"
  },
  {
    "key": "ship-floor123",
    "art": "ship-floor123",
    "label": "船内・床",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": true,
    "tile": "f",
    "indoor": true,
    "file": "assets/interiors-v123/ship-floor123.png"
  },
  {
    "key": "ship-accent123",
    "art": "ship-accent123",
    "label": "船内・模様の床",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": true,
    "tile": "f",
    "indoor": true,
    "file": "assets/interiors-v123/ship-accent123.png"
  },
  {
    "key": "ship-wall123",
    "art": "ship-wall123",
    "label": "船内・壁",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": "X",
    "indoor": true,
    "file": "assets/interiors-v123/ship-wall123.png"
  },
  {
    "key": "ship-panel123",
    "art": "ship-panel123",
    "label": "船内・飾り壁",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": "X",
    "indoor": true,
    "file": "assets/interiors-v123/ship-panel123.png"
  }
];
