import {MATERIALS123} from './materials123.mjs';
const MATERIALS=[
  {
    "key": "nature73-grass-spring-short",
    "art": "nature73-grass-spring-short",
    "name": "grass-spring-short",
    "label": "春の草むら・短い",
    "w": 1,
    "h": 1,
    "group": "grass",
    "walkable": true,
    "tile": "\"",
    "source": "village",
    "file": "assets/nature-v73/grass-spring-short.png"
  },
  {
    "key": "nature73-grass-spring-medium",
    "art": "nature73-grass-spring-medium",
    "name": "grass-spring-medium",
    "label": "春の草むら・ふつう",
    "w": 1,
    "h": 1,
    "group": "grass",
    "walkable": true,
    "tile": "\"",
    "source": "village",
    "file": "assets/nature-v73/grass-spring-medium.png"
  },
  {
    "key": "nature73-grass-spring-long",
    "art": "nature73-grass-spring-long",
    "name": "grass-spring-long",
    "label": "春の草むら・長い",
    "w": 1,
    "h": 1,
    "group": "grass",
    "walkable": true,
    "tile": "\"",
    "source": "village",
    "file": "assets/nature-v73/grass-spring-long.png"
  },
  {
    "key": "nature73-grass-summer-short",
    "art": "nature73-grass-summer-short",
    "name": "grass-summer-short",
    "label": "夏の草むら・短い",
    "w": 1,
    "h": 1,
    "group": "grass",
    "walkable": true,
    "tile": "\"",
    "source": "village",
    "file": "assets/nature-v73/grass-summer-short.png"
  },
  {
    "key": "nature73-grass-summer-medium",
    "art": "nature73-grass-summer-medium",
    "name": "grass-summer-medium",
    "label": "夏の草むら・ふつう",
    "w": 1,
    "h": 1,
    "group": "grass",
    "walkable": true,
    "tile": "\"",
    "source": "village",
    "file": "assets/nature-v73/grass-summer-medium.png"
  },
  {
    "key": "nature73-grass-summer-long",
    "art": "nature73-grass-summer-long",
    "name": "grass-summer-long",
    "label": "夏の草むら・長い",
    "w": 1,
    "h": 1,
    "group": "grass",
    "walkable": true,
    "tile": "\"",
    "source": "village",
    "file": "assets/nature-v73/grass-summer-long.png"
  },
  {
    "key": "nature73-grass-autumn-short",
    "art": "nature73-grass-autumn-short",
    "name": "grass-autumn-short",
    "label": "秋の草むら・短い",
    "w": 1,
    "h": 1,
    "group": "grass",
    "walkable": true,
    "tile": "\"",
    "source": "village",
    "file": "assets/nature-v73/grass-autumn-short.png"
  },
  {
    "key": "nature73-grass-autumn-medium",
    "art": "nature73-grass-autumn-medium",
    "name": "grass-autumn-medium",
    "label": "秋の草むら・ふつう",
    "w": 1,
    "h": 1,
    "group": "grass",
    "walkable": true,
    "tile": "\"",
    "source": "village",
    "file": "assets/nature-v73/grass-autumn-medium.png"
  },
  {
    "key": "nature73-grass-autumn-long",
    "art": "nature73-grass-autumn-long",
    "name": "grass-autumn-long",
    "label": "秋の草むら・長い",
    "w": 1,
    "h": 1,
    "group": "grass",
    "walkable": true,
    "tile": "\"",
    "source": "village",
    "file": "assets/nature-v73/grass-autumn-long.png"
  },
  {
    "key": "nature73-grass-winter-short",
    "art": "nature73-grass-winter-short",
    "name": "grass-winter-short",
    "label": "冬の草むら・短い",
    "w": 1,
    "h": 1,
    "group": "grass",
    "walkable": true,
    "tile": "\"",
    "source": "village",
    "file": "assets/nature-v73/grass-winter-short.png"
  },
  {
    "key": "nature73-grass-winter-medium",
    "art": "nature73-grass-winter-medium",
    "name": "grass-winter-medium",
    "label": "冬の草むら・ふつう",
    "w": 1,
    "h": 1,
    "group": "grass",
    "walkable": true,
    "tile": "\"",
    "source": "village",
    "file": "assets/nature-v73/grass-winter-medium.png"
  },
  {
    "key": "nature73-grass-winter-long",
    "art": "nature73-grass-winter-long",
    "name": "grass-winter-long",
    "label": "冬の草むら・長い",
    "w": 1,
    "h": 1,
    "group": "grass",
    "walkable": true,
    "tile": "\"",
    "source": "village",
    "file": "assets/nature-v73/grass-winter-long.png"
  },
  {
    "key": "nature73-flowers-white",
    "art": "nature73-flowers-white",
    "name": "flowers-white",
    "label": "白の花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-white.png"
  },
  {
    "key": "nature73-flowers-cream",
    "art": "nature73-flowers-cream",
    "name": "flowers-cream",
    "label": "クリームの花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-cream.png"
  },
  {
    "key": "nature73-flowers-lemon",
    "art": "nature73-flowers-lemon",
    "name": "flowers-lemon",
    "label": "レモンの花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-lemon.png"
  },
  {
    "key": "nature73-flowers-gold",
    "art": "nature73-flowers-gold",
    "name": "flowers-gold",
    "label": "黄金の花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-gold.png"
  },
  {
    "key": "nature73-flowers-orange",
    "art": "nature73-flowers-orange",
    "name": "flowers-orange",
    "label": "オレンジの花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-orange.png"
  },
  {
    "key": "nature73-flowers-coral",
    "art": "nature73-flowers-coral",
    "name": "flowers-coral",
    "label": "珊瑚の花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-coral.png"
  },
  {
    "key": "nature73-flowers-red",
    "art": "nature73-flowers-red",
    "name": "flowers-red",
    "label": "赤の花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-red.png"
  },
  {
    "key": "nature73-flowers-crimson",
    "art": "nature73-flowers-crimson",
    "name": "flowers-crimson",
    "label": "深紅の花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-crimson.png"
  },
  {
    "key": "nature73-flowers-pink",
    "art": "nature73-flowers-pink",
    "name": "flowers-pink",
    "label": "ピンクの花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-pink.png"
  },
  {
    "key": "nature73-flowers-rose",
    "art": "nature73-flowers-rose",
    "name": "flowers-rose",
    "label": "ローズの花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-rose.png"
  },
  {
    "key": "nature73-flowers-magenta",
    "art": "nature73-flowers-magenta",
    "name": "flowers-magenta",
    "label": "マゼンタの花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-magenta.png"
  },
  {
    "key": "nature73-flowers-lavender",
    "art": "nature73-flowers-lavender",
    "name": "flowers-lavender",
    "label": "ラベンダーの花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-lavender.png"
  },
  {
    "key": "nature73-flowers-purple",
    "art": "nature73-flowers-purple",
    "name": "flowers-purple",
    "label": "紫の花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-purple.png"
  },
  {
    "key": "nature73-flowers-violet",
    "art": "nature73-flowers-violet",
    "name": "flowers-violet",
    "label": "すみれの花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-violet.png"
  },
  {
    "key": "nature73-flowers-sky",
    "art": "nature73-flowers-sky",
    "name": "flowers-sky",
    "label": "水色の花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-sky.png"
  },
  {
    "key": "nature73-flowers-blue",
    "art": "nature73-flowers-blue",
    "name": "flowers-blue",
    "label": "青の花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-blue.png"
  },
  {
    "key": "nature73-flowers-teal",
    "art": "nature73-flowers-teal",
    "name": "flowers-teal",
    "label": "青緑の花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-teal.png"
  },
  {
    "key": "nature73-flowers-lime",
    "art": "nature73-flowers-lime",
    "name": "flowers-lime",
    "label": "黄緑の花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-lime.png"
  },
  {
    "key": "nature73-flowers-peach",
    "art": "nature73-flowers-peach",
    "name": "flowers-peach",
    "label": "桃の花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-peach.png"
  },
  {
    "key": "nature73-flowers-rainbow",
    "art": "nature73-flowers-rainbow",
    "name": "flowers-rainbow",
    "label": "虹色の花畑",
    "w": 1,
    "h": 1,
    "group": "flower",
    "walkable": true,
    "tile": ",",
    "source": "village",
    "file": "assets/nature-v73/flowers-rainbow.png"
  },
  {
    "key": "nature73-rock-gray-small",
    "art": "nature73-rock-gray-small",
    "name": "rock-gray-small",
    "label": "灰の石（1マス）",
    "w": 1,
    "h": 1,
    "group": "rock",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/rock-gray-small.png"
  },
  {
    "key": "nature73-rock-gray-large",
    "art": "nature73-rock-gray-large",
    "name": "rock-gray-large",
    "label": "灰の大岩（2×2）",
    "w": 2,
    "h": 2,
    "group": "rock",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/rock-gray-large.png"
  },
  {
    "key": "nature73-rock-white-small",
    "art": "nature73-rock-white-small",
    "name": "rock-white-small",
    "label": "白の石（1マス）",
    "w": 1,
    "h": 1,
    "group": "rock",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/rock-white-small.png"
  },
  {
    "key": "nature73-rock-white-large",
    "art": "nature73-rock-white-large",
    "name": "rock-white-large",
    "label": "白の大岩（2×2）",
    "w": 2,
    "h": 2,
    "group": "rock",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/rock-white-large.png"
  },
  {
    "key": "nature73-rock-brown-small",
    "art": "nature73-rock-brown-small",
    "name": "rock-brown-small",
    "label": "茶の石（1マス）",
    "w": 1,
    "h": 1,
    "group": "rock",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/rock-brown-small.png"
  },
  {
    "key": "nature73-rock-brown-large",
    "art": "nature73-rock-brown-large",
    "name": "rock-brown-large",
    "label": "茶の大岩（2×2）",
    "w": 2,
    "h": 2,
    "group": "rock",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/rock-brown-large.png"
  },
  {
    "key": "nature73-rock-ochre-small",
    "art": "nature73-rock-ochre-small",
    "name": "rock-ochre-small",
    "label": "黄土の石（1マス）",
    "w": 1,
    "h": 1,
    "group": "rock",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/rock-ochre-small.png"
  },
  {
    "key": "nature73-rock-ochre-large",
    "art": "nature73-rock-ochre-large",
    "name": "rock-ochre-large",
    "label": "黄土の大岩（2×2）",
    "w": 2,
    "h": 2,
    "group": "rock",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/rock-ochre-large.png"
  },
  {
    "key": "nature73-rock-red-small",
    "art": "nature73-rock-red-small",
    "name": "rock-red-small",
    "label": "赤の石（1マス）",
    "w": 1,
    "h": 1,
    "group": "rock",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/rock-red-small.png"
  },
  {
    "key": "nature73-rock-red-large",
    "art": "nature73-rock-red-large",
    "name": "rock-red-large",
    "label": "赤の大岩（2×2）",
    "w": 2,
    "h": 2,
    "group": "rock",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/rock-red-large.png"
  },
  {
    "key": "nature73-rock-black-small",
    "art": "nature73-rock-black-small",
    "name": "rock-black-small",
    "label": "黒の石（1マス）",
    "w": 1,
    "h": 1,
    "group": "rock",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/rock-black-small.png"
  },
  {
    "key": "nature73-rock-black-large",
    "art": "nature73-rock-black-large",
    "name": "rock-black-large",
    "label": "黒の大岩（2×2）",
    "w": 2,
    "h": 2,
    "group": "rock",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/rock-black-large.png"
  },
  {
    "key": "nature73-path-meadow",
    "art": "nature73-path-meadow",
    "name": "path-meadow",
    "label": "草原",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/path-meadow.png"
  },
  {
    "key": "nature73-path-brick",
    "art": "nature73-path-brick",
    "name": "path-brick",
    "label": "レンガ",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/path-brick.png"
  },
  {
    "key": "nature73-path-soil",
    "art": "nature73-path-soil",
    "name": "path-soil",
    "label": "土",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/path-soil.png"
  },
  {
    "key": "nature73-path-sand",
    "art": "nature73-path-sand",
    "name": "path-sand",
    "label": "砂",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/path-sand.png"
  },
  {
    "key": "nature73-path-tile",
    "art": "nature73-path-tile",
    "name": "path-tile",
    "label": "タイル",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/path-tile.png"
  },
  {
    "key": "nature73-path-road",
    "art": "nature73-path-road",
    "name": "path-road",
    "label": "舗装道路",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/path-road.png"
  },
  {
    "key": "nature73-path-europe",
    "art": "nature73-path-europe",
    "name": "path-europe",
    "label": "ヨーロッパの石畳",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/path-europe.png"
  },
  {
    "key": "nature73-path-swiss",
    "art": "nature73-path-swiss",
    "name": "path-swiss",
    "label": "スイスの山村",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/path-swiss.png"
  },
  {
    "key": "nature73-path-africa",
    "art": "nature73-path-africa",
    "name": "path-africa",
    "label": "サヘルの土の道",
    "w": 1,
    "h": 1,
    "group": "floor",
    "walkable": false,
    "tile": ".",
    "source": "village",
    "file": "assets/nature-v73/path-africa.png"
  }
];

export const NATURE73=[...MATERIALS123,...MATERIALS].map(p=>p.group==='rock'?{...p,tile:'#'}:p);
