import {drawReadable84} from './readableArt84.js';
import {REFERENCE78} from './referenceCatalog78.mjs';
import {EXTRA75} from './extraCatalog75.mjs';
import {PATHS75,OBJECTS75} from './gardenCatalog75.mjs';
import {NATURE73} from './natureCatalog73.mjs';
import {LEGACY73} from './legacyCatalog73.mjs';
const defs=[...NATURE73,...LEGACY73,...PATHS75,...OBJECTS75,...EXTRA75,...REFERENCE78],images=new Map();
function get(key){const d=defs.find(d=>d.key===key);if(!d)return null;let im=images.get(key);if(!im){im=new Image();im.src=new URL('../'+d.file,import.meta.url).href;images.set(key,im);}return im;}
export function natureReady73(map){return [...(map.editorGround72||[]),...(map.elevations75?.length?[{material:"garden75-extra-cliff"}]:[]),...(map.room?.furniture||[]).filter(f=>f[0].startsWith('reference78-')).map(f=>({material:f[0]})),...(map.climbs75||[]).map(l=>({material:"garden75-extra-"+l.kind}))].every(t=>{const im=get(t.material);return !im||im.complete&&im.naturalWidth>0;});}
export function drawNature73(c,key,x,y,w,h){if(drawReadable84(c,key,x,y,w,h))return true;const im=get(key);if(!im)return false;if(!im.complete||!im.naturalWidth)return true;c.imageSmoothingEnabled=false;const d=defs.find(d=>d.key===key);if(d.group==='floor'){c.save();c.translate(x+w/2,y+h/2);c.rotate((d.rotation||0)*Math.PI/2);if(d.shape81){c.beginPath();if(d.shape81==='edge'){c.moveTo(-w/2,-h/2+6);for(let i=0;i<=8;i++)c.lineTo(-w/2+i*w/8,-h/2+[6,4,7,3][i%4]);c.lineTo(w/2,h/2);c.lineTo(-w/2,h/2);}else if(d.shape81==='corner'){c.roundRect(-w/2,-h/2,w,h,[w*.42,0,0,0]);}else{c.rect(-w/2,-h/2,w,h);c.moveTo(-w/2,-h/2);c.lineTo(-w/2,-h/2+h*.32);c.quadraticCurveTo(-w/2+w*.32,-h/2+h*.32,-w/2+w*.32,-h/2);c.closePath();}c.clip('evenodd');}c.drawImage(im,-w/2,-h/2,w,h);c.restore();}else if(d.group==='grass'&&key.endsWith('-long')){for(let i=0;i<3;i++){const hh=h*(i===1?1.25:1.05),ww=hh*im.naturalWidth/im.naturalHeight;c.drawImage(im,x+i*w/3+(w/3-ww)/2,y+h-hh,ww,hh);}}else{const maxH=d.group==='grass'?h*(key.endsWith('-short')?.55:key.endsWith('-long')?1.25:.85):h;const scale=Math.min(w/im.naturalWidth,maxH/im.naturalHeight),dw=im.naturalWidth*scale,dh=im.naturalHeight*scale;c.drawImage(im,x+(w-dw)/2,y+h-dh,dw,dh);}return true;}
