export const NEW_PEOPLE119=['青い服の旅人','黄色い服の旅人','雪山の旅人（黒）','雪山の旅人（紫）','赤い服の登山家','青い服の登山家','ぼうしの子供','湖のハイカー','ニット帽の旅行者','民族衣装の男性（黒）','民族衣装の男性（赤）','民族衣装のおじいさん','民族衣装の女性（青）','民族衣装の女性（紫）','民族衣装の女性（赤）','ピンクの旅人','ワークジャケットの男性','黒いTシャツの男性','白いTシャツの男性','濃緑のポロシャツの男性'];
export const HAIRSTYLES119={boy:[['default','もとの髪型'],['mohawk','モヒカン'],['buzz','坊主'],['undercut','ツーブロック'],['center','センターパート'],['mushroom','マッシュ'],['crop','短髪'],['short','ショート'],['medium','ミディアム'],['long','ロング'],['swept','かき上げショート'],['spiky','スパイキーショート'],['wave','ウェーブセンター']],girl:[['default','もとの髪型'],['long','ロング'],['c-curl','Cカール'],['twintails','ツインテール'],['ponytail','ポニーテール'],['bun','お団子'],['techno','テクノカット'],['bob','ボブ'],['center','センター分け'],['side-bob','サイド分けボブ'],['ear-short','耳かけショート'],['flip-bob','外はねボブ'],['blunt-bob','ぱっつんボブ']]};
export const PALETTES119=[['original','もとの色'],['red-black','赤・黒髪'],['green-blond','緑・金髪'],['teal-silver','青緑・銀髪'],['purple-brown','紫・茶髪'],['orange-black','橙・黒髪'],['navy-auburn','紺・赤茶髪'],['cream-ash','白・灰茶髪'],['pink-platinum','桃・白金髪'],['charcoal-copper','黒・銅色髪']];
export const PALETTE_BASES119=[['winter-boy','冬の旅人（男）',34],['winter-girl','冬の旅人（女）',35],['bard','音楽家',19],['explorer','探検家',14],['florist','花屋さん',10]];
export const GIRL_VARIANTS119=['紺のロング','緑のポニーテール','黄のツインテール','紫のCカール','青緑のお団子','桃のセンター分け','白の耳かけショート','深紅のぱっつんボブ','水色の外はねボブ','橙の三つ編み'];
export const ADDITIONAL_PEOPLE119=[...NEW_PEOPLE119.map((label,i)=>({label,key:'new-'+i})),...PALETTE_BASES119.flatMap(([base,label])=>PALETTES119.slice(1).map(([color,name])=>({label:label+'（'+name+'）',key:'palette-'+base+'-'+color}))),...GIRL_VARIANTS119.map((label,i)=>({label:'冒険少女（'+label+'）',key:'girl-variant-'+String(i+1).padStart(2,'0')})),{label:'ヤノケン',key:'yanoken'},{label:'ライバル（迷彩ジャケット）',key:'rival-camo'},...['女の子の霊','おじいさんの霊','白い服の長髪の霊'].map((label,i)=>({label,key:'ghost139-'+['girl','elder','white'][i]}))];
export function personKey119(variant){return Number.isInteger(variant)&&variant>=34?ADDITIONAL_PEOPLE119[variant-34]?.key:variant>=0&&variant<34?'npc-'+String(variant).padStart(2,'0'):null;}
export function battleKey119(variant){const base=PALETTE_BASES119.find(b=>b[2]===variant);return base?'palette-'+base[0]+'-original':personKey119(variant);}
export const OUTFITS119=[['default','いつもの服'],...NEW_PEOPLE119.map((label,i)=>['new-'+i,label])];
