import {personKey119,battleKey119,HAIRSTYLES119,OUTFITS119} from './peopleCatalog119.mjs';
import {dressHero} from './fashionArt.js';
const sheets=new Map(),frames=new Map();
function asset(key,battle=false){const id=(battle?'battle/':'map/')+key;if(!sheets.has(id)){const im=new Image();im.src=new URL('../assets/people-v119/'+id+'.png',import.meta.url).href;sheets.set(id,im);}return sheets.get(id);}
export function sheetFrame119(key,dir='down',step=1){if(!key)return null;const id=key+':'+dir+':'+step;if(frames.has(id))return frames.get(id);const im=asset(key);if(!im.complete||!im.naturalWidth)return null;const c=document.createElement('canvas');c.width=32;c.height=48;const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.drawImage(im,({down:0,left:1,right:2,up:3}[dir]??0)*32,Math.max(0,Math.min(2,step))*48,32,48,0,0,32,48);frames.set(id,c);return c;}
export function mapPerson119(n,step=1){const key=n.eden?'eden':n.name==='ヤノケン'||['v5:dex','voyage:yanoken','frontier:yanoken'].includes(n.script)?'yanoken':Number.isInteger(n.winterVariant)?'winter-'+n.winterVariant:personKey119(Number.isInteger(n.variant)?n.variant:n.script==='v5:mother'?7:({boy:0,girl:1,prof:2,oldman:3,nurse:4,clerk:5,hiker:6,sailor:12}[n.look]??0));return sheetFrame119(key,n.dir,step);}
export function trainerBattle119(n){const key=n.name==='ヤノケン'||['v5:dex','voyage:yanoken','frontier:yanoken'].includes(n.script)?'yanoken':n.variant===2||n.look==='prof'||/スイス/.test(n.name||'')?'npc-02':battleKey119(n.variant);if(!key)return null;const im=asset(key,true);return im.complete&&im.naturalWidth?im:null;}
export function heroBattle119(look={},view='front'){const im=asset('hero-'+(look.gender==='girl'?'girl':'boy')+'-'+(view==='back'?'back':'front'),true);return im.complete&&im.naturalWidth?im:null;}
const dressed=new Map();
export function mapHeroFrame119(dir,step,look={}){const gender=look.gender==='girl'?'girl':'boy',hair=HAIRSTYLES119[gender].some(([id])=>id===look.hairMap119)?look.hairMap119:'default',outfit=OUTFITS119.some(([id])=>id===look.outfit119)?look.outfit119:'default';const base=sheetFrame119(hair==='default'?'hero-'+gender:'hair-'+gender+'-'+hair,dir,step);if(!base)return null;const body=sheetFrame119(outfit==='default'?'hero-'+gender:outfit,dir,step);if(!body)return null;const id=JSON.stringify([look,dir,step]);if(dressed.has(id))return dressed.get(id);const c=document.createElement('canvas');c.width=32;c.height=48;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.imageSmoothingEnabled=false;ctx.drawImage(base,0,0);if(outfit!=='default'||hair!=='default'){ctx.clearRect(0,26,32,22);ctx.drawImage(body,0,26,32,22,0,26,32,22);}
 const d=ctx.getImageData(0,0,32,48),p=d.data,src=base.getContext('2d').getImageData(0,0,32,48).data,rgb=/^#[0-9a-f]{6}$/i.test(look.hair||'')?[1,3,5].map(i=>parseInt(look.hair.slice(i,i+2),16)):null;
 const mask=new Uint8Array(1536);for(let y=0;y<36;y++)for(let x=0;x<32;x++){const i=(y*32+x)*4,r=src[i],g=src[i+1],b=src[i+2],max=Math.max(r,g,b),min=Math.min(r,g,b);const skin=r>165&&g>90&&r>g*1.15&&g>b*1.1,eye=b>r*1.4&&b>g*1.2,white=min>175;const isHair=src[i+3]>127&&max>30&&!skin&&!eye&&!white&&(y<15||gender==='girl'&&r>g*1.15&&g>b*1.05&&r<175||gender==='boy'&&y<24&&max<95);if(!isHair)continue;mask[y*32+x]=1;if((outfit!=='default'||hair!=='default')&&y>=26)for(let j=0;j<4;j++)p[i+j]=src[i+j];if(rgb){const shade=Math.max(.3,Math.min(1.45,max/(gender==='girl'?115:70)));for(let j=0;j<3;j++)p[i+j]=Math.min(255,Math.round(rgb[j]*shade));}}
 ctx.putImageData(d,0,0);c.protectedHead=mask;if(outfit==='default')dressHero(c,c,look,dir);if(dressed.size>512)dressed.clear();dressed.set(id,c);return c;}
