export const REFERENCE78=[
  {
    "key": "reference78-throne",
    "art": "reference78-throne",
    "label": "王座",
    "w": 2,
    "h": 2,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/throne.png"
  },
  {
    "key": "reference78-column",
    "art": "reference78-column",
    "label": "石の柱",
    "w": 1,
    "h": 3,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/column.png"
  },
  {
    "key": "reference78-banner",
    "art": "reference78-banner",
    "label": "城の旗",
    "w": 1,
    "h": 2,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/banner.png"
  },
  {
    "key": "reference78-armor",
    "art": "reference78-armor",
    "label": "よろいの置物",
    "w": 1,
    "h": 2,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/armor.png"
  },
  {
    "key": "reference78-bamboo",
    "art": "reference78-bamboo",
    "label": "竹の植え込み",
    "w": 2,
    "h": 3,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/bamboo.png"
  },
  {
    "key": "reference78-stone-lantern",
    "art": "reference78-stone-lantern",
    "label": "石灯籠",
    "w": 1,
    "h": 2,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/stone-lantern.png"
  },
  {
    "key": "reference78-plaster-wall",
    "art": "reference78-plaster-wall",
    "label": "白壁と瓦の塀",
    "w": 2,
    "h": 2,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/plaster-wall.png"
  },
  {
    "key": "reference78-birch-fence",
    "art": "reference78-birch-fence",
    "label": "白樺の柵",
    "w": 2,
    "h": 1,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/birch-fence.png"
  },
  {
    "key": "reference78-stool",
    "art": "reference78-stool",
    "label": "丸い木のスツール",
    "w": 1,
    "h": 1,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/stool.png"
  },
  {
    "key": "reference78-mailbox",
    "art": "reference78-mailbox",
    "label": "白いポスト",
    "w": 1,
    "h": 2,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/mailbox.png"
  },
  {
    "key": "reference78-barrel",
    "art": "reference78-barrel",
    "label": "木のたる",
    "w": 1,
    "h": 1,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/barrel.png"
  },
  {
    "key": "reference78-bucket",
    "art": "reference78-bucket",
    "label": "ブリキのバケツ",
    "w": 1,
    "h": 1,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/bucket.png"
  },
  {
    "key": "reference78-watering-can",
    "art": "reference78-watering-can",
    "label": "じょうろ",
    "w": 1,
    "h": 1,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/watering-can.png"
  },
  {
    "key": "reference78-garden-table",
    "art": "reference78-garden-table",
    "label": "青いガーデンテーブル",
    "w": 2,
    "h": 1,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/garden-table.png"
  },
  {
    "key": "reference78-picnic",
    "art": "reference78-picnic",
    "label": "ピクニックセット",
    "w": 2,
    "h": 2,
    "walkable": true,
    "tile": ",",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/picnic.png"
  },
  {
    "key": "reference78-teddy",
    "art": "reference78-teddy",
    "label": "ガオンのぬいぐるみ",
    "w": 1,
    "h": 1,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/teddy.png"
  },
  {
    "key": "reference78-daisy-parasol",
    "art": "reference78-daisy-parasol",
    "label": "花のパラソル",
    "w": 2,
    "h": 3,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/daisy-parasol.png"
  },
  {
    "key": "reference78-flower-arch",
    "art": "reference78-flower-arch",
    "label": "白い花のアーチ",
    "w": 3,
    "h": 3,
    "walkable": true,
    "mask": [
      "#.#",
      "#.#",
      "#.#"
    ],
    "tile": ",",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/flower-arch.png"
  },
  {
    "key": "reference78-pergola",
    "art": "reference78-pergola",
    "label": "ぶどうのパーゴラ",
    "w": 3,
    "h": 3,
    "walkable": true,
    "mask": [
      "#.#",
      "#.#",
      "#.#"
    ],
    "tile": ",",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/pergola.png"
  },
  {
    "key": "reference78-pedestal",
    "art": "reference78-pedestal",
    "label": "白い台座",
    "w": 1,
    "h": 1,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/pedestal.png"
  },
  {
    "key": "reference78-vase",
    "art": "reference78-vase",
    "label": "青い飾りつぼ",
    "w": 1,
    "h": 2,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/vase.png"
  },
  {
    "key": "reference78-telescope",
    "art": "reference78-telescope",
    "label": "望遠鏡",
    "w": 1,
    "h": 2,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/telescope.png"
  },
  {
    "key": "reference78-gramophone",
    "art": "reference78-gramophone",
    "label": "蓄音機",
    "w": 1,
    "h": 1,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/gramophone.png"
  },
  {
    "key": "reference78-pond-rock",
    "art": "reference78-pond-rock",
    "label": "池のふちの石",
    "w": 1,
    "h": 1,
    "walkable": false,
    "tile": "#",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/pond-rock.png"
  },
  {
    "key": "reference78-mushrooms",
    "art": "reference78-mushrooms",
    "label": "森のきのこ",
    "w": 1,
    "h": 1,
    "walkable": true,
    "tile": ",",
    "group": "decor",
    "source": "village",
    "file": "assets/reference-v78/mushrooms.png"
  }
];
