import {STYLE105} from './styleCatalog105.mjs';
const images=new Map(STYLE105.map(p=>{const im=new Image();im.src=new URL('../assets/style-v105/'+p.key+'.png',import.meta.url).href;return[p.key,im];}));
const train132=new Image();train132.src=new URL('../assets/environment-v132/train.png',import.meta.url).href;images.set('train',train132);
const fence139=new Image();fence139.src=new URL('../assets/fence-v139/vertical.png',import.meta.url).href;images.set('fenceVertical',fence139);
const centeredLab114=new Image();centeredLab114.src=new URL('../assets/style-v105/chaletStone114.png',import.meta.url).href;images.set('chaletStone',centeredLab114);
const replacements115={"fenceHorizontal":"fence115","autumn-flower109":"autumn-flower115","winter-dry-flower109":"winter-flower115","garden75-extra-castle-wall-white":"castle-white115","garden75-extra-castle-wall-dark":"castle-dark115","garden75-prop-chalkboard":"sign115","shopCounter":"counter115","power-wall115":"power-wall115","power-fence115":"power-fence116","power-tank115":"power-tank116","blue-flower115":"blue-flower115"};for(const[key,file]of Object.entries(replacements115)){const im=new Image();im.src=new URL('../assets/style-v105/'+file+'.png',import.meta.url).href;images.set(key,im);}
let trainBounds132,trainPixels132;
function trainRect132(im){if(trainBounds132)return trainBounds132;const cv=document.createElement('canvas');cv.width=im.naturalWidth;cv.height=im.naturalHeight;const c=cv.getContext('2d');c.drawImage(im,0,0);const a=c.getImageData(0,0,cv.width,cv.height).data;let l=cv.width,t=cv.height,r=-1,b=-1;for(let y=0;y<cv.height;y++)for(let x=0;x<cv.width;x++)if(a[(y*cv.width+x)*4+3]>32){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y);}return trainBounds132=r>=l?[l,t,r-l+1,b-t+1]:[0,0,cv.width,cv.height];}
const aliases={'v41-fence':'fenceHorizontal','garden75-prop-wood-bench':'outdoor-bench105'};
export function styleKey105(key){const k=key?.replace(/^legacy73-/,'');return aliases[k]||k;}
export const styleReady105=()=>[...images.values()].every(im=>im.complete&&im.naturalWidth>0);
export function drawStyle105(c,key,x,y,w,h){const canonical=styleKey105(key),im=images.get(canonical);if(canonical==='fence-left116'||canonical==='fence-right116'){c.save();c.beginPath();c.rect(x+(canonical==='fence-left116'?w/8:0),y,w*7/8,h);c.clip();const drawn=drawStyle105(c,'fenceHorizontal',x,y,w,h);c.restore();return drawn;}if(!im)return false;if(im.complete&&im.naturalWidth){if(canonical==='train'){const [sx,sy,sw,sh]=trainRect132(im);if(!trainPixels132){trainPixels132=document.createElement('canvas');trainPixels132.height=64;trainPixels132.width=Math.round(sw/sh*64);const g=trainPixels132.getContext('2d');g.imageSmoothingEnabled=false;g.drawImage(im,sx,sy,sw,sh,0,0,trainPixels132.width,64);}const fit=Math.min(w/trainPixels132.width,h/64),scale=fit>=1?Math.floor(fit):fit,dw=trainPixels132.width*scale,dh=64*scale;c.imageSmoothingEnabled=false;c.drawImage(trainPixels132,Math.round(x+(w-dw)/2),Math.round(y+h-dh),dw,dh);return true;}if(canonical==='fenceVertical'&&h>w*1.05){c.save();c.beginPath();c.rect(x,y,w,h);c.clip();for(let dy=0;dy<h;dy+=w)drawStyle105(c,canonical,x,y+dy,w,w);c.restore();return true;}if(canonical==='fenceHorizontal'&&w>h*1.05){c.save();c.beginPath();c.rect(x,y,w,h);c.clip();for(let dx=0;dx<w;dx+=h)drawStyle105(c,canonical,x+dx,y,h,h);c.restore();return true;}if(canonical==='fenceHorizontal'){c.imageSmoothingEnabled=false;for(let i=0;i<2;i++)c.drawImage(im,0,0,im.naturalWidth/2,im.naturalHeight,x+i*w/2,y,w/2,h);return true;}const scale=Math.min(w/im.naturalWidth,h/im.naturalHeight),dw=im.naturalWidth*scale,dh=im.naturalHeight*scale;c.imageSmoothingEnabled=false;c.drawImage(im,Math.round(x+(w-dw)/2),Math.round(y+h-dh),Math.round(dw),Math.round(dh));}return true;}
