import {MAPS} from './data/maps.js';
import {statOf,maxHp,expForLevel,normalizeMonStats} from './state.js';
import {SPECIES} from './data/species.js';
import {move} from './data/moves.js';
import {item} from './data/items.js';
import {battleArt} from './data/battleart.js';
const labels={hp:'HP',atk:'アタック',def:'ブロック',spc:'マジック',sdef:'バリア',spd:'スピード'};
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;};
export function ensureSummaryStyle124(){if(document.getElementById('summary-css124'))return;const l=el('link');l.id='summary-css124';l.rel='stylesheet';l.href=new URL('./summary124.css',import.meta.url).href;document.head.append(l);}
export async function showSummary124(mon,{readOnly=false,onChange=()=>{}}={}){
 ensureSummaryStyle124();const m=readOnly?structuredClone(mon):mon;normalizeMonStats(m);const sp=SPECIES[m.sp],root=el('section',null,'summary124');root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('aria-label','ガオンのつよさ');document.body.append(root);let tab=0,chosen=0,swap=-1,resolve;const done=new Promise(r=>resolve=r),oldFocus=document.activeElement;
 const button=(text,fn)=>{const b=el('button',text);b.type='button';b.onclick=fn;return b;};
 const close=()=>{document.removeEventListener('keydown',key,true);root.remove();oldFocus?.focus?.();resolve();};
 const rows=(parent,list)=>{const dl=el('dl');for(const[k,v]of list)dl.append(el('dt',k),el('dd',String(v)));parent.append(dl);};
 function render(){root.replaceChildren();const panel=el('div',null,'summary-panel124'),head=el('header');head.append(el('h1','ガオンのつよさ'),button('もどる',close));panel.append(head);const tabs=el('nav');tabs.setAttribute('aria-label','つよさのページ');['基本情報','能力・育成','わざ','出会いの記録'].forEach((name,i)=>{const b=button(name,()=>{tab=i;swap=-1;render();});b.setAttribute('aria-pressed',String(tab===i));tabs.append(b);});panel.append(tabs);const body=el('div',null,'summary-body124'),portrait=el('aside'),img=el('img'),art=battleArt(m.sp);if(art)img.src=art.src;img.alt=m.sp;portrait.append(el('h2',(m.nick||m.sp)+'　Lv.'+m.lv),img,el('p',sp.types.join('・')),el('p','HP '+m.hp+' / '+maxHp(m)));body.append(portrait);const content=el('section',null,'summary-content124');
 if(tab===0){rows(content,[['図鑑番号','No.'+String(sp.no).padStart(3,'0')],['種類',m.sp],['名前',m.nick||m.sp],['状態',m.status||'げんき'],['経験値',m.exp??'記録なし'],['次のレベルまで',m.lv>=100?'最高レベル':m.exp==null?'記録なし':Math.max(0,expForLevel(m.lv+1)-m.exp)],['持ち物',m.heldItem||'なし']]);if(m.heldItem)content.append(el('p',item(m.heldItem).desc));}
 if(tab===1){const table=el('table'),h=el('tr');for(const t of ['能力','数値','努力値','個体値'])h.append(el('th',t));table.append(h);for(const[k,label]of Object.entries(labels)){const r=el('tr');r.append(el('th',label),el('td',statOf(m,k)),el('td',m.ev[k]),el('td',m.iv[k]));table.append(r);}content.append(table,el('p','努力値 合計 '+Object.values(m.ev).reduce((a,b)=>a+b,0)+' / 510'),el('small','努力値：育成で伸ばした力（各能力252まで）\n個体値：そのガオンが生まれ持つ力（31まで）'));}
 if(tab===2){const list=el('div',null,'summary-moves124');m.moves.forEach((mv,i)=>{const d=move(mv.name),b=button(d.type+'　'+mv.name+'　'+mv.pp+'/'+mv.max,()=>{chosen=i;render();});b.setAttribute('aria-pressed',String(i===chosen));list.append(b);});content.append(list);const mv=m.moves[chosen];if(mv){const d=move(mv.name);rows(content,[['分類',({phys:'ぶつり',spec:'とくしゅ',stat:'へんか'})[d.cat]||d.cat],['威力',d.pow||'—'],['命中',d.acc||'—'],['PP',mv.pp+' / '+mv.max]]);content.append(el('p',d.desc||''));if(!readOnly&&m.moves.length>1)content.append(button(swap<0?'このわざを並べかえる':'ここに移す',()=>{if(swap<0)swap=chosen;else{[m.moves[swap],m.moves[chosen]]=[m.moves[chosen],m.moves[swap]];swap=-1;onChange();}render();}));if(swap>=0)content.append(el('small','移動先のわざを選んで「ここに移す」'));}}
 if(tab===3){const r=m.encounter124;rows(content,[['出会った日',r?.date?new Date(r.date).toLocaleDateString('ja-JP'):'記録なし'],['出会った場所',MAPS[r?.place]?.name||r?.place||'記録なし'],['出会ったレベル',r?.level?'Lv.'+r.level:'記録なし'],['最初のトレーナー',r?.trainer||'記録なし'],['一緒に歩いた距離',Math.floor(m.walkBond121?.distance||0)+' マス']]);if(!r)content.append(el('p','このガオンの出会いの記録は残っていません。'));}
 body.append(content);panel.append(body,el('footer','← → ページ切替　B / Esc もどる'));root.append(panel);}
 function key(e){if(['Escape','x','X','b','B','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter','z','Z'].includes(e.key)){e.stopImmediatePropagation();if(e.key==='Escape'||['x','X','b','B'].includes(e.key)){e.preventDefault();close();}else if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();tab=(tab+(e.key==='ArrowLeft'?3:1))%4;swap=-1;render();}}}
 document.addEventListener('keydown',key,true);render();root.querySelector('button').focus();await done;
}
export async function showGrowth124(mon,growth){ensureSummaryStyle124();for(const g of growth||[]){const root=el('section',null,'summary124'),p=el('div',null,'summary-panel124 growth124');p.append(el('h1',(mon.nick||mon.sp)+'　Lv.'+g.level),el('p','レベルが あがった！'));const table=el('table'),h=el('tr');['能力','上昇量','いまの数値'].forEach(x=>h.append(el('th',x)));table.append(h);for(const[k,label]of Object.entries(labels)){const r=el('tr');r.append(el('th',label),el('td','+'+(g.after[k]-g.before[k])),el('td',g.after[k]));table.append(r);}p.append(table);root.append(p);root.setAttribute('role','dialog');root.setAttribute('aria-label','レベルアップした能力');document.body.append(root);await new Promise(resolve=>{const close=()=>{document.removeEventListener('keydown',key,true);root.remove();resolve();},key=e=>{e.stopImmediatePropagation();if(['Enter','z','Z','x','X','Escape','b','B'].includes(e.key)){e.preventDefault();close();}};const b=el('button','つづける');b.onclick=close;p.append(b);b.focus();document.addEventListener('keydown',key,true);});}}
