const KEY='gaon:welcome102:done';
let installEvent=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;});
export function shouldWelcome102({local,signedIn,seen}){return !local&&!signedIn&&!seen;}
export async function welcome102(local,cloud,showAuth){
 let seen=false;try{seen=!!(localStorage.getItem(KEY)||localStorage.getItem('vmon:lastname')||sessionStorage.getItem(KEY));}catch{}
 if(!shouldWelcome102({local,signedIn:cloud.signedIn,seen}))return;
 const dialog=document.createElement('dialog');dialog.className='welcome102';dialog.setAttribute('aria-labelledby','welcome-title102');
 const style=document.createElement('style');style.textContent='.welcome102{color-scheme:light;background:#fffdf3;color:#214837;border:0;border-radius:24px;width:min(460px,calc(100vw - 24px));max-height:90dvh;padding:24px;font:17px/1.8 sans-serif;touch-action:pan-y;box-shadow:0 20px 70px #0008}.welcome102::backdrop{background:#102b3bbb}.welcome102 button{font:700 16px/1.6 sans-serif;min-height:46px;border:2px solid #aec8b7;border-radius:12px;background:white;color:#214837;padding:9px 14px;cursor:pointer}.welcome102 h2{font-size:24px;line-height:1.5;margin:12px 0}.welcome102 p{margin:12px 0}.welcome102 .big102{background:#195640;color:white;width:100%;margin:10px 0}.welcome102 .exit102{display:block;margin-left:auto;width:46px}.welcome102 .hint102{background:#e7f2df;border-radius:14px;padding:14px;font-size:15px}.welcome102 .bottom102{display:flex;justify-content:space-between;gap:12px}.welcome102 button:focus-visible{outline:4px solid #d89516;outline-offset:2px}.welcome102 img{width:70px;height:70px;object-fit:contain;float:right;image-rendering:pixelated}';document.head.append(style);document.body.append(dialog);
 let done;const finished=new Promise(r=>done=r);const close=()=>{try{localStorage.setItem(KEY,'1');}catch{try{sessionStorage.setItem(KEY,'1');}catch{}}dialog.close();dialog.remove();style.remove();done();};dialog.addEventListener('cancel',e=>{e.preventDefault();close();});
 const make=(t,text)=>{const e=document.createElement(t);e.textContent=text;return e;};
 function page(step){dialog.replaceChildren();const x=make('button','×');x.className='exit102';x.setAttribute('aria-label','案内をとじる');x.onclick=close;dialog.append(x);const no=make('small',(step+1)+' / 2　はじめての人へ'),title=make('h2',step?'ホーム画面に置こう！':'ぼうけんの記録を守ろう！');title.id='welcome-title102';const im=document.createElement('img');im.src='/gaon-icon-192.png';im.alt='ガオン・ワールドのアイコン';dialog.append(im,no,title);
 if(!step){dialog.append(make('p','メールアドレスなしで、かんたん登録！ 名前と「あいことば」を決めるだけだよ。'));const p=make('p','ログインすると、ネットにつながって保存できた記録を、同じアカウントで続けられるよ。スマホを変えたり、ブラウザーのデータが消えても安心。');dialog.append(p);const hint=make('p','名前とあいことばは、忘れないようにひかえてね。保存できたことも、ゲームの表示でたしかめよう。');hint.className='hint102';dialog.append(hint);const signup=make('button','登録・ログインしてみる');signup.className='big102';signup.onclick=async()=>{dialog.close();await showAuth('signup');if(cloud.signedIn)page(1);dialog.showModal();};dialog.append(signup);
 }else{dialog.append(make('p','アイコンをおすだけで、すぐにあそべるよ。ホーム画面への追加は無料！'));const select=document.createElement('select');select.style='font:inherit;max-width:100%;padding:8px';select.setAttribute('aria-label','使っているスマホ');for(const[t,v]of [['iPhone・iPad','ios'],['Android','android'],['パソコン','pc']]){const o=make('option',t);o.value=v;select.append(o);}select.value=/iPhone|iPad/.test(navigator.userAgent)?'ios':/Android/.test(navigator.userAgent)?'android':'pc';const instructions=make('p','');instructions.className='hint102';const explain=()=>instructions.textContent=select.value==='ios'?'① Safariでゲームをひらく → ② 共有ボタン（四角から上向き矢印）→ ③「ホーム画面に追加」→ ④「追加」をおそう。':select.value==='android'?'① Chromeでゲームをひらく → ② 右上の「︙」→ ③「ホーム画面に追加」または「アプリをインストール」をえらぼう。':'ブラウザーのメニューに「アプリをインストール」があれば使えるよ。ブックマークに入れても、すぐにひらけるよ。';select.onchange=explain;explain();dialog.append(select,instructions);if(matchMedia('(display-mode: standalone)').matches||navigator.standalone)dialog.append(make('p','この画面は、ホーム画面からひらけているよ！'));else if(installEvent){const install=make('button','ホーム画面に追加');install.className='big102';install.onclick=async()=>{if(!installEvent)return;await installEvent.prompt();const result=await installEvent.userChoice;installEvent=null;install.textContent=result.outcome==='accepted'?'追加できたよ！':'上の手順でも追加できるよ';install.disabled=true;};dialog.append(install);}dialog.append(make('p','ホーム画面に追加しても、ログインは別だよ。同じ名前とあいことばでログインしてね。'));}
 const bottom=make('div','');bottom.className='bottom102';const skip=make('button','スキップ');skip.onclick=close;const next=make('button',step?'ゲームへすすむ →':'つぎへ →');next.onclick=step?close:()=>page(1);bottom.append(skip,next);dialog.append(bottom);dialog.scrollTop=0;}
 page(0);dialog.showModal();await finished;
}
