import {WORKSHOP_EXITS181} from './workshopExits181.mjs';
import {twoCellExits140} from './mapExits140.mjs';
import {protectedNpc111} from './npcSettings111.mjs';
export const GROUPS181={shadowDepths:['shadowDepths','shadowDepths2','shadowDepths3','shadowDepths4'],volcanicDepths:['volcanicDepths','volcanicDepths2','volcanicDepths3','volcanicDepths4'],forgottenRuins:['forgottenRuins','forgottenRuins2','forgottenRuins3','forgottenRuins4'],volcano:['volcano1','volcano2','volcano3','volcanoSummit'],glacier:['glacier','glacier2','glacier3','glacier4']};
export const BLANK_MAPS181=[...Object.values(GROUPS181).flat(),'clearTown','route13','route14','route15','route16','blizzard'];
export const blankTarget181=id=>BLANK_MAPS181.includes(id);
const themeFor=id=>id.startsWith('volcan')?'volcano':id.startsWith('forgotten')?'ruins':id.startsWith('shadow')?'cave':id.startsWith('glacier')?'ice':'snow';
function hash(m){if(m.legacyHash123)return m.legacyHash123;let n=2166136261;for(const ch of JSON.stringify(m.npcs?.some(n=>n.managed120)?{...m,npcs:m.npcs.filter(n=>!n.managed120)}:m)){n^=ch.charCodeAt(0);n=Math.imul(n,16777619);}return(n>>>0).toString(16);}
export function extendWorkshop181(maps){for(const [id,exits]of Object.entries(WORKSHOP_EXITS181)){const m=maps[id];if(!m||m.workshopExits181)continue;const oldHash=hash(m);m.warps=exits.map(w=>({...m.warps.find(p=>p.to===w.to&&p.x===w.x&&p.y===w.y)||m.warps.find(p=>p.to===w.to),...w}));m.legacyHash123=oldHash;m.workshopExits181=true;}for(const[root,ids]of Object.entries(GROUPS181)){if(root==='volcano'||!maps[root])continue;const first=maps[root];if(first.workshopChain181)continue;const oldHash=hash(first),w=first.rows[0].length,h=first.rows.length,cy=Math.floor(h/2);for(let i=1;i<4;i++){const id=ids[i];if(!maps[id])maps[id]={id,name:first.name+'・'+(i+1),kind:first.kind,chapter:1,tileWorld:true,workshopNew181:true,rows:Array.from({length:h},(_,y)=>Array.from({length:w},(_,x)=>x===0||x===w-1||y===0||y===h-1?'X':first.kind==='cave'?'C':',').join('')),props:[],npcs:[],signs:[],items:[],objects:[],warps:[],spawn:{x:2,y:cy},enc:structuredClone(first.enc),workshopChain181:true};}first.legacyHash123=oldHash;first.workshopChain181=true;for(let i=0;i<3;i++){const a=maps[ids[i]],b=maps[ids[i+1]];for(let lane=0;lane<2;lane++){const south=i===0&&root==='forgottenRuins',sx=south?Math.floor(w/2)+lane:w-1,sy=south?h-1:cy+lane;a.warps.push({x:sx,y:sy,to:b.id,tx:1,ty:cy+lane,edge:1,workshop181:true});b.warps.push({x:0,y:cy+lane,to:a.id,tx:south?sx:w-2,ty:south?h-2:sy,edge:1,workshop181:true});}}}return maps;}
export function keepActor181(n){return protectedNpc111(n)||!!(n?.artMon&&!n.residentPet||n?.itemArt||n?.propArt);}
const groundCache181=new WeakMap();
export function blankGround181(base){if(groundCache181.has(base))return groundCache181.get(base);const w=base.rows[0].length,h=base.rows.length,theme=themeFor(base.id),floor=theme+'-floor173',wall=theme+'-wall173',open=new Set((base.warps||[]).map(p=>p.x+','+p.y));const exits=structuredClone(base);exits.rows=base.rows.map((r,y)=>[...r].map((_,x)=>(x===0||y===0||x===w-1||y===h-1)&&!open.has(x+','+y)?'X':base.kind==='cave'?'C':',').join(''));for(const p of twoCellExits140(exits).warps)open.add(p.x+','+p.y);const tiles=[];for(let y=0;y<h;y++)for(let x=0;x<w;x++)tiles.push({x,y,material:(x===0||y===0||x===w-1||y===h-1)&&!open.has(x+','+y)?wall:floor});groundCache181.set(base,tiles);return tiles;}
export function blankTiles181(base,patches){const patch=new Map(patches.map(t=>[t.x+','+t.y,t]));return blankGround181(base).map(t=>patch.get(t.x+','+t.y)||t);}
export function upgradeBlank181(base,d){if(!blankTarget181(base.id)||d.blank181)return d;const w=base.rows[0].length,h=base.rows.length,theme=themeFor(base.id);
 const actors=d.actors.map((a,i)=>{const n=a.id.startsWith('n:')?base.npcs[Number(a.id.slice(2))]:null;return{...a,x:Math.floor(w/2)-4+(i%5)*2,y:Math.floor(h/2)+Math.floor(i/5)*2,mode:'still',owner:null,...(keepActor181(n)?{}:{stored79:true})};});for(const a of actors)if(keepActor181(base.npcs[Number(a.id.slice(2))]))delete a.stored79;
 return{...d,blank181:true,layout173:true,theme173:theme,tiles:[],objects:d.objects.filter(o=>!o.id.startsWith('g:')).map(o=>({...o,stored79:true})),actors,elevations:[],climbs:[],rug:null,links:(d.links||[]).map(({sourceAnchor,targetAnchor,...l})=>l)};}
