const C=require('./_friendCatalog.json');
const clone=x=>JSON.parse(JSON.stringify(x));
const clamp=(x,a,b)=>Math.max(a,Math.min(b,Math.floor(Number(x)||0)));
const stage=n=>[.25,.28,.33,.4,.5,.66,1,1.5,2,2.5,3,3.5,4][clamp(n,-6,6)+6];
function stats(m,key){const sp=C.species[m.sp];let n=Math.floor((2*sp.base[key]+clamp(m.iv?.[key],0,31)+Math.floor(clamp(m.ev?.[key],0,252)/4))*m.lv/100)+(key==='hp'?m.lv+10:5);if(C.items?.[m.heldItem]?.stat===key)n=Math.floor(n*1.1);return n;}
function combatMon(input,level){if(!input||!C.species[input.sp])throw Error('ガオンが見つかりません');const m=clone(input);m.lv=level||clamp(m.lv,1,100);m.maxHp=stats(m,'hp');m.hp=m.maxHp;m.status='';m.st={};m.sleep=0;m.leech=false;m.flinch=false;m.moves=(m.moves||[]).filter(x=>C.moves[x.name]).slice(0,4).map(x=>({name:x.name,pp:C.moves[x.name].pp,max:C.moves[x.name].pp}));if(!m.moves.length)m.moves=[{name:'タックル',pp:35,max:35}];return m;}
function teamFromSave(save,ids,rule){if(!Array.isArray(ids)||new Set(ids).size!==ids.length)throw Error('ガオンを重複せず選んでください');const party=save.party||[],size=rule==='level50'?3:party.length;if(ids.length!==size||!size)throw Error(rule==='level50'?'3匹を選んでください':'手持ち全員を選んでください');return ids.map(id=>{const m=party.find(x=>x.companionId===id);if(!m)throw Error('手持ちのガオンを選んでください');return combatMon(m,rule==='level50'?50:undefined)});}
function begin(sides,coop=false){return {sides:clone(sides).map((s,i)=>({...s,group:s.group??i,active:0})),turn:1,pending:{},logs:['バトル開始！'],finished:false,winner:null,coop};}
function current(side){return side.team[side.active]}
function submit(b,actor,action,turn,random=Math.random){if(b.finished)throw Error('バトルは終了しました');if(turn!==b.turn)throw Error('ターンが更新されました');const side=b.sides.find(s=>s.id===actor);if(!side||side.ai)throw Error('このバトルには参加していません');if(b.pending[actor])throw Error('選択済みです');const mon=current(side);if(action.kind==='switch'){if(!Number.isInteger(action.index)||!side.team[action.index]?.hp||action.index===side.active)throw Error('交代できません');}else if(action.kind==='move'){if(mon.moves.some(m=>m.pp>0)){if(!Number.isInteger(action.index)||!mon.moves[action.index]?.pp)throw Error('その技は使えません');}}else throw Error('行動を選んでください');b.pending[actor]=clone(action);const humans=b.sides.filter(s=>!s.ai&&s.team.some(m=>m.hp>0));if(humans.every(s=>b.pending[s.id]))resolve(b,random);return b;}
function resolve(b,rng){const chance=p=>rng()<p,rand=n=>Math.floor(rng()*n);b.logs=[];for(const s of b.sides){current(s).flinch=false;if(s.ai){const available=current(s).moves.map((m,i)=>m.pp?i:-1).filter(i=>i>=0);b.pending[s.id]={kind:'move',index:available[rand(available.length)]??-1};}}
 const order=b.sides.filter(s=>s.team.some(m=>m.hp>0)).map(s=>{const a=b.pending[s.id],m=current(s),d=C.moves[m.moves[a?.index]?.name];return {s,a,priority:a?.kind==='switch'?10:d?.pri||0,speed:stats(m,'spd')*stage(m.st.spd||0)*(m.status==='まひ'?.25:1),tie:rng(),original:m};}).sort((a,z)=>z.priority-a.priority||z.speed-a.speed||z.tie-a.tie);
 for(const {s,a,original}of order){let m=current(s);if(!m.hp||m!==original)continue;if(a.kind==='switch'){s.active=a.index;current(s).st={};b.logs.push(s.name+'は '+current(s).sp+'に交代！');continue;}const enemies=b.sides.filter(e=>e.group!==s.group&&current(e).hp>0);if(!enemies.length)break;const enemy=enemies[rand(enemies.length)],dmon=current(enemy);if(m.status==='ねむり'){if(--m.sleep>0){b.logs.push(m.sp+'は眠っている');continue;}m.status='';}if(m.flinch||m.status==='まひ'&&chance(.25)){b.logs.push(m.sp+'は動けない');continue;}let mv=m.moves[a.index],d;if(!mv||mv.pp<=0){mv={name:'わるあがき'};d={pow:50,cat:'phys',acc:100,type:'ノーマル',fx:{recoil:.25}};}else{mv.pp--;d=C.moves[mv.name];}b.logs.push(m.sp+'の '+mv.name+'！');if(!chance(d.acc/100*stage(m.st.acc||0))){b.logs.push('こうげきは はずれた');continue;}const fx=d.fx||{},eff=C.species[dmon.sp].types.reduce((n,t)=>n*(C.types[d.type]?.[t]??1),1);if(d.pow&&eff===0){b.logs.push('こうかが ない');continue;}let total=0;if(d.pow){const count=fx.multi?fx.multi[0]+rand(fx.multi[1]-fx.multi[0]+1):1;for(let i=0;i<count&&dmon.hp;i++){const ak=d.cat==='phys'?'atk':'spc',dk=d.cat==='phys'?'def':'sdef',crit=chance(fx.crit ? .125 : .0625);let A=stats(m,ak)*(crit?1:stage(m.st[ak]||0)),D=stats(dmon,dk)*(crit?1:stage(dmon.st[dk]||0));if(!crit&&d.cat==='phys'&&m.status==='やけど')A*=.5;let damage=Math.floor(Math.floor(Math.floor(2*m.lv/5+2)*d.pow*A/Math.max(1,D))/50)+2;if(crit)damage*=2;if(C.species[m.sp].types.includes(d.type))damage=Math.floor(damage*1.5);damage=Math.max(1,Math.floor(Math.floor(damage*eff)*(217+rand(39))/255));const dealt=Math.min(dmon.hp,damage);dmon.hp-=dealt;total+=dealt;}b.logs.push(dmon.sp+'に '+total+' ダメージ');}
 if(fx.drain)m.hp=Math.min(m.maxHp,m.hp+Math.max(1,Math.floor(total*fx.drain)));if(fx.recoil)m.hp=Math.max(0,m.hp-Math.max(1,Math.floor(total*fx.recoil)));
 if(fx.self)for(const[k,v]of Object.entries(fx.self))m.st[k]=clamp((m.st[k]||0)+v,-6,6);
 if(dmon.hp){if(fx.foe&&chance(fx.chance??1))for(const[k,v]of Object.entries(fx.foe))dmon.st[k]=clamp((dmon.st[k]||0)+v,-6,6);if(fx.status&&!dmon.status&&chance(fx.chance??1)){const ts=C.species[dmon.sp].types;if(!(fx.status==='やけど'&&ts.includes('ほのお')||fx.status==='まひ'&&ts.includes('でんき'))){dmon.status=fx.status;dmon.sleep=1+rand(3);}}if(fx.leech)dmon.leech=s.id;if(fx.flinch&&chance(fx.flinch))dmon.flinch=true;}
 if(fx.heal)m.hp=Math.min(m.maxHp,m.hp+Math.floor(m.maxHp*fx.heal));if(fx.rest){m.hp=m.maxHp;m.status='ねむり';m.sleep=2;}if(fx.reset)for(const side of b.sides)current(side).st={};}
 for(const s of b.sides){const m=current(s);if(m.hp&&(m.status==='やけど'||m.status==='どく'||m.leech)){const damage=Math.min(m.hp,Math.max(1,Math.floor(m.maxHp/8)));m.hp-=damage;if(m.leech){const other=b.sides.find(x=>x.id===m.leech);if(other&&current(other).hp)current(other).hp=Math.min(current(other).maxHp,current(other).hp+damage);}}if(!m.hp){b.logs.push(m.sp+'は倒れた');const next=s.team.findIndex(x=>x.hp>0);if(next>=0){s.active=next;current(s).st={};b.logs.push(current(s).sp+'が出てきた');}}}
 const groups=[...new Set(b.sides.filter(s=>s.team.some(m=>m.hp>0)).map(s=>s.group))];if(groups.length<=1){b.finished=true;b.winner=groups[0]??null;b.logs.push(groups.length?'バトル終了！':'ひきわけ');}b.turn++;b.pending={};}
function view(b,actor){const v=clone(b);v.waiting=Object.keys(v.pending);delete v.pending;for(const s of v.sides)if(s.id!==actor)for(const m of s.team){delete m.iv;delete m.ev;delete m.companionId;}return v;}
module.exports={combatMon,teamFromSave,begin,submit,view,stats};
