const L=require('./_lib'),S=require('./_friendStore'),B=require('./_friendBattle'),T=require('./_friendTrade'),D=require('./_friendDungeon'),crypto=require('crypto');
const clone=x=>JSON.parse(JSON.stringify(x));const roomKey=code=>'room:'+code;
function publicRoom(r,actor){return {code:r.code,mode:r.mode,rule:r.rule,phase:r.phase,version:r.version,offerRevision:r.offerRevision||0,confirmations:Object.keys(r.confirmations||{}),seq:r.seq||{},players:r.players.map(p=>({id:p.id,name:p.name,ready:p.ready,online:Date.now()-p.seenAt<45000,team:p.team?.map(m=>({sp:m.sp,lv:m.lv}))})),offers:Object.fromEntries(Object.entries(r.offers||{}).map(([id,o])=>[id,{mon:{sp:o.mon.sp,nick:o.mon.nick,lv:o.mon.lv,moves:o.mon.moves,heldItem:o.mon.heldItem}}])),battle:r.battle?B.view(r.battle,actor):null,dungeon:r.dungeon?D.view(r.dungeon,actor):null,result:r.result||'',expires:r.expires};}
function unlock(r,users){for(const p of r.players){if(users[p.id]?._activeRoom===r.code)delete users[p.id]._activeRoom;}}
async function operate(code,actor,b){const key=roomKey(code);for(let attempt=0;attempt<6;attempt++){
 const first=(await S.read([key]))[key];if(!first?.data)throw Error('ルームが見つかりません');const ids=first.data.players.map(p=>p.id);if(b.action==='join'&&!ids.includes(actor))ids.push(actor);
 const keys=[key,...ids.map(S.userKey)],docs=await S.read(keys),r=clone(docs[key]?.data);if(docs[key]?.version!==first.version)continue;if(!r)throw Error('ルームが見つかりません');const users=Object.fromEntries(ids.map(id=>[id,clone(docs[S.userKey(id)]?.data)])),expected=Object.fromEntries(keys.map(k=>[k,docs[k]?.version||0]));let changed=false;
 const member=r.players.find(p=>p.id===actor);if(!member&&b.action!=='join')throw Error('このルームには参加していません');
 if(r.expires<Date.now()&&r.phase!=='closed'){r.phase='closed';r.result='ルームの有効時間が終了しました';unlock(r,users);changed=true;}
 if(b.action==='join'&&!member){if(r.phase!=='lobby'||r.players.length>=2)throw Error('このルームには参加できません');const u=users[actor];if(!u?.payload)throw Error('先にレポートを保存してください');if(u._activeRoom&&u._activeRoom!==code)throw Error('先に今のルームを退出してください');r.players.push({id:actor,name:u.display||u.payload.name,ready:false,seenAt:Date.now()});u._activeRoom=code;r.confirmations={};changed=true;}
 const me=r.players.find(p=>p.id===actor);if(!me)throw Error('参加できません');
 const replay=b.requestId&&r.receipts?.includes(b.requestId);
 if(!replay&&b.action!=='state'&&b.action!=='join'){
 if(b.action==='leave'){if(r.phase==='battle'){r.result=me.name+'が退出したためバトルを終了しました';}else r.result=r.result||'ルームを終了しました';r.phase='closed';unlock(r,users);}
 else {if(r.phase==='closed'||r.phase==='complete')throw Error('このルームは終了しました');
 if(b.action==='ready'){if(r.phase!=='lobby'||r.mode==='trade')throw Error('準備を変更できません');me.team=r.mode==='coop'?[B.combatMon((users[actor].payload.party||[]).find(m=>m.companionId===b.ids?.[0]),50)]:B.teamFromSave(users[actor].payload,b.ids,r.rule);me.ready=true;if(r.players.length===2&&r.players.every(p=>p.ready)){if(r.mode==='battle'){r.battle=B.begin(r.players.map(p=>({id:p.id,name:p.name,team:p.team})));r.phase='battle';}else {r.dungeon=D.start(r.players);r.phase='dungeon';}}}
 else if(b.action==='offer'){if(r.mode!=='trade')throw Error('交換ルームではありません');T.offer(r,actor,users[actor].payload,b.ref);}
 else if(b.action==='confirm'){if(r.mode!=='trade')throw Error('交換ルームではありません');const updated=T.confirm(r,actor,b.offerRevision,users);if(updated){Object.assign(users,updated);unlock(r,users);}}
 else if(b.action==='battle'){if(r.mode==='battle'&&r.phase==='battle'){B.submit(r.battle,actor,b.command,b.turn);if(r.battle.finished){r.phase='complete';r.result=r.battle.winner===null?'ひきわけ':r.battle.sides.find(s=>s.group===r.battle.winner).name+'の勝利！';unlock(r,users);}}else if(r.mode==='coop'&&r.phase==='dungeon')D.act(r.dungeon,actor,b.command,b.turn);else throw Error('バトル中ではありません');}
 else if(b.action==='walk'){if(r.phase!=='dungeon')throw Error('探索中ではありません');r.seq ||= {};if(b.seq!==(r.seq[actor]||0))throw Error('位置を更新しています。もう一度移動してください');D.walk(r.dungeon,actor,b.dx,b.dy);r.seq[actor]=(r.seq[actor]||0)+1;}
 else if(b.action==='interact'){if(r.phase!=='dungeon')throw Error('探索中ではありません');D.interact(r.dungeon,r.players,actor);if(r.dungeon.complete){r.phase='complete';r.result='協力ダンジョンをクリア！ レベルの実を1個もらった！';for(const p of r.players){const u=users[p.id],save=u.payload;save.bag ||= {};save.bag['レベルの実']=(save.bag['レベルの実']||0)+1;save.friendEpoch=(save.friendEpoch||0)+1;u.rev=(u.rev||0)+1;save.savedAt=u.savedAt=Date.now();}unlock(r,users);}}
 else throw Error('不明な操作です');}
 changed=true;r.receipts ||= [];if(b.requestId)r.receipts.push(b.requestId);r.receipts=r.receipts.slice(-128);
 }
 if(Date.now()-me.seenAt>15000){me.seenAt=Date.now();changed=true;}
 if(!changed)return {room:publicRoom(r,actor),payload:users[actor]?.payload,user:L.publicUser(users[actor])};
 r.version=(r.version||0)+1;const writes={[key]:r};for(const id of ids){const old=docs[S.userKey(id)]?.data;if(JSON.stringify(users[id])!==JSON.stringify(old))writes[S.userKey(id)]=users[id];}
 if(await S.commit(expected,writes))return {room:publicRoom(r,actor),payload:users[actor]?.payload,user:L.publicUser(users[actor])};
 }throw Error('通信が混み合っています。もう一度お試しください');}
module.exports=async(req,res)=>{L.cors(req,res);if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST')return res.status(405).json({message:'POST only'});if(!L.configured()||!S.enabled())return res.status(503).json({message:'通信の準備中です'});const claim=L.readToken(L.bearer(req));if(!claim)return res.status(401).json({message:'ログインしてください'});try{const user=await L.readUser(claim.id);if(!user)return res.status(401).json({message:'ログインしてください'});const b=L.body(req);if(JSON.stringify(b).length>16000)return res.status(413).json({message:'データが大きすぎます'});
 if(b.action==='resume'){if(!user._activeRoom)return res.status(200).json({room:null});return res.status(200).json(await operate(user._activeRoom,user.id,{action:'state'}));}
 if(b.action==='create'){if(user._activeRoom)return res.status(200).json(await operate(user._activeRoom,user.id,{action:'state'}));if(!['battle','trade','coop'].includes(b.mode)||!['level50','current'].includes(b.rule||'level50'))throw Error('遊び方を選んでください');if(!user.payload?.party?.length)throw Error('先にガオンを仲間にしてください');const code=crypto.randomBytes(4).toString('hex').toUpperCase(),key=roomKey(code),uk=S.userKey(user.id);const room={code,mode:b.mode,rule:b.rule||'level50',phase:'lobby',players:[{id:user.id,name:user.display||user.payload.name,ready:false,seenAt:Date.now()}],version:1,expires:Date.now()+1800000};const u=S.cleanUser(user);u._activeRoom=code;if(!await S.commit({[key]:0,[uk]:user._friendVersion},{[key]:room,[uk]:u}))throw Error('ルーム作成をもう一度お試しください');return res.status(200).json({room:publicRoom(room,user.id)});}
 const code=String(b.code||'').toUpperCase().replace(/[-\s]/g,'');if(!/^[A-F0-9]{8}$/.test(code))throw Error('8文字の合言葉を入力してください');if(b.requestId&&!/^[a-z0-9-]{8,80}$/i.test(b.requestId))throw Error('操作IDが不正です');res.status(200).json(await operate(code,user.id,b));
 }catch(e){res.status(409).json({message:e.message||'通信に失敗しました'});}};
module.exports.operate=operate;
