const L=require('./_lib'),F=require('./_friendStore');
const originalBase=require('../assets/editor-v72/base-maps.json'),species=require('../assets/editor-v72/species.json');
const model=import('../src/editorModel72.mjs');const connections=import('../src/connections75.mjs');const anchors=import('../src/linkAnchors78.mjs');
const PUB='maps72:published',DEFS='maps82:definitions';const custom=import('../src/customMaps82.mjs');
// Pinned to the existing account record, not a self-assigned display name or client flag.
const isAdmin=u=>!!u&&u.id==='ヤノケン'&&Number(u.created)===1789724902905;
module.exports=async(req,res)=>{L.cors(req,res);if(req.method==='OPTIONS')return res.status(204).end();try{
 const b=L.body(req);if(req.method==='GET'){const doc=(await F.read([PUB]))[PUB];return res.status(200).json({revision:doc?.version||0,maps:doc?.data?.maps||{},definitions:doc?.data?.definitions||{}});}
 if(req.method!=='POST')return res.status(405).json({message:'未対応の操作です。'});
 const auth=L.readToken(L.bearer(req));if(!auth)return res.status(401).json({message:'ゲームのアカウントでログインしてください。'});const user=await L.readUser(auth.id);if(!isAdmin(user))return res.status(403).json({message:'このアカウントにはマップの管理権限がありません。'});
 const registry=(await F.read([DEFS]))[DEFS],definitions=registry?.data?.definitions||{},customTools=await custom,base=customTools.extendMaps82({...originalBase},definitions);
 if(b.action==='create'){const d=b.definition;if(!customTools.validDefinition82(d)||Object.hasOwn(base,d.id))return res.status(400).json({message:'マップの名前・大きさ・識別番号が不正です。'});if(Object.keys(definitions).length>=50)return res.status(400).json({message:'追加マップは50個までです。'});const clean={id:d.id,name:d.name.trim(),kind:d.kind,width:d.width,height:d.height};if(!await F.commit({[DEFS]:registry?.version||0},{[DEFS]:{definitions:{...definitions,[d.id]:clean}}}))return res.status(409).json({message:'別の画面でマップが追加されました。再読み込みしてください。'});return res.status(200).json({ok:true,definition:clean});}
 if(b.action==='session')return res.status(200).json({admin:true,name:user.display||user.id,definitions});
 if(typeof b.map!=='string'||!Object.hasOwn(base,b.map))return res.status(400).json({message:'マップが見つかりません。'});
 const key='maps72:draft:'+b.map,history='maps72:previous:'+b.map,docs=await F.read([key,PUB,history]),draft=docs[key],published=docs[PUB],previous=docs[history];
 if(b.action==='read')return res.status(200).json({draft:draft?.data?.edit||null,draftRevision:draft?.version||0,published:published?.data?.maps?.[b.map]||null,publicRevision:published?.version||0,hasPrevious:!!previous?.data});
 if(!['save','publish','rollback'].includes(b.action))return res.status(400).json({message:'未対応の操作です。'});
 if(!Number.isInteger(b.revision)||b.revision!==(draft?.version||0))return res.status(409).json({message:'別の画面で下書きが更新されました。再読み込みしてください。'});
 if(b.action!=='save'&&b.publicRevision!==(published?.version||0))return res.status(409).json({message:'公開状態が更新されています。再読み込みしてください。'});
 const m=await model,cat=m.catalog(base,species);let edit=b.action==='rollback'?previous?.data?.edit:b.edit;if(b.action==='rollback'&&!previous?.data)return res.status(400).json({message:'戻せる履歴がありません。'});
 if(edit===undefined)return res.status(400).json({message:'編集データがありません。'});if(edit!==null){if(JSON.stringify(edit).length>2000000)return res.status(413).json({message:'編集データが大きすぎます。'});const errors=m.validateEdit(base[b.map],edit,cat);if(errors.length)return res.status(400).json({message:errors.join('\n'),errors});edit=JSON.parse(JSON.stringify(edit));}else if(b.action!=='rollback')return res.status(400).json({message:'編集データがありません。'});
 const anchorTools=await anchors,previousEdits=JSON.parse(JSON.stringify(published?.data?.maps||{})),previousViews={...base};for(const[id,d]of Object.entries(previousEdits))if(base[id]&&!m.validateEdit(base[id],d,cat).length)previousViews[id]=m.applyEdit(base[id],d,cat);for(const[id,d]of Object.entries(previousEdits))if(previousViews[id])anchorTools.attachLinkAnchors78(d,previousViews[id],previousViews);if(b.action!=='save'&&edit?.links?.some(l=>definitions[l.to]&&l.to!==b.map&&!published?.data?.definitions?.[l.to]))return res.status(400).json({message:'接続先の新しいマップを先に公開してください。'});if(edit)anchorTools.attachLinkAnchors78(edit,m.applyEdit(base[b.map],edit,cat),previousViews);
 const effective={...base};for(const[id,d]of Object.entries(previousEdits)){if(base[id]&&!m.validateEdit(base[id],d,cat).length)effective[id]=m.applyEdit(base[id],d,cat);}effective[b.map]=edit?m.applyEdit(base[b.map],edit,cat):base[b.map];const linkErrors=(await connections).validateLinks75(effective);if(linkErrors.length)return res.status(400).json({message:linkErrors.join('\n'),errors:linkErrors});
 const expected={[key]:draft?.version||0},writes={[key]:{edit,by:user.id,at:Date.now()}};
 if(b.action!=='save'){const maps={...previousEdits};const old=maps[b.map]||null;if(edit)maps[b.map]=edit;else delete maps[b.map];if(JSON.stringify(maps).length>1400000)return res.status(413).json({message:'公開データの上限です。不要な床の変更を減らしてください。'});expected[PUB]=published?.version||0;expected[history]=previous?.version||0;writes[PUB]={maps,definitions:{...published?.data?.definitions,...(definitions[b.map]?{[b.map]:definitions[b.map]}:{})},at:Date.now()};writes[history]={edit:old,at:Date.now()};}
 if(!await F.commit(expected,writes))return res.status(409).json({message:'編集が競合しました。再読み込みしてください。'});
 return res.status(200).json({ok:true,draftRevision:expected[key]+1,publicRevision:b.action==='save'?published?.version||0:expected[PUB]+1,hasPrevious:b.action!=='save'||!!previous?.data});
 }catch(e){console.error('map editor:',e.message);return res.status(503).json({message:'保存サーバーに接続できません。下書きを端末に書き出し、再度お試しください。'});}};
